### ISSUE TITLE
Routing using a dynamic model

### ISSUE THREAD

**Issue by FayssalLantema** [OData/AspNetCoreOData#100]
We are working on an OData endpoint for a dynamic model. 

We thought that a possible solution could be to map all incoming requests to 1 generic controller. The problem is that, because of the dynamic model, we don't have actual entity classes in our model. Is it possible to (even though the classes aren't present in the model) map the request to 1 generic controller?

**Comment by xuzhg** [comment]
@FayssalLantema Would you please share more detail requirement?

**Comment by FayssalLantema** [comment]
I have to expose a model that is coming from configuration and not from C# classes. The configuration is something that is called an ontology; but essentuale my model is described in a json file.

What I now did is used a Microsoft.OData.Edm.EdmModel to expose a dictionary as model. 
That works great. But the problem here is that each EntitySet requires an own (name based) controller.

```
  private IEdmModel GetEdmModel()
        {
            var models = new Dictionary<string, string>()
            {
                    {"Customer", "CustomerId" },
                    {"Car", "CarId" },
                    {"School", "SchoolId" }
            };

            var model = new EdmModel();

            EdmEntityContainer container = new EdmEntityContainer("Default", "Container");

            for (int i = 0; i < models.Count; i++)
            {
                var name = models.ElementAt(i);
                EdmEntityType element = new EdmEntityType("Default", name.Key, null, false, true);
                element.AddKeys(element.AddStructuralProperty(name.Value, EdmPrimitiveTypeKind.Int32));

                model.AddElement(element);
                container.AddEntitySet(name.Key, element);
            }

            model.AddElement(container);
            return model;

        }
```

After that I’ve tried to create a generic Rest controller, which also works great, but I couldn’t manage to activate OData in here. It was just a normal Rest endpoint.

I would like to have one controller for multiple ‘Edm classes’, which classes are, like said, not really C# classes.

It would look something like this:

```
        [HttpGet("{classname}")]
        [Authorize(Policy = "FullControl")]
        [EnableQuery]
        public async Task<List<string>> GetTest(string classname)
        {
            var searchengine = await pandoraSearchEngineAPI.Search.SearchEntitiesWithHttpMessagesAsync(1, 100, body: new SearchEngine.Client.Models.EntitySearchQuery() { IncludeFields = new List<String> { "Id", "CaseId" } });

            var ontology = await ontologyFactory.CreateAsync();

            var y = new List<string> { "Customer", "Car", "School" };

            return y;
        }
```

I’m working in OData v8

**Comment by xuzhg** [comment]
@FayssalLantema 
I created a sample for your reference. You can find it here: https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataCustomizedSample

please let me know any questions.

**Comment by FayssalLantema** [comment]
This is exactly what I was looking for. Thank you very much!
