### ISSUE TITLE
[Question] Is it possible to create my own custom $filter function?

### ISSUE THREAD

**Issue by AndriiLesiuk** [OData/AspNetCoreOData#1000]
Hi

I'm looking at creating my own custom function inside the $filter function:

<ServiceUrl>/TableName?$filter=MyCustom.Function(property=property_name, values=['value1', 'value2', 
'value3' ]) etc.

I found only this article on this topic:
[https://devblogs.microsoft.com/odata/customizing-filter-for-spatial-data-in-asp-net-core-odata-8/](url)

But for some reason when I try to implement something similar it doesn't work.
Under debug, it doesn't even go into my CustomFilter code.

![image](https://github.com/OData/AspNetCoreOData/assets/50627950/d1481c70-ec0d-4ee7-b3c9-1b09883bc8f9)

My CustomFilter:

```
using Microsoft.AspNetCore.OData.Query.Expressions;
using Microsoft.OData.UriParser;
using System.Linq.Expressions;

public class CustomFilterBinder : FilterBinder
{
    internal const string CustomFilterFunctionName = "Custom.Filter";

    public override Expression BindSingleValueFunctionCallNode(SingleValueFunctionCallNode node, QueryBinderContext context)
    {
        switch (node.Name)
        {
            case CustomFilterFunctionName:
                return base.BindSingleValueFunctionCallNode(node, context);

            default:
                return base.BindSingleValueFunctionCallNode(node, context);
        }
    }
}
```

ODataModel code:

```
 public static ODataOptions AddODataModel(this ODataOptions? options)
        {
            options ??= new ODataOptions();
            options.EnableQueryFeatures(3000);
            options.AddRouteComponents(routePrefix: "odata", model: CreateEdmModel(), services =>
            {
                services.AddSingleton<IFilterBinder, CustomFilterBinder>();
                services.AddSingleton<ISearchBinder, SearchBinder>();
                services.AddSingleton<ODataBatchHandler>(GetBatchHandler());
            });
            options.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;
            options.EnableAttributeRouting = true;

            return options;
        }
```

I tried to reproduce the functionality that I found in the article that I shared above (geo.distance).
It works.
But when I tried to change the function name, it stops working for some reason.
I will be grateful for any help and advice.

**Comment by julealgon** [comment]
I'm confused. You first provide an example calling `MyCustom.Function`, but then in the error message it says `Custom.Filter`, which is different.

Also, your example shows an usage which doesn't seem to make sense. In the article, you can see that the `geo.distance` function _returns_ a value that is the compared. In your case, you are just making a call and "assigning" that to `$filter`?

Could you please double check and provide actual final examples of what you want?

**Comment by julealgon** [comment]
> 1. Is it possible to implement the logic I want with the IFilterBinder implementation?

It feels to me like it should be possible. I wonder if you'd need to so something like 
```
$filter=Custom.Filter(property_name, ['value1', 'value2', 'value3' ]) eq 'true'
``` 
though. That's the only difference between your example and the one in the article.

There is also the fact that you want to take _an array of values_ as the second parameter. To debug this, I'd suggest first trying with a single value like in the sample, because there might be additional complexities with passing an array there.

> 2. If so, what am I doing wrong and why is it not stopping at a breakpoint in my code?

Since you are dealing with an abstract template class, I'd suggest overriding all the methods just in case. It might be possible that the class is being hit, but is calling a different method than the one you expect. Another alternative would be to just implement the raw interface instead, just to confirm that it is being hit in the spot you expect first before doing anything else.

**Comment by AndriiLesiuk** [comment]
@julealgon 
I definitely won't need this par:
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/d7ea6cf3-d97d-4928-bbd1-7c6c0a892622)

Tomorrow I will try to implement your advice and give some update.
Thanks.

**Comment by AndriiLesiuk** [comment]
@julealgon 
I found the reason.
In addition to everything mentioned above, I also need to teach the library's internal OData validation to skip my custom function.
I found 2 interfaces that might allow me to do this:
IFilterQueryValidator and IODataQueryValidator.
I haven't found any examples of how to configure them yet, but I'll try to do something about it myself.

@xuzhg 
If you have any advice on how to make the validator not to fight with my function, and at the same time save the current functional, I will be very grateful for them.

**Comment by julealgon** [comment]
So @AndriiLesiuk does your function work if you pass a single value to it the same way the one in the article does?

**Comment by AndriiLesiuk** [comment]
@julealgon 
It doesn't work because validation doesn't allow the function name.
This is not a problem of the number or type of parameters.

**Comment by AndriiLesiuk** [comment]
@julealgon 
The error occurs in the EnableQueryAttribute, inside the CreateQueryOptionsOnExecuting function.
I just found the exact place where this error occurs.
Now I have another question:
How do I add the name of my custom function to CustomUriFunctions?
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/217fb8e7-a2fc-423d-933d-956bb71fc15a)

**Comment by AndriiLesiuk** [comment]
@julealgon 
And geo.distance works because it already exists in the code in the BuiltInUriFunctions class.
That is why it is being validated.
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/0f3164fc-e930-49cc-8583-a9045be1b8d5)

**Comment by AndriiLesiuk** [comment]
Ok, I already found how to add the name of my custom function to CustomUriFunctions.
It would be nice of you to write an article on how to work with such things, because I unfortunately did not find anything, and spent a lot of time trying to figure it out.
Cheers.

**Comment by julealgon** [comment]
> @julealgon And geo.distance works because it already exists in the code in the BuiltInUriFunctions class. That is why it is being validated. ![image](https://user-images.githubusercontent.com/50627950/256838793-0f3164fc-e930-49cc-8583-a9045be1b8d5.png)

Ok this is extremely confusing to me now.... if `geo.distance` is already in the code, why is there an article explaining how to add it as if it was a completely custom function?

Am I missing something obvious here perhaps?

**Comment by AndriiLesiuk** [comment]
@julealgon 
Maybe it was added only to the validator, but its functionality must be implemented separately.
One way or another, you should ask the person who wrote this article)

**Comment by julealgon** [comment]
> @julealgon Maybe it was added only to the validator, but its functionality must be implemented separately. One way or another, you should ask the person who wrote this article)

Oh to be clear, I wasn't necessarily singling you out @AndriiLesiuk , but more of raising the question here to anybody on the team to answer. This looks incredibly nebulous to me right now.

> Ok, I already found how to add the name of my custom function to CustomUriFunctions.

Would you mind sharing what your solution was? It might benefit other people in the future who are looking for something similar.

**Comment by AndriiLesiuk** [comment]
@julealgon 
Yes of course)
But I will share my solution, but I still haven't fully implemented the desired functionality yet.
My CustomFilterBinder code:

```
using MyProject.Infrastructure.Constants;
using Microsoft.AspNetCore.OData.Query.Expressions;
using Microsoft.OData.UriParser;
using System.Linq.Expressions;

namespace MyProject.Infrastructure.CustomFilterBinder
{
    public class CustomFilterBinder : FilterBinder
    {
        public override Expression? BindFilter(FilterClause filterClause, QueryBinderContext context)
        {
            if (filterClause == null || context == null)
            {
                return null;
            }

            if (filterClause.Expression is SingleValueFunctionCallNode functionCallNode &&
                functionCallNode.Name == CustomFilterUriFunctionNames.Custom_Filter_FunctionName)
            {
                return BindCustomMethodExpressionOrNull(functionCallNode, context);
            }

            return base.BindFilter(filterClause, context);
        }

        protected override Expression? BindCustomMethodExpressionOrNull(SingleValueFunctionCallNode node, QueryBinderContext context)
        {
            if (node.Name == CustomFilterUriFunctionNames.Custom_Filter_FunctionName)
            {
                var elementType = context.ElementClrType;
                var expression = BindFilter(elementType, node, context);

                return expression;
            }

            return base.BindCustomMethodExpressionOrNull(node, context);
        }

        private static Expression? BindFilter(Type elementType, SingleValueFunctionCallNode node, QueryBinderContext context)
        {
            var parameterExpression = Expression.Parameter(elementType, "record");
            var property = node.Parameters.FirstOrDefault() as SingleValuePropertyAccessNode;
            var memberExpression = Expression.Property(parameterExpression, property?.Property?.Name ?? "");

            var equalExpressions = new List<Expression>();
            foreach (var constantNode in node.Parameters.Skip(1))
            {
                if (constantNode is ConstantNode constant)
                {
                    var constantExpression = Expression.Constant(constant.Value, typeof(string));
                    var equalExpression = Expression.Equal(memberExpression, constantExpression);
                    equalExpressions.Add(equalExpression);
                }
            }

            if (equalExpressions.Any())
            {
                Expression orExpression = equalExpressions.Aggregate(Expression.OrElse);
                return Expression.Lambda(orExpression, parameterExpression);
            }

            return null;
        }
    }
}
```

This is how I add my custom function to the CustomUriFunctions list so that the validator understands it.
It may not be the best solution, but it works:

```
public static ODataOptions AddODataModel(this ODataOptions? options)
        {
            AddCustomUriFunctions();

            options ??= new ODataOptions();
            options.EnableQueryFeatures(3000);
            options.AddRouteComponents(routePrefix: "odata", model: CreateEdmModel(), services =>
            {
                services.AddSingleton<IFilterBinder, CustomFilterBinder>();
                services.AddSingleton<ISearchBinder, SearchBinder>();
                services.AddSingleton<ODataBatchHandler>(GetBatchHandler());
            });
            options.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;
            options.EnableAttributeRouting = true;

            return options;
        }

        private static void AddCustomUriFunctions()
        {
            #region DataPlatform.in
            FunctionSignatureWithReturnType signatureString;
            signatureString = new FunctionSignatureWithReturnType(
                EdmCoreModel.Instance.GetBoolean(false),
                EdmCoreModel.Instance.GetString(true),
                EdmCoreModel.Instance.GetString(true));

            CustomUriFunctions.AddCustomUriFunction(CustomFilterUriFunctionNames.DataPlatform_In_FunctionName, signatureString);
            #endregion
        }
```

The function works so far only when I send it alone without combining it with other filter functions (startswith, endswith, eq etc):

/odata/MyTable?$filter=Custom.Filter(Name,'Malawi')

but when I try to combine them, then I get all sorts of errors:
/odata/MyTable?$filter=Source_code eq 'MWI' and Custom.Filter(Name,'Malawi') and contains(Name, 'awi')
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/09aaf05a-a971-4148-8230-831910302f76)


It seems that the internal functionality does not understand how to work with the Expression that my code built.
But I still don't know how to make it work.
I will be grateful for any help or idea.
Cheers
