### ISSUE TITLE
Always dispaly @odata.id, or do not display @odata.editLink

### ISSUE THREAD

**Issue by alifemove** [OData/AspNetCoreOData#1010]
More of a question than a bug and not sure where else to ask it.

Is it possible to either always display @odata.id without having to specify `accept: applicaiton/json;odata.metadata=full` or can I at least NOT display @odata.editLink when using that header just so users don't get confused as to why that is there.

**Comment by julealgon** [comment]
> More of a question than a bug and not sure where else to ask it.

Best place to ask questions is the "Discussions" section whenever that is enabled in any given repository:
![image](https://github.com/OData/AspNetCoreOData/assets/461579/d854e8a5-2d0a-4851-b2f1-520d7696b0d7)

**Comment by alifemove** [comment]
Didnt notice that

**Comment by alifemove** [comment]
https://github.com/OData/AspNetCoreOData/discussions/1011

**Comment by julealgon** [comment]
@alifemove please use the "Close as not planned" option when closing issues that have not been implemented (i.e. were cancelled, created by mistake, etc).

This can help with tracking what was actually implemented later.

**Comment by alifemove** [comment]
@julealgon discussions getting nowhere fast, do you have an idea on this by chance? Also looking to know how to modify the raw sql query that is being used before the query is executed

**Comment by julealgon** [comment]
> @julealgon discussions getting nowhere fast, do you have an idea on this by chance? 

Oh sorry, no, I unfortunately can't help you much on this one (I would've done so in my first reply if I did).

You might have to wait for someone on the team to help with that.

> Also looking to know how to modify the raw sql query that is being used before the query is executed

Not sure exactly what you are trying to achieve, but I would perhaps suggest looking into EFCore Global Filters (on the EF side) as well as using `ODataQueryOptions<T>` manually and applying it yourself to the `IQueryable<T>`, which would allow you to perform extra work either before or after executing the query (not at the SQL level, mind you, but at the queryable level).

Another potential way to modify the query depending on what you need to do would be to introduce something like [AutoMapper.OData](https://github.com/AutoMapper/AutoMapper.Extensions.OData) into the mix. It allows you to create mappings and apply them at the database level while integrating with OData.

**Comment by alifemove** [comment]
The problem is in npgsql there are no query translations for BitArray which I need to query on so when I try from the queryable it doesn't know what. OData doesn't know how to process that filter either. The query it ends up with is `where get_bit(col, 0) = 1`. So feels like the only way to do it is to just override the raw sql if I can.

`public BitArray? col { get; set; }`
```
[EnableQuery(PageSize = 500)]
public IActionResult Get()
{
     var x = _db.GetAll().AsQueryable(); // .Where(x => x.col.Get(0)); // Cant use rn, no query translations
     return Ok(x);
}
```

**Comment by julealgon** [comment]
@alifemove take a look at custom database functions in EFCore, use that, then implement the custom function in OData as well (not trivial).
- https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping
- https://github.com/OData/AspNetCoreOData/issues/1000#event-9984656510

**Comment by alifemove** [comment]
Cool, thanks for your help.
