### ISSUE TITLE
$filter IN doesn't work if the search text contains an apostrophe

### ISSUE THREAD

**Issue by AndriiLesiuk** [OData/AspNetCoreOData#1019]
Hi
I am trying to send such an OData request:
https://localhost/odata/table_name?$filter=field in ('Cote d'Ivoire')

and I've got this error:
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/cabaf8de-c2ae-4c97-bac3-1c5b1f19cec7)

This is because the search text contains an apostrophe.
I think this is a bug that needs to be resolved.

**Comment by julealgon** [comment]
@AndriiLesiuk when closing issues like this when there were no actual changes/fixes, please use the "Close as unplanned" option instead.
