### ISSUE TITLE
Can't discover Odata routes with attribute routing when route component starts with a tilde (~) 

### ISSUE THREAD

**Issue by NikoGJ** [OData/AspNetCoreOData#1038]
**Describe the bug**
I had a hard time figuring out what went wrong in my code, but I think I spotted the issue.
I have defined a basic Odata entity with `~/odata` as the route component prefix:
```
builder.Services.AddControllers().AddOData(options =>
{
	var builder = new ODataConventionModelBuilder();
	var appKeyEntityConfiguration = builder.EntitySet<ApplicationKey>("applicationKeys").EntityType;
	appKeyEntityConfiguration.HasKey(x => x.Id);
	appKeyEntityConfiguration.Property(x => x.ApiKey);
	appKeyEntityConfiguration.Property(x => x.RowVersion).IsConcurrencyToken();
	options
		.EnableQueryFeatures(100)
		.AddRouteComponents("~/odata", builder.GetEdmModel());
});
```
And the following controller (Note that I'm deriving for the ControllerBase and not the ODataController, so I'm using attribute routing)
```
[ApiController]
[ODataAttributeRouting]
public class ApplicationKeysController : ControllerBase
{
	<snip>

	[EnableQuery]
	[HttpGet("~/odata/applicationKeys")]
	public IQueryable<ApplicationKey> Get()
	{
		return _dbContext.ApplicationKeys.AsNoTracking();
	}
}
```

I thought I had checked all necessary conditions for attribute routing to work but the odata debug endpoint listed my endpoint as non-odata (notice however that the template being displayed is omitting the "~/" character for my endpoint)
![image](https://github.com/OData/AspNetCoreOData/assets/18424051/cf15d5f9-bbb0-4c01-8e83-4994d3814108)

I tested different route patterns on the `HttpGet` attribute, with/without the tilde, also adding a `[Route("~/odata")]` on top of my controller without any success.

Strangely enough, if I change the route component prefix from `~/odata` to just `odata` and the HttpGet attribute to `"odata/applicationKeys"` (to keep the same logic), the route is just being recognized just fine
![image](https://github.com/OData/AspNetCoreOData/assets/18424051/f9756a12-205d-4e08-90ab-051732b8eb2e)

I'm no sure I'm doing something wrong, but it seems the tilde looks like an edge case where the template matching is being inconsistent.

**Comment by xuzhg** [comment]
@NikoGJ Yes, 'odata' as a prefix example used in most of cases in the repo, but it doesn't mean "odata" is only valid prefix. Actually, you can use anything for the prefix. However, there are two exceptions.  See https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0#ar6


![image](https://github.com/OData/AspNetCoreOData/assets/9426627/63822e37-c014-4ae9-b8c3-3c5d461f6316)

So, OData follows up the above rule. If a route template starts with "/" or "~/", it's considered as an absolute template.

If you do want to use "~" in your request Url, you can build a route parameter in the prefix.

```diff
- .AddRouteComponents("~/odata", builder.GetEdmModel());
+ .AddRouteComponents("{param}/odata", builder.GetEdmModel());
```

Update 
```diff
-[HttpGet("~/odata/applicationKeys")]
+[HttpGet("/{param}/odata/applicationKeys")]
```

Then, you can call the api using '~' or other characters.

**Comment by gathogojr** [comment]
@NikoGJ Did you consider the response from @xuzhg? Please let us know if it helped resolve your issue
