### ISSUE TITLE
Nuget Package Deprecated

### ISSUE THREAD

**Issue by solkh** [OData/AspNetCoreOData#1039]
I think you have mistakingly deprecated the latest Microsoft.AspNetCore.OData nuget package:

![image](https://github.com/OData/AspNetCoreOData/assets/13716815/ed3bc0bb-3c1a-4f0e-802b-5c12807ea3f5)

**Comment by wachugamaina** [comment]
8.2.2 was marked as deprecated as it had a regression in it. We deprecated rather than unlisting it for consumers to be aware of the issue. We will have a new 8.2.3 version that will address the issue.
