### ISSUE TITLE
(Cosmosdb) $orderby with $top is throwing up composite index error

### ISSUE THREAD

**Issue by svoruganti** [OData/AspNetCoreOData#105]
I have been using version 8 preview 3 with cosmos db. When I try using $orderby with $top, I have been getting "The order by query does not have a corresponding composite index that it can be served from." error. If I remove $top, then it is working as expected i.e., returning results. I created composite index, in cosmos, as suggested by the error like below:

`"compositeIndexes": [
        [
            {
                "path": "/Surname",
                "order": "ascending"
            },
            {
                "path": "/Cursor",
                "order": "descending"
            }
        ]
    ]`

I have been getting composite index error even after creating a composite index using above code. We even waited for two days just to make sure that cosmos builds the composite index properly.

I am not using EFCore with cosmos for querying purposes. I am just using following to get IQueryable:

`CosmosContainer.GetItemLinqQueryable<User>(true)`

Query parameters that we are using are:

`Users?$select=Surname&$orderby=Surname asc,Cursor desc&$filter=Surname eq 'test'&$top=2`

Any suggestions on how to resolve the issue i.e., using $top with $orderby.

**Comment by xuzhg** [comment]
@svoruganti 
$top with $orderby by default,  it will add "key" into the sortable list to make sure the items are stable sorted, then return the $top items.

You can use `EnsureStableOrdering` on the `EnableQueryAttribute` to disable the stable ordering. Let me know the result.

**Comment by svoruganti** [comment]
@xuzhg
Thanks for the suggestion. It did the trick. Now, I am able to use $orderby with $top after setting EnsureStableOrdering to false.

Thanks

**Comment by xuzhg** [comment]
@svoruganti you are welcome
