### ISSUE TITLE
A lot of time is spent processing navigation links even when we they're not written in response

### ISSUE THREAD

**Issue by habbes** [OData/AspNetCoreOData#1071]
Navigation links are usually only written when writing full metadata (`ODataMetadataLevel.Full`). By default, we do not write them in the response. However, we always process the navigation links when serializing the response, even we don't write them.

In the `ODataResourceSerializer.WriteResponseAsync` method below, we have a call to `WriteNavigationLinks`. 

![image](https://github.com/OData/AspNetCoreOData/assets/8460169/589ffeed-c699-4235-9808-83ade71c8bf6)

This method will create and process navigation links, which will eventually not be written unless we're in full metadata. The actual navigation links values that are written are retrieved from a subclass of `ODataResourceMetadataBuilder`. A different type of `ODataResourceMetadataBuilder` is created depending on the metadata level. In the default case, the `NoOpResourceMetadataBuilder` is used, which returns null for the links. However, there's still a substantial amount of processing and expensive code that's executed before we get to the JSON output.

As you can see from the following graph, `WriteNavigationLinks` takes about 17% of CPU when profiling some sample code. 
![image](https://github.com/OData/AspNetCoreOData/assets/8460169/2e9484d7-1465-4b8e-a916-9ad831dcfed9)

Can we skip calling this method if the metadata level is not set to full?

**Comment by gathogojr** [comment]
The question we first need to answer is whether navigation links are written only when `odata.metadata=full`. If possible, this optimization should be considered alongside [Perf: investigate repeated metadata lookups when reading/writing payloads](https://github.com/OData/odata.net/issues/2480) in ODL

**Comment by mikepizzo** [comment]
Note that, if the user explicitly puts a navigation property in $select, it means to include the navigation link, but this still gets omitted in minimal metadata as long as it follows convention.
