### ISSUE TITLE
General project roadmap/timelines

### ISSUE THREAD

**Issue by Greg-Hitchon** [OData/AspNetCoreOData#108]
Hello All,

Is there a document/guidance on the roadmap/timelines of this project? We are big fans of the project but some issues like #104 seem to indicate there is a pretty big gap between the current preview and release. Would love to get a sense if the production ready release will be in days/months/years!

**Comment by xuzhg** [comment]
@Greg-Hitchon I'd like to have it RTM at end of this Quarter.
