### ISSUE TITLE
OData $count and Select By Entity Id  is not working with .NET Core 6 

### ISSUE THREAD

**Issue by DevDavee** [OData/AspNetCoreOData#1093]
**Assemblies affected**
 <TargetFramework>net6.0</TargetFramework>
  Microsoft.AspNetCore.OData" Version="8.0.10"
  Microsoft.EntityFrameworkCore Version="6.0.0"

**1. Describe the bug**
https://localhost:7080/odata/Person?$count

 Microsoft.OData.ODataException: The value for OData query '$count' cannot be empty.
 at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ThrowIfEmpty(String queryValue, String queryName)

  https://localhost:7080/odata/Person?$count=true
  
  Status Code 200 with the object but count is not displayed. Its a know issue many have faced and I tried their options its still not working as mentioned in this post [https://github.com/OData/AspNetCoreOData/issues/247](url) 

 **2. https://localhost:7080/odata/Person(id)  Id is Primary Key in Model and in Database too but it returns  Returns 404**

 **All these $select,$filter,$top,$skip works**
 
   **3."@odata.context": "{url}/$metadata#Person"**
    "value": [ {} ]
       Is also not generated in Response.
**Reproduce steps**
Controller
    [Route("odata/[controller]")] 
     public class PersonController : ODataController
     {
     private readonly IPersonRepo _repo;
     public PersonController(IPersonRepo repo)
     {
        _repo = repo;
     }

    [HttpGet]
    [EnableQuery(PageSize = 5)]
    //[HttpGet("Person/$count")]
    public IQueryable<Person> Get()
    {
        return _repo.Get();
    }
    }

**Data Model**
public class Person
{ 
  [Key]
  public int Id {get;set;}

  public string FirstName {get;set;}

  public string LastName {get;set;}
}

  Program.cs
  
  static IEdmModel GetEdmModel()
{
ODataConventionModelBuilder builder = new();
builder.EntitySet<Person>("Persons");
return builder.GetEdmModel();
}
     builder.Services.AddControllers()
    .AddOData(options => options
    .AddRouteComponents("odata", GetEdmModel())
    .Select()
    .Filter()
    .OrderBy()
    .SetMaxTop(20)
    .Count()
    .Expand()
     );

**Additional context**
What am I doing wrong.

**Comment by aboryczko** [comment]
could you try `builder.EntitySet<Person>("Persons");`?

**Comment by DevDavee** [comment]
> builder.EntitySet<Person>("Persons");

Hi, its in Program.cs  

static IEdmModel GetEdmModel()
{
    ODataConventionModelBuilder builder = new();
    builder.EntitySet<Person>("Persons");
    return builder.GetEdmModel();
}

**Comment by aboryczko** [comment]
EntitySet**<Person>**

**Comment by DevDavee** [comment]
> instead of `builder.EntitySet("Persons");` try `builder.EntitySet<Person>("Persons");`
Same errors with changed syntax, is it related these two issues too:-
2. https://localhost:7080/odata/Person(id) 
3."@odata.context": "{url}/$metadata#Person" in response 


static IEdmModel GetEdmModel()
{
    ODataConventionModelBuilder builder = new();
    builder.EntitySet<Person>("Persons");
    return builder.GetEdmModel();
}

**Comment by aboryczko** [comment]
your controller is named `PersonController` but the set name is `Persons` the convention is that the Entity Set name is **Name**Controller. Change `PersonController` to `PersonsController`

**Comment by DevDavee** [comment]
> your controller is named `PersonController` but the set name is `Persons`. The convention is that the controller of the Entity Set is **EntitySetName**Controller. Change `PersonController` to `PersonsController`

Count is coming &  "@odata.context": "https://localhost:7084/odata/$metadata#Person",
    "@odata.count": 10
    
    But ,https://localhost:7080/odata/Person(id) is 404

**Comment by aboryczko** [comment]
for that you need to implement in PersonsController something similar to:
```
public SingleResult<Person> Get(int key)
{
    return SingleResult.Create(_repo.Get().Where(x=>x.Id == key));
}
```

you can check out https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataRoutingSample for some examples of how Controllers are structured.

**Comment by DevDavee** [comment]
I will try this but in my actual case I have to pass Raw SQL with multiple joins to DB as SP I can't use. But in existing Project I have not seen a separate Action to handle Id Odata take PK which is a Key in Entity and it displays.

Also I have noted $select was giving Newtonsoft Json error not working so I have to uninstall Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.21"
and commented from Program.cs then $select worked, not sure about that.

`
//builder.Services.AddControllers(mvcOptions =>
//           mvcOptions.EnableEndpointRouting = false)
//       .AddNewtonsoftJson();`

**Comment by julealgon** [comment]
- https://github.com/OData/AspNetCoreOData/issues/430

**Comment by DevDavee** [comment]
> [julealgon](/julealgon)

Am unable to understand how my latest comment fits into the link which you have shared.

**Comment by DevDavee** [comment]
> for that you need to implement in PersonsController something similar to:
> 
> ```
> public SingleResult<Person> Get(int key)
> {
>     return SingleResult.Create(_repo.Get().Where(x=>x.Id == key));
> }
> ```
> 
> you can check out https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataRoutingSample for some examples of how Controllers are structured.
I did like this
    
  `      public IQueryable<Person> GetById(int id)
          {   
       var result = _context.MastJobs.FromSqlRaw("SELECT id,firstname from Person where id = {0}", id);
	 
	   return result.AsQueryable();
   }   `

Thank you so much.

**Comment by DevDavee** [comment]
> Controller
> [Route("odata/[controller]")]
> public class PersonController : ODataController
> {

So you are trying to say [Route("odata/[controller]")] attribute routing is not supported in Odata and in the example which you have given the controllers are not inheriting from ODataController

Controller

//No need for routing here
public class PersonController : ODataController
{
}

**Comment by julealgon** [comment]
> So you are trying to say [Route("odata/[controller]")] attribute routing is not supported in Odata...

Correct. For now.

> ...and in the example which you have given the controllers are not inheriting from ODataController

I'm not sure what you mean exactly here. The samples I've provided in that other issue do inherit from `ODataController`.

> Controller
> 
> //No need for routing here public class PersonController : ODataController { }

Just keep in mind that if you omit the routing attributes, you fallback into conventional routing. As long as you fully understand that and the consequences, yes, you don't need the routing attributes whatsoever.

**Comment by DevDavee** [comment]
> > So you are trying to say [Route("odata/[controller]")] attribute routing is not supported in Odata...
> 
> Correct. For now.
> 
> > ...and in the example which you have given the controllers are not inheriting from ODataController
> 
> I'm not sure what you mean exactly here. The samples I've provided in that other issue do inherit from `ODataController`.
> 
> > Controller
> > //No need for routing here public class PersonController : ODataController { }
> 
> Just keep in mind that if you omit the routing attributes, you fallback into conventional routing. As long as you fully understand that and the consequences, yes, you don't need the routing attributes whatsoever.

Thanks for detailed explanation.

**Comment by DevDavee** [comment]
> for that you need to implement in PersonsController something similar to:
> 
> ```
> public SingleResult<Person> Get(int key)
> {
>     return SingleResult.Create(_repo.Get().Where(x=>x.Id == key));
> }
> ```
> 
> you can check out https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataRoutingSample for some examples of how Controllers are structured.

To achieve **Requesting Single Entity by ID** I did this as suggested and it works but other features doesn't works returns 404

**Requesting Single Property Value** 
https://localhost:7085/odata/Persons(15)/FirstName 
 https://localhost:7085/odata/Persons(15)/LastName
 
![One](https://github.com/OData/AspNetCoreOData/assets/150951017/6171cff4-1f12-4658-aa0e-62dcff023042)

**Source**
[https://www.odata.org/odata-services/](url)

        [HttpGet("({id})")]
        [EnableQuery]
        public IQueryable<MastJob> Get([FromODataUri] int id)
        {
            return _repo.GetById(id);
        }

**Comment by aboryczko** [comment]
check #116

**Comment by DevDavee** [comment]
> check #116
> 
> I personally just use ?$select=FirstName

select=FirstName will select all the FirstName from the collection and the /issues/116 is of 2021,so till 2023 its not improved by Odata you mean.

**Comment by aboryczko** [comment]
also works with Persons(15)?$select=FirstName, but like in the issue you could implement appropriate methods that would support entity/property requests.

**Comment by DevDavee** [comment]
> ?$select=

You mean ?$select= is an alternate to

 **Requesting Single Property Value**

GET https://services.odata.org/TripPinRESTierService/Airports('KSFO')/Name 

I tried this 

https://localhost:7085/odata/Persons/(154)?select=firstName

It works

 [HttpGet("({id})")]
 [EnableQuery]
 public IQueryable<Person> Get([FromODataUri] int id)
 {
     return _repo.GetById(id);
 }

**Comment by DevDavee** [comment]
> ```cs
> [HttpGet("odata/Persons({key})/{property}")]
> public IActionResult GetProperty(int key, string property)
> {
>     var p = Expression.Parameter(typeof(Person), "$it");
>     var propertySelector = Expression.Lambda<Func<Person, object>>(Expression.PropertyOrField(p, property), p);
>     return Ok(_repo.Get().Where(x => x.Id == key).Select(propertySelector).FirstOrDefault());
> }
> ```

Regarding this method 

>[HttpGet("odata/Persons({key})/{property}")]
>public IActionResult GetProperty(int key, string property)
>{
> var p = Expression.Parameter(typeof(Person), "$it"); // What does $it do 

> var propertySelector = Expression.Lambda<Func<Person, object>>(Expression.PropertyOrField(p, property), p);
>// If property is of type int Error (: 'Expression of type 'System.Int32' cannot be used for return type 'System.Object'')
 >// I tried to convert var propertySelector = Expression.Convert(Expression.Lambda<Func<MastJob, object>>(Expression.PropertyOrField(p, property)), p); 
 Looks like am using the convert in a wrong way.
 
 > return Ok(_repo.Get().Where(x => x.Id == key).Select(propertySelector).FirstOrDefault());
>}

**Comment by aboryczko** [comment]
Regarding $select=FirstName it is different than /FirstName as you can see by the result one returns
```JSON
{
    "@odata.context": "https://localhost:7044/odata/$metadata#Persons(FirstName)/$entity",
    "Person": "John"
}
```
the other one
```JSON
{
    "@odata.context": "https://localhost:7044/odata/$metadata#Persons(1)/FirstName",
    "value": "John"
}
```

With $select you can query for multiple parameters at once and it's just a query feature, with /Property you have also write capabilities for those single properties, but then again you could achieve similar stuff with PATCH.

As for the dynamic property example it was just a simplified example. It would need 404 handling for non-existing properties, and probably more.
this is how Expression.Convert should have been used:
```C#
var propertySelector = Expression.Lambda<Func<Person, object>>(Expression.Convert(Expression.PropertyOrField(p, property), typeof(object)), p);
```

the original expression was $it => $it.Id
$it is the Expression.Parameter($it)
.Id is Expression.Property
and Expression.Lambda is the =>
you want the expression to look like $it => (object) $it.Id
hence you wrap the Expression.Property with an Expression.Convert

I would suggest to brush up on expression trees in .NET in order to better understand how to work with the OData API as it utilizes them heavily and this is just one use case for it. If you plan to implement a fully OData adherent API you will probably need to at some point implement custom expression binders.

**Comment by DevDavee** [comment]
> With $select you can q

With $select you can q... I understood your explanation for select part.

  > 
        [HttpGet("({id})/{property}")]
        [EnableQuery]
        public IActionResult GetProperty(int id, string property)
        {
            var p = Expression.Parameter(typeof(Person), "$it");
            var propertySelector = Expression.Lambda<Func<Person, object>>(Expression.Convert(Expression.PropertyOrField(p, property), typeof(object)), p);
            return Ok(_repo.Get().Where(x => x.id == id).Select(propertySelector).AsQueryable());
        }
>  https://localhost:7044/odata/$metadata#Persons(1)/FirstName works fine and returns and "@odata.context": is missing
   [
    Sam
   ]
   > {
    "@odata.context": "https://localhost:7044/odata/$metadata#Persons(1)/FirstName",
    "value": "John"
    }
   Are you getting response in this format.
   
   >
      {
    "@odata.context": "https://localhost:7044/odata/$metadata#Persons(FirstName)/$entity",
    "Person": "John"
     }

 For this (FirstName)/$entity" am not clear.

**Comment by DevDavee** [comment]
FirstOrDefault() I tried still same response --> John as result and in no **@odata.context**

> ```json
> {
>     "@odata.context": "https://localhost:7044/odata/$metadata#Persons(1)/FirstName",
>     "value": "John"
> }
> ```

>{
>   "@odata.context": "https://localhost:7044/odata/$metadata#Persons(1)/FirstName",
>  "value": "John"
>}
>
        [HttpGet("({id})/{property}")]
        [EnableQuery]
        public IActionResult GetProperty(int id, string property)
        {
            var p = Expression.Parameter(typeof(MastJob), "$it");
            var propertySelector = Expression.Lambda<Func<MastJob, object>>(Expression.Convert(Expression.PropertyOrField(p, property), typeof(object)), p);
            return Ok(_repo.Get().Where(x => x.id == id).Select(propertySelector).FirstOrDefault());
> }

**Comment by aboryczko** [comment]
as said here:
> > > [julealgon](/julealgon)
> > 
> > 
> > Am unable to understand how my latest comment fits into the link which you have shared.
> 
> I wasn't necessarily referring to your last comment, but to your sample code. OData doesn't currently support the `[controller]` placeholder in routes so that will be considered "as-is" for attribute routing, creating incorrect routes for you that will then not be OData routes.
> 
> If you look at the output of the $odata endpoint, you should be seeing some invalid routes in there.

OData doesn't support [controller] in the routing attributes, that's why have specified the full path in the `[HttpGet]` attribute
