### ISSUE TITLE
ODataController operations without key paramater

### ISSUE THREAD

**Issue by tomasfabian** [OData/AspNetCoreOData#11]
Hi,
I have a [derived base class from ODataController](https://github.com/tomasfabian/Joker/blob/master/Joker.OData/Controllers/ODataControllerBase.cs) using Microsoft.AspNetCore.OData 7.4.0 with the following signatures without explicit key parameters:
```C#
  public abstract class ODataControllerBase<TEntity> : ODataController
    where TEntity : class
  {
    public async Task<IActionResult> Patch(Delta<TEntity> entity)
    {
    }

    public async Task<IActionResult> Put([FromBody]TEntity entity)
    {
    }

    public async Task<IActionResult> Delete()
    {
    }

    [AcceptVerbs("POST", "PUT")]
    public async Task<IActionResult> CreateRef(string navigationProperty, [FromBody] Uri link)
    {
    }

    public async Task<IActionResult> DeleteRef(string navigationProperty)
    {
    }
  }
```
In 8.0.0-preview I have to specify the key parameter. 
```C#
public async Task<IActionResult> Delete(int key) //or
public async Task<IActionResult> Delete(string key) //etc etc
```
We need a way to create a general purpose ODataController for all types of keys including **compound** keys. Please add back this functionality. The key(s) can be extracted from ODataPath programatically during runtime:
```C#
var keys = odataPath.Segments.OfType<KeySegment>();
```

Thank you

**Comment by tomasfabian** [comment]
Same for the HttpGet methods. Get without the key paramater should be recognized based on the return type to avoid ambiguity: 
```C#
    //https://localhost:5003/Authors(2)?$expand=Books
    [EnableQuery]
    public SingleResult<TEntity> Get()
    {
      var keyPredicate = CreateKeysPredicate(GetKeysFromPath());

      IQueryable<TEntity> result = OnGetAll(keyPredicate);// .Where(p => p.Id == key);

      return SingleResult.Create(result);
    }

    //https://localhost:5003/Authors?$expand=Books
    [EnableQuery]
    public OkObjectResult Get(ODataQueryOptions<TEntity> queryOptions)
    {
      AuthenticateQuery(queryOptions);

      IQueryable<TEntity> entities = OnGetAll();
      
      return Ok(entities);
    }
```

Let me know if I should create a separate issue.

**Comment by xuzhg** [comment]
@tomasfabian:

 Microsoft.AspNetCore.OData 7.4.0 can support the "Patch, Put, Delete" without the key for the following ????

```C#
    public async Task<IActionResult> Patch(Delta<TEntity> entity)
    {
    }

    public async Task<IActionResult> Put([FromBody]TEntity entity)
    {
    }

    public async Task<IActionResult> Delete()
    {
    }
```

If that's the case, it is not OData convention. Do you have customized routing convention to support? (Basically, i think you do)

At 8.0, you can do the similar customize by implement "IODataControllerActionConvention".

**Comment by tomasfabian** [comment]
@xuzhg yes Microsoft.AspNetCore.OData 7.4.0 supports the above mentioned "conventions". I didn't customize it.

**Comment by xuzhg** [comment]
I don't think it is OData convention. I'd like to leave such functionality to customize

**Comment by tomasfabian** [comment]
you can try it. It is a breaking change

**Comment by tomasfabian** [comment]
@xuzhg I found out that this is really an undocumented feature, I haven't found it in the official documentation, I figure this out probably via trial and error tinkering. On the other hand we are still "explointing" this behavior in our environments. What does the community think about this approach?

**Comment by tomasfabian** [comment]
Hi @xuzhg, I created an IODataControllerActionConvention which does not require the key attribute. 

I found out that It is not easy to create custom conventions based on OData code, because there are lot of private/internal modifiers for extensions etc.

Thx
