### ISSUE TITLE
POST works outside of batch but fails validation inside batch

### ISSUE THREAD

**Issue by wgibbons1** [OData/AspNetCoreOData#1120]
My OData server successfully handles individual POST requests, but it fails to handle the same message when inside a batch. It fails because of a validation error (despite there being no validation errors when the same message is not in a batch).

To make matters worse, the validation message returned is clearly incorrect because it says `product` is missing, when it should be saying that a certain property of `product` is invalid. 'product' is the name of the parameter to the action method.

Unlike POST messages, GETs within batches are working.

I'm using Microsoft.AspNetCore.OData 8.2.3 with net8.0.

Batch contents:

```
--27299603-ca16-4b05-b381-249c1e4a9759
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /odata/Products HTTP/1.1
Content-Type: application/json

{
    "Field1": 18,
    "Field2":"a"
}

--27299603-ca16-4b05-b381-249c1e4a9759--
```

Validation error message:
`{"error":{"code":"","message":"The input was not valid.\r\n\r\nproduct:\r\nThe product field is required.","details":[{"code":"","message":"The input was not valid."},{"code":"","target":"product","message":"The product field is required."}]}}`

**Comment by julealgon** [comment]
@wgibbons1 does the same error happen if you try to use the [Json Batch format](https://learn.microsoft.com/en-us/odata/client/batch-operations#json-batch)?

**Comment by wgibbons1** [comment]
@julealgon: apologies but it appears you've been mislead owing to my having omitted information.
I mean to say that that my OData server is having this problem when handling an incoming batch request. I think you understood that I was having problems sending a batch request from .NET?
I have now updated my original message so nobody else gets confused by it.

**Comment by wgibbons1** [comment]
@julealgon The suggested "new" batch syntax works! Many thanks.
The reported validation issues still exist, but I would consider that a different issue (and #1119 already deals with it), so I will close this.
