### ISSUE TITLE
isIeee754Compatible is not set to true when passing IEEE754Compatible=true in Accept request header/$format query.

### ISSUE THREAD

**Issue by DanielVernall** [OData/AspNetCoreOData#1123]
**Assemblies affected**
ASP.NET Core OData 8.x

**Describe the bug**
According to [the spec](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html), OData v4 services should return int64 and decimal types in string format when IEEE754Compatible=true is included in the Content-Type request header. This doesn't appear to happen when setting up a ASP.Net Core OData 8 project following Microsoft's Microsoft's [Getting Started with ASP.NET Core OData 8](https://learn.microsoft.com/en-us/odata/webapi-8/getting-started?tabs=net60%2Cvisual-studio-2022%2Cvisual-studio) tutorial.

See this [screenshot](https://i.stack.imgur.com/EIyY9.png) showing the response returned from request with the Content-Type request header set to, `application/json;IEEE754Compatible=true`

I have hosted the repo [here](https://github.com/DanielVernall/AspNetCoreOdata8IEEE754Compatibility). It is almost entirely the sample code given on Microsoft's getting started page, but I've included a `CustomStreamBasedJsonWriterFactory` in order to show that isIeee754Compatible is not set to true when the header is sent.

More details can be found in my [question](https://stackoverflow.com/q/77599004/1324919) over on StackOverflow. 

**Reproduce steps**
Go to the [repo](https://github.com/DanielVernall/AspNetCoreOdata8IEEE754Compatibility) and run the code.

Otherwise,

1. Create a new project exactly as described in Microsoft's [Getting Started with ASP.NET Core OData 8] (https://learn.microsoft.com/en-us/odata/webapi-8/getting-started?tabs=net60%2Cvisual-studio-2022%2Cvisual-studio) tutorial.
2. Add a new property `TestLong` with type `long` to the `Customer` model
3.  Initialise the property in the test Customers construction code to `long.MaxValue`

**Data Model**
See the [repo](https://github.com/DanielVernall/AspNetCoreOdata8IEEE754Compatibility)

**EDM (CSDL) Model**
```xml
<?xml version="1.0"?>
    <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:DataServices>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="TestIEEE754Compatibility.Models">
          <EntityType Name="Order">
            <Key>
              <PropertyRef Name="Id"/>
            </Key>
            <Property Name="Id" Type="Edm.Int32" Nullable="false"/>
            <Property Name="Amount" Type="Edm.Decimal" Nullable="false" Scale="Variable"/>
          </EntityType>
          <EntityType Name="Customer">
            <Key>
              <PropertyRef Name="Id"/>
            </Key>
            <Property Name="Id" Type="Edm.Int32" Nullable="false"/>
            <Property Name="Name" Type="Edm.String" Nullable="false"/>
            <Property Name="TestLong" Type="Edm.Int64" Nullable="false"/>
            <NavigationProperty Name="Orders" Type="Collection(TestIEEE754Compatibility.Models.Order)"/>
          </EntityType>
        </Schema>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
          <EntityContainer Name="Container">
            <EntitySet Name="Customers" EntityType="TestIEEE754Compatibility.Models.Customer"/>
          </EntityContainer>
        </Schema>
    </edmx:DataServices>
    </edmx:Edmx>```
```
**Request/Response**
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/23134d26-eef4-4f98-91a5-c30959a7333a)

**Response headers:**
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/f61ff800-0632-41f0-bd6b-45c6c5026df9)

**Expected behavior**
I expect that sending IEEE754Compatible=true in the Content-Type request header causes the OData service to serialize responses in an IEEE 754 compatible way, where int64 and decimal types are serialized in string format, not number format.

**Screenshots**
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/b486ff68-9b18-4698-a7d8-942d9fd2397f)
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/8207af5f-834d-463c-b7d2-6743fb31ebce)
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/2532c734-f8bd-4870-a3e8-191376155552)

**Comment by gathogojr** [comment]
Thank you @DanielVernall for reporting this issue. Please include the `IEEE754Compatible` flag in the `Accept` header or `$format` query option and report back whether it works

**Comment by DanielVernall** [comment]
Hi @gathogojr,
I have tried both approaches, but I get the same results.

Accept header:
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/8f9c4232-4235-46e0-adce-512541dc2f82)

Format query option - Here I'm not certain of the format syntax:
![image](https://github.com/OData/AspNetCoreOData/assets/6403967/c73b4bfe-c2bf-4c83-986a-d3ea3aeb8afc)

**Comment by DanielVernall** [comment]
@gathogojr Is there any update on this issue, by any chance?

**Comment by gathogojr** [comment]
@DanielVernall I'm looking into it at the moment

**Comment by DanielVernall** [comment]
Awesome, thanks for the quick turn around! I've confirmed that it works for me using `8.2.3-Nightly202312181316` 👍
