### ISSUE TITLE
The type 'OData.EntityReference' of a resource in an expanded link is not compatible with the element type 'OData.EntityReference' of the expanded link. Entries in an expanded link must have entity types that are assignable to the element type of the expanded link.

### ISSUE THREAD

**Issue by only4study** [OData/AspNetCoreOData#1125]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.2.3

**Describe the bug**
when i return a value for a complex type field, i got error "The type 'OData.EntityReference' of a resource in an expanded link is not compatible with the element type 'OData.EntityReference' of the expanded link. Entries in an expanded link must have entity types that are assignable to the element type of the expanded link.";
i don't think there is any wrong usage in my code. but i don't know what the problem is. Please help

**Reproduce steps**
my code is:

IEdmComplexType complexType = ComplexTypeMetadata.EntityReference;
EdmComplexObject complexValue = new EdmComplexObject(complexType);
complexValue.TrySetPropertyValue("Id", Guid.Parse("EFD9B6C7-79E6-4F44-94A0-25A0D16DAD31"));
complexValue.TrySetPropertyValue("Name", "abc");
complexValue.TrySetPropertyValue("LogicalName", "efg");

entity.TrySetPropertyValue(propertyName, complexValue);

**EDM (CSDL) Model**

![image](https://github.com/OData/AspNetCoreOData/assets/10803158/b141bb12-9203-4630-9be9-9032ffd1b488)

**Comment by only4study** [comment]
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="DatasetsNamespace">
<EntityType Name="ave_profile">
<Key>
<PropertyRef Name="ave_profileId"/>
</Key>
<Property Name="ave_profileId" Type="Edm.Guid"/>
<Property Name="UpdatedDate" Type="Edm.Date"/>
<Property Name="CreatedDate" Type="Edm.Date"/>
<Property Name="CreatedBy" Type="Edm.Guid"/>
<Property Name="ModifiedBy" Type="Edm.Guid"/>
<Property Name="ave_profileName" Type="Edm.String"/>
</EntityType>
<EntityType Name="ave_person">
<Key>
<PropertyRef Name="ave_personId"/>
</Key>
<Property Name="ave_personId" Type="Edm.Guid"/>
<Property Name="ave_personName" Type="Edm.String"/>
<Property Name="ave_profiledata" Type="OData.EntityReference"/>
<Property Name="CreatedDate" Type="Edm.Date"/>
<Property Name="UpdatedDate" Type="Edm.Date"/>
<Property Name="ModifiedBy" Type="Edm.Guid"/>
<Property Name="CreatedBy" Type="Edm.Guid"/>
<NavigationProperty Name="ave_person.ave_profiledata.ave_profile.ave_profileId" Type="DatasetsNamespace.ave_profile" Nullable="false"/>
</EntityType>
<EntityContainer Name="DatasetsContainer">
<EntitySet Name="ave_profile" EntityType="DatasetsNamespace.ave_profile"/>
<EntitySet Name="ave_person" EntityType="DatasetsNamespace.ave_person"/>
</EntityContainer>
</Schema>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="OData">
<ComplexType Name="EntityReference">
<Property Name="Id" Type="Edm.Guid" Nullable="false"/>
<Property Name="Name" Type="Edm.String"/>
<Property Name="LogicalName" Type="Edm.String" Nullable="false"/>
</ComplexType>
<ComplexType Name="OptionSetValue">
<Property Name="Value" Type="Edm.Int32" Nullable="false"/>
<Property Name="FormatValue" Type="Edm.String"/>
</ComplexType>
</Schema>
</edmx:DataServices>
</edmx:Edmx>

**Comment by gathogojr** [comment]
Thank you @only4study for reporting this issue. Can you share a simple repro that we can use to troubleshoot the issue?

**Comment by aboryczko** [comment]
I think that you are trying to use a Complex Type object where you should be using an Entity Type Object. From the Model that you have pasted ave_profiledata is a normal Property instead of a NavigationProperty. Only NavigationProperties can be used in $expand. Did you try EdmEntityObject?

**Comment by aboryczko** [comment]
I think it's because you use the `EntityReference` type in the `ave_profile` entity set and the library wants to treat it as an entity type even though you have specified it explicitly as a complex type. You could try to remove the entity set and check if it helps.

**Comment by only4study** [comment]
hi @gathogojr , attached is my sample code. when you access https://{ip}:{port}/odata/local/test_person you will find the error in the console.  looking forward to your reply.
[ODataSample.zip](https://github.com/OData/AspNetCoreOData/files/13578455/ODataSample.zip)

**Comment by julealgon** [comment]
@only4study was the issue resolved for you? Would it make sense to close this now?

**Comment by gathogojr** [comment]
Resolved
