### ISSUE TITLE
Double unescaping of function parameters?

### ISSUE THREAD

**Issue by sherlock1982** [OData/AspNetCoreOData#1131]
**Assemblies affected**
ASP.NET Core OData 8.2.3

**Describe the bug**
Function parameters needs to be escaped twice

**Reproduce steps**
I have an entity Foo with a string key. And I can call delete method like this:

    DELETE /Foo('key%253A')

The string `key%3A` was escaped. This works fine and key will have a proper value `key%3A`

Now I have a function that takes two parameters. And I call it like this:

     GET /Foo/Func(val1=5,val2='key%253A')

I expect val2 to have the value `key%3A` while in reality the value will be `key:`. Meaning that somewhere inside OData this value was unescaped twice.

**Expected behavior**
One time escape should be enough

**Additional context**
The only place I found where OData directly does `UnescapeDataString` is inside SegmentTemplateHelpers.cs. I want to understand if this double escaping is desirable and if it is what are the rules?
Why I have to double escape function parameters but not entity operation parameters? 

**Way to reproduce**

Check this repository:
https://github.com/sherlock1982/odata-double-escape

Note that you can get entity `/Foo` with `'key%3A'` correctly. - OK
But if you call the function `/MyFunction` with `'key%3A'` the result will be 'key:' - NOK

**Comment by xuzhg** [comment]
It seems we should do the same at https://github.com/OData/AspNetCoreOData/blob/e4339327ac3d9becc1cc8133424b5d1301bfb37f/src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs#L179C76-L179C76 for function parameter.

**Comment by xuzhg** [comment]
See: https://github.com/OData/AspNetCoreOData/pull/806
