### ISSUE TITLE
[FromBody] parameter ignored in OData actions if it's not in EDM model

### ISSUE THREAD

**Issue by Shifu462** [OData/AspNetCoreOData#115]
Hi.

I have a project on OData 7.2.1 and .NET Core 2.2 that I want to update to .NET 5.

After updating, I've found out that in OData actions arguments with `[FromBody]` attribute are now ignored and `null` by default. 
The problem is that those DTOs passed to actions are not registered in EDM model. If I register my DTO as `ComplexType`, the parameter is not `null` and works as expected.

----

Reproducible case:
https://github.com/OData/AspNetCoreOData/blob/717d36853d09f577c5f6a3e78c98234c538bc060/sample/ODataRoutingSample/Controllers/ProductsController.cs#L76-L85

Modify this part like:
```cs
public class ProductDto
{
    public int Id { get; set; }

    public string Category { get; set; }

    public Color Color { get; set; }
}

[HttpPost]
[EnableQuery]
public IActionResult Post([FromBody]ProductDto product, CancellationToken token)
{
    // _context.Products.Add(product);

    // _context.SaveChanges();

    return Created(product);
}
```

And the body is not mapped to `product`, the `product` parameter becomes `null`.
To fix this, I have to register `ProductDto` as `ComplexType`.

Identical code on OData 7.2.1 works as expected without registering the DTO.

Is this behavior introduced to enforce developers to strictly follow OData conventions?
Is there a way to use DTOs without registering in EDM?

**Comment by Shifu462** [comment]
Update:
OData 7.8.2, .NET Core 3.1 — not reproduced, model binding works as expected without registering models as complex types.

**Comment by xuzhg** [comment]
@Shifu462 You mean it works fine with ODL 7.8.2, .NET Core 3.1?  
Which version are you using for this project (8.0)?

**Comment by Shifu462** [comment]
> @Shifu462 You mean it works fine with ODL 7.8.2, .NET Core 3.1?  
Yes, I get non-null values in action parameters with OData 7.8.2 and NET Core 3.1, and everything works fine.

> Which version are you using for this project (8.0)?
8.0.0-preview3

**Comment by Shifu462** [comment]
@xuzhg

Update (sorry for blurry screenshots):
I've noticed that with `[FromBody]` I get `null` both on `8.0.0-preview3` and `8.0.0-beta`:
![image](https://user-images.githubusercontent.com/17011936/112150909-acf44180-8bf1-11eb-9b9b-4e49e8eb0823.png)

But if I remove that attribute I get model bound as expected:
![image](https://user-images.githubusercontent.com/17011936/112150786-8afabf00-8bf1-11eb-8759-231683e4698e.png)

Not sure if that behavior is right, because it differs from the 7.x.x where `[FromBody]` parameters were non-null, but for now it becomes easier to migrate.
