### ISSUE TITLE
Using SearchBinder and BatchHandler together

### ISSUE THREAD

**Issue by flexwie** [OData/AspNetCoreOData#1169]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.2.3

**Describe the bug**
I try to use a custom batch handler and a custom SearchBinder together on the same route component. If I add both to the service provider, only the search binder is picked up and no matter what I do, I can't get the batch handler to work in this configuration.

```csharp
opt.AddRouteComponents(Constants.apiBaseUrl,
    EdmModelBuilder.GetEdmModel(),
    services =>
    {
        services.AddSingleton<ISearchBinder, EntitySearchBinder>();
        services.AddSingleton(sp => new ODataBatchHandler());
    });
```

I took the configuration for the batch handler from the `ODataOptions.cs` as there is no overload that allows to specify both te batch handler and a way to configure services.

However the only way I don't get a 405 response when I post to the `/$batch` endpoint, is if I use the overload for the `AddRouteComponents` function but then I loose the ability to add my search binder.

```csharp
var batchHandler = new ODataBatchHandler();

opt.AddRouteComponents(Constants.apiBaseUrl,
    EdmModelBuilder.GetEdmModel(),
    batchHandler);
```

I observe the same behaviour if I try to add the default batch handler to the service provider.

**Comment by julealgon** [comment]
This particular section is not making sense to me:
```csharp
services.AddSingleton(sp => new ODataBatchHandler());
```

`ODataBatchHandler` is an abstract class and thus cannot be instantiated: this code wouldn't compile.

https://github.com/OData/AspNetCoreOData/blob/f8a84cf9b9e0e597eb7b0c336d77c27506af8f89/src/Microsoft.AspNetCore.OData/Batch/ODataBatchHandler.cs#L20

Can you please double check and send the actual code you are using there @flexwie ?

**Comment by flexwie** [comment]
Sorry for the confusion, this was only to demonstrate that I am using a custom batch handler instead of the `DefaultODataBatchHandler`.

So I guess a better way to show it would be:

```csharp
services.AddSingleton(sp => new CustomODataBatchHandler());
```

**Comment by julealgon** [comment]
> Sorry for the confusion, this was only to demonstrate that I am using a custom batch handler instead of the `DefaultODataBatchHandler`.
> 
> So I guess a better way to show it would be:
> 
> ```cs
> services.AddSingleton(sp => new CustomODataBatchHandler());
> ```

Can you try this instead please @flexwie ?
```cs
services.AddSingleton<ODataBatchHandler>(sp => new CustomODataBatchHandler());
```

**Comment by flexwie** [comment]
This yields the same result, a POST request to `/$batch` returns a 405

**Comment by julealgon** [comment]
> This yields the same result, a POST request to `/$batch` returns a 405

Does this also happen if you remove your search binder and leave just the batch handler @flexwie ?

Because looking at the code for that other registration method, all it does is register the batch handler anyways... it shouldn't matter:
https://github.com/OData/AspNetCoreOData/blob/f8a84cf9b9e0e597eb7b0c336d77c27506af8f89/src/Microsoft.AspNetCore.OData/ODataOptions.cs#L115-L118

**Comment by flexwie** [comment]
Yes, same result. The code snipped you posted is where I drew the inspiration for my first solution, assuming that this would work. When debugging I can also see that there is no service for the batch handler registered.
Let me see if I can create a repro, it's a bit complicated to remove our business logic.
Anyways thanks for your help so far, @julealgon!

**Comment by flexwie** [comment]
Found the issue, our batch handler was lazily named `ODataBatchHandler` and shadowed the abstract `ODataBatchHandler`. That's why it wasn't picked up even when specifying the generic type.
Sorry for my oversight there but thanks a lot for your help!
