### ISSUE TITLE
ODataResourceSetDeserializer wrong cast

### ISSUE THREAD

**Issue by Xriuk** [OData/AspNetCoreOData#1171]
**Assemblies affected**
ASP.NET Core OData 8.x

**Describe the bug**
I was debugging your library for my hacky-things, and came onto this line:
https://github.com/OData/AspNetCoreOData/blob/f8a84cf9b9e0e597eb7b0c336d77c27506af8f89/src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceSetDeserializer.cs#L63

The last extension method seems to be this one:
https://github.com/OData/odata.net/blob/57572612f1ff833d395b44e6b2c498d7d0d31890/src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs#L2432-L2436

And it returns a `IEdmTypeReference` which get casted as `IEdmStructuredType` and it always results in null, since one is a type reference and the other is a type. Maybe it was an oversight?

**Comment by Xriuk** [comment]
Good point, I am not sure about that, but from what I have seen those two interface have different meanings model-wise and there _should not_ be a single type which implements both somehow.

**Comment by Xriuk** [comment]
Just to add to this, I'm able to read a collection as a property of an entity with `InputFormatter` (through `ODataResourceDeserializer`) but not the collection standalone (through `ODataResourceSetDeserializer`), and I highly suspect it is because of this null structured type.

**Comment by Xriuk** [comment]
So I cloned the project locally and managed to solve this by adding a `.Definition` at the end of the line, just as I thought it was missing:
```csharp
IEdmStructuredType structuredType = edmType.AsCollection().ElementType().Definition as IEdmStructuredType;
```
And now I can correctly read ResourceSets, maybe no one noticed this because there are not that much collection payloads being read?
This could use some tests and it should be good.

**Comment by julealgon** [comment]
Nice find.

You might want to consider sending a PR with that fix @Xriuk . Folks might then be able to help with any testing needed I think.

**Comment by habbes** [comment]
Thanks for reporting and investing that issue @Xriuk. I agree with @julealgon, you could contribute a PR and we'll review it.
