### ISSUE TITLE
How to forward OData request to backend service

### ISSUE THREAD

**Issue by slawomirpiotrowski** [OData/AspNetCoreOData#1176]
Is this possible to forward OData requests to backend service to be processed there?

My first attempt was to serialize ODataQueryOptions but it looks like it's not easily serializable. So I decided to forward an Url and recreate ODataQueryOptions inside my backend service (first HttpRequest, then ODataQueryContext and then ODataQueryOptions).

It looks like it works. I mean ODataQueryOptions gets created inside backend service and can execute the query on IQueryable (using all the parameters like $filter, $expand and so on).

But now I have another problem: How to pass it's reply back to my api server? Looks like the result of ODataQueryOptions.ApplyTo(IQueryable) is not easily serializable.

I think I could try to build the reply (Http response) in a way similar to what is usually done in OData controller and pass back Http response (probably as a string as Http response will most likely not be serializable either).

Is there any standard method to achieve something like that?

**Comment by julealgon** [comment]
There is nothing native that cleanly supports this.

Being able to serialize and easily transfer OData queries is a goal of OData.Neo:
- https://github.com/OData/OData.Neo

> My first attempt was to serialize ODataQueryOptions but it looks like it's not easily serializable. So I decided to forward an Url and recreate ODataQueryOptions inside my backend service (first HttpRequest, then ODataQueryContext and then ODataQueryOptions).
>
> It looks like it works. I mean ODataQueryOptions gets created inside backend service and can execute the query on IQueryable (u1sing all the parameters like $filter, $expand and so on).

This is what I'd do as well.

> But now I have another problem: How to pass it's reply back to my api server? Looks like the result of ODataQueryOptions.ApplyTo(IQueryable) is not easily serializable.

Now you got me confused. You want to have something other than the API processing your query, but still respond on the same API request? Why would you want to do something like this?

Depending on what you are attempting to do here, I'd suggest using events instead, and potentially looking into Reaqtor:
- https://reaqtive.net/

**Comment by robertmclaws** [comment]
Yeah I'd love to understand more specifically what the architecture is here.

1) Part of the way it is phrased is making it sound like you need something like [YARP](https://github.com/microsoft/reverse-proxy) as a reverse-proxy, but I don't think that's what you're really looking for.

2) [Restier](https://github.com/OData/Restier) is an API platform designed to execute OData queries, provide EntitySet-level security by running Filters on NavigationProperties (so you don't accidentally return more data than you should through "traversal attacks"), and triggers events post-request.

If you remember WCF Data Services back in the day, it's the same thing. I help manage that project, and also use it in all my apps.

3) If you're just looking for something that can finish executing other processes after an OData API controller processes the query, you can take a look at [SimpleMessageBus](https://github.com/CloudNimble/SimpleMessageBus). It's similar to RabbitMQ but is designed on top of the Azure Functions runtime and can be deployed locally or in the cloud.

4) If you're wanting to have OData URLs craft a LINQ query, serialize the query _parameters_, and then forward those results over HTTP to a totally different API to be processed... then I would need to understand the requirements to evaluate if what you're looking to do is the right approach.

Let me know which one it's the closest to and I'll see if I can help.

**Comment by slawomirpiotrowski** [comment]
Thanks for all the replies and links you gave me.

Reverse proxy would be tricky as I don't think it's possible to put HTTPS service inside Orleans grain. I could build aspnetcore web service that is using Orleans as it's backend but it would require serialisation too (and in fact it's more or less what we are trying to do now).

OData.Neo looks like it's not finished (?) and Restier relies heavily on Entity Framework (we have our data in IQueryable, but not using Entity Framework).

Not sure if Reaqtor would help us here. I think it needs to serialize everything as well as Orleans so would finish with very similar problems.



My plan is to execute the query on another computer (server farm). So I'd like to forward OData query by some other mean to another computer, process it there and send the reply back to be sent by HTTPS. Current plan is to put our backend service in a grain inside Orleans silo as most of the application logic is built inside Orleans grains (their ability to keep recently used data in RAM, distributed beetween servers is amazing, especially for application requiring a lot of reads and not allowing to return stale data when source has just changed and something was cached), but it could be a server farm processing requests by RabbitMQ or anything else.

The point is that backend service has access to all the data of the tenant that request belongs to (and it's already formatted in a way that allows OData library to process even $expand parameters). But we need to forward the request somehow and send the reply back. Forwarding the requests as an Url in a string already works. Unfortunatelly result of ODataQueryOptions.ApplyTo consists of some classes internal to OData (in namespace Microsoft.AspNetCore.OData.Wrapper). Those classes are not serializable (even if I tell Orleans to use Newtonsoft serialiser).

I think OData library has to generate Http string response somehow. I hoped it was possible to generate that reply inside our backend service and serialise that reply as a string. In our initial plan it was assumed it should be an easy task, but somehow I can't find a way to do that.



An obvious another way would be to not use Microsoft.AspNetCore.OData, just bare Microsoft.OData.Core. Unfortunatelly this library is not that easy to use. We can't simply give it OData parameters as string and expect the reply as a string too. Guess we'd need to duplicate a lot of code from ODataQueryOptions to support all the query parameters.



Backup plan would be to not use OData at all. Instead switch to GraphQL and check if there is a library that support GraphQL than allows forwarding of the requests beetween computers. It should be as GraphQL is not that tied to HTTP(S) transport. But that would mean changing a lot of already working code. I think in our current place sending OData reply as a string should be much easier to do.

**Comment by robertmclaws** [comment]
Thanks for that additional information. Restier is not dependent on Entity Framework at all. You can use it with any IQueryable, it doesn't matter where it came from. It just might take a little setup to get working, but it would certainly work.

However, it sounds like there would potentially be multiple serialization / deserialization hops between the back-end and the front-end... (client <=> server <=> server) which is certainly not ideal. That could cause a BIG performance issue.

I would need to understand a little bit more about the specifics of the situation in order to give more useful advice. What's the time frame you're working on?

**Comment by julealgon** [comment]
> OData.Neo looks like it's not finished (?)

Correct.

After reading your context, it all seems kinda crazy to me... if you are not _extremely_ careful, this could introduce a ton of performance problems and latency. It would probably be a good idea to use something like gRPC to send/receive the request in that context.

I think you _should_ be able to serialize the payload though somehow using the same classes that OData uses in a normal MVC project. Can't you just take the formatter and call it manually? You are correct in that OData has some classes that don't rely on "normal" serializers, but that shouldn't matter if you can just tap into the main abstraction it uses in web apps to perform the whole serialization.

I'd start with these 2 classes here probably:
- https://github.com/OData/AspNetCoreOData/blob/65ddb10cbe42822e94f467b293395abd1fddd33a/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterFactory.cs#L19
- https://github.com/OData/AspNetCoreOData/blob/65ddb10cbe42822e94f467b293395abd1fddd33a/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs#L35

It does look like you'll have to force some fake request information and a fake `ODataFeature` though.

**Comment by slawomirpiotrowski** [comment]
Thanks for your replies.

I am aware that my architecture leads to dual serialization. But in fact it shouldn't be that bad as URL is quite short and serializing strings is fast. Serializing the reply is worse, but still our client side code takes care to avoid requesting a lot of data (uses paging and so on) so amount of serialized data is reasonably sized (with exception of exporting the data, but export is allowed to be slow).

In fact decision about using Orleans as backend framework means that everything will be serialized everywhere. It's the cost of virtual actor framework. We just need to avoid sending large amounts of data beetween grains.

But I think reverse proxy would be better in fact as it could avoid additional serializations. We could install Kestrel on all of our Silo servers and allow each of them to execute calls locally by retrieving IQueryable directly from the grain without serialization at all (mark it as read only, as far as I understand Orleans avoids serialization if call is local and parameters are read only). This way IQueryable would be available in local Kerstrel controller (on the Silo server) without seiralizing it's contents and we could execute OData by the book (using [EnableQuery]).

Silo servers are not addressable on public internet so we would need to find a way to check where given grain is activated and use it dynamically in our custom reverse proxy. So this reverse proxy would work as Orleans client and call Orleans library to find out where given grain is activated, find out associated HTTPS (or HTTP as it's on private network) endpoint and forward the HTTPS request to proper Silo server as HTTP request. Would need to detect edge case situations like grain just got deactivated and need to find where it is now and retry redirecting.

This should be possible but I'm not sure if difference in efficiency would justify complication.

I think I'll try to use ODataOutputFormatter first and if it works then I'd execute performace tests to check if I'm ok with it. I'll only work on custom reverse proxy if either using output formatters fails completly or if efficiency is too bad for our needs.

**Comment by julealgon** [comment]
> I have a small problem with links returned by OData library (@context, $metadata). I need to fix them inside my proxy. Is this possible to tell OData to generate links using different server in them? I'd prefer to let backend OData service generate links that point to reverse proxy so I'd not need to fix them inside the proxy.

Check the forwarding headers middleware, which is supposed to fix that kind of issue:
- [Configure ASP.NET Core to work with proxy servers and load balancers - Forwarded headers](https://github.com/diasurgical/devilutionX/issues/6992)

Not sure they will resolve your particular scenario though, but it's worth a try.

**Comment by slawomirpiotrowski** [comment]
Sorry for the delay but we have had a lot of other problems that needed fixes before I could confirm if it works. So now I can confirm that x-forwarded-for header works. So in short using reverse proxy to redirect odata requests to the silo where destination grain is activated works. Thanks for your help!

**Comment by julealgon** [comment]
Glad to hear that ended up working for you scenario @slawomirpiotrowski !
