### ISSUE TITLE
Contribution to the project

### ISSUE THREAD

**Issue by andrei-galkin** [OData/AspNetCoreOData#118]
Hi guys,
I have created ODataRoutingSample.Tests as the example how to unit test a controller method which supports odata and I am thinking this will be useful for the devs. 
Can I contribute to the project and how?
I tried to publish my branch but it seems I do not have the access to do that.

Please advice can I contribute and how or I can not.

Thank you
Andrei

**Comment by xuzhg** [comment]
@andrei-galkin You can fork the repository and do your work at your "local/fork" repository. Typically, you create branch at your "local/fork". When your development is finished, you can back here and create a PR for us. 

![image](https://user-images.githubusercontent.com/9426627/112933783-5f864180-90d5-11eb-87a5-ca12166bca3e.png)

I am looking forward your contribution.
