### ISSUE TITLE
Unwanted $count endpoint

### ISSUE THREAD

**Issue by SMAH1** [OData/AspNetCoreOData#1184]
**Assemblies affected**
 ASP.NET Core OData 8.2.5

**Describe the bug**
See $count endpoint in Controller after update from version ASP.NET Core OData 7 to ASP.NET Core OData 8

**What happened?**
I had _dotnet core (version 6)_ project with _ASP.NET Core OData 7.6.5_. **Everything is fine** (endpoint, swagger, ...).
I Try update to _ASP.NET Core OData 8_. After Update by `NUget` and change `startup.cs` see swagger.
There were **some** controllers with `$count endpoint` like this:

![DESC](https://github.com/OData/AspNetCoreOData/assets/21136680/d8fe7306-82f4-4870-88bf-74ef0bc3ce63)

but some controllers were find.
I test `$count endpoint` and that is work (appears in Swagger doc and work)!
I compared two controllers with/without this bug.
I found:

> When use function like `Get<CONTROL ENDPOINT>` in control, appears `$count endpoint`.

see below images:

![ERROR](https://github.com/OData/AspNetCoreOData/assets/21136680/9fd9c72c-78c1-4be0-a4f7-f03562ede128)

![OK](https://github.com/OData/AspNetCoreOData/assets/21136680/f9689ae1-cfb4-457a-91c6-e2f3e2357128)

**Comment by julealgon** [comment]
@SMAH1 are you sure these endpoints weren't already exposed in your API, just not showing in Swagger? Can you try making a request to one of them from outside Swagger and see if they respond?

Also, you can double check your endpoints using the `$odata` debug endpoint as explained in the readme.

Avoid using the Swagger view as a source of truth.

**Comment by SMAH1** [comment]
I am sure these endpoints weren't already exposed in your API.
in older version is not available (Below image for older version that use now).

![image](https://github.com/OData/AspNetCoreOData/assets/21136680/1c4a98b7-bc1b-4036-9fc6-e687a08a1c8f)

In first time I thought Swagger showed extra API. I tested that API (and use breakpoint in code). Two extra APIs are worked.

I check `debug endpoint`.
Only **Two extra APIs** are in **OData Endpoint Mappings**, Other APIs are **Non-OData Endpoint Mappings**.
I define ‍EDM model‍ But it doesn't seem to work.

**Comment by SMAH1** [comment]
@https://github.com/OData/AspNetCoreOData/issues/649#issuecomment-1195970221
It seems that this is not a bug and that is exactly how it was implemented.

**Comment by julealgon** [comment]
> I am sure these endpoints weren't already exposed in your API. in older version is not available (Below image for older version that use now).
> 
> ![image](https://private-user-images.githubusercontent.com/21136680/309986261-1c4a98b7-bc1b-4036-9fc6-e687a08a1c8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTA5MDIsIm5iZiI6MTcwOTY1MDYwMiwicGF0aCI6Ii8yMTEzNjY4MC8zMDk5ODYyNjEtMWM0YTk4YjctYmMxYi00MDM2LTlmYzYtZTY4N2EwOGExYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0NTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NjZmODI0M2M4MTNiZjM3OGJkNWE0YzkxZDgyMjE1MjZjNDMwZDkxZTJlOWQ5OGM1NzNkM2FiZDQxNWRkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pEWxT8dwBWU-TgryRaYtn94_OQoMB5vuIIsIBLEk00w)

Again, you are using the Swagger UI as your source of truth for which endpoints are available. This is a bad idea as Swagger also progressed over time to be more comprehensive.

Use the `$odata` endpoint for double checking routes instead.

> I check `debug endpoint`. Only **Two extra APIs** are in **OData Endpoint Mappings**, Other APIs are **Non-OData Endpoint Mappings**. I define ‍EDM model‍ But it doesn't seem to work.

Non-OData endpoints mean you have something wrong in your mapping that is making OData not be able to match with the EDM information. Feel free to provide more information about it so we can help.

> @[#649 (comment)](https://github.com/OData/AspNetCoreOData/issues/649#issuecomment-1195970221)
> It seems that this is not a bug and that is exactly how it was implemented.

I fail to see how that comment addresses your issues though. Up to you however if you want to bring more information here.
