### ISSUE TITLE
Passing OData query options in request body

### ISSUE THREAD

**Issue by vistnesr** [OData/AspNetCoreOData#119]
Hi,

In version 7.5, it was possible to pass query options in the request body:
https://docs.microsoft.com/en-us/odata/webapi/query-options-in-request-body.

This does not seem to work in 8.0-beta.

Am I doing something wrong, or has it not yet been implemented?

**Comment by xuzhg** [comment]
That's not ported from 7.x. 
@gathogojr Would you please help on it?

**Comment by gathogojr** [comment]
Hi @xuzhg. It's long overdue. I have created a work item for it and will get started on it right away

**Comment by xuzhg** [comment]
@gathogojr don't worry, I am almost done. Will share a link for you review.

**Comment by xuzhg** [comment]
@gathogojr here it is: https://github.com/OData/AspNetCoreOData/commit/31fa96022390048c13146241408afd8287fb41a1

Based on your implementation in 7.x, i made some changes. please take a look and let me know your thoughts. 

By the way, https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs#L231 is for you. :)

**Comment by xuzhg** [comment]
@vistnesr You can try this feature in the latest nightly. Please let us know your questions.

**Comment by gathogojr** [comment]
> @gathogojr here it is: [31fa960](https://github.com/OData/AspNetCoreOData/commit/31fa96022390048c13146241408afd8287fb41a1)
> 
> Based on your implementation in 7.x, i made some changes. please take a look and let me know your thoughts.
> 
> By the way, https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs#L231 is for you. :)

Will take a look and revert.
_DollarQueryTests.cs_ contains the tests for the $query feature and I see you already migrated it over.

**Comment by vistnesr** [comment]
> @vistnesr You can try this feature in the latest nightly. Please let us know your questions.

I just tried the latest nightly and it works. I looked over the code, too, and I like the way it was implemented.

Thanks for the quick response @xuzhg

**Comment by gathogojr** [comment]
Feature ported to 8.x via https://github.com/OData/AspNetCoreOData/commit/31fa96022390048c13146241408afd8287fb41a1
