### ISSUE TITLE
Attribute Routing doesn't works on  8.0.0 Preview

### ISSUE THREAD

**Issue by rahul7720** [OData/AspNetCoreOData#12]
Consider following controller class:  
```
[Route("api/[controller]")]
[ApiController]
public class StudentsController: ODataController
{
   ...
}
```
Attribute routing stopped working after upgrading the Microsoft.AspNetCore.OData Nuget package version to 8.0.0. Preview from version 7.5.0

**Comment by xuzhg** [comment]
@rahul7720 what's your attribute, i can't find it from your sample code.

Actually, attribute routing in OData is using:

1) ODataRoutePrefixAttribute
2) ODataRouteAttribute

Do you use them in your project?

Here's an example: https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/AttributeRoutingConventionTests.cs#L177-L178

**Comment by rahul7720** [comment]
@xuzhg 
I'm decorating the odata controller with `ApiControllerAttribute` in order to leverage the advantages of it like:

1. automatic model state validation
2. binding source parameter inference (To avoid attributes like [FromBody] on method parameters)

Since `ApiControllerAttribute` requires an endpoint routing, I have decorated the OData controller with 'RouteAttribute'

How can I achieve my requirement with the  version 8.0.0?

**Comment by xuzhg** [comment]
for "binding source parameter inference (To avoid attributes like [FromBody] on method parameters)", you can add the model binding attribute on the [FromBody] parameter type, so you can avoid [FromBody].

For your scenario, can you add the route attributes all in your controller to see the result?

**Comment by rahul7720** [comment]
@xuzhg  
1. "you can add the model binding attribute on the [FromBody] parameter type, so you can avoid [FromBody]" - Can you please provide a short example?
2. I don't wan to check `ModelState.IsValid` on POST, PUT methods, instead I want that to happen automatically. `[ApiController]` took care of the Model State validation automatically. What is the alternative in 8.0.0?

**Comment by xuzhg** [comment]
1) https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Formatter/ODataActionParameters.cs#L14

2) I mean you can use [ApiController] and [ODataRouteAttribute] together on the action or controller.

**Comment by rahul7720** [comment]
@xuzhg 

Using  [ApiController] and [ODataRouteAttribute] together on the action throws runtime exception when program starts:
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
```
_Action 'TestProject.Controllers.StudentsController.Get (TestProject)' does not have an attribute route. Action methods on controllers annotated with ApiControllerAttribute must be attribute routed._

**Comment by sag3ll0** [comment]
I prepared a (test project](https://github.com/sag3ll0/OData8NetCore5Test) to demonstrate my problem, which is that if you do not use the `ApiController` attribute, the `POST` request does not correctly receive input parameters. Added a description of the problem in the project.
If not use `ApiController` attribute in controller i get null value.
![null](https://user-images.githubusercontent.com/18505406/100337800-e375d300-2fe8-11eb-8190-ce5a156fef9f.png)

If enable `ApiController` and disable odata its will ok.

**Comment by xuzhg** [comment]
@sag3ll0 Sorry for delay. The failing is related to the case sensitive.
I replied it to you at https://github.com/sag3ll0/OData8NetCore5Test/issues/1

Thanks for your question. 
By the way, I changed the attribute routing strategy. 
If you are interested in, you can refer to https://devblogs.microsoft.com/odata/attribute-routing-in-asp-net-core-odata-8-0-rc/
and leave any comments for me. Thanks.
