### ISSUE TITLE
Odata 8 RC IODataRoutingMetadata removes HttpMethods breaking Troubleshooting helper service

### ISSUE THREAD

**Issue by ramious76** [OData/AspNetCoreOData#120]
The Readme.md on creating the ODataRouteHandler.HandleOData utilizes IODataRoutingMetadata.HttpMethods. On the RC that was just released this interface is no longer available and removes a column from the troubleshooter route listings. I find this considerably helpful with some troubleshooting I am currently doing that a blazor dotnet 5 backend is not creating the routes for the OData links. I had to roll back the OData from 8 Release Candidate to Preview 3 and got the interface back that was referenced.

` IODataRoutingMetadata metadata = endpoint.Metadata.GetMetadata();

....

string httpMethods = string.Join(",", metadata.HttpMethods); //Fails to resolve here from missing HttpMethods
sb.Append($"{httpMethods}");
`

Well...doesn't exactly break it but seeing the registered http methods is nice.

**Comment by ramious76** [comment]
The Readme.md on creating the ODataRouteHandler.HandleOData utilizes IODataRoutingMetadata.HttpMethods.  On the RC that was just released this interface is no longer available and removes a column from the troubleshooter route listings.  I find this considerably helpful with some troubleshooting I am currently doing that a blazor dotnet 5 backend is not creating the routes for the OData links.  I had to roll back the OData from 8 Release Candidate to Preview 3 and got the interface back that was referenced.

**Comment by xuzhg** [comment]
@ramious76 

Thanks for trying this.
"HttpMethods" is never used again, so I removed it. You can use https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataSampleCommon/ODataEndpointController.cs#L116-L125 to replace it.  I also updated all samples in the repo. 

Typically, "ODataRouteHanlder.HandleOData" is replaced with a  controller. You can find this controller at:

https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataSampleCommon/ODataEndpointController.cs

It has the similar "$odata" functionality, but, you don't need to call "MapRoute(....)" again in the startup.cs.
Just copy/paste the controller into your project, it works automatically. 

I also used it in my e2e test troubleshotting, see here: https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.E2E.Tests/DynamicProperties/DynamicPropertiesTest.cs#L28-L42

Looking forward your feedbacks.

**Comment by RobTF** [comment]
Hi @xuzhg,

I'm trying to update to the RC as well and ran into this too - I see the current code has a middleware for this and an extension, `app.UseODataQueryRequest();` for using it. This doesn't appear to be in the RC however, will this be present going forward?

thanks

**Comment by xuzhg** [comment]
@RobTF Maybe I am confusing.
`app.UseODataQueryRequest()` is to support `$query` ( see [here](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_PassingQueryOptionsintheRequestBody) feature.  It's a new extension method designed and implemented **after** RC release.  So, it's not in RC version. (I'd like to iterate the release quickly, so it will be available sooner in RC2?)

@ramious76 's question is related to a debug functionality using "$odata". the codes are located in sample (not in product), because we originally thought it's not part of the product. Do you think it's better to:

1) put the routing table codes in product
2) provide an extension method 'app.UseDollarOData()' to disable/enable "$odata"? 

So, customer can do:

```C#
if (env.IsDevelopment())
{
      app.UseDeveloperExceptionPage();
      app.UseDollarOData();
}
```

**Comment by RobTF** [comment]
Ah yes my mistake! I didn't look properly I just glanced at it and assumed that was it in the routing sample as I couldn't see that controller. Your proposal sounds great to me, maybe call it something like `UseODataRouteDebug()` perhaps?

I think as the debugger is so useful for so many people (we use it on all of our APIs in development) that adding it to the product as an optional middleware would be worth it.

**Comment by xuzhg** [comment]
@RobTF @ramious76 Let me know your thought about **https://github.com/OData/AspNetCoreOData/commit/9b14682c5125fdabe55b1eeb9918ce51785adf88**

**Comment by RobTF** [comment]
Looks perfect to me :)

**Comment by ramious76** [comment]
Awesome.  Thank you!
