### ISSUE TITLE
Passing a Complex object in the ODATA function

### ISSUE THREAD

**Issue by dalip-negi-tfs** [OData/AspNetCoreOData#1210]
I have requirement to get a response like : 
{
    "configuration": [],
    "fullInformation": [],
    "serverInformation": {
        "Date": "",
        "ExpirationDate": "",
        "Numbers": "1,2",
        "error": "None",
        "mode": "test"
    },
    "summary": {
        "Flags": [
            {
                "Id": "1223",
                "Total": 0,
                "InUse": 0,
                "Active": 0
            },
            {
                "Id": "3445",
                "Total": 0,
                "InUse": 0,
                "ActiveI": 0
            }
        ]
    }
}

and the request payload is : 
{
    "RequiredConfiguration": true,
    "Configuration": [],
    "RequiredFullInformation": true,
    "FullInformation": [],
    "ServerInformation": true,
    "RequiredSummary": true,   
    "RequiredConnectionCheck": false
}
how to pass complex object as request payload in ODATA Function or any other way is there in ODATA

**Comment by julealgon** [comment]
Use the "Discussions" area for questions.

**Comment by xuzhg** [comment]
@dalip-negi-tfs See comments at https://github.com/xuzhg/WebApiSample/blob/main/v8.x/FunctionTest/readme.md

**Comment by corranrogue9** [comment]
@xuzhg  can you please update your doc to remove the sample that puts the complex type in the request body (unless `$query` is used)?

**Comment by xuzhg** [comment]
> @dalip-negi-tfs See comments at https://github.com/xuzhg/WebApiSample/blob/main/v8.x/FunctionTest/readme.md

Updated: 

It's not recommended to use Request body to pass the function parameter value.  OData specs say:

**To invoke a function through a function import the client issues a GET request to a URL identifying the function import and passing parameter values using [inline parameter syntax](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_InlineParameterSyntax)."**


**Parameter values passed to functions MUST be specified either as a URL literal (for primitive values) or as a JSON formatted OData object (for complex values, or collections of primitive or complex values).** 

We'd recommend to use the OData action (not odata function) and send your action parameter through the action request body.

**Comment by dalip-negi-tfs** [comment]
thanks for the inputs
