### ISSUE TITLE
Data not loaded correctly in Excel and Power BI Desktop with the use of $expand in OData feed

### ISSUE THREAD

**Issue by peterkovecses** [OData/AspNetCoreOData#1219]
I am using .NET 8 with Microsoft.AspNetCore.OData 8.2.5 package.
When I use an OData feed URL containing an $expand query in Excel or Power BI Desktop applications, only the expanded columns appear in the results.
For example, when using a URL like https://localhost:7289/odata/Books?$expand=authors only the author-related columns are displayed, while other columns from the Books entity are not loaded correctly.

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/631139c2-7c39-4cd0-9c03-385d55c6fe36)

I expect all columns from the Books entity to be loaded, not just the ones specified in the $expand query. 

I'm currently experiencing this behavior with every current version of the OData API. A few days ago, data loading was working perfectly with all APIs and nothing has been changed in the code. This leads me to believe that the issue might not lie within the specific implementation, but possibly within the OData service or the client applications (Excel and Power BI Desktop).

I have found a temporary workaround by first loading the data without $expand and then loading the expanded columns afterwards. However, this is less convenient for our users compared to the previous method, especially when the $expand query contains filters.

https://localhost:7289/odata/Books

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/1a8583e4-eb2a-4de8-a70e-fae85329809b)

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/a8e57162-95b6-49f6-8975-9bad35834d2f)

**Comment by julealgon** [comment]
Can you provide the code for your API and the JSON results you are getting when calling it directly?

**Comment by julealgon** [comment]
@peterkovecses I see nothing wrong with that payload you shared.

Do you have any means to grab a similar payload from the version you mentioned was working before so we can compare?

> A few days ago, data loading was working perfectly with all APIs and nothing has been changed in the code. 

If not even package versions have changed, I don't see how the problem would be in the OData library at all.

The only other thing I would personally try here would be to add an explicit `$select=*` to your `$expand` query and see if that changes the behavior on the Excel/PowerBI side at all.

**Comment by peterkovecses** [comment]
@julealgon this is the source code for another OData API of mine: https://github.com/peterkovecses/ODataDemo

When I use the following request: https://localhost:7092/odata/books?$expand=authors,priceoffers
I similarly only see the expanded columns:

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/3385f26e-e6bc-4489-a33a-f5b881dc7ee5)

This is the JSON result:
`{
    "@odata.context": "https://localhost:7092/odata/$metadata#Books(Authors(*),PriceOffers(*))",
    "value": [
        {
            "Id": 1,
            "Title": "Refactoring: Improving the Design of Existing Code",
            "Price": 40,
            "Authors": [
                {
                    "Id": 1,
                    "Name": "Martin Fowler"
                }
            ],
            "PriceOffers": [
                {
                    "Id": 1,
                    "Price": 30,
                    "BookId": 1
                },
                {
                    "Id": 6,
                    "Price": 28,
                    "BookId": 1
                }
            ]
        },
        {
            "Id": 2,
            "Title": "Clean Code: A Handbook of Agile Software Craftsmanship",
            "Price": 50,
            "Authors": [
                {
                    "Id": 2,
                    "Name": "Robert C. Martin"
                }
            ],
            "PriceOffers": [
                {
                    "Id": 2,
                    "Price": 35,
                    "BookId": 2
                }
            ]
        },
        {
            "Id": 3,
            "Title": "Code Complete: A Practical Handbook of Software Construction",
            "Price": 60,
            "Authors": [
                {
                    "Id": 3,
                    "Name": "Steve McConnell"
                }
            ],
            "PriceOffers": [
                {
                    "Id": 3,
                    "Price": 45,
                    "BookId": 3
                }
            ]
        },
        {
            "Id": 4,
            "Title": "The Art of Agile Development",
            "Price": 45,
            "Authors": [
                {
                    "Id": 1,
                    "Name": "Martin Fowler"
                },
                {
                    "Id": 2,
                    "Name": "Robert C. Martin"
                }
            ],
            "PriceOffers": [
                {
                    "Id": 4,
                    "Price": 40,
                    "BookId": 4
                },
                {
                    "Id": 5,
                    "Price": 40,
                    "BookId": 4
                }
            ]
        }
    ]
}`

A few days ago, as with the other application I showed earlier, all columns were present in the result.

I have also tried your suggestion (not sure if this is exactly what you had in mind): https://localhost:7092/odata/books?$select=*&$expand=authors,priceoffers

Unfortunately, this still did not produce the desired result, as while it did load the previously missing columns, it did not load the expanded columns.

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/df236011-04c7-4005-8dea-7f52883c573a)

**Comment by julealgon** [comment]
> I have also tried your suggestion (not sure if this is exactly what you had in mind): https://localhost:7092/odata/books?$select=*&$expand=authors,priceoffers
> 
> Unfortunately, this still did not produce the desired result, as while it did load the previously missing columns, it did not load the expanded columns.

This is a surprising result to me...... can you try this then?
- `https://localhost:7092/odata/books?$select=*,authors,priceoffers&$expand=authors,priceoffers`

I have no idea what exactly is going on here but I initially suspected it could be the `@odata.context` value that could be influencing the behavior on the consumer side.

**Comment by peterkovecses** [comment]
> * https://localhost:7092/odata/books?$select=*,authors,priceoffers&$expand=authors,priceoffers

Unfortunately, that doesn't work either:

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/058e1eb5-eef4-4ec8-bec6-41c4d29e50d3)

However, I have a thought. A one or two weeks ago, I started facing another issue. The same thing happened as in this case - I didn't change anything in the code, and the Excel/Power BI process that had been working led to an error. This was also related to $expand queries:

Steps: 
url: https://localhost:7092/odata/books?$expand=authors

It used to load all columns. Then, clicking not on the Transform Data button, but on the Load button also worked. When this issue appeared, it still loaded all the data (displayed all columns), but clicking the Load button led to an error message. I would also like to note here that I have experienced this in the case of any current version OData application. 

Here's an example from Excel: [screenshot]

![image](https://github.com/OData/AspNetCoreOData/assets/89272499/7baf41ed-c7af-4503-847e-1a824bef4f56)

A little interesting fact: when I tested it yesterday, the Load function worked once with the same url, unchanged code. It's not working again today.

The common in the two errors are the $expand query and the fact that in both cases the process was working flawlessly, then from one day to the next without any code modification it was not. I could think of some Power Platform updates that might cause these issues.

**Comment by corranrogue9** [comment]
@peterkovecses you said in the original description:
> A few days ago, data loading was working perfectly with all APIs and nothing has been changed in the code.

Does this mean that you were able to load the data into excel using the same endpoint URL and you received all of the rows and columns that you expected? It's very strange for this to stop working without any changes on the service side, especially because the response payloads you provided [here](https://github.com/OData/AspNetCoreOData/issues/1219#issuecomment-2066552486) and [here](https://github.com/OData/AspNetCoreOData/issues/1219#issuecomment-2067039045) look correct from the OData side. 

It seems like this is an issue on the excel or powerBI side if you are receiving the same OData response payload but the data is not being formatted the way that you expect it to be each time. I would suggest filing a bug with those teams.

**Comment by peterkovecses** [comment]
Thank you @julealgon, @corranrogue9 I close the issue.

**Comment by julealgon** [comment]
@peterkovecses we should prefer "closing as not planned" for this instead of "closing as completed". This avoids confusion for folks looking at the issue later and thinking something might have been fixed/implemented in the OData side.

**Comment by peterkovecses** [comment]
@julealgon ok, I corrected it.

**Comment by peterkovecses** [comment]
@julealgon  ok, I corrected it.
