### ISSUE TITLE
Function composability question

### ISSUE THREAD

**Issue by RobTF** [OData/AspNetCoreOData#122]
Hi all,

A quick question on composability;

If I have an entity, `User` and I have the following function;

```csharp
builder.EntitySet<User>("Users")

var getUsersByAccount =
        builder.EntitySet<User>("Users")
        .EntityType
        .Collection
        .Function("GetByAccount")
        .ReturnsFromEntitySet<User>("Users");
getUsersByAccount.Parameter<int>("AccountId").Required();
```

Then let's say I can use
`/Users/`
to get all users, or
`/Users/GetByAccount(123)/`
to query for users within an account only.

Now, imagine I want to add an action to a user, `MarkAsFavourite`. I might do this;

```csharp
builder.EntitySet<User>("Users")
        .EntityType
        .Action("MarkAsFavourite");
```

I can then do this
`/Users(456)/MarkAsFavourite()`

but how can I allow for
`/Users/GetByAccount(123)/456/MarkAsFavourite()`
or possibly something like
`/Users/GetByAccount(123)(456)/MarkAsFavourite()`
?

How would I go about making it such that any path which resolves to a single `User` entity allows me to compose further to access the actions available on the `User` type? Is this supported? Does any further work need to be done other than just making the function composable? I can't quite seem to get it to work.

Thanks

**Comment by xuzhg** [comment]
@RobTF I added your scenario into the routing sample. See https://github.com/OData/AspNetCoreOData/commit/93a4f5294dc03fde2dc241f7f25bdfadb8c48f3a.

**Comment by RobTF** [comment]
Thanks @xuzhg!

Your sample works, but I'm not sure it makes 100% sense as I would imagine you would mark a specific organization as a favourite, but your function appears to be on the collection itself?

e.g.
v1/Organizations/GetByAccount(accountId={aId})/**{id}**/MarkAsFavourite
or
v1/Organizations/GetByAccount(accountId={aId})**({id})**/MarkAsFavourite

Does that make sense?

**Comment by xuzhg** [comment]
@RobTF See this new sample: https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Controllers/v1/OrganizationsController.cs#L120-L128

It works fine with `v1/Organizations/GetByAccount(accountId={aId})/{id}/MarkAsFavourite`

but, ODL throws except for invalid path for `v1/Organizations/GetByAccount(accountId={aId})({id})/MarkAsFavourite`.

But, it think at least one is working.

Be noted, the return function call in model builder is different. See detail here: https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Models/EdmModelBuilder.cs#L105

**Comment by KenitoInc** [comment]
@RobTF Was the issue resolved?

**Comment by xuzhg** [comment]
Please file new issues if you have further concerns. Thanks.
