### ISSUE TITLE
Casting segment to `KeySegmentTemplate` invalidates the use of Custom segment with `Kind == ODataSegmentKind.Key`

### ISSUE THREAD

**Issue by Leandro-Albano** [OData/AspNetCoreOData#125]
O the ODataDynamicModel sample it shown how to dynamically build the EdmModel.

One of the elements, `EntitySetWithKeyTemplateSegment` shows how to deal with the key segment, but it is actually set with `Kind == ODataSegmentKind.EntitySet`. 

If we change that to `ODataSegmentKind.Key` then we get a NullReferenceException, and that is because on [ODataPathTemplate](https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Routing/Template/ODataPathTemplate.cs#L73) there is a explicit cast to `KeySegmentTemplate`, although later on the `AppendKeyTemplate` does not use anything specific from `KeySegmentTemplate`.

My proposal is to remove that cast so any custom segment of `ODataSegmentKind.Key` kind can also automatically get both segment and parenthesis key feature according to `ODataRouteOptions`.

**Comment by xuzhg** [comment]
@Leandro-Albano When I worked on the DynamicModel sample, i noticed this "problem". 
In my future plan, I want to remove the "Kind" property, (also as IsSingle).

Your proposal is to remove 'KeySegmentTemplate keySg = segment as KeySegmentTemplate;' , would you please share more about how to generate the key segment if we remove this cast?

Besides, I marked the `public virtual IEnumerable<string> GetTemplates(ODataRouteOptions options = null)` as virtual, so, if current GetTemplates method can't match your requirement, you can derived from `ODataPath` and override `GetTemplates`

let me know your thougths?

**Comment by Leandro-Albano** [comment]
Hi @xuzhg, first of all, thanks for this quick reply.

So I added a pull request about how I think it may work. Maybe I'm missing something that can go wrong down in the pipeline.
Let me know what you think.

**Comment by xuzhg** [comment]
@Leandro-Albano Now, I got your idea. I merged your PR and Thanks for your contribution. Looking forward to more contribution. 
😄
