### ISSUE TITLE
Disabling Automatic Expansion in Nested OData Entity Objects

### ISSUE THREAD

**Issue by anjanasagathiya** [OData/AspNetCoreOData#1268]
**Subject:** Disabling Automatic Expansion in Nested OData Entity Objects

**Problem Description:**

We are using AspNetCoreOData version 7.20.0 and need to disable the automatic expansion of nested objects in our OData entities. Here FYI, the data retrieval is from a single table.

**Example** Below is an example illustrating the issue.

```
Public class OdataEntity
{
  [DataMember(Name = "id")]
  public long Id { get; set; }
  
  [DataMember(Name = "credit_memo")]
  public CreditMemo CreditMemo { get; set; }
}

[ComplexType] 
[DataContract]
public class CreditMemo
{
   [DataMember(Name = "id")]
   public long Id { get; set; }

   [DataMember(Name = "name")]
   public string Name { get; set; }
}

```
In the above OdataEntity, we want to prevent the automatic expansion of the CreditMemo object. If the user explicitly includes $expand=CreditMemo in the OData query, then the CreditMemo object should be included in the response.

Could you please guide us on how to achieve this?

We appreciate any insights or solutions that can help resolve this issue efficiently.

**Comment by WanjohiSammy** [comment]
@anjanasagathiya `ComplexType` cannot be directly used as a navigation property because navigation properties imply entity relationships, and `ComplexTypes` do not have identities or keys. 
[Complex types](https://learn.microsoft.com/en-us/odata/concepts/data-model?view=odata-edm-7.0#complex-types)

However, it is possible to have navigation properties under `ComplexType`.

You can review the doc: 
- [Complex Type with Navigation Property](https://learn.microsoft.com/en-us/odata/webapi/complextypewithnavigationproperty)
- [Navigation property in complex type](https://learn.microsoft.com/en-us/odata/odatalib/navigation-under-complex)

**Comment by anjanasagathiya** [comment]
@WanjohiSammy My question is related to expansion of navigation property. How can I disable automatic expansion of navigation property if data is retrieved from same table?

**Comment by julealgon** [comment]
@anjanasagathiya you should consider renaming your question to make it explicit you are talking about a complex type model. Normal navigations are _not_ expanded by default.

Have you tried just calling `AutoExpand(false)` in the EDM configuration for your property?

**Comment by WanjohiSammy** [comment]
@anjanasagathiya
Update us on whether you’ve resolved the issue related to navigation properties. 
Additionally, consider referring to the following documentation for a helpful walkthrough on navigation properties:

- [OData - Navigation Properties](https://learn.microsoft.com/en-us/odata/client/navigation-properties)

> Remember that `related entities or entity types` are not returned or expanded by default.  
> To make navigation properties expand automatically without `expand` query option, use [AutoExpand attribute](https://learn.microsoft.com/en-us/odata/webapi/autoexpand-attribute)

**Feel free to rename this issue or close it as completed.**

**Comment by anjanasagathiya** [comment]
@julealgon @WanjohiSammy I have removed the [complex type] attribute from the navigation property and now navigation properties can't be expanded automatically. Thanks for the helping me to find out the solution.
