### ISSUE TITLE
Secure environment will not allow generated routing in OData

### ISSUE THREAD

**Issue by ramious76** [OData/AspNetCoreOData#129]
This is more of a question than an Issue.  I work for a government agency that uses the DoD STIG environment and its a pain.  I have been able to get OData in Dotnet 5 working fine and doing what I need it to on a off network laptop.  But on my build in the work environment I cannot even debug and have it generate the OData route connections to the OData controllers.  Building it offline then moving it is not an option.
The main question is can I manually create the routes in the configuration to bypass this issue?

**Comment by xuzhg** [comment]
@ramious76 Can you share more your requirement?

**Comment by ramious76** [comment]
What I am after is setting my odata in the startup and you use your builder to set the data model object can I manually set the controller that it links to that it does on its own on build and forcibly map it to a controller.  That mapping is being interfered with on my computer environment.  So when I do that routing debug page it never gets mapped.

So using your sample code  for clarification from https://github.com/xuzhg/MyAspNetCore/tree/master/src/BookStoreAspNetCoreOData8Preview/BookStoreAspNetCoreOData8Preview 

The startup.cs 
`
   services.AddOData(opt => opt.AddModel("odata", GetEdmModel())
                .AddModel("v{version}", GetEdmModel())
                .Filter().Select().Expand());


   private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Book>("Books");
            builder.EntitySet<Press>("Presses");
            return builder.GetEdmModel();
        }
`

And the controller 

`
   public class BooksController : ODataController
    {
        private BookStoreContext _db;

        public BooksController(BookStoreContext context)
        {
            _db = context;
            _db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            if (context.Books.Count() == 0)
            {
                foreach (var b in DataSource.GetBooks())
                {
                    context.Books.Add(b);
                    context.Presses.Add(b.Press);
                }
                context.SaveChanges();
            }
        }

        [EnableQuery(PageSize = 1)]
        public IActionResult Get()
        {
            return Ok(_db.Books);
        }

        [EnableQuery]
        public IActionResult Get(int key, string version)
        {
            return Ok(_db.Books.FirstOrDefault(c => c.Id == key));
        }
`

No matter what I do the build won't create the route to the OData Employee.  All it generates is the  default odata and $metadata link I put in.
Is there a way to manually configure the connection to the controller and force the route?  I am not sure if one or both of these steps are being interfered with on the build.

**Comment by ramious76** [comment]
Things have changed quite a bit with release of 8.0 closing because the base has changed so much and will see if this is still an issue in the future.
