### ISSUE TITLE
Composite key doesn't work

### ISSUE THREAD

**Issue by yongkeecho** [OData/AspNetCoreOData#1297]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.2.5

**Describe the bug**
Composite key doesn't work.

**Reproduce steps**
```
public class AssetSmesController(AdminDbContext dbContext) : ODataController
{
    [EnableQuery]
    [HttpGet]
    public async Task<IList<AssetSme>> Get() => await dbContext.AssetSmes.ToListAsync();

    [EnableQuery]
    [HttpGet]
    [ProducesResponseType(typeof(User), 200)]
    [ProducesResponseType(404)]
    public async Task<ActionResult<User>> Get([FromODataUri] int keyAssetId, [FromODataUri] string keyUserId)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        if (keyAssetId <= 0 || string.IsNullOrEmpty(keyUserId))
            return BadRequest();

        var assetSme = await dbContext.AssetSmes.FirstOrDefaultAsync(assetSme => assetSme.AssetId == keyAssetId && assetSme.UserId == keyUserId);
        return assetSme == null ? NotFound() : Ok(assetSme);
    }
}
```

**Data Model**
```
public class AssetSme
{
    public required int AssetId { get; set; }

    public required string UserId { get; set; }
}
```

**EDM (CSDL) Model**
```
var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<AssetSme>("AssetSmes").EntityType.HasKey(sme => new { sme.AssetId, sme.UserId });
builder.Services.AddControllers().AddOData(
    options => options.Select().Filter().OrderBy().Expand().Count().SetMaxTop(null).AddRouteComponents(
        "odata",
        modelBuilder.GetEdmModel(),
        new DefaultODataBatchHandler()));
```

**Screenshots**
Cannot see the route for the Get endpoint with a composite key .

**Comment by yongkeecho** [comment]
![image](https://github.com/user-attachments/assets/f88a1e73-72b9-4572-a3a4-00f2ef7eeaf9)

**Comment by julealgon** [comment]
@yongkeecho would you mind sharing a repro project showcasing the issue?

**Comment by yongkeecho** [comment]
@julealgon Of course. Thank you.
https://github.com/yongkeecho/ODataCompositeKeyExample

**Comment by julealgon** [comment]
@yongkeecho found what the problem is in your case.

It's basically due to the following setting:
```csharp
modelBuilder.EnableLowerCamelCase();
```

If you rename your key parameter names it works:
```diff
- public async Task<ActionResult<AssetSme>> Get([FromODataUri] int keyAssetId, [FromODataUri] string keyUserId)
+ public async Task<ActionResult<AssetSme>> Get([FromODataUri] int keyassetId, [FromODataUri] string keyuserId)
```

It will start to be picked up by the convention again:
![image](https://github.com/user-attachments/assets/c4e7295f-26ec-452f-8df6-90aaf7aeaa1e)

Now...... do I like this? Not really... I think this is fairly confusing. But that's the setting that is causing the difference here when using the automatic entity conventions.

**Comment by yongkeecho** [comment]
Thank you @julealgon . It works like a charm!

**Comment by xuzhg** [comment]
@julealgon @yongkeecho 

For your reference, the property name is case-sensitive by default, but you can use https://github.com/OData/AspNetCoreOData/blob/7bc661da289c575191be22c314c54a10469e560d/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L64 to enable property name case-insensitive. 

If you can try, love to see the result.

**Comment by KenitoInc** [comment]
This  issue has been resolved
