### ISSUE TITLE
No option for json camelcase serialization

### ISSUE THREAD

**Issue by Gigabyte0x1337** [OData/AspNetCoreOData#13]
Please add an option to enable camelcase serialization

**Comment by xuzhg** [comment]
@GerjanVlot camelCase for the property name or the property value? 

for example:
```json
{
    "myFullDescription": "this is the value for description, how about the camelCase"
}
```

If it's only for the property name, it's also supported in the model builder.

**Comment by GerjanVlot** [comment]
This is the response now:
```
{
"@odata.context": "https://localhost:5010/api/v1.0/$metadata#debitors",
"value": [
{
"Code": "1000",
"Name": "",
"ShortName": "TEST"
}
]
}
```

Entity/Model:
```
public class Debitor
    {
        [Key]
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    }
```

This is what i want without setting the manualy the json property name attribute.
```
{
"@odata.context": "https://localhost:5010/api/v1.0/$metadata#debitors",
"value": [
{
"code": "1000",
"name": "",
"shortName": "TEST"
}
]
}
```

In odata 7 there was posibility to set the odata json serializtion convensions.
Tried this but that also doesnt work.
```
services.AddControllers().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            });
```

**Comment by weitzhandler** [comment]
I think this is a general question: How do I have OData use my injected `JsonSerializerOptions` from DI container.
Please change the title accordingly.

Ideally, it should operate against `IOptions<JsonSerializerOptions>`.

**Comment by weitzhandler** [comment]
I've posted a repro to my issue: https://github.com/weitzhandler/JsonIssueRepro
I also reported the issue here: https://github.com/dotnet/runtime/issues/45587

**Comment by GerjanVlot** [comment]
It just uses the internal serializer https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs

So, no wonder that options are not being used for now this is a great alternative.
It just renames the EDM properties to camel case.

```
var builder = new ODataConventionModelBuilder();
builder.EnableLowerCamelCase();
```

**Comment by ArrowRaider** [comment]
How can I use camel case without EDM?  My backing data store is MongoDB, I am not using Entity Framework.  I serialize my JSON to Camel Case, so I'd like OData to use Camel Case too so it matches.

**Comment by jacobmohl** [comment]
Hi @ArrowRaider - Did you find an answer to your question. I have a couple of Controllers which don't use EDM Models, but "just" [EnableQuery] on top of the Controller method. For a request without any OData query strings (like $top etc), the result is camelCase. But if we use OData features it's converted to PascalCase.

**Comment by zdzislaw** [comment]
> Hi @ArrowRaider - Did you find an answer to your question. I have a couple of Controllers which don't use EDM Models, but "just" [EnableQuery] on top of the Controller method. For a request without any OData query strings (like $top etc), the result is camelCase. But if we use OData features it's converted to PascalCase.

I have the same problem.

**Comment by Ya-Wang** [comment]
> > Hi @ArrowRaider - Did you find an answer to your question. I have a couple of Controllers which don't use EDM Models, but "just" [EnableQuery] on top of the Controller method. For a request without any OData query strings (like $top etc), the result is camelCase. But if we use OData features it's converted to PascalCase.
> 
> I have the same problem.

I 3rd that. It doesn't make sense why it would do that.

**Comment by xuzhg** [comment]
In the non-Edm scenario, by default, it's using the System.Text.Json to do the serialization/deserialization.  Do you enable the correct setting?

If you want to use Newtonsoft.Json, you can add the 'Microsoft.AspNetCore.OData.NewtonsoftJson' package and call `AddODataNewtonsoftJson`

**Comment by KenitoInc** [comment]
@Gigabyte0x1337 Was your issue resolved?

**Comment by gerjanvl** [comment]
> @Gigabyte0x1337 Was your issue resolved?

Yes i think so.

**Comment by Gigabyte0x1337** [comment]
> @Gigabyte0x1337 Was your issue resolved?

Yes, if you just rename your entire edm to camel case it works properly for me.

**Comment by KenitoInc** [comment]
Kindly close the issue
