### ISSUE TITLE
Bound/Unbound function producing 404

### ISSUE THREAD

**Issue by nickjisc** [OData/AspNetCoreOData#1303]
**Assemblies affected**
v9.0.0

**Describe the bug**
Define a bound/unbound function and call that action ending the url with () (which is what the metadata outputs) produces a 404.  Remove the parentheses and the function works correctly.  

If you have parameters, those function do not work as the parentheses cause a 404

**Reproduce steps**
Create a EDM and API with a bound/unbound function and call that with the ending parentheses.

**Data Model**
```C#
                t.Collection.Function("Consent").Returns<ActionResult>().Parameter<string>("scopes");
                var ta = t.Function("adminconsent");
                ta.Returns<IActionResult>();
                ta.Parameter<string>("scopes").Required();
                t.Collection.Function("LookupPolicy").ReturnsCollection<LookupPolicy>();
```

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Expected behavior**
api calls ending with parentheses should be processed the same as with no parentheses

**Comment by xuzhg** [comment]
@nickjisc Can you share more codes, especially for the 'Program.cs' to config the service and your controller/action?

By the way, do you know about the configuration of 'https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L142C17-L142C63'?

**Comment by nickjisc** [comment]
Hi @xuzhg I was not aware of that configuration, I'll have a look at that now

Program.cs
```C#
builder.Services.AddControllers(options => {
    options.Conventions.Add(new AuthorizeFiltersControllerConvention());
    options.EnableEndpointRouting = true;
}).AddOData(options => {
    options.Count().Filter().SkipToken().Expand().Select().OrderBy().SetMaxTop(9999)
        .AddRouteComponents("v1.0", EdmHelpers.EdmModel, b =>
            b.AddSingleton<IODataDeserializerProvider, Jisc.M365CS.ODataDeserializerProvider>()
             .AddSingleton<IODataSerializerProvider, Jisc.M365CS.ODataSerializerProvider>()
    );
    options.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;
}).AddJsonOptions(options => {
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
    options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
    options.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
});
```

The controller (ignore the OdataIgnored, that's how I ended up getting it working

Controller.cs
```C#
        [AllowAnonymous()]
        [ODataIgnored]
        [HttpGet("v1.0/tenants/consent(scopes={scopes})")]
        [HttpGet("v1.0/tenants/consent")]
        [HttpGet("v1.0/tenants/consent()")]
        public ActionResult Consent(string? scopes) {
....
        }

        [Authorize(Roles = "Admin")]
        [EnableQuery]
        [HttpGet]
        public async Task<ActionResult<IODataPagedResultWrapper<LookupPolicy>>> LookupPolicy() {
...
       }
```

Turning off EnableNonParenthesisForEmptyParameterFunction fixes the latter api call, but doesn't fix the others.

**Comment by xuzhg** [comment]
I don't know what's the root cause from your codes. Here's my test:

## Program.cs
```C#
using Microsoft.AspNetCore.OData;
using WebApplication1;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers()
    .AddOData(opt => opt.AddRouteComponents("v1.0", MyModelBuilder.GetEdmModel()));

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseODataRouteDebug();

app.MapControllers();

app.Run();
```

## Controller
```C#
    public class CustomersController : ODataController
    {
        [HttpGet]
        public IActionResult Consent(string scopes)
        {
            return Ok("You can return anything");
        }

        [HttpGet]
        public IActionResult LookupPolicy()
        {
            return Ok("You can return anything");
        }
    }
```

### Models

```C#
    public class Customer
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }

    public class LookupPolicy
    {
        public string? Name { get; set; }
    }

    public static class MyModelBuilder
    {
        public static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            var t = builder.EntitySet<Customer>("Customers").EntityType;
            t.Collection.Function("Consent").Returns<string>().Parameter<string>("scopes");
            t.Collection.Function("LookupPolicy").ReturnsCollection<LookupPolicy>();
            return builder.GetEdmModel();
        }
    }
```


## TEST
If you run it and send '$odata', you can see the following endpoints:

```C#
http://localhost:5253/$odata
```
the Routing table:

![image](https://github.com/user-attachments/assets/d0f0c59e-e92e-446b-bc77-d10dd69509e1)

You can see the empty parenthesis in the endpoint and it means you  should have the parenthesis when calling the endpoint.

## Improve

You can use the config to enable non-parenthesis for empty parameter function as
```
builder.Services.AddControllers()
    .AddOData(opt => opt.AddRouteComponents("v1.0", MyModelBuilder.GetEdmModel()).RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true);
```

Then, you can get updated routing table as:
![image](https://github.com/user-attachments/assets/2b0be3a1-8dc9-4d41-bdf6-55b45997124d)

You can see there's no empty parathesis in the routing template.

**Comment by nickjisc** [comment]
Hi @xuzhg, I think I've fixed it, some client calls weren't adding ' '  around the string in the scopes.  All working thanks
