### ISSUE TITLE
Incorrect Assert in ConvertPrimitiveValue

### ISSUE THREAD

**Issue by dxrdxr** [OData/AspNetCoreOData#131]
Hitting an incorrect assert in `ConvertPrimativeValue` in [EdmPrimitiveHelper.cs](https://github.com/OData/AspNetCoreOData/blob/e1ded5dc6120c7871b7db1c4938d9b06f6884788/src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs#L127
)
```
Contract.Assert(type == typeof(uint) || type == typeof(ushort) || type == typeof(ulong));
```

The controller has a signature of:

```
public async Task<ActionResult> Delete([FromODataUri] int key)
```

The URI sent is:

```
DELETE http://localhost:5000/odata/Certifications('PDMSDT')
```

The result is that the `type`  is `int32` and the `value` is `"PDMSDT"` .

This should **NOT** be an assert causing a 500 status code as it is not a library bug, it is a user sending an incorrect value that should cause a `ValidationException`, such as `PropertyMustBeInt32` (or some such).

In `ConvertPrimativeValue` the code should be expanded to always call `Convert.ChangeType` and catch the well defined exceptions: `InvalidCastException`, `FormatException`, and `OverflowException`. _[Not Compiled]_

```
    // Note that we are not casting the return value to nullable<T> as even if we do it
    // CLR would unbox it back to T.
    try
    {
        return Convert.ChangeType(value, type, CultureInfo.InvariantCulture);
    }
    catch (Exception ex)
    {
        switch (ex)
        {
            case InvalidCastException:
            case FormatException:
            case OverflowException:
                throw new ValidationException(Error.Format(SRResources.PropertyInvalidType));
            default:
                throw;
        }
    }
```

**Comment by xuzhg** [comment]
@dxrdxr Would you please share me a PR for contribution?
