### ISSUE TITLE
Make CreatedODataResult<T> and its peers conform to the aspnetcore pattern for generic ActionResults

### ISSUE THREAD

**Issue by garethj-msft** [OData/AspNetCoreOData#134]
### Description
Today in a standard aspnetcore project, controllers can return ActionResult<T>, and then thru that still return results that do not have a <T> generic parameter such as NotFoundResult.

This is done with the system of implicit casts between ActionResult and ActionResult<T> and provides a lot of convenience and consistency between controllers action methods.

Types such as CreatedODataResult<T> don't work in a controller that returns ActionResult<T>, as they don't derive from ActionResult<T> or ActionResult (instead deriving directly from IActionResult).

### Expected
All FooODataResult<T> types should be able to be returned from a controller action method that returns ActionResult<T>

### Actual 
Only some of this set of types can be so returned.  e.g. NotFoundODataResult works, as it is derived from NotFoundResult.

**Comment by gathogojr** [comment]
@garethj-msft We can close this issue, no?
https://github.com/OData/AspNetCoreOData/blob/df2143d0af6d485fae3e848c4b0717da4b97d71c/src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs#L25
https://github.com/OData/AspNetCoreOData/blob/df2143d0af6d485fae3e848c4b0717da4b97d71c/src/Microsoft.AspNetCore.OData/Results/UpdatedODataResult.cs#L23

**Comment by julealgon** [comment]
Looks like it's also related to this:
- https://github.com/OData/AspNetCoreOData/issues/17

Which from what I'm seeing, should be closed? That's been implemented since, correct?

**Comment by gathogojr** [comment]
Fixed by:
https://github.com/OData/AspNetCoreOData/pull/906
https://github.com/OData/AspNetCoreOData/pull/981
