### ISSUE TITLE
[Packaging] Incorrect nuspec dependencies for  Microsoft.AspNetCore.OData 8.2.6

### ISSUE THREAD

**Issue by MaceWindu** [OData/AspNetCoreOData#1348]
**Assemblies affected**
 Microsoft.AspNetCore.OData 8.2.6

**Describe the bug**
`net6.0` built against `Microsoft.OData.Edm` 7.21.6.0 but nuspec [reference](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.2.6#dependencies-body-tab)  defined as:
[Microsoft.OData.Edm](https://www.nuget.org/packages/Microsoft.OData.Edm/) (>= 7.20.0 && < 8.0.0)

This leads to build error:

`
Assembly 'Microsoft.AspNetCore.OData' with identity 'Microsoft.AspNetCore.OData, Version=8.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.OData.Edm, Version=7.21.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.OData.Edm' with identity 'Microsoft.OData.Edm, Version=7.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
`

**Reproduce steps**
Add ` Microsoft.AspNetCore.OData 8.2.6` reference to .net 6 project and build.

**Workarounds**

- don't update to 8.2.6
- add explicit `Microsoft.OData.Edm` and `Microsoft.OData.Core` 7.21.6 references

**Comment by WanjohiSammy** [comment]
@MaceWindu Try updating `Microsoft.OData.Edm`, `Microsoft.OData.Core` to `7.21.6` explicitly

**Comment by WanjohiSammy** [comment]
@MaceWindu This has been fixed in `8.2.7`
