### ISSUE TITLE
How to change global EdmModel?

### ISSUE THREAD

**Issue by ptrushin** [OData/AspNetCoreOData#1351]
As far as I understand, EdmModel is a static singleton. I want to be able to change it at certain points in time when my entity settings change, for example field names (they change through the UI and are saved in the database). 
How i can change global EdmModel?

**Comment by habbes** [comment]
Hello @ptrushin  could you share more details about your use case and setup?

AspNetCoreOData does not come with a default "global" EdmModel. It's up to the developer to define and provide the `IEdmModel`. The framework expects a model per "route", where the route represents a collection of endpoints in a single "logical serivce" (you can have multiple "routes" in your service, each with a different model. One use case for this is to have different versions of an API or host different OData APIs in the same ASP.NET Core services).

How and where you get the `IEdmModel` is up to you. The most common way, however, is to generate a model using the `Microsoft.OData.ModelBuilder` library using the `ODataConventionModelBuilder`. This provides a quick way to build an `IEdmModel` from C# classes using common/opinionated conventions. You could also use the less opinionated `ODataModelBuilder` which has fewer conventions baked in and requires you to configure things more explicitly. However, both versions return a "final" `IEdmModel` which is expected to be immutable, the underlying implementation is not exposed.

But you do not have to use the model builder. You can create a model manually using the `EdmModel` class, create entity types, define their properties, etc. (see: https://learn.microsoft.com/en-us/odata/odatalib/edm/build-basic-model). Using the `EdmModel` you can add types to the model dynamically on the fly. You could also parse the model from a file using the `CsdlReader` (see: https://learn.microsoft.com/en-us/odata/odatalib/edm/read-write-model). However, these approaches have not been extensively tested in ASP.NET Core OData. There are certain known gaps with this approach: ASP.NET Core OData expects some configuration to be attached to the model via the `model.SetAnnotationValue/GetAnnotationValue` pattern. When such configuration does not exist, some features may not work correctly. For example, for dynamics property to work with C# classes, the OData serializer expects their to be a Dictionary<string, object> property in the class, the model builder usually adds some configuration to the `IEdmModel` that allows the serializer to find this property. If you create `EdmModel` and need to support dynamic properties, you would need to add this config as well. However this is not documented and causes confusion. So the easiest way to tell is to test your service and see what breaks. This is an area we're looking to improve.

**Comment by ptrushin** [comment]
Hello, @habbes 
By "global model" I mean the model that is used, for example, when I use the [EnableQuery] attribute in a controller method. 
My system is built in such a way that there are several universal fields in class, for example Number1, Number2, Number3. A user can customize the names for these fields, for example, Weight (for Number1), Volume (for Number2) and ignore Number3. 
I want the global model to be updated after the user makes these settings, using these specific names instead (the changes I need to make are property name changes and ignoring certain properties, such as Number3).
I can make these changes when constructing the model, but I can't seem to update them after the initial setup. That's the question at hand: how can I update the model at the point when the user has made their changes?

**Comment by julealgon** [comment]
> By "global model" I mean the model that is used, for example, when I use the [EnableQuery] attribute in a controller method.

@ptrushin check this:
- https://github.com/OData/AspNetCoreOData/issues/381
