### ISSUE TITLE
OData.Client 8.2.1 does not materialize data service responses

### ISSUE THREAD

**Issue by dotnetero** [OData/AspNetCoreOData#1354]
I apologize, I wrote this report, but it should have been in the OData.Net section, if any administrator can delete it, I would appreciate it.

**Assemblies affected**

- Microsoft.OData.Client 8.2.1
- Microsoft.OData.Core 8.2.1
- Microsoft.OData.Edm 8.2.1
- Microsoft.Spatial 8.2.1

**Other libraries used in the project:**

- Microsoft.EntityFrameworkCore 9.0.0
- Microsoft.EntityFrameworkCore.Design 9.0.0
- Microsoft.EntityFrameworkCore.SqlServer 9.0.0
- Microsoft.EntityFrameworkCore.Tools 9.0.0
- Microsoft.AspNetCore.OData 9.1.0

**Describe the bug**

In all requests made by using a unit of work that encapsulates a DataServiceContext, it is not possible to materialize the results, obtaining the same error in all methods "Value cannot be null (Parameter 'key')".

Multiple client applications were programmed on Blazor Server, Wpf Core, among others. These must consume multiple services made with AspNetCore.OData, prior to updating to the assemblies mentioned above, everything worked fine, at this time the calls to the OData services do not materialize. 
AspNetCore.OData services work well and return results correctly.

**Reproduce steps**

- Create an API with AspNetCore.OData, which consumes data from a database in Sql Server with or without primary keys.
- Use the OData Connected Service extension to read the metadata and create the class for consumption in client applications.
- Make a request to the data service, and it should throw the error mentioned above.

**Data Model**

![image](https://github.com/user-attachments/assets/bf84e181-2cb1-420d-b3ab-1aca789940dd)

**EDM (CSDL) Model**

![image](https://github.com/user-attachments/assets/d92a7f6d-e350-43b9-ba67-6f4fa2ef6278)

**Request/Response**

Request:
![image](https://github.com/user-attachments/assets/46cbc11e-e288-4d8d-8dc7-0bcd657e43d2)

Response: 
The following image shows that the data service adequately responds to all methods:
![image](https://github.com/user-attachments/assets/2f5efcd5-ba5d-4431-a795-670a500374dd)
The response it´s empty on blazor server app or Wpf app.

**Expected behavior**

Whether the data service returns IQueryable<T>, Enumerable<T>, List<T>, etc. It is expected to be able to materialize these results for consumption in client applications.

**Screenshots**
![image](https://github.com/user-attachments/assets/807693bb-31bb-4d93-89a4-fff5d8fefe7f)
![image](https://github.com/user-attachments/assets/8a4d903d-9529-4ae8-97f5-fdef9888dd2b)
![image](https://github.com/user-attachments/assets/2bb59302-002a-44d7-b34d-e81df3ee2862)
![image](https://github.com/user-attachments/assets/78d974a4-da7f-4103-86ed-2d484c9ec256)

**Additional context**

If you use Microsoft.OData.Client 8.1.0, everything works as expected. Leaving client applications with Net 9 and data services with AspNetCore.Odata 9.1.0 and EntityFrameworkCore 9.0.0.

**Comment by habbes** [comment]
This is a client-side issue. See: https://github.com/OData/odata.net/issues/3124
