### ISSUE TITLE
any() on OpenType not filtering but checking for any match?

### ISSUE THREAD

**Issue by Bl4d3s** [OData/AspNetCoreOData#1358]
**Assemblies affected**
Microsoft.AspNetCore.OData > 9.0.0 (Lower versions did not support openTypes, if I understand the git history correctly)

**Describe the bug**
any() on collection types (specifically tested for openTypes) does not filter but checks if any element matches

**Reproduce steps**
Repro project can be found here: [Minimal repro](https://github.com/Bl4d3s/OdataOpenTypeAnyRepro)
1. Create a model with only an openType dictionary
2. Filter data with any()
    1. When filter matches any element, all elements are returned
    2. When filter matches no element, no data is returned
The repro contains the Swagger UI for easier debugging.

**Data Model**
[DynamicData](https://github.com/Bl4d3s/OdataOpenTypeAnyRepro/blob/main/OdataOpenTypeAnyRepro/DynamicData.cs)

**EDM (CSDL) Model**
Created programmatically [here](https://github.com/Bl4d3s/OdataOpenTypeAnyRepro/blob/main/OdataOpenTypeAnyRepro/Controllers/WeatherForecastController.cs)

**Request/Response**
Existing name: 
https://localhost:7135/WeatherForecast?filter=stations%2Fany%28station%3A%20station%2Fname%20eq%20%27Test1%27%29
returns all data (unexpected, expected only stations with matching name)

Non-existing name:
https://localhost:7135/WeatherForecast?filter=stations%2Fany%28station%3A%20station%2Fname%20eq%20%27Test12%27%29
returns no data (expected)

**Expected behavior**
Only elements matching the any() filter should be returned, see [oData proposal](https://www.odata.org/blog/support-for-any-and-all/).
Similar to the LINQ Where.

**Comment by WanjohiSammy** [comment]
@Bl4d3s 

The `any()` is working as expected.

Consider the following queries and expected result:
1. https://localhost:7135/WeatherForecast?filter=stations/any(station: station/name eq 'Test2')
   This will return everything in the type where `name eq 'Test2'`
   ```json
     [
      {
          "type": "weather",
          "stations": [
              {
                  "name": "Test1",
                  "temps": [
                      1,
                      2,
                      3
                  ]
              },
              {
                  "name": "Test2",
                  "temps": [
                      -1,
                      -2,
                      -3
                  ]
              }
          ]
      }
   ]
   ```

3. https://localhost:7135/WeatherForecast?filter=stations/any(station: station/name eq 'Test0')
   This will return everything in the type "history_weather" where `name eq 'Test0'`
   ```json
      [
          {
              "type": "history_weather",
              "stations": [
                  {
                      "name": "Test1",
                      "temps": [
                          4,
                          5,
                          6
                      ]
                  },
                  {
                      "name": "Test0",
                      "temps": [
                          0
                      ]
                  }
              ]
          }
      ]
   ```
5. https://localhost:7135/WeatherForecast?filter=stations/any(station: station/name eq 'Test1')
   This will return all data because per type, there is `name eq 'Test1'`
  ```json
    [
        {
            "type": "weather",
            "stations": [
                {
                    "name": "Test1",
                    "temps": [
                        1,
                        2,
                        3
                    ]
                },
                {
                    "name": "Test2",
                    "temps": [
                        -1,
                        -2,
                        -3
                    ]
                }
            ]
        },
        {
            "type": "history_weather",
            "stations": [
                {
                    "name": "Test1",
                    "temps": [
                        4,
                        5,
                        6
                    ]
                },
                {
                    "name": "Test0",
                    "temps": [
                        0
                    ]
                }
            ]
        }
    ]
  ```
7. https://localhost:7135/WeatherForecast?filter=stations/any(station: station/name eq 'Test10')
   This will return nothing because there is no `name eq 'Test10'`

**Comment by Bl4d3s** [comment]
@WanjohiSammy thank you for the clarification. I misunderstood the sample defined in the proposal.
