### ISSUE TITLE
Model becomes invalid when the request is chunked

### ISSUE THREAD

**Issue by bjallemad** [OData/AspNetCoreOData#136]
When posting object model from a .net core client, the request is always chunked and the model becomes invalid (null).

The following client code will not work:
```
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;

namespace ODataClientTest
{
	class Program
	{
		static void Main()
		{
			var customer = new Customer() { Name = "Test" };

			using var httpClient = new HttpClient();

			//var result = httpClient.PostAsync("http://localhost:2087/test/odata/customers", new StringContent(JsonSerializer.Serialize(customer), Encoding.UTF8, "application/json")).Result;
			var result = httpClient.PostAsync("http://localhost:2087/test/odata/customers", JsonContent.Create(customer)).Result;

			result.EnsureSuccessStatusCode();

			Console.WriteLine(result.Content.ReadAsStringAsync().Result);
		}
	}

	public class Customer
	{
		public string Name { get; set; }
	}
}
```

This did work in the 7.* version of OData/WebApi.

I took the server sample from the 7.* version and updated to the 8.0 release candidate.
If posting as StringContent instead, it will work (commented code line above). But since we have multiple third-party clients, this is not a workaround for us.

If using fiddler in the JsonContent/StringContent the only difference is that the content is chunked.
JsonContent (not working):
POST http://localhost:2087/test/odata/customers HTTP/1.1
Host: localhost:2087
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

F
{"name":"Test"}
0

StringContent (working):
POST http://localhost:2087/test/odata/customers HTTP/1.1
Host: localhost:2087
Content-Type: application/json; charset=utf-8
Content-Length: 15

{"Name":"Test"}

Both server and client projects are attached.

[Client.zip](https://github.com/OData/AspNetCoreOData/files/6276358/Client.zip)
[Server.zip](https://github.com/OData/AspNetCoreOData/files/6276360/Server.zip)

**Comment by xuzhg** [comment]
@bjallemad 
Thanks for reporting this. I took a look and made some code changes at your client:

```C#
static void Main()
{
	var customer = new Customer() { Name = "Test" };

	using var httpClient = new HttpClient();

	//var result = httpClient.PostAsync("http://localhost:5000/odata/Customers", new StringContent(JsonSerializer.Serialize(customer), Encoding.UTF8, "application/json")).Result;

	JsonSerializerOptions options = new JsonSerializerOptions
	{
		PropertyNamingPolicy = null
	};
	JsonContent content = JsonContent.Create(customer, typeof(Customer), null, options);
	content.Headers.ContentLength = 15; // You should set the content length correctly.
	var result = httpClient.PostAsync("http://localhost:5000/odata/Customers", content).Result;

	Console.WriteLine(result.Content.ReadAsStringAsync().Result);

	result.EnsureSuccessStatusCode();

}
```

I can get the result:
![image](https://user-images.githubusercontent.com/9426627/116476757-88af0480-a830-11eb-8798-d2d5af0d0f0d.png)

1) ContentLength is required, otherwise it's a chunked request. OData doesn't handle chuncked request body. 
2) the value "15" should match the whole length.
3) PropertyNamingPolicy = null is necessary to keep the property name case sensitive. OData reads the payload case sensitive.

**Comment by bjallemad** [comment]
The actual client is a nuget-package that is already distributed and used by third-party developers. So I cannot easily change that code since it is already distributed in different custom applications...
Regarding the PropertyNamingPolicy = null, this is already set in the real client, I just missed that in my sample.
Even if i made changes in the real client, the content-length seems impossible to calculate in all cases, so that is not an option.

Can you make the new version support chunked request, like in the previous version?

**Comment by xuzhg** [comment]
@bjallemad I made a change.  Would you please try the latest nightly and let me know the result? (FYI, I used your server and client, it works fine)

1) It's ok for chunked request.
2) It's ok without PropertyNamingPolicy setting.

**Comment by bjallemad** [comment]
All of our tests are working just fine with the rc2.
Thanks!

**Comment by xuzhg** [comment]
Good. Let us know any other questions, concerns.
