### ISSUE TITLE
Queries with $apply retrieves data outside of the default response body structure

### ISSUE THREAD

**Issue by ljsomm** [OData/AspNetCoreOData#1376]
When I try to use`$apply` in a oData query it retrieves data outside of the default object that contains the `value` attribute.
I'm currenly using the 9th version of the library, specifically: 9.0.0 (already tested with 9.1.1)

### Assemblies affected

OData .Net lib 9.x

### Reproduce steps

Just performing oData query with `$apply` query parameter

### Expected result

It should retrieve me data inside the default structure as following:

```
{
	"@odata.context": "",
	"value": []
}

```

### Actual result

```
[]
```

**Comment by corranrogue9** [comment]
A possible workaround to try (it's not clear if this will work) is to `ActionResult<IQueryable<T>>` as the return type.

If that doesn't work, please provide a repro, specifically the controller class and the relevant controller method.

**Comment by julealgon** [comment]
Duplicate:
- https://github.com/OData/AspNetCoreOData/issues/181

**Comment by ljsomm** [comment]
Thank you @corranrogue9, I'll follow up the link that @julealgon shared.
