### ISSUE TITLE
Microsoft.AspNetCore.OData 8.0.0-beta Cannot use OData and Conventional Routing Attribute

### ISSUE THREAD

**Issue by groogiam** [OData/AspNetCoreOData#138]
With the .NET Core 3.1 ODataControllers could have RouteAttribute specified which allowed a standard rest endpoint to be created in addition to the OData end point. This looks like it no longer works in 8.0.0-beta. See attached repro with [Route("api/[controller]")] added to the Books Controller

### Assemblies affected

Microsoft.AspNetCore.OData 8.0.0-beta

### Reproduce steps

Run repro and try to navigate to the books controller

### Expected result

Endpoints for odata/Books and api/Books would both work.

### Actual result

Neither endpoint works. Adding the [Route] attribute appears to break the routing altogether.

### Additional detail

[BookStoreAspNetCoreOData8Preview.zip](https://github.com/OData/WebApi/files/6055265/BookStoreAspNetCoreOData8Preview.zip)

**Comment by xuzhg** [comment]
@groogiam 

For the attribute routing, I have a latest post at: https://devblogs.microsoft.com/odata/attribute-routing-in-asp-net-core-odata-8-0-rc/  Please let me know your thoughts.

**Comment by groogiam** [comment]
It looks like you have done alot of great work in allowing for the customization of the routing. After reading this and doing some testing it appears that can get the same method to expose an odata and non odata endpoint using a configuration as below.

```c#
using System.Linq;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    [Route("api/[controller]")]
    public class BooksController : ODataController
    {
        private BookStoreContext _db;

        public BooksController(BookStoreContext context)
        {
            _db = context;
            _db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            if (context.Books.Count() == 0)
            {
                foreach (var b in DataSource.GetBooks())
                {
                    context.Books.Add(b);
                    context.Presses.Add(b.Press);
                }

                context.SaveChanges();
            }
        }

        [EnableQuery(PageSize = 1)]
        [HttpGet("~/api/[controller]")]
        public IActionResult Get()
        {
            return Ok(_db.Books);
        }

        [HttpGet("[action]")]
        public IActionResult CustomAction()
        {
            return Ok(nameof(CustomAction));
        }

    }
}
```

However it does not look like I can pass odata query arguments to the /api/Books endpoint for a non OData endpoint.

E.g. this http://localhost:50246/api/Books?$select=id

results in

`{"Message":"The query specified in the URI is not valid. Could not find a property named 'id' on type 'BookStore.Models.Book'.","ExceptionMessage":"Could not find a property named 'id' on type 'BookStore.Models.Book'.","ExceptionType":"Microsoft.OData.ODataException","StackTrace":"   at Microsoft.OData.UriParser.SelectPathSegmentTokenBinder.ConvertNonTypeTokenToSegment(PathSegmentToken tokenIn, IEdmModel model, IEdmStructuredType edmType, ODataUriResolver resolver, BindingState state)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.ProcessSelectTokenPath(PathSegmentToken tokenIn)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.GenerateSelectItem(SelectTermToken tokenIn)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.Bind(ExpandToken expandToken, SelectToken selectToken)\r\n   at Microsoft.OData.UriParser.SelectExpandSemanticBinder.Bind(ODataPathInfo odataPathInfo, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration, BindingState state)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()\r\n   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.get_SelectExpandClause()\r\n   at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.Validator.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)"}`

I could be mistaken but I recall that this type of query against a non odata endpoint would work in previous versions. Thoughts?

**Comment by xuzhg** [comment]
@groogiam The property is case sensitive.  So far, we don't support the case insensitive in the query property. 

Besides, the RC version maybe not working, there's a fix in the latest nightly. 

That's related to this fix. Please try the nightly and let me know any problem.

https://github.com/OData/AspNetCoreOData/commit/f4e1cf718d9102c8968c953a5033d1b6d8083af5

**Comment by xuzhg** [comment]
Be ware of your controller: 

It works for OData routing because of the OData conventional routing.

BooksController  ==> "Books" is the valid entity set.
Get() ==> is a valid entity set "Get Http Request action". 

Use the latest nightly, enable the OData Debug route middleware.   Call "app.UseODataDebugRoute()". 

Send "~/$odata" request, you can see "odata route" and "non odata route".

**Comment by groogiam** [comment]
Yes looks like the non odata endpoint works in the 04/09 nightly so long as the casing is correct on the query properties. Yes I am aware these routes work because of the default OData routing. Am I correct in assuming that these defaults will be maintained?

Also is app.UseODataDebugRoute() did not appear to be defined in the latest nightly. I was able to use the controller from the sample referenced in your blog post to look at the route templates thought. Is this method going to be in the final release version. It seems like it will be pretty helpful.

**Comment by xuzhg** [comment]
@groogiam Please forgive me. I replied the previous message at last mid night. At that time, my face is 😵.  

the extension name should be "app.UseODataRouteDebug();", not "app.UseODataDebugRoute(); ". I test it in the nightly, it has such.

![image](https://user-images.githubusercontent.com/9426627/114280960-8c4d2980-99f0-11eb-876d-7a52b164aa4f.png)

**Comment by groogiam** [comment]
@xuzhg That explains why I could not find it. I know how it goes working late at night. Thanks for all your help on this.
