### ISSUE TITLE
`$filter` crashes in .NET 6 Preview 3 because there are 2 Enum.TryParse overloads with 2 parameters

### ISSUE THREAD

**Issue by pkanavos** [OData/AspNetCoreOData#141]
The following [field initializer in ExpressionBinderBase](https://github.com/OData/AspNetCoreOData/blob/44705715b79564d29cd1f1a056a71f496b12d4ef/src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs#L42) fails in .NET 6 Preview 3 

```
internal static readonly MethodInfo EnumTryParseMethod = typeof(Enum).GetMethods()
                        .Single(m => m.Name == "TryParse" && m.GetParameters().Length == 2);
```
Because [Enum.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=net-6.0) has two matching overloads:

-  [TryParse<TEnum>(ReadOnlySpan<Char>, TEnum)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=net-6.0#System_Enum_TryParse__1_System_ReadOnlySpan_System_Char____0__)
- [TryParse<TEnum>(String, TEnum)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=net-6.0#System_Enum_TryParse__1_System_String___0__)

This causes an `InvalidOperationException` in all filtering operations: 

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.OData.Query.Expressions.ExpressionBinderBase..cctor() in .../AspNetCoreOData/src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs:line 42
```

# Steps to reproduce

In [ODataRoutingSample](https://github.com/OData/AspNetCoreOData/tree/44705715b79564d29cd1f1a056a71f496b12d4ef/sample/ODataRoutingSample) 

1. Change the `TargetFramework` to `net6.0`
2. Upgrade all `EntityFrameworkCore` packages to the latest preview versions
3. Try to use `$filter`, eg `http://localhost:5000/Products?$filter=Id eq 3`

# Potential Fixes

1. Replace `Single` with `First`.This will resolve to `TryParse(String, TEnum)` in .NET 5 and  `TryParse(ReadOnlySpan, TEnum)` in .NET 6.

2. Explicitly specify the overload using the [Type.MakeGenericMethodParameter](https://docs.microsoft.com/en-us/dotnet/api/system.type.makegenericmethodparameter?view=net-5.0)  method added in .NET Core 2.1

```
internal static readonly MethodInfo EnumTryParseMethod =  typeof(Enum).GetMethod("TryParse",
                        new[] {  
                            typeof(string),
                            Type.MakeGenericMethodParameter(0).MakeByRefType() 
                        }); 
```

**Comment by xuzhg** [comment]
@pkanavos Thanks a lot. 

I take your second fixes and merged it into the master. 

Would you please help test your project again using the latest nightly?

**Comment by ysmoradi** [comment]
I've got the same issue with web api 2 / owin / odata

https://github.com/OData/WebApi/issues/2518

Could you please provide the same fix there? @xuzhg 

I've also provided a PR that is a little different from @pkanavos 's approach.

It passes all automated tests anyway.
