### ISSUE TITLE
After Convert .Net Core 2.1 to .Net Core 3.1 Request model is not parsing, coming null always

### ISSUE THREAD

**Issue by prashantaggarwal1990** [OData/AspNetCoreOData#144]
I am facing an issue where the request model is coming as null always after updating the Framework from .Net core 2.1 to 3.1. Using Microsoft.AspNetCore.OData, Version=7.5.7.0 for OData implementation, after framework update all Post/Put calls have the issue:

 [HttpPost, ODataRoute]
public async Task<IActionResult> PostOrder([FromBody] OrderModel orderDetail)

OrderModel is as follows:

```C#
public class OrderModel 
{
        [Key]
        [DisableUpdate]
        public int OrderId { get; set; }
        [DisableUpdate]
        public int QuoteId { get; set; }
        [Required]
        public string CustomerName { get; set; }
        [DisableUpdate]
        public OrderType DocumentFolderType { get; set; }
        [DisableUpdate]
        public bool IsDeleted { get; set; }
        [DisableUpdate]
        public int CreatedBy { get; set; }
        [DisableUpdate]
        public DateTimeOffset CreatedTimestamp { get; set; }
        public int? LastModifiedBy { get; set; }
        public DateTimeOffset? LastModifiedTimestamp { get; set; }
}
```
Here is the code from the ConfigureServices method from Startup.cs
```C#
services.AddControllers(o =>
{
o.Filters.Add(new AuthorizeFilter(Options.DefaultName));
}).AddNewtonsoftJson();
services.AddApiVersioning(x => x.ReportApiVersions = true);
services.AddPlatformOData(query =>
{
query.MaxNodeCount = int.MaxValue;
});
```
Please help to resolve the same.

**Comment by prashantaggarwal1990** [comment]
Actually my model have one child model reference

public class OrderModel
{
[Key]
[DisableUpdate]
public int OrderId { get; set; }
[DisableUpdate]
public int QuoteId { get; set; }
[Required]
public string CustomerName { get; set; }
[DisableUpdate]
public OrderType DocumentFolderType { get; set; }
[DisableUpdate]
public bool IsDeleted { get; set; }
[DisableUpdate]
public int CreatedBy { get; set; }
[DisableUpdate]
public DateTimeOffset CreatedTimestamp { get; set; }
public int? LastModifiedBy { get; set; }
public DateTimeOffset? LastModifiedTimestamp { get; set; }
public List<Vendor> Vendor { get; set; }
}

public class Vendor
{
public string VendorId { get; set; }
public int VendorName { get; set; }
}

When passing this vendor list from json {"vendor":[]}, it is not parsing and showing complete model as null.

**Comment by xuzhg** [comment]
@prashantaggarwal1990 Can you share me your repro?

**Comment by prashantaggarwal1990** [comment]
@xuzhg I have resolved this problem while getting the ODataEdmModel, creating an ODataConventionModelBuilder object and called EnableLowerCamelCase method which is resolved the issue: 

var builder = new ODataConventionModelBuilder(serviceProvider);
builder.EnableLowerCamelCase();
