### ISSUE TITLE
Add public methods for corresponding option classes to build Expression.

### ISSUE THREAD

**Issue by FlaviusHouk** [OData/AspNetCoreOData#150]
**General description**
There is known issue with asyncronous query materialization like described [here](https://github.com/OData/WebApi/issues/2152). As a user I would like to have an opportunity to use OData and be able to execute database queries asynchronously. 

**Proposed solution**
Let's take filtering for example. FilterQueryOption class contains method called ApplyTo(IQueryable query, ODataQuerySettings querySettings). It does some input validation and uses FilterBinder class to create Expression that represents given predicate. The same Expression might be used by the application to do query to the database in the most appropriate way (example 2). While experimenting with the code I used reflection to achieve my goal (example 1). 

Example 1.

```csharp
public class Controller
{
     [HttpGet]
     [EnableQuery]
     public async Task<IActionResult> GetData(ODataQueryOptions options)
     {
            var serviceProvider = new MockedServiceProvider(); //mocked class that implements IServiceLocator. Used only to create 
            //Registering services need to create FilterBinder with public constructor.
            serviceProvider.Register(typeof(ODataQuerySettings), new ODataQuerySettings()
            {
                PageSize = 100
            });
            serviceProvider.Register(typeof(IEdmModel), options.Context.Model); //Just something to pass.
            var filderBinder = new FilterBinder(serviceProvider);

            //Method used to generate expression
            var method = typeof(FilterBinder).GetMethod("BindFilterClause", 
                                                        System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
            var expr = method.Invoke(null, new object [] { filderBinder, options.Filter.FilterClause, typeof(MyDataClass) }) as LambdaExpression;
            var predicate = expr as Expression<Func<MyDataClass, bool>>; //predicate that might be used to filter data.

            return await _repository.Query<MyDataClass>(predicate); //returns IEnumerable<MyDataClass> filtered on db side and materialized with EF Core ToArrayAsync()
     }
}
```

Example 2.

```csharp
public class Controller
{
     [HttpGet]
     [EnableQuery]
     public async Task<IActionResult> GetData(ODataQueryOptions options)
     {
            Expression<Func<MyDataClass, bool>> predicate = options.Filter.GetFilterPredicate<MyDataClass>(); 
            options.Filter.IsUserHandled = true; //Indicates that filtering was handled by the user
            return await _repository.Query<MyDataClass>(predicate); //returns IEnumerable<MyDataClass> filtered on db side and materialized with EF Core ToArrayAsync()
     }
}
```
As a workaround I'm currently using code like in the example 3. FilterExpressionBuilder is a class that traverses FilterClause.Expression tree and builds correspinding expression that is used for filtering. This is not the best thing for performance as there will be one more filter cycle by the OData library itself. So I think It would be nice to use builder from OData library rather than create my own implementations.

Example 3.

```csharp
public class Controller
{
     [HttpGet]
     [EnableQuery]
     public async Task<IActionResult> GetData(ODataQueryOptions options)
     {
            Expression<Func<MyDataClass, bool>> predicate = FilterExpressionBuilder.BuildExpression<Func<MyDataClass, bool>, MyDataClass>(options.FIlter.FilterClause);
            return await _repository.Query<MyDataClass>(predicate);
     }
}
```

**Comment by xuzhg** [comment]
That's one of our task to make the binder working with DI. 

before that, would you please share me a PR with your proposal?

**Comment by FlaviusHouk** [comment]
I will try to prepare a PR with required changes and send it here in a few days.

**Comment by FlaviusHouk** [comment]
[Here](https://github.com/OData/AspNetCoreOData/pull/156) is the draft version. I will add comments and other things required by contributing guideline later if the idea of the change is OK.

**Comment by KenitoInc** [comment]
@FlaviusHouk 
In `v8.0.5` we added ability to customize the `FilterBinder`.
Does that solve your issue?

**Comment by FlaviusHouk** [comment]
@KenitoInc yes, now it is possible to get expression from FilterClause. Thanks.
