### ISSUE TITLE
UseMVC is not mapping model

### ISSUE THREAD

**Issue by komdil** [OData/AspNetCoreOData#162]
Can you show example with UseMVC. Seems it is not working

**Comment by xuzhg** [comment]
@komdil you mean to use the classic IRouter based routing? not endpoint routing?

I want to say we supports endpoint routing, not IRouter based routing. Is there any reasons that you have to use "UseMvc"?

**Comment by komdil** [comment]
@xuzhg  UseEndpoints causing memory leak problems, (l created issue for that) i couldn't find a reason of this.  thats why I am trying ro use usemvc

**Comment by xuzhg** [comment]
Close it, since we don't want to support the old IRouter based MVC routing in 8. Please use the 7.x version for IRouter based routing.
