### ISSUE TITLE
Issue with $expand on function seems fixed in 8.0.0-rc2 but need confirmation

### ISSUE THREAD

**Issue by esteinmann** [OData/AspNetCoreOData#163]
In my project I have a Controller with the following relevant actions:
```
        [HttpGet]
        [EnableQuery()]
        public IActionResult Get()
        {
            return Ok(OrdersQuery());
        }

        [HttpGet]
        [EnableQuery()]
        public IActionResult ByCustomer(string customer)
        {
            return Ok(OrdersQuery()
                .Where(o => o.Customer.Contains(customer, StringComparison.OrdinalIgnoreCase)));
        }
```

The last action matches the function ByCustomer as defined in the model
```
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Order>("Orders").EntityType.HasKey(x => x.Code);
            builder.EntitySet<OrderLine>("OrderLines").EntityType.HasKey(x => new { x.Order, x.LineNo });
            builder.EntitySet<Invoice>("Invoices").EntityType.HasKey(x => new { x.Code });            
            var func = builder.EntityType<Order>().Collection.Function("ByCustomer")
                .ReturnsCollectionFromEntitySet<Order>("Orders");
            func.Parameter<string>("customer");
            return builder.GetEdmModel();
```
Normal route: http://localhost:5000/api/odata/orders?$expand=Lines
Function route: http://localhost:5000/api/odata/orders/ByCustomer(customer='cust')?$expand=Lines

On the normal Get() action $expand works fine. On the ByCustomer action $expand did nothing in 8.0.0-preview3. I wanted to recreate the situation at home but then I installed 8.0.0-rc2 and noticed $expand is working fine on the function route too. Browsed the issues and was comparing relases: https://github.com/OData/AspNetCoreOData/compare/8.0.0-preview3...8.0.0-rc2 but cannot find where this was fixed. Is this deliberately fixed?

Thanks for the good work on OData by the way!

**Comment by xuzhg** [comment]
@esteinmann It's related to https://github.com/OData/AspNetCoreOData/commit/d7c448b489bc6c142986b9bf59fc4eebcc68095b

The main reason why 8.0.0 preview3 can not work is that the navigation source from the function can't retrieved. Without the navigation source, $expand can't work.

With the changes, we can retrieve the navigation source (Orders) from the annotation and use it in the $expand.

Hope it help.
Thanks.

**Comment by fbcoder** [comment]
Thanks for the explanation. Can I expect this to still be working when 8.0.0 is stable/final?

**Comment by esteinmann** [comment]
Thanks! I assume this should keep working now when 8.0.0 final version is released?

**Comment by xuzhg** [comment]
@esteinmann I think so.
