### ISSUE TITLE
'UpdatedODataResult' and 'CreatedODataResult' are not convertible to 'ActionResult<T>'

### ISSUE THREAD

**Issue by julealgon** [OData/AspNetCoreOData#17]
Both OData-specific action result types `UpdatedODataResult` and `CreatedODataResult` do not currently support being converted into a `ActionResult<T>` value. This is because neither type inherit from the abstract `ActionResult` type, which is what allows the automatic conversion to take place.

From my understanding, this gap in functionality occurred when the core MVC team introduced `ActionResult<T>` and the `ActionResult` base class. At that time, these OData-specific types already existed and only implemented `IActionResult`.

Allowing the OData results to also be convertible to `ActionResult<T>` will result in a more consistent and friendly framework (imagine migrating normal controllers to OData for example, and the "principle of least astonishment" violation) as well as provide better readability by exposing the type on the return explicitly (be it for the developers, or tools like Swagger).

**Comment by weitzhandler** [comment]
@julealgon `ActionResult<T>` is sealed. However we could have them inherit from `ActionResult`, and have them implement `IConvertToActionResult`. See #33.

**Comment by julealgon** [comment]
> @julealgon ActionResult<T> is sealed.

Yes, I'm aware of that.

> However we could have them inherit from ActionResult

That's actually what I suggested in the OP. Sorry if I wasn't clear.

> See #33.

Nice! Thanks for raising that.

**Comment by julealgon** [comment]
Can this be closed as implemented?

**Comment by gathogojr** [comment]
Fixed by:
https://github.com/OData/AspNetCoreOData/pull/906
https://github.com/OData/AspNetCoreOData/pull/981
