### ISSUE TITLE
Is there a way to remove the parentheses from functions?

### ISSUE THREAD

**Issue by cyril-iselin** [OData/AspNetCoreOData#171]
I define a function like this:

` config.Collection.Action("MyAction") ....`

The result is a route like

`MyEntity.MyAction**()**`

Before 8.0 with the same configuration the **()** wasn't part of the route. Can I remove them ?

**Comment by xuzhg** [comment]
@cyril-iselin 

In 8.0, 

* A route for an Edm action is not parenthesis in the route template.

* A route for an Edm function should have a parenthesis in the route template, even this function doesn't have parameters.

So, I can't understand where to remove parenthesis for `Action`. 
Can you share more details?

**Comment by cyril-iselin** [comment]
Hello @xuzhg . Thanks for your answer.

**A route for an Edm function should have a parenthesis in the route template, even this function doesn't have parameters.**

So that's a breaking change for 8.0 ? Is there an option to make parenthesis optional on functions without parameters?
_(for not breaking old routes)_

**Comment by cyril-iselin** [comment]
Thanks for your answer xuzhg. I'm still (since years) confused about functions and actions, I provide some sample:


**OData 8 declaration**

```
  [HttpGet("WhatEver")]
  [ODataApiLoginAuthorize]
  public DateTime WhatEver()
  {
     return m_service.WhatEver<TEntity>();
  }
```

**Odata 7 declaration:**

```
 [ODataRoute("WhatEver")]
 [ODataApiLoginAuthorize]
 [HttpGet]
 public DateTime WhatEver()
 {
       return m_service.WhatEver<TEntity>();
 }
```

**Configuration (both 7 & 8)**

`builder.EntityType<TDto>().Collection.Function("WhatEver").Returns<DateTime>();`


**Route in Odata 7**

odata/v2/Entity/WhatEver


**Route in Odata 8**

odata/v2/Entity/WhatEver()


**So yes, in 7.X  parenthesis for empty parameter function was not present. I hope there is an option for 8.0 to enable the same behaiovir because of backwards compatibility....**

**Comment by xuzhg** [comment]
@cyril-iselin The  latest has a option to enable the non-parenthesis for empty parameter function. 
https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L108

**Comment by xuzhg** [comment]
@cyril-iselin It's available in the latest rc3 version, please try and let me know any other questions.

**Comment by buchatsky** [comment]
EnableNonParenthesisForEmptyParameterFunction does not work as expected. If it is true it not only enables non-parenthesis function calls but also disables with-parenthesis ones. It makes a problem when different odata clients are used
