### ISSUE TITLE
AddOData extension method missing from 8.0.0-rc2

### ISSUE THREAD

**Issue by omnilogix** [OData/AspNetCoreOData#178]
@xuzhg 

After upgrading from 8.0.0-rc to 8.0.0-rc2, the extension method 
`AddOData(this IServiceCollection services, Action<ODataOptions> setupAction);`
is no longer present.  

I have been using this method to setup the EdmModel and add a custom ODataSerializerProvider.

Is this a breaking change?  If so, what is the workaround?

**Comment by xuzhg** [comment]
@omnilogix Thanks for point this. It's a breaking change.  Details please refer to: https://github.com/OData/AspNetCoreOData/commit/8434b45b5d38db29059cc91c4c3e1c6614a6821c

Based on this change, you can call `AddControllers()` first, then call `AddOData`
See the example: 
https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Startup.cs#L57
