### ISSUE TITLE
How to suppress @odata.context in payload?

### ISSUE THREAD

**Issue by omnilogix** [OData/AspNetCoreOData#184]
How can i prevent the @odata.context metadata being written with my json results payload?

`
{
@odata.context=https://localhost:44327/odata/$metadata#MyModel()/$entity,
...
}`

**Comment by xuzhg** [comment]
@omnilogix 

you can use odata.metadata=null to get rid of the odata control metadata.

1) using query option $format=application/json;odata.metadata=null
2) using request accept header.

**Comment by omnilogix** [comment]
> @omnilogix
> 
> you can use odata.metadata=null to get rid of the odata control metadata.
> 
> 1. using query option $format=application/json;odata.metadata=null
> 2. using request accept header.


Can you give a code example?
adding to accept header to client gives FormatException, adding $format... to query still returns the metadata

**Comment by xuzhg** [comment]
@omnilogix sorry, there's a typo. 

it should be: `application/json;odata.metadata=none`

it should be "none" not "null".  

You can find a lot of usage in the E2E project in this repo. for example: https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.E2E.Tests/ComplexTypeInheritance/ComplexTypeInheritanceSerializeTest.cs#L43

**Comment by omnilogix** [comment]
@xuzhg  Is there a way to make this the default on the server side?  It would be nice to avoid the extra header data for every request.

**Comment by xuzhg** [comment]
@omnilogix one quick solution (maybe not best) is to create a middleware to add the $format into the OData request query options before into endpoint routing.

**Comment by cverons** [comment]
Hi @xuzhg,

> you can use odata.metadata=none to get rid of the odata control metadata.
> 
>     1. using query option $format=application/json;odata.metadata=none
>     2. using request accept header.

I'm using the version 8.0.1 of Microsoft.AspNetCore.OData, and the method `#2` doesn't work whereas the `#1` works like a charm.

Is there something in particular to do with the configuration of OData in .Net 5 ?

**Comment by BloodyRain2k** [comment]
Funny, I got the exact opposite issue: $format is validated but ignored while the header works. (Graph Explorer)
