### ISSUE TITLE
No support for expanding properties referenced in $select

### ISSUE THREAD

**Issue by cryogen** [OData/AspNetCoreOData#195]
When expanding a navigation property, excel will send a query that looks like this:

/odata/RootEntity?$select=Properties,On,RootEntity,SubEntity

Where SubEntity is a navigation property on RootEntity.

The OData spec seems to suggest this is allowed, but it doesn't work with AspNetCoreOData. The SubEntity is ignored

**Comment by cryogen** [comment]
I re-read it and I obviously misunderstood it the first time I looked at it. Apologies.

It does say what you say, that there should be a navigation link in the response. But I'm not seeing one. The query looks like this:

/odata/RootEntity?$expand=ChildEntity($select=ChildOfChildEntity)

In the response I see:

```
        {
            "RootProperty": "value",
            "ChildEntities": [
                {
                    "ChildProperty": 1
                },
          ]
} 
```
ChildOfChildEntity is missing entirely, which causes excel to give this error:

![image](https://user-images.githubusercontent.com/1053365/121430780-6d2b3380-c970-11eb-825a-dcb1ebcf37dc.png)

**Comment by xuzhg** [comment]
@cryogen If your request hits OData endpoint, the payload should have a "odata.context" metadata in the payload.
But, your payload doesn't have.

Can you share me your repro?

**Comment by cryogen** [comment]
https://github.com/cryogen/ODataTest

Clone this repo and run the solution
Open excel, create a new worksheet
Go to the data tab -> Get Data -> From other sources -> From OData feed
Enter url of running example  e.g.  http://localhost:5000/odata
Select Parent entity and click edit
Expand "Childs" property -> select all columns -> click ok
Expand "Childs.ChildOfChild" property -> select all columns -> click ok
Error occurs

**Comment by xuzhg** [comment]
You should use $expand=ChildOfChildEntity in the nested $expand.

/odata/RootEntity?$expand=ChildEntity($expand=ChildOfChildEntity)

Below is your example test at my side:
![image](https://user-images.githubusercontent.com/9426627/121571139-7d2a2e00-c9d7-11eb-93ad-2ea08a30abb6.png)

**Comment by cryogen** [comment]
Yes but that is not what Excel does. I have no control over what queries Excel generates and it's clearly expecting them to return different data than they are :)

**Comment by xuzhg** [comment]
@cryogen I think it's a gap in Excel to support nested $expand for OData data provider.

**Comment by cryogen** [comment]
The issue seems to have been with the way I was defining navigation properties. If the conventions were unable to figure out the referential properties, they would be excluded from the XML which meant that excel was unclear on how to expand them. I've fixed that and it's now able to do so. Sorry for the noise!
