### ISSUE TITLE
Question: Does this library provides better way to parse Expressions ?

### ISSUE THREAD

**Issue by danleydmello** [OData/AspNetCoreOData#198]
Hi,

I am investigating this OData 8.0.0-rc3 for our prototype where we don't want to use EF and IQUeryable (since we don't to create strongly typed).  Looking at the sample provided in this repo, helped me to figure out how to create a dynamic routing and EDM model without requiring strongly typed class. 
Now the next milestone for me as to how to parse the expressions ( filter, orderby etc) and transform to target query. Is there better support in this library than using visitor patterns and implementing visitor classes ?

Thanks
Dan

**Comment by xuzhg** [comment]
@danleydmello Do you mean you want to parse the $filter, $orderby by yourself?

If yes, you can add ODataQueryOptions<T> into your action, and parse the AST (abstract search tree) by yourself?
If no, would you please share more details about your requirements?

**Comment by danleydmello** [comment]
Thanks Sam for response, 
yes to parse  $filter, $orderby, etc and to translate to target query. I was going to use ODataQueryOptions  as well but just want to find out if there was a better way.
By the way, is there full-fledged library that translates  $filter, $orderby straight to Sql Server sql ? 

Thanks
Dan

**Comment by FlaviusHouk** [comment]
@danleydmello check out [odata.net](https://github.com/OData/odata.net) repository. AspNetCoreOData only integrates OData-related functionality into AspNetCore. Most of the parsing, type checking and binding are done in that library. If you are interesting in that you can start with [parser](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs) from that repository. 

Translation into SQL is done by IQueryable and IQueryProvider implementation for concrete sources. Check code for some database clients like npgsql for Postgresql (I cannot point you to the implementation for Sql Server, but I think you can start from EnityFramework Sql Server provider). Actual translation happens on a level closer than database. OData implementation has nothing to do with it.

**Comment by danleydmello** [comment]
@FlaviusHouk , Thanks for the link , hopefully, it will help me to build the parser for our target query
