### ISSUE TITLE
select result serialization broken (upgrading from 7.5 to 8)

### ISSUE THREAD

**Issue by stevendarby** [OData/AspNetCoreOData#20]
It is now serializing as:

```JSON
{
    "instance": null,
    "container": {
        "name": "column",
        "value": "value",
        "next0": {
            "name": "column2",
            "value": "value2",
            "autoSelected": true
        },
        "autoSelected": false
        },
        "modelID": "62488a16-0c3a-485f-9a66-bd74bb192560",
        "untypedInstance": null,
        "instanceType": null,
        "useInstanceForProperties": false
}
```

when previously it was:
```JSON
{
    "column": "value"
}
```

Looks like this is because you know use an STJ converter instead of Newtonsoft. This seems like quite a large breaking change, is there any way to configure the behaviour? Newtonsoft is still a very popular solution

**Comment by xuzhg** [comment]
@snappyfoo Would you please share a repo?

**Comment by snappyfoo** [comment]
You can use your sample project with a few minor modifications:
1. add Microsoft.AspNetCore.Mvc.NewtonsoftJson nuget
2. In the Startup, change to `services.AddControllers().AddNewtonsoftJson();` 
3. In BooksController, change Get to:

```C#
public IActionResult Get(ODataQueryOptions<Book> opts)
{
    var list = opts.ApplyTo(_db.Books).Cast<object>().ToList();
    return Ok(list);
}

Previously the SelectSome would serialize correctly, but now it doesn't. Example given is very simplistic - we have other reasons for manually applying options and manually ToListing etc.

**Comment by snappyfoo** [comment]
@xuzhg is above sufficient, is there any more detail or repo you need for this?

**Comment by xuzhg** [comment]
It should work with the new package at: 

https://www.nuget.org/packages/Microsoft.AspNetCore.OData.NewtonsoftJson/
