### ISSUE TITLE
Microsoft.AspNetCore.OData --version 8.0.0-rc3 not showing @odata.* properties in response, becuase of that not able to view count 

### ISSUE THREAD

**Issue by Naveen512** [OData/AspNetCoreOData#205]
![odata](https://user-images.githubusercontent.com/11847198/123292334-96cb8980-d530-11eb-8eac-babafc8bf2db.PNG)

---
`namespace Dot5.OData8.Api.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
       
        }
        [EnableQuery]
        [HttpGet("odata/WeatherForecast")]

        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Id = (index + 1),
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}
`

--- Startup.cs --------
```C#
services.AddControllers()
            .AddOData(opt => opt.AddModel("odata",GetEdmModel()).Select().Filter().Count().Expand());
```

```C#
public static IEdmModel GetEdmModel()
{
	ODataConventionModelBuilder modelBuilder = new ODataConventionModelBuilder();
	modelBuilder.EntitySet<WeatherForecast>("WeatherForecasts").EntityType.HasKey(_ => _.Id);
	return modelBuilder.GetEdmModel();
}
```

**Comment by xuzhg** [comment]
@Naveen512 your entity set name is "WeatherForecasts", but neither your controller name nor the template name in "HttpGet" is with "s".

**Comment by Naveen512** [comment]
@xuzhg 
Thanks i removed 's' in the 'EntitySet' name now working
