### ISSUE TITLE
How about .NET 6?

### ISSUE THREAD

**Issue by henrikdahl8240** [OData/AspNetCoreOData#217]
I have tried to upgrade my current project to .NET 6.0 preview 5.

Unfortunately the line with `endpoints.MapODataRoute("odata", ...);` throws an error, so it doesn' work.

Currently I am using Microsoft.AspNetCore.OData version 7.4.1.

Microsoft.AspNetCore.OData version 8.0 is still not really complete.

So, if we use OData, we just cannot continue with .NET 6 or is there some way to handle the incompatibilities?

Can you share some indication of when we may continue to .NET 6, will it for instance be the latest when .NET 6 RTM will be ready?

I am particularly curious because Microsoft fixed some problems in .NET 5 before RTM, which I had discovered, without which I could not have used .NET 5. I would like to be sure, that I can use .NET 6 as well, therefore I have the attention to this.

**Comment by stevendarby** [comment]
Will extra work need to go into OData to support the new DateOnly and TimeOnly types in.NET 6?

**Comment by markhealy88** [comment]
@henrikdahl8240 If the exception was an `ArgumentNullException` on that line you could try updating to 7.5.12.  

https://github.com/dotnet/aspnet-api-versioning/issues/796#issuecomment-1002749080

**Comment by xuzhg** [comment]
@stevendarby Yes, that's our planning to support DateOnly and TimeOnly. 

@henrikdahl8240 have to close it, please file new issues if you have further concerns/questions.

**Comment by henrikdahl8240** [comment]
@xuzhg I am sorry I have not responded. It works excellent now.

**Comment by julealgon** [comment]
> Will extra work need to go into OData to support the new DateOnly and TimeOnly types in.NET 6?

FYI @stevendarby
- https://github.com/OData/odata.net/issues/2293
