### ISSUE TITLE
Is the whole .Net 5 package stack finished yet?

### ISSUE THREAD

**Issue by TehWardy** [OData/AspNetCoreOData#232]
I can't seem to find all the dependencies needed for a complete stack on nuget.

For example where the hell is Microsoft.AspNetCore.Mvc.Core version 5.0.0 ?
Latest version listed appears to be 2.2.5 

Similar problems all over the place.
I thought .Net 6 was in preview so figured i'd look to migrate my codebase to .Net 5 and it's a total mess.

**Comment by TehWardy** [comment]
Ok update ...
I got it to compile through a bit of "brute force and ignorance" style randomly adding and removing references and then reloading projects.
It seems that have VS recognise .Net 5 frameworks properly is a bit weird.

Now that it's compiling the goal post sorta moved and i'm getting this error ...
     JsonSerializationException: Self referencing loop detected for property 'ReturnType' with type
.... 

I'm configuring it like this in configure services  ...

services.AddControllers()
    .AddNewtonsoftJson(opts => opts.SerializerSettings.UpdateFrom(ObjectExtensions.ODataJsonSettings))
    .AddOData(opt => {
        opt.Count().Filter().Expand().Select().OrderBy().SetMaxTop(5);
        builders.ForEach(b => opt.AddRouteComponents(b.GetType().Name.Replace("ModelBuilder", ""), b.Build().EDMModel));
        //opt.Conventions.Add(new MyConvention())
    });

... 

the options referenced there are defined like this ...

ODataJsonSettings = new JsonSerializerSettings
        {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            TypeNameHandling = TypeNameHandling.None,
            Formatting = Newtonsoft.Json.Formatting.None,
            DateFormatHandling = DateFormatHandling.IsoDateFormat,
            NullValueHandling = NullValueHandling.Ignore,
            DateTimeZoneHandling = DateTimeZoneHandling.Utc,
            ContractResolver = new DefaultContractResolver { IgnoreSerializableAttribute = true },
            MaxDepth = 4
        };

...

so i'm little confused how I'm getting this exception at this point.

**Comment by xuzhg** [comment]
@TehWardy 1) To support Newtonsoft Json need a separate package. The codes are read, It is not shipped yet.  You can find it https://github.com/OData/AspNetCoreOData/blob/master/AspNetCoreOData.NewtonsoftJson.sln  . I'd like to finish it ASAP.

2) You can not find the latest version of 'Microsoft.AspNetCore.Mvc.Core" on nuget.org. That's expected.  Since ASP.NET Core 3.0, they moved the most of package into the .NET Core SDK. See detail https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio.

**Comment by TehWardy** [comment]
Yeh I think i cracked the compilation side.
are you saying that Newtonsoft serialisation doesn't work at the moment for odata?

**Comment by TehWardy** [comment]
Ah ok ... soon as I removed the  .AddNewtonsoftJson(...) call it sprang to life!
So I have it spun up at least :)

**Comment by TehWardy** [comment]
Thanks @xuzhg  I think I have the worst of it beat.

**Comment by xuzhg** [comment]
@TehWardy By default, we are using System.Text.Json. For newtonsoft.json, I will provide a separate package to support it.

**Comment by TehWardy** [comment]
I thought I had that as I have a reference to ...
  Microsoft.AspNetCore.Mvc.NewtonsoftJson
  
I assume that's a generic non OData one ?
Presumably I can drop that reference at this time until you provide the replacement?

**Comment by xuzhg** [comment]
@TehWardy Our project has the reference to that package. https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData.NewtonsoftJson/Microsoft.AspNetCore.OData.NewtonsoftJson.csproj#L19.

To be clear, our package is build upon "Mvc.NewtonsoftJson" to provide the serialization for the "internal" OData object correctly.

**Comment by TehWardy** [comment]
Ah that makes sense ... so I was on the right track, you're extending that to account for OData'ish things :)
Thanks for the feedback Sam always appreciated.
