### ISSUE TITLE
Swagger and OData URIs integration

### ISSUE THREAD

**Issue by callummarshall9** [OData/AspNetCoreOData#236]
Hey,

So I've got everything working in that an swagger.json file and the UI is working however for one of our controllers in particular with OData Uri options it seems to append the Uri option onto the end rather than where it has been specified in the OData route....

Example:

![image](https://user-images.githubusercontent.com/9967255/125775206-4a540b54-1626-47f9-a498-1f2e1e7658d8.png)

The {systemId} in the URL should be swapped for 'Test'... so it becomes B2B/ActiveTransaction/FromSystem(SystemId='Test') rather than B2B/ActiveTransaction/FromSystem(({systemId}))?systemId=Test
The controller & model is defined as follows...

```cs
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        [HttpGet]
        public IActionResult FromSystem([FromODataUri] string systemId)
        {
            var systems = systemId.Split(',');
            return Ok(Service.GetAll().Where(t => systems.Contains(t.SourceSystemId)));
        }
```

The OData model has the following entry...
            
```cs
Builder.EntityType<ActiveTransaction().Collection.Function("FromSystem").ReturnsCollectionFromEntitySet<ActiveTransaction>("activeTransactionsFromSystem").Parameter<string>("systemId");
```

Yet the swagger UI seems to be getting this wrong.

Thanks,
Callum

**Comment by TehWardy** [comment]
@xuzhg Looks like he's saying Odata is giving the wrong info to the swagger API?
Is this something we need to put an attribute on in the controller action?

**Comment by callummarshall9** [comment]
Using [FromRoute] instead of [FromODataUri] seems to of solved it in the mean time.
