### ISSUE TITLE
Batch request return 404 

### ISSUE THREAD

**Issue by siasty** [OData/AspNetCoreOData#24]
Hi, I update app to new library but i have problem with batch request.
when i test bacht - my responde has no found 
but when check request has link respond is found.
![odata](https://user-images.githubusercontent.com/39690589/97855145-a45ea580-1cfa-11eb-9215-7e067a39c034.png)

can you tell me what's wrong?

https://github.com/siasty/OdataAPI/tree/master/OdataAPI

**Comment by xuzhg** [comment]
@siasty The request in the $batch should include the prefix "odata". Can you test it and let me know the result?

**Comment by xuzhg** [comment]
Here's my test:

![image](https://user-images.githubusercontent.com/9426627/97935577-df2e0100-1d2d-11eb-9c77-1bef96a18d1f.png)

Here's the response:
![image](https://user-images.githubusercontent.com/9426627/97935683-22886f80-1d2e-11eb-8eff-093b776794c5.png)


Be noted: 

1) it seems you have to add "/" before the sub request uri.
2) It seems the query options doesn't apply to the batch. I will take a look about it.

**Comment by siasty** [comment]
Ok,  it works! but in the documentation we have information that the website must also support such a solution

![Przechwytywanie](https://user-images.githubusercontent.com/39690589/97961461-a6d10600-1db3-11eb-97e2-455406df2fad.PNG)

http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ReferencingtheETagofanEntity

**Comment by xuzhg** [comment]
@siasty Thanks for your testing. I think it's an issue  in the code. and Fixed at https://github.com/OData/AspNetCoreOData/commit/0808d381c0ef8691e66edd1ad70785363666e29f

With that change, I can get the following test result: (Would you please to verify)

## Request payload:

```json
{                                                                                                        
{                                                                                                        
  "requests":[                                                                                             
      {
      "id": "1",                                                                                               
      "atomicityGroup": "transaction",                                                                         
      "method": "get",                                                                                        
      "url": "http://localhost:5000/odata/Products?$select=Id,Name&$skip=1&$top=2",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" }
      },
      {
      "id": "2",                                                                                               
      "atomicityGroup": "transaction",                                                                         
      "method": "get",                                                                                        
      "url": "Products?$top=2",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" }
      },
      {
      "id": "3",                                                                                               
      "atomicityGroup": "transaction",                                                                         
      "method": "get",                                                                                        
      "url": "/odata/Products?$select=Name&$top=2",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" }
      }
  ]
}
```
## Response result:

```json
{
    "responses": [
        {
            "id": "1",
            "atomicityGroup": "2ef5a022-6e30-4532-b5b6-62a737c4faba",
            "status": 200,
            "headers": {
                "odata-version": "4.0",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true"
            },
            "body": {
                "@odata.context": "http://localhost:5000/odata/$metadata#Products(Id,Name)",
                "value": [
                    {
                        "Id": 2,
                        "Name": "Fanta"
                    },
                    {
                        "Id": 3,
                        "Name": "Pepsi"
                    }
                ]
            }
        },
        {
            "id": "2",
            "atomicityGroup": "2ef5a022-6e30-4532-b5b6-62a737c4faba",
            "status": 200,
            "headers": {
                "odata-version": "4.0",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true"
            },
            "body": {
                "@odata.context": "http://localhost:5000/odata/$metadata#Products",
                "value": [
                    {
                        "Id": 1,
                        "Name": "Cola",
                        "Price": 130,
                        "Category": "drink",
                        "SupplierId": 1
                    },
                    {
                        "Id": 2,
                        "Name": "Fanta",
                        "Price": 140,
                        "Category": "drink",
                        "SupplierId": 1
                    }
                ]
            }
        },
        {
            "id": "3",
            "atomicityGroup": "2ef5a022-6e30-4532-b5b6-62a737c4faba",
            "status": 200,
            "headers": {
                "odata-version": "4.0",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true"
            },
            "body": {
                "@odata.context": "http://localhost:5000/odata/$metadata#Products(Name)",
                "value": [
                    {
                        "Name": "Cola"
                    },
                    {
                        "Name": "Fanta"
                    }
                ]
            }
        }
    ]
}
```

**Comment by siasty** [comment]
Hi, thanks it works, but unfortunately I have another problem :(

app running od linux not returning CRLF
https://github.com/OData/WebApi/issues/2073#issuecomment-686957430

in section 5.1.1 https://tools.ietf.org/html/rfc2046#section-5.1.1 about Content-Type > "multipart" we have information
"The Content-Type field for multipart entities requires one parameter,
"boundary". The boundary delimiter line is then defined as a line
consisting entirely of two hyphen characters ("-", decimal value 45)
followed by the boundary parameter value from the Content-Type header
field, optional linear whitespace, and a terminating CRLF."

do you know any solution run applications on linux?

example app with batch request http://145.239.95.108/

**Comment by xuzhg** [comment]
@siasty Recently, we added a configuration at ODL side, see here: https://github.com/OData/odata.net/commit/61a81e9c99b80c28109f0555b1151c981c1a0c15

When the next ODL releases, i think you can use that setting to accomplish it?

**Comment by siasty** [comment]
Great! Now it works as i wanted :) 

http://145.239.95.108/

Thank you for your help.
