### ISSUE TITLE
How to define action

### ISSUE THREAD

**Issue by sgom84** [OData/AspNetCoreOData#244]
Hello. With .net core 3.1 and odata 7.5.7 I had the following action:
```
builder.Namespace = "Default"; 

var av = builder.Action("RequireBaseLock");
av.CollectionParameter<RequestLock>("toRequest");
av.Returns<ResponseLock>();
```
(RequestLock and ResponseLock being my classes)

on the controller, the method is defined in this way:

public virtual async Task<IActionResult> RequireBaseLock(ODataActionParameters parameters)

with the following attributes:
```
[HttpPost]
[ODataRoute("RequireBaseLock()")]
```
being my odata mapped with "odata", this call has success:
http://localhost:63258/odata/RequireBaseLock()

All right. Now on the project updated to .net5 and odata 8.0.0

- changed [ODataRoute("RequireBaseLock()")] to [Route("RequireBaseLock()")] (OdataRoute doesn't exist anymore)

if I call
http://localhost:63258/odata/RequireBaseLock()
I get a 405 error method not allowed. It says that only delete, get and put are allowed.

Ok. so I tried changing [HttpPost] to [HttpPut]
In this case I get a 404 not found error
I tried calling with and without parenthesis (), and also with the namespace (http://localhost:63258/odata/Default.RequireBaseLock()) without success

Any idea whatI'm doing wrong?
Thank You

**Comment by xuzhg** [comment]
@sgom84 Can you enable OData route debug and check your OData route template? 

https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Startup.cs#L80

**Comment by sgom84** [comment]
Hi @xuzhg and thank You.
With odata route debug I see that all of my actions/functions are in the non odata mappings.

So http://localhost:63258/odata/RequireBaseLock() gives a 404, (a 405 if I try with POST)
and http://localhost:63258/RequireBaseLock() reaches the action.

So for some reason the route isn't in the odata endpoint. I found a blog of yours
https://devblogs.microsoft.com/odata/attribute-routing-in-asp-net-core-odata-8-0-rc/
about an RC version. Here You talk about [ODataRouting] attribute, but It isn't int the library (Intellisense suggest installing
Microsoft.AspNet.WebApi.OData or Microsoft.AspNet.OData, but if I'm correct those are libraries for .net framework)

**Comment by xuzhg** [comment]
@sgom84 We renamed "ODataRoutingAttribute" to "ODataAttributeRoutingAttribute". See here: https://docs.microsoft.com/en-us/odata/changelog/aspnetcoreodata-8x#800

**Comment by sgom84** [comment]
Even with [ODataAttributeRouting] the action goes to the non odata.
I also see that [ODataAttributeRouting] shouldn't be necessary (the controller in which there is my action derives from a class that inherits from ODataController).

So now my action has these attributes:
[ODataAttributeRouting]
[HttpPut("RequireBaseLock()")]

and it isn't mapped in odata

**Comment by xuzhg** [comment]
@sgom84  you can use [Route("odata")] to set the route prefix.

**Comment by sgom84** [comment]
@xuzhg thank You for your help

**Comment by sgom84** [comment]
Ah, one last thing (maybe this should be a different issue)

Actions now work only with put (as I said, if I try to call actions with post I receive a 405 error code and the message that only delete, get and put are allowed)

When I started using OData I remember that in different sources It was said that for actions use post or put was indifferent (in my project I have some actions with post and some actions with put)

Now, is this a change (actions have to be mapped with put) or is this a problem with my project?
(I have no problem changing actions with post to actions with put)

**Comment by xuzhg** [comment]
@sgom84 From OData spec, to call an action, you should send a POST HTTP request.  to call a function, you should send a GET HTTP request.  But, that's a requirement in the built-in conventional routing.  See here: https://github.com/OData/AspNetCoreOData/blob/e83394da46c144753cedfb4f31158d86b44fab76/src/Microsoft.AspNetCore.OData/Routing/Conventions/ActionRoutingConvention.cs#L35-L38

For attribute routing, I didn't add any limitations. All is in your control. 
Maybe I need to add a similar check in the attribute routing ?

**Comment by sgom84** [comment]
Hi. I tried again with post and It works.
Now my action has the following attribute:

[HttpPost(ServerInfo.ODataPrefix + "/RequireBaseLock")] ( ServerInfo.ODataPrefix is a const string "odata")

and it works (the action is mapped in http://localhost:63258/$odata and works with POST)

maybe the 405 error was bound to the fact that the action wasn't mapped correctly in odata (when I missed the "odata/" part)

**Info** 
the action works also with 
[HttpPut(NovaServerInfo.ODataPrefix + "/RequireBaseLock")]
The action is mapped with Put in http://localhost:63258/$odata and it works being called with Put, so if this should't happen
You should check this.

Thank You so much
