### ISSUE TITLE
Possible to apply additional filtering to expand when using [EnableQuery]?

### ISSUE THREAD

**Issue by groogiam** [OData/AspNetCoreOData#252]
I have a security requirement where I need to be able to add some additional conditional checks to expanded entities. E.g. A user may have permission to read a given root entity but may not have permission to read all sub entities of a particular navigation. Is there any mechanism to manipulated the expand expression or inject additional logic into the generated expansion query? 

Using the standard enablequery pattern below there does not seem to be any mechanism to manipulate IQueryable created by [EnableQuery] as the controller method does not appear to have access to this object. Thanks in advance for your help.

```c#
        [HttpGet]
        [EnableQuery(EnableCorrelatedSubqueryBuffering = true, PageSize = 500)]
        public Task<IQueryable<MyEntity>> Get()
        {
            //if the query contains and expand I would like to apply and additional where clause to it
            return _db.Entities;
        }
```

**Comment by TehWardy** [comment]
EF will handle this with Set Filters ensuring the filter is applied anywhere the entity appears in the graph.
Is that what you need ?

**Comment by groogiam** [comment]
I'm not sure that the EF Filter functionality suites my use case. The additional filters are generated dynamically based the users security context can be quite complex in some cases. The EF core query filters just don't seem expressive enough. Further more this seems like the wrong layer to add this logic. The security filter is a function of the public api and there are cases where the underlying server could would want to run queries against the database without the security filtering.

What I am really looking for as a way to manipulate the underlying query that is generated from the EnableQuery filter. Would this be possible using another Action filter or by extending the EnableQuery attribute?

**Comment by TehWardy** [comment]
I have exactly the same problem you do by the sounds of things.
By applying the filtering at the FB level in this manner I can ensure that when I go to the db I never pull data out that the user doesn't have access to no matter where it appears in the expression tree.

My solution was to add a "User" property in to my DbContext.
When loading the user property in to memory (on first access) I disable all the filters and pull the user with their attached roles.

Then I apply my filters based on that user info.
The filters in EF can be switched on or off at will with a simple db.DisableFilters) or db.EnableFilters) call too for those edge cases where you need to grab something without the filters applied.

Here's a sample from my codebase ...

```cs
    public partial class CoreDataContext : DbContext
    {
        IEnumerable<int> AdminOf => User.Roles?.Where(r => r.Role.Privileges.Any(p => p == "app_admin")).Select(r => r.Role.AppId) ?? Array.Empty<int>();
        IEnumerable<Guid> CurrentUserRoles => User.Roles?.Select(r => r.RoleId) ?? Array.Empty<Guid>();
        User user = null;
        public override User User
        {
            get
            {
                if (user == null)
                {
                    DisableFilters();
                    var userName = AuthInfo.Name ?? "Guest";
                    user = GetAll<User>(false)
                        .Include(u => u.Roles)
                            .ThenInclude(r => r.Role)
                        .FirstOrDefault(u => u.Id == userName)
                            ??
                        new User { DefaultCultureId = string.Empty, IsActive = true, Id = "Guest", DisplayName = "Guest" };

                    if (user.Id != AuthInfo.Name)
                    {
                        ImportUserFromMembership();
                        user = GetAll<User>(false)
                            .Include(u => u.Roles)
                                .ThenInclude(r => r.Role)
                            .FirstOrDefault(u => u.Id == userName);
                    }
                    EnableFilters();
                }
                return user;
            }
        }
        
        void ApplyFilters(ModelBuilder builder)
{
    // DMS security
    builder.Entity<FolderRole>().HasQueryFilter(fr => fr.Role != null);
    builder.Entity<Folder>().HasQueryFilter(f => AdminOf.Contains(f.AppId) || f.Roles.Any(r => CurrentUserRoles.Contains(r.RoleId) && r.Role.Privs.Contains("folder_read")));
    builder.Entity<File>().HasQueryFilter(f => AdminOf.Contains(f.Folder.AppId) || (f.Folder != null && f.Folder.Roles.Any(r => CurrentUserRoles.Contains(r.RoleId) && r.Role.Privs.Contains("file_read"))));
    builder.Entity<FileContent>().HasQueryFilter(i => i.File != null);

    // CMS security
    builder.Entity<Role>().HasQueryFilter(r => AdminOf.Contains(r.AppId) || CurrentUserRoles.Contains(r.Id));
    builder.Entity<UserRole>().HasQueryFilter(ur => ur.Role != null);
    builder.Entity<User>().HasQueryFilter(u => u.Roles.Any());
    builder.Entity<PageRole>().HasQueryFilter(pr => pr.Role != null);
    builder.Entity<Page>().HasQueryFilter(p => AdminOf.Contains(p.AppId) || p.Roles.Any(pr => CurrentUserRoles.Contains(pr.RoleId) && pr.Role.Privs.Contains("page_read")));
    builder.Entity<PageInfo>().HasQueryFilter(i => i.Page != null);
    builder.Entity<Content>().HasQueryFilter(i => i.Page != null);

    // Mail security
    builder.Entity<SentEmail>().HasQueryFilter(mail => mail.SentByUserId == User.Id || AdminOf.Contains(mail.AppId));
    builder.Entity<QueuedEmail>().HasQueryFilter(mail => mail.SentByUserId == User.Id || AdminOf.Contains(mail.AppId));

    // other
    builder.Entity<ScheduledTask>().HasQueryFilter(t => AdminOf.Contains(t.AppId));
    builder.Entity<Calendar>().HasQueryFilter(c => AdminOf.Contains(c.AppId) || c.App.Roles.Any(r => CurrentUserRoles.Contains(r.Id) && r.Privs.Contains("calendar_read")));
    builder.Entity<CalendarEvent>().HasQueryFilter(e => e.Calendar != null);
}
 ```

This represents a chunk of security info based on the user for a DB that stores data for my custom content management system and my custom document management system.
As you can see the filters hang off the loaded user but also in some cases hang off visibility of parent entities allowing me to build out some pretty deep complexity with very simple rules.

From an OData point of view then I don't have to worry about it.
But we do also apply other priv checks for various situations in the "service layer" (my stack is layered like: API > Service > Data)

....

Still not convinced then ok ...
Why not return a wrapper object around the IQueyable from the controller actions just like how the OData framework works ny doing something like ...

```cs
return Ok(new SecureQueryable(user, Db.GetAll<T>()));
```

... as I suggested here: https://github.com/OData/AspNetCoreOData/issues/266 though this may result in what looks like garbage in the Expression tree.
EF today is really good at building very tidy queries.

**Comment by TehWardy** [comment]
Sorry for the late reply, must have missed the last notif on this ticket but here's what you need to do ...
```cs
public class MyDbContext : DbContext 
{
        public void DisableFilters() => FilteringEnabled = false;
        public void EnableFilters() => FilteringEnabled = true;
        ...
}
```
I have these methods as part of my interface to abstract away EF ... although I realise this is basically an impossibility due to how tightly bound EF is to other tech like OData.

You could just use ...
```cs
var ctx = new YourDbContext();
ctx.FilteringEnabled = false;
```
... if you prefer.
