### ISSUE TITLE
8.0.1 How do we replace DefaultSkipTokenHandler and customize response?

### ISSUE THREAD

**Issue by stack111** [OData/AspNetCoreOData#262]
in 7.5.x we have a way to replace the default skip token handler to be any derived type of SkipTokenHandler.

In 8.0.1 we would need to do the same to to update to the latest version.
In 8.0.1, I have tried to replace like so:

```
services
                .AddControllers(options =>
                {
                    options.InputFormatters.RemoveType<ODataInputFormatter>();
                })
                .AddOData(opt => opt
                    .AddRouteComponents("odata", GetEdmModel(), svcs =>
                    {
                        svcs.RemoveFirstOccuranceOfService<SkipTokenHandler>();
                        svcs.RemoveFirstOccuranceOfService<DefaultSkipTokenHandler>();
                        svcs.AddSingleton<SkipTokenHandler, CosmosDbSkipTokenHandler>();
                    })
                    .Select().Filter().OrderBy().Count().SetMaxTop(ModelConstants.MaxTopCount).SkipToken()
                    .RouteOptions.EnableControllerNameCaseInsensitive = true)
```

I confirmed the instances are removed from the container and I have added my implementation.

However, during execution of `EnableQueryAttribute` exception is thrown and it's is coming from DefaultSkipTokenHandler.cs, 

```
{
    "message": "The query specified in the URI is not valid. Expected literal type token but found token 'f7b2'.",
    "exceptionMessage": "Expected literal type token but found token 'f7b2'.",
    "exceptionType": "Microsoft.OData.ODataException",
    "stackTrace": "   at Microsoft.OData.UriParser.ExpressionLexerLiteralExtensions.ReadLiteralToken(ExpressionLexer expressionLexer)\r\n   at Microsoft.OData.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference)\r\n   at Microsoft.AspNetCore.OData.Query.DefaultSkipTokenHandler.PopulatePropertyValuePairs(String value, ODataQueryContext context)\r\n   at Microsoft.AspNetCore.OData.Query.DefaultSkipTokenHandler.ApplyToCore(IQueryable query, ODataQuerySettings querySettings, IList`1 orderByNodes, ODataQueryContext context, String skipTokenRawValue)\r\n   at Microsoft.AspNetCore.OData.Query.DefaultSkipTokenHandler.ApplyToImplementation(IQueryable query, SkipTokenQueryOption skipTokenQueryOption, ODataQuerySettings querySettings, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.DefaultSkipTokenHandler.ApplyTo(IQueryable query, SkipTokenQueryOption skipTokenQueryOption, ODataQuerySettings querySettings, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.SkipTokenQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)"
}
```

It appears a new ODataQueryOptions is created in the attribute and then follows all the way down to possibly a [singleton instance of DefaultSkipTokenHandler](https://github.com/OData/AspNetCoreOData/blob/78270ec9eb9bf5d5678fcd6911a58ad8fddf6625/src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs#L31). 

https://github.com/OData/AspNetCoreOData/blob/78270ec9eb9bf5d5678fcd6911a58ad8fddf6625/src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs#L31

I suspect this is because somehow the context is null, but I'm a bit confused because the [ODataQueryOptions is validating for the container to exist](https://github.com/OData/AspNetCoreOData/blob/cdd28f3aaf0a6f86b5918e65d96e40f00800945c/src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs#L75) in the attribute which the call stack started.

https://github.com/OData/AspNetCoreOData/blob/cdd28f3aaf0a6f86b5918e65d96e40f00800945c/src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs#L75

## Workaround / Not Complete

I used reflection to replace the `DefaultSkipTokenHandler.Instance`.

```
var instance = typeof(DefaultSkipTokenHandler)
               .GetField("Instance", BindingFlags.Static | BindingFlags.NonPublic)
               .GetValue(null) as DefaultSkipTokenHandler;

            typeof(DefaultSkipTokenHandler)
               .GetField("Instance", BindingFlags.Static | BindingFlags.NonPublic)!
               .SetValue(instance, new CosmosDbSkipTokenHandler());
```

The work around produced the passthrough validation I was looking for, However as a side-effect I lost the wrapping metadata json object. The object I mean is the `{ "items": [ {...}, {...}, {...} ], "count": 100, "odata.context": "abc" }`, 

Second issue is how do we rename these properties?
Expected (from 7.5.x):
![image](https://user-images.githubusercontent.com/778070/127263147-7cf9c914-db58-4644-b7d1-a250cb2e7bfa.png)

Actual (8.0.1):
![image](https://user-images.githubusercontent.com/778070/127262906-79c9aaf1-f287-4b33-8e4a-92317fe325e0.png)

**Comment by mikepizzo** [comment]
We changed how dependency injection works in 8.0.  This could be a basic dependency injection issue.

**Comment by stack111** [comment]
This has been resolved now. [Public documentation](https://learn.microsoft.com/odata/webapi-8/tutorials/custom-skiptokenhandler?tabs=net60%2Cvisual-studio) is available, and I have confirmed it works as expected.
