### ISSUE TITLE
Dynamic property is null with endpoint routing

### ISSUE THREAD

**Issue by sunliangqin** [OData/AspNetCoreOData#27]
I was following this [post](https://devblogs.microsoft.com/odata/dynamic-properties-container-property-in-odata-client/) to build a service with dynamic property support. The example in github works fine for me. However, when I try to enable endpoint routing by adding [Route("odata/test")] to the [post method](https://github.com/gathogojr/ExDP/blob/f726f32c79385398a81d217fbd52ccdab384f73c/ExDP/Controllers/DirectorsController.cs#L71). The dynamic property is always null. Is this a known issue? Any comments are highly appreciated.

**Comment by xuzhg** [comment]
RouteAttribute is not used in OData attribute routing.
OData attribute routing is using [ODataRouteAttribute] and [ODataRoutePrefixAttribute].

**Comment by xuzhg** [comment]
@gathogojr  Since it's related to your post, would you please take a look?

**Comment by gathogojr** [comment]
@sunliangqin I hope you're able to make a distinction between following three things:
- ASP.NET Core attribute routing (using `RouteAttribute` - `Route` in short form), 
- OData attribute routing (using `ODataRouteAttribute` and `ODataRoutePrefixAttribute` - `ODataRoute` and `ODataRoutePrefix` in short form respectively)
- Endpoint routing

Actions are either conventionally-routed or attribute-routed. Placing a route on the controller or the action (_like you have done above_) makes it attribute-routed, not endpoint-routed. However, you can either call `MapControllers` inside `UseEndpoints` to map attribute-routed controllers or call `MapControllerRoute` to map both conventionally-routed controllers and attribute-routed controllers.

You can read more about ASP.NET Core routing [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1) and OData attribute routing [here](https://docs.microsoft.com/en-us/odata/webapi/attribute-routing)

I have added a sample service to the repo with endpoint routing enabled. If you changed [this line](https://github.com/gathogojr/ExDP/blob/19bf511a588bcbffb7fe48fe35fe45d0b4e15c23/ExDP.Client/Program.cs#L13) in the client project, 
from:
```csharp
var serviceUri = new Uri("http://localhost:8302/odata");
``` 
to
```csharp
var serviceUri = new Uri("http://localhost:1538/api");
```
you'll find everything works the same, with endpoint routing enabled.

**Comment by sunliangqin** [comment]
Sorry for the beginner questions. After switching to the Odata attribute routing. It worked for me. Thanks both for the help!
