### ISSUE TITLE
$expand not working with ODataDymanicModel sample project

### ISSUE THREAD

**Issue by danleydmello** [OData/AspNetCoreOData#275]
I am running ODataDynamicModel sample locally as is [https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataDynamicModel]. I tried using `$expand` query option on DetailInfo navigation property of Products but it does not show DetailInfo in the output result:

Query:
`http://localhost:4527/odata/mydatasource/Products?$expand=DetailInfo`

Output:
{"@odata.context":"http://localhost:4527/odata/mydatasource/$metadata#Products","value":[{"Name":"abc","ID":1},{"Name":"def","ID":2}]}

**Comment by danleydmello** [comment]
I played with the code and made the expand option working by adding this loging in the controller:

  ODataQueryOptionParser parser = new(Request.GetModel(), edmEntityType, source, options);
Request.ODataFeature().SelectExpandClause = parser.ParseSelectAndExpand();


Is this the correct way for this approach?

**Comment by xuzhg** [comment]
@danleydmello Thanks for your codes. 

I think your codes are good.  And It does work fine.
Another way is to create an ActionFilter, similar to https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs#L38 or derived from it and override the methods. 

Do you mind creating a PR to include your codes (or new implementation using ActionFilter) to help other customers? 

I'd love to review it and merge it.

**Comment by danleydmello** [comment]
@xuzhg , sure will do but I am not familiar with EnableQuery logic so I will just add my code to HandleAllController [](https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataDynamicModel/Controllers/HandleAllController.cs), Is that okay ?

**Comment by xuzhg** [comment]
@danleydmello Yes, That's ok.

**Comment by danleydmello** [comment]
@xuzhg , I am getting 403  when pushing branch to this repo.

**Comment by xuzhg** [comment]
@danleydmello you'd better to fork our repo and create the branch at your fork repo and use that to create the PR.

**Comment by danleydmello** [comment]
@xuzhg , ok created fork, push my changes, created a PR, accepted the contributor license but for some reason I can't add the reviewer. https://github.com/OData/AspNetCoreOData/pull/280

**Comment by xuzhg** [comment]
@danleydmello It doesn't matter. We can do it. Thanks.

**Comment by xuzhg** [comment]
@danleydmello Your PR looks good to me. I merged it and thanks for your contribution. 
Looking forward to your next PR. 
![image](https://user-images.githubusercontent.com/9426627/129975635-72162002-a9a5-447a-9f23-06d1c63e88c1.png)

**Comment by danleydmello** [comment]
your welcome, thanks for your help as well, as we are implementing the dynamic odata framework for our multi tenant model
