### ISSUE TITLE
Why are all navigation properties included if there is no expand option?

### ISSUE THREAD

**Issue by AndrewZenith** [OData/AspNetCoreOData#276]
https://github.com/OData/AspNetCoreOData/blob/a1977e3c2491fc5ebdf51f6a924f5530422f3568/src/Microsoft.AspNetCore.OData/Formatter/Serialization/SelectExpandNode.cs#L148

```
if (selectExpandClause == null)
                {
                    SelectAllDynamicProperties = true;

                    // includes navigation properties
                    SelectedNavigationProperties = structuralTypeInfo.AllNavigationProperties;
```

As there is no expand clause then navigation properties shouldn't be included?

Our tables have many columns and many navigation properties, and for example I think this is increasing the time taken to serialize from about 100ms to 700ms.

**Comment by xuzhg** [comment]
@AndrewZenith Thanks for your input.

In full metadata scenario ($format=application/json;odata.metadata=full), OData tries to write the navigation property link for all navigation properties in a resource.  `SelectedNavigationPropeties` is used to accomplish this. Most of the time, it doesn't retrieve the navigation properties data from database.

However, "ExpandedProperties" is for $expand. 
https://github.com/OData/AspNetCoreOData/blob/a1977e3c2491fc5ebdf51f6a924f5530422f3568/src/Microsoft.AspNetCore.OData/Formatter/Serialization/SelectExpandNode.cs#L82

If we have the navigation property expanded, such navigation property should be removed from "SelectedNavigationProperties". See code here: https://github.com/OData/AspNetCoreOData/blob/a1977e3c2491fc5ebdf51f6a924f5530422f3568/src/Microsoft.AspNetCore.OData/Formatter/Serialization/SelectExpandNode.cs#L565-L573

**Comment by AndrewZenith** [comment]
GET http://lambda.fcluk1/81a/odata/FCL/ConsignmentStatistics?$top=100 HTTP/1.1
User-Agent: PostmanRuntime/7.28.3
Accept: */*
Cache-Control: no-cache
Postman-Token: acfef52b-47da-4256-ab92-ed86b25ae1a3
Host: lambda.fcluk1
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

Response took 646 ms.

GET http://lambda.fcluk1/81a/odata/FCL/ConsignmentStatistics?$top=100&$format=application/json;odata.metadata=none HTTP/1.1
User-Agent: PostmanRuntime/7.28.3
Accept: */*
Cache-Control: no-cache
Postman-Token: 81897b66-b5ad-4758-afaa-48186a93c428
Host: lambda.fcluk1
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

Response took 648 ms.

A get on:
http://lambda.fcluk1/81a/odata/FCL/$metadata#ConsignmentStatistics

Takes 625 ms.

I'm pretty sure the piece of code I highlighted is run through regardless of whether the metadata is requested or not, and the metadata is huge in itself in my Model (I spotted it using the 1st of these GETS).  I can see it's not reading the navigation data itself, but just going all the way through the model is just not needed and slowing things down dramatically!

**Comment by AndrewZenith** [comment]
http://lambda.fcluk1/81a/odata/FCL/ConsignmentStatistics?$top=100&$select=Sql_Rfa,ClientIDPrincipal
Takes about 40ms.  And debugging I can see that it's not going through the 66 navigation properties, each of which have other navigation properties.

**Comment by xuzhg** [comment]
@AndrewZenith To be clear, $top=100 by default will include the "key" in the query and use that to "orderby" then return the top 100. I think most of time is used in the sorting. Can you try to use "avoid stable sorting"?
