### ISSUE TITLE
UseOData* Middleware order should be documented

### ISSUE THREAD

**Issue by dxrdxr** [OData/AspNetCoreOData#293]
The OData documentation and samples do not define the order of OData middleware used in `Startup.Configure()` and in existing examples the order may be inconsistent.

The order of Middleware is documented [here ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order). It states "The order is critical for security, performance, and functionality", additionally searching platforms such as **StackOverFlow** shows many questions/problems that are resolved by fixing the middleware ordering. In particular ordering relative to `UseRouting` can be problematic. Note that in the diagram, it shows "Custom Middlewares" **after** "Routing" but most (but not all)  OData samples OData middleware  **before** `UseRouting`, which is confusing.

I have identified the following OData middleware (via `UseMiddleware`) that does not clearly specify ordering:

- `UseODataBatching`
- `UseODataQueryRequest`
- `UseODataRouteDebug`
- `UseODataOpenApi`

It is preferable to also create a sample that uses most of the common middleware. A good example [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order) has a variety of "app.Use*" middleware in the required ordering, with less commonly used middleware commented out. Creating an OData sample that takes this existing sample and expands it to include OData (and Swagger?) middleware would be highly beneficial.

**Comment by xuzhg** [comment]
See the doc at: https://github.com/OData/AspNetCoreOData/blob/master/docs/odatamiddelware.md
