### ISSUE TITLE
OData result caching guidance

### ISSUE THREAD

**Issue by seanlmcgill** [OData/AspNetCoreOData#294]
I'm trying to determine a strategy for caching of OData results.   Typically with regular API controllers it's possible to utilize the IDistributedCache interface to do so just before returning the results, however since with OData controllers a queryable is being returned that is not the case.  

I've had some luck in creating a resource filter attribute (IResourceFilter, Attribute) to intercept the result in the , eg:
```
public void OnResourceExecuted(ResourceExecutedContext context)
{
         if (context.Result is not OkObjectResult result) return;
            var json = JsonSerializer.Serialize(result.Value);
            var cache =
                (IDistributedCache)context.HttpContext.RequestServices.GetService(typeof(IDistributedCache));
          ... 
```

However this fails on things like $count & $expand so I'm going to continue digging a bit.  Just wondering though, is there any official guidance or plans on supporting caching in a similar manner?  It'd be great if there was some sort of way to hook-in such functionality so that the existing IDistributedCache interface could be utilized in the correct manner.  Thanks!

**Comment by seanlmcgill** [comment]
Was able to achieve utilizing IDistributedCache result caching from a custom middleware along w/ an attribute to enable it selectively

**Comment by Mhirji** [comment]
Hello @seanlmcgill ,

With respect to your solution, are your controllers returning an IQueryable?  I was just trying to do what you managed to do and am struggling a bit with the response.  Would you be able to share your code by any chance?

Thanks!

**Comment by julealgon** [comment]
This should be moved to discussions.

**Comment by seanlmcgill** [comment]
> Hello @seanlmcgill ,
> 
> With respect to your solution, are your controllers returning an IQueryable? I was just trying to do what you managed to do and am struggling a bit with the response. Would you be able to share your code by any chance?
> 
> Thanks!

I am, sorry just saw your question here.  I can't share my code as it's for my current company, however - what I did was create a middleware that checks for an attribute on the current controller, like [CacheODataResult(string prefix)], then I use the service collection to get an instance of the IDistributedCache object and see if the result already lives in the cache from a well known key & return it.  If not, grab the result, cache it, return it.
