### ISSUE TITLE
ODATA 8.0.1 [AutoExpand] Attribute Not Working

### ISSUE THREAD

**Issue by martinicr** [OData/AspNetCoreOData#297]
**Note**: I'm still not sure if this attribute is fully supported in the new version of OData (8.0.1).

I have the following classes:

```csharp
public class ClassA
{
  public string Id { get; set; };

  [AutoExpand]
  public ClassB ClazzB { get; set; };
}

public class ClassB
{
  public string SomeProp { get; set; };

  [AutoExpand]
  public ClassC ClazzC { get; set; }
}

public class ClassC
{
  public string Id { get; set; }

  public string AnotherProp { get; set; }
}
```

When querying `ClassA` model, mny expectation is to get something like:

```json
{
    "@odata.context": "https://...$metadata#ClassA/$entity",
    "id": "a6fb7183-e87a-428e-8b62-c159920b2a5e",
    "clazzB": {
        "someProp": "some-prop",
        "clazzC" : {
           "Id": "random-id",
           "anotherProp": "another-prop"
         }
    }
}
```

However, actual response body is:

```json
{
    "@odata.context": "https://...$metadata#ClassA/$entity",
    "id": "a6fb7183-e87a-428e-8b62-c159920b2a5e",
    "clazzB": {
        "someProp": "some-prop"
         }
    }
}
```

I see the `[AutoExpand]` attribute is documented [here](https://docs.microsoft.com/en-us/odata/webapi/autoexpand-attribute), however, I'm not sure if this is supported in version 8. If not, what's the preferred way to enable auto expansion in OData models?

Thanks in advance.

**Comment by xuzhg** [comment]
@martinicr It's a known issue same as https://github.com/OData/WebApi/issues/2552.

Because `ClassB` is defined as a complex type.  Autoexpand navigation property on complex type is not fully supported.

I'd like to enable it in the next version if it's ok.
