### ISSUE TITLE
QueryOptions not working with Dynamic model 

### ISSUE THREAD

**Issue by steverash** [OData/AspNetCoreOData#298]
Hi - 

I've created a project based off the Dynamic model sample.   I've managed to adapt it to get query options (filter, expand, select) successfully - and built my dynamic data accordingly.   For various reasons I'm not using EF, but doing SQL directly.   

However these options are not getting applied when the result in serialized.   So, for example, the expanded data does not serialize.   

I've tracked this down in the OData code.  The serialization relies on the HttpRequest having the ODataFeature.QueryOptions object set.  

https://github.com/OData/AspNetCoreOData/blob/04541a22505afc2819fd05c54508142bb547dc79/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterHelper.cs#L101

However this is only ever set during the call to ODataQueryOptions.ApplyTo(IQueryable.

https://github.com/OData/AspNetCoreOData/blob/04541a22505afc2819fd05c54508142bb547dc79/src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs#L458

Since with the Dynamic model I am not using an IQueryable and cannot use this method.   The ODataFeature class has the QueryOptions marked as internal - so I cannot set in my code.  

https://github.com/OData/AspNetCoreOData/blob/04541a22505afc2819fd05c54508142bb547dc79/src/Microsoft.AspNetCore.OData/Abstracts/ODataFeature.cs#L139

In my project I've changed this to public and set it within my code - and that does solve the problem.   

I'm happy to submit that as a PR if it is agreed to be a reaosnable fix - unless there is another way I've missed.

**Comment by xuzhg** [comment]
@steverash 
So far, that's internal because we will refactor/improve that in the future. 
As a workaround now, maybe you can use reflection to reset the internal property on the feature.

**Comment by steverash** [comment]
I've switched to use reflection to set the property and it does work around the problem.

**Comment by xuzhg** [comment]
Please file new issue if you have further questions. thanks.
