### ISSUE TITLE
Allow to override behavior of SelectExpandBinder.

### ISSUE THREAD

**Issue by FlaviusHouk** [OData/AspNetCoreOData#304]
## Motivation and use cases

Our application has database (postgresql) tables like here
```SQL
CREATE TABLE my_table
(
    id SERIAL,
    some_value text,
    ...
    metadata jsonb
);
```
Entity framework allows to map System.Text.Json.JsonDocument to that json column. So our database object looks like
```c#
public class MyObject
{
    int Id { get; init; }
    string SomeValue { get; init; }
    ...
    JsonDocument Metadata { get; init; }
}
```

Model for this type defined like this
```c#
            EdmEntityType type = new("My.Project.Namespace",
                                     nameof(MyObject));

            type.AddStructuralProperty(nameof(MyObject.SomeValue), EdmPrimitiveTypeKind.String);

            keyProp = type.AddStructuralProperty(nameof(MyObject.Id), EdmPrimitiveTypeKind.Int32);
            type.AddKeys(keyProp);

            EdmComplexType metadataType =
                new("System.Text.Json", nameof(JsonDocument), null, false, true);

            EdmComplexTypeReference typeRef =
                new(metadataType,
                        isNullable: true);

            type.AddStructuralProperty(nameof(MyObject.Metadata), typeRef);
            EdmEntitySet objects = container.AddEntitySet("objects", type, false);

            model.AddElement(type);
            model.AddElement(metadataType);
```

I defined such FilterBinder implementation that allows to create proper expressions for that (.../odata/objects?$filter=metadata/prop eq 'MyValue' to obj.Metadata.RootObject.GetProperty(prop.Name).GetString()) and implementation for ODataResourceSerializer to write values from JsonDocument to ODataWriter. And now everything works except $select. SelectExpandBinder cannot create proper expressions for JsonDocument and as a result when I do .../odata/objects?$select=metadata I receive [... "value": {"metadata": {}} ...]. To be able to process JsonDocument there I would like to provide my own implementation of SelectExpandBinder that will build proper expressions. 

## Change proposal
1. Make SelectExpandBinder class public and maybe introduce interface for it.
2. Register it in DI system instead and use object from there instead of calling static method (examples in SelectExpandQueryOptions).

**Comment by xuzhg** [comment]
@FlaviusHouk Thanks for your suggestion, We are doing a similar refactor at https://github.com/OData/AspNetCoreOData/pull/296.

please feel free to share your suggestions/comments at that PR.

**Comment by FlaviusHouk** [comment]
@xuzhg thank you for your response. Will look there.

**Comment by KenitoInc** [comment]
@FlaviusHouk FYI, we welcome contributions. If you can, share a PR we will review
