### ISSUE TITLE
Detected package version outside of dependency constraint: Microsoft.OData.Core 7.9.0 requires Microsoft.Spatial (= 7.9.0) but version Microsoft.Spatial 7.9.1 was resolved.

### ISSUE THREAD

**Issue by swidz** [OData/AspNetCoreOData#305]
After installing NuGet package Microsoft.AspNetCore.Odata 8.0.2 the following warning is displayed in build error list

**Comment by xuzhg** [comment]
@swidz It's werid. I just tested it by starting a new Web Api application and installing the 8.0.2. And No errors.

OData.ModelBuilder (1.0.7) depends on ODL 7.9.0
Meanwhile, AspNetCore.OData (8.0.2) depends on ODL 7.9.0.

I don't know why do you have 7.9.1 installed. Are you starting from an existing project? Or did you install ODL 7.9.1 separately?

**Comment by swidz** [comment]
Hi, My fault, It was another project in the solution that had dependency to Microsoft.Spatial 7.9.1
