### ISSUE TITLE
Does this library support requesting specific type of $metadata?

### ISSUE THREAD

**Issue by danleydmello** [OData/AspNetCoreOData#318]
As per [oData specs](https://www.odata.org/blog/queryable-odata-metadata/), it supports requesting specific types using the standard OData query conventions.:
GET http://localhost:999/dataservice/$metadata/ResourceTypes('Namespace.Product')

Is this supported ?

**Comment by xuzhg** [comment]
@danleydmello No, it's not supported yet. 

In OData v4, it is this spec. http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406398100

However, it's pruned in OData v4.01. See here: https://docs.oasis-open.org/odata/new-in-odata/v4.01/cn04/new-in-odata-v4.01-cn04.html#sec_PrunedMetadataService

**Comment by danleydmello** [comment]
Thanks @xuzhg  for clarification
