### ISSUE TITLE
Conflicts with EF Core tools 5.0

### ISSUE THREAD

**Issue by weitzhandler** [OData/AspNetCoreOData#32]
Reported here: https://github.com/OData/ModelBuilder/issues/12.

**Comment by keatkeat87** [comment]
any update or workaround ?

**Comment by weitzhandler** [comment]
Workaround: install the System.ComponentModel.Annotations package.

**Comment by xuzhg** [comment]
Thanks for reporting this. The next version will include the dependency updates.

**Comment by weitzhandler** [comment]
@keatkeat87 

The solution now (until next version is released), to explicitly install the latest version of `Microsoft.OData.ModelBuilder`, so you can get rid of those warnings.
