### ISSUE TITLE
Filtering for Nullable value types and Nullable reference types produces different results

### ISSUE THREAD

**Issue by SviatoslavBachynskyi** [OData/AspNetCoreOData#338]
Filtering by Nullable value types produces queries that cannot be translated by MongoDriver and possibly ORMs like EntityFramework

### Assemblies affected

Microsoft.AspNetCore.OData lib 8.0.3*

### Reproduce steps

1. Call endpoint with `$filter=nullableInt eq 123`
where nullableInt is property
`int? NullableInt { get; set; }`

### Expected result

preduces expression similar to this:
`document => document.NullableInt == 123`

### Actual result
produces experession similar to this:
`document => (document.NullableInt == 123) == (bool? true)`

```
'(.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>)
.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>(Classes.Document $$it) {
    ($$it.NullableInt == (System.Nullable`1[System.Int32]).Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty)
    == .Constant<System.Nullable`1[System.Boolean]>(True)
}
```

### Additional detail

It causes problems with MongoDb driver, but I might do the same for ORMs like EntityFramework. MongoDb doesn't support Filtering with bool? and throws an exception. The only way to make it work is to apply filters for data loaded in memory.
A similar issue is happening with DateTime? and DateTimeOffset?, it returns bool? as the result of the comparison.

Additionally, it is unclear why filtering for string produces normal query. This comparison to `(bool? true)` is a redundant step.

`document => document.NullableString == "123"`

```
'(.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>)

.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>(Classes.Document $$it) {
    $$it.NullableString == .Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty
}
```

**Comment by xuzhg** [comment]
@SviatoslavBachynskyi  can you explicitly make the property non-nullable? 
or can you use the configuration on the EnableQueryAttribute to suppress the nullable?

**Comment by xuzhg** [comment]
@SviatoslavBachynskyi 
Can you use 'https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Query/HandleNullPropagationOption.cs#L30' on EnableQueryAttribute?

For the "non-nullable", I mean can you build the Edm property explicitly as non-nullabel Edm property without changing the Clr Type?

**Comment by SviatoslavBachynskyi** [comment]
I use OdataQueryOptions to apply them to queryable, so [EnableQuery] didn't have any effect.

But I was able to pass query settings to ApplyTo Functions and it helped to solve the issue.

queryOptions.ApplyTo(queryable, new ODataQuerySettings(){ HandleNullPropagation = HandleNullPropagationOption.False})

Thank you @xuzhg  for your help.
