### ISSUE TITLE
Case Insensitivity Support

### ISSUE THREAD

**Issue by sjd2021** [OData/AspNetCoreOData#357]
https://github.com/OData/WebApi/issues/812 references the removal of the case insensitivity support, and I'm looking to see if there's a more standardized approach in the latest version of this package than rolling our own resolver and convention combo.

**Comment by xuzhg** [comment]
@sjd2021 Request URI is by default case insensitive in 8. There's no need to set the resolver.

**Comment by sjd2021** [comment]
> @sjd2021 Request URI is by default case insensitive in 8. There's no need to set the resolver.

My mistake. I thought that referred to the entire string. My api callers all receive payloads back in camel case, so they're always lost when I have to tell them to use pascal case to reference the entities in the odata parameters. 

`$orderby=created asc` doesn't work, but `$orderBy=Created` does. Is there any way around that?

**Comment by xuzhg** [comment]
@sjd2021 Can you try the latest nightly?

See fix at: 4ab80c7caa657dcadef2815cbdf423402829a67b

**Comment by xuzhg** [comment]
related: https://github.com/OData/AspNetCoreOData/issues/255

**Comment by sjd2021** [comment]
That worked. Thank you!

**Comment by xuzhg** [comment]
Shipped with 8.0.4. See https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.0.4
