### ISSUE TITLE
8.0.0-preview2 and EnableQueryAttribute without model ("Non-Edm Approach")

### ISSUE THREAD

**Issue by mikoskinen** [OData/AspNetCoreOData#36]
Trying to use EnableQueryAttribute without model throws an exception in 8.0.0-preview2:

> System.ArgumentNullException: Value cannot be null. (Parameter 'edmModel')
>    at Microsoft.AspNetCore.OData.Edm.EdmClrTypeMapExtensions.GetEdmType(IEdmModel edmModel, Type clrType)
>    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.GetModel(Type elementClrType, HttpRequest request, ActionDescriptor actionDescriptor)
>    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.GetODataQueryContext(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)

This seems to work OK with 7.5.2.

Based on the code in EnableQueryAttribute, I think the idea is that this should work:

            if (model == EdmCoreModel.Instance || model.GetEdmType(elementClrType) == null)
            {
                // user has not configured anything or has registered a model without the element type
                // let's create one just for this type and cache it in the action descriptor
                model = actionDescriptor.GetEdmModel(request, elementClrType);
            }

**Comment by ut786** [comment]
I have registered an EDM model in the setup but still getting the same error

**Comment by RobTF** [comment]
I see a similar issue - it almost feels like the library simply isn't complete in this regard;

If I do not call `.AddModel` as part of the `AddOData` call in `Startup.cs`, but instead simply add an `ODataQueryOptions<T>` parameter to an action method the library bombs out with the following exception;

```
System.ArgumentNullException: Value cannot be null. (Parameter 'model')
   at Microsoft.AspNetCore.OData.Query.ODataQueryContext..ctor(IEdmModel model, Type elementClrType, ODataPath path)
   at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
```

This appears to be down to code in ODataQueryParameterBindingAttribute.cs in the QDataQueryParameterBinding class, BindModelAsync method.

```
IEdmModel userModel = request.GetModel();
IEdmModel model = userModel != EdmCoreModel.Instance ? userModel : GetEdmModel(actionDescriptor, request, entityClrType);
ODataQueryContext entitySetContext = new ODataQueryContext(model, entityClrType, request.ODataFeature().Path);
```

The call to GetModel() on request always returns `null`. There appears to be some attempt to look for a sort of default model in `EdmCoreModel.Instance` with a call to `GetEdmModel()` which appears to be some sort of attempt at either creating an EDM model upfront, or at least looking elsewhere for it, but the method appears simply unfinished;

```
            internal static IEdmModel GetEdmModel(ActionDescriptor actionDescriptor, HttpRequest request, Type entityClrType)
            {
                if (actionDescriptor == null)
                {
                    throw Error.ArgumentNull("actionDescriptor");
                }

                if (request == null)
                {
                    throw Error.ArgumentNull("request");
                }

                if (entityClrType == null)
                {
                    throw Error.ArgumentNull("entityClrType");
                }

                IEdmModel model = null;

                return model;
            }
```

Is this functionality not currently in the preview? this approach worked fine in V7.

**Comment by lukas-gmuer** [comment]
#66 duplicate

**Comment by xuzhg** [comment]
Non-Edm scenario should work in the latest version. I'd close this issue. Please file new issue if you have further concerns or questions. thanks a lot.
