### ISSUE TITLE
"access-control-allow-methods" in header of url/$batch is "GET" instead of "POST"

### ISSUE THREAD

**Issue by ghost** [OData/AspNetCoreOData#364]
CORS preflight OPTIONS Request to [some api url]/$batch responds with header "access-control-allow-methods: GET", shouldn't this be "POST"?
Im using Odata 8.0.4.

**Comment by xuzhg** [comment]
@marabooy

**Comment by marabooy** [comment]
Thanks @xuzhg  I will investigate this.

**Comment by siasty** [comment]
has something moved on this? i have also problem with CORS in $batch request latest version
![image](https://user-images.githubusercontent.com/39690589/187652247-ef611a18-b1ed-4db1-ad3c-feb418714d80.png)
![image](https://user-images.githubusercontent.com/39690589/187652383-e3ee8b1c-c49d-4b3e-b051-b99003cc4ddd.png)

**Comment by julealgon** [comment]
I believe `$batch` used to work with `GET` in some older version, and was shifted to `POST` later right?

Isn't this a very simple and easy change to make? Any particular reason why it is still not fixed?

**Comment by marabooy** [comment]
@julealgon is this still an issue? I had a fix that was merged in https://github.com/OData/AspNetCoreOData/pull/308. Can you share a repro to assist with fixing this issue?

**Comment by marabooy** [comment]
Closes fixed issue for cors and $batch

**Comment by marabooy** [comment]
@siasty you may need to check the cors registration as the batch middleware not delegates all cors calls to the next middleware.
