### ISSUE TITLE
Invalid Uri for $ref request in a batch request with single changeset

### ISSUE THREAD

**Issue by gathogojr** [OData/AspNetCoreOData#365]
Invalid Uri for $ref request in a batch request with single changeset

### Assemblies affected

- Microsoft.OData Client 7.9.2
- Microsoft.OData.Core 7.9.2
- Microsoft.AspNetCore.OData 7.x
- Microsoft.AspNetCore.OData 8.x

### Reproduce steps

Consider an OData client application containing two entities related as follows:
```csharp
public class TestA
{
    public int Id { get; set; }
    public List<TestB> TestBs { get; set; }
}

public class TestB
{
    public int Id { get; set; }
    public int Value { get; set; }
}
```
If one wishes to send a batch request with a single changeset containing `TestA` and `TestB` entities together with the link between the two, the payload generated contains an invalid `Uri` for the `$ref` request.

**Code in client application:**
```csharp
var testA = new TestA { Id = 1 };
var testB = new TestB { Id = 1, Value = 13 };
context.AddToTestAs(testA);
context.AddToTestBs(testB);
context.AddLink(testA, "TestBs", testB);

context.SaveChanges(SaveChangesOptions.BatchWithSingleChangeset);
```
**Batch payload generated internally:**
```
--batch_c6718d3f-c42b-4650-bbf2-acf33e38c65d
Content-Type: multipart/mixed; boundary=changeset_cd219c83-deef-4b21-a6cf-59f0b8d960e3

--changeset_cd219c83-deef-4b21-a6cf-59f0b8d960e3
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST http://localhost/odata/TestAs HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.9.2

{"@odata.type":"#Ex113.Models.TestA","Id":1}
--changeset_cd219c83-deef-4b21-a6cf-59f0b8d960e3
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

POST http://localhost/odata/TestBs HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.9.2

{"@odata.type":"#Ex113.Models.TestB","Id":1,"Value":13}
--changeset_cd219c83-deef-4b21-a6cf-59f0b8d960e3
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

POST $1/TestBs/$ref HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
Content-Type: application/json;odata.metadata=minimal
User-Agent: Microsoft.OData.Client/7.9.2

{"@odata.id":"$2"}
--changeset_cd219c83-deef-4b21-a6cf-59f0b8d960e3--
--batch_c6718d3f-c42b-4650-bbf2-acf33e38c65d--
```

### Expected result

Valid Uri: POST http://localhost/TestBs/$ref HTTP/1.1

### Actual result

Invalid Uri: POST $1/TestBs/$ref HTTP/1.1

### Additional Details
This issue is not observed if the parent item already exists, e.g., if `TestA` entity was retrieved from the service.

**Comment by gathogojr** [comment]
Affects both 7.x and 8.x

**Comment by mikepizzo** [comment]
If we fix CopyAbsoluteUrl to handle relative Urls (similar to how the code would have worked in 7.x), does that fix the problem?  i.e., if we create just create it as a relative uri for the request, does it get resolved lower down in the code?  Note that there is code in ContentIdHelpers.ResolveContentId() to resolve these relative urls when processing individual requests.
