### ISSUE TITLE
OData 8: No more support for model distribution depending on http request?

### ISSUE THREAD

**Issue by JL-Ikosoft** [OData/AspNetCoreOData#373]
Hello :)

I cannot find any way to dynamically distribute EdmModel depending on URL parameter.

Let say that my uri is as follow: `https://domain.com/api/odata/<MyServiceSubscriberIdentifier>/STOCK`

"MyServiceSubscriberIdentifier" can change and EdmModel depends on that. For one subscriber EdmModel for STOCK will have 2 properties, for another one it will have 10.

It was supported in version 7 thanks to the MapODataRoute that has a container builder that accepts scoped services.

```csharp
app.UseEndpoints(
	endpoints =>
	{
		endpoints.MapODataRoute(
			"odata",
			$"api/odata/{{MyServiceSubscriberIdentifier}}",
			containerBuilder =>
			{
				containerBuilder.AddService(
					Microsoft.OData.ServiceLifetime.Scoped,
					typeof(IEdmModel),
					sp =>
					{
						var serviceScope = sp.GetRequiredService<HttpRequestScope>();
						string dataSourceName = serviceScope.HttpRequest.GetDataSourceFromRoute();
						if (string.IsNullOrWhiteSpace(dataSourceName))
						{
							dataSourceName = serviceScope.HttpRequest.GetDataSourceFromPath();
						}

						var provider = serviceScope.HttpRequest.HttpContext.RequestServices;
						var modelProvider = (IModelProvider)provider.GetService(typeof(IModelProvider));
						return modelProvider.GetModel(dataSourceName);
					});

				containerBuilder.AddService(
					Microsoft.OData.ServiceLifetime.Scoped,
					typeof(IEnumerable<IODataRoutingConvention>),
					sp =>
					{
						IList<IODataRoutingConvention> routingConventions = ODataRoutingConventions.CreateDefault();
						routingConventions.Insert(0, new MatchAllRoutingConvention());
						return routingConventions.ToList().AsEnumerable();
					});
			});
	});
```

How can we do now? Using `AddRouteComponents` doesn't help because it requires a model at startup.
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers().AddOData(opt =>
    {
        opt.Select();

        opt.AddRouteComponents("odata", GetEdmModel(), (services) =>
        {
            services.AddScoped<MyODataModelService>();
        });
    });
    services.AddHttpContextAccessor();
}
```
As There might be thousands of models i cannot load them a startup.

Thank you very much in advance for your help.

Kind regards

**Comment by xuzhg** [comment]
@JL-Ikosoft does https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataDynamicModel sample help?

Or something in https://devblogs.microsoft.com/odata/api-versioning-extension-with-asp-net-core-odata-8/ helping?

**Comment by JL-Ikosoft** [comment]
@xuzhg Yes it does Thanks! Really different approach. It's disturbing :D
