### ISSUE TITLE
There are 2 OData, Simple OData and EDM OData

### ISSUE THREAD

**Issue by andrew-vdb** [OData/AspNetCoreOData#374]
This is the tutorial for Simple OData ---> This simple version return array of object, not odata object
https://devblogs.microsoft.com/odata/up-running-w-odata-in-asp-net-6/

This is the tutorial for EDM OData --> This is working with $count=true !!!!!
https://devblogs.microsoft.com/odata/simplifying-edm-with-odata/
There are some steps missing from this tutorial
- Inherit ODataController in your Controller
- 
```
builder.Services.AddControllers().AddOData(opt => {
    ODataConventionModelBuilder odataBuilder = new ODataConventionModelBuilder();
    odataBuilder.EntitySet<Student>("Students");
    odataBuilder.EnableLowerCamelCase(); // to return for camel case
    opt.Expand().Count().Select().OrderBy().SkipToken().Filter().SetMaxTop(100);    //configure as needed
    opt.AddRouteComponents("odata",odataBuilder.GetEdmModel()); //notice the route prefix, can be anything
});
 ```
- Add the routing to action
```
        [HttpGet("odata/students")]
        [EnableQuery]
```

We just demo how simple odata is until it does not work with third party component which require edm odata.

**Comment by xuzhg** [comment]
@hassanhabib

**Comment by hassanhabib** [comment]
@andrew-vdb the 3rd party component is going to have to adapt to the non-EDM approach. But even with the Edm approach OData is still simple to setup with just an extra method for mapping and building the convention model.

If I may ask, what 3rd party are you trying to integrate with?

**Comment by andrew-vdb** [comment]
@hassanhabib Devextreme datagrid

https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ODataStore/

**Comment by hassanhabib** [comment]
@andrew-vdb I see. Yeah if the client isn't compatible with the non-EDM version approach you gonna have to go EDM. Like I said earlier the setup is just few extra lines of code.

**Comment by andrew-vdb** [comment]
Ok, thanks

**Comment by andrew-vdb** [comment]
@hassanhabib how to make it async?

This is working but SYNC, this will return edm model
```
[HttpGet("odata/students")]
        [EnableQuery]
        public IQueryable<Model.Student> OData()
        {               
            return _context.Students;
        } 
```

This is working, ASYNC but its **not** returning **edm** odata
```
[HttpGet("odata/students")]
        [EnableQuery]
        public IAsyncEnumerable<Model.Student> OData()
        {
            return _context.Set<Model.Student>().AsAsyncEnumerable();
        }
```

That's the only thing i change

**Comment by andrew-vdb** [comment]
to be clear
Odata need to return EDM model with async way

**Comment by andrew-vdb** [comment]
creating new issue here
https://github.com/OData/AspNetCoreOData/issues/390
