### ISSUE TITLE
"@odata.context" is inconsistently returned

### ISSUE THREAD

**Issue by Grauenwolf** [OData/AspNetCoreOData#382]
Sometimes my JSON payload includes an `@odata.context` key and a `value` key, sometimes it doesn't.

What controls this? I don't really care if it's there or not, but I need it to be consistent across projects.

**Comment by Grauenwolf** [comment]
Found it.

		services.AddControllers()
				.AddOData(opt => opt
					.AddRouteComponents(ODataPath, edmModel)
					.EnableQueryFeatures()
				)

* If `ODataPath` is "/api/odata" then I will NOT get the `@odata.context` key.
* If `ODataPath` is "api/odata" then I will get the `@odata.context` key.

The only difference is the leading `/`. I'm not sure is a bug or a documentation issue. Nothing in the `AddRouteComponents` XML docs says that a leading `/` isn't allowed.

**Comment by habbes** [comment]
Hi @Grauenwolf, the intended behavior is that `@odata.context` is part of the response. When you don't see the `@odata.context` key, it usually means the request was not handled by the OData library.

In this case, it appears that when you register the `ODataPath` with a leading `/` then the requests are not routed to OData, but handled by the built-in serializer. We will investigate this, but in the meanwhile consider registering the odata path without the leading `/`.
