### ISSUE TITLE
Async odata endpoint not returning edm model

### ISSUE THREAD

**Issue by andrew-vdb** [OData/AspNetCoreOData#390]
Actual:
The setup use EDM model, 
when we use IQueryable, the db call will be done synchronously and return EDM model
when we use IAsyncEnumerable, the db call will be done async and return simple model..
Expected:
when we use IAsyncEnumerable, the db call will be done async and should return EDM model..

```
//This return EDM model
[HttpGet("odata/students")]
        [EnableQuery]
        public IQueryable<Model.Student> OData()
        {
            return _context.Students;
        }

//This NOT return EDM model
        [HttpGet("odata/students")]
        [EnableQuery]
        public IAsyncEnumerable<Model.Student> OData()
        {
            return _context.Students.AsAsyncEnumerable();
        }
```

**Comment by andrew-vdb** [comment]
This is not supported
```
[HttpGet("odata/students")]
        [EnableQuery]
        public IAsyncQueryable<Model.Student> OData()
        {
            return _context.Students.AsAsyncEnumerable().AsAsyncQueryable();
        }
```

**Comment by xuzhg** [comment]
Could be similar to https://github.com/OData/WebApi/issues/2598

**Comment by andrew-vdb** [comment]
Just tested with EnableQueryAsync in another issue...

https://localhost:7040/odata/students?$count=true&$top=2

The select top will run async
The select **count** will run **sync**
and it will return edm data as expected

**Comment by jr01** [comment]
See my other issue for count async support: https://github.com/OData/WebApi/issues/2269

**Comment by jr01** [comment]
See this issue for count async in [EnableQueryAsync] https://github.com/OData/WebApi/issues/2325
