### ISSUE TITLE
How to make a Property, a ComplexProperty or a CollectionProperty IsOptional()?

### ISSUE THREAD

**Issue by henrikdahl8240** [OData/AspNetCoreOData#398]
Hello!

Using the older version of the Microsoft.AspNetCore.OData component, it was possible to make a Property, a ComplexProperty or a CollectionProperty IsOptional()

How to achieve that using version 8.0.4?

**Comment by xuzhg** [comment]
@henrikdahl8240 It should be changed as "IsNullable()".
