### ISSUE TITLE
ODataDynamicModel: Query a single value does not work

### ISSUE THREAD

**Issue by manureini** [OData/AspNetCoreOData#402]
I'm starting the Sample: ODataDynamicModel.

Calling
`GET http://localhost:5000/odata/mydatasource/Products(1)`
results in 404.

`GET http://localhost:5000/odata/mydatasource/Products/1`
returns expected result of the GET above

Also
`http://localhost:5000/odata/mydatasource/Products(1)/Name`
returns 404

Version 8.0.4 and latest master

**Comment by xuzhg** [comment]
@manureini 

The sample project only builds the key as a segment template. See 

![image](https://user-images.githubusercontent.com/9426627/145863787-9403dad5-6278-43d3-ba14-0e6e3bb6d083.png)

The codes are https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataDynamicModel/Extensions/EntitySetWithKeyTemplateSegment.cs#L24.

If you want to support the key in parentheses, you can add a new segment template.

```C#
        public override IEnumerable<string> GetTemplates(ODataRouteOptions options)
        {
            yield return "/{key}";
            yield return "({key})";  // add this template
        }
```
Then it supports the key in parenthesis.

**Comment by manureini** [comment]
got it ;)
Thank you very much!
