### ISSUE TITLE
Routing issues with nested objects with composite keys

### ISSUE THREAD

**Issue by jazzmanro** [OData/AspNetCoreOData#406]
Maybe I don't know how to configure and use things but starting with the Customer/Orders example, for some reasons I want the Orders stored in a dedicated CosmosDB collection to use composite key of CustomerId + OrderDate (a string like 01-02-2021.X).

I did setup this and mostly works, but having actions like a GET /v1/customers/{customerId}/orders/{orderDate} throws warnings at startup that the URL "is not a valid OData path template. The number of keys specified in the URI does not match number of key properties for the resource".

How come? It's a clean RESTful URL specifying both parts of the composite key but not in the same path segment as I saw on some examples around.

How to configure this properly? Or do I need to actually implement a custom routing convention? If yes, is there a good such example anywhere? I can't seem to find any.

Thanks.

**Comment by xuzhg** [comment]
@jazzmanro  can you share your metadata and controller/action routing template?

**Comment by jazzmanro** [comment]
@xuzhg I put together a fast sample ilustrating the issue. It isn't fully wired to the DB though, I don't think it is relevant, the issues can be easily reproduced: https://github.com/jazzmanro/ODataIssue406

Please check the comments in the Customer and Order models and CustomerOrdersController. Bottom line, I want to use a very friendly route to access my data like /v1/customers/john@doe.com/orders/2021-12-17 but can't figure out how to configure that properly for OData to recognize it. OData complains at startup:
`The path template 'v1/customers/{customerId}/orders/{dateId}' on the action 'GetOrderForCustomer' in controller 'CustomerOrders' is not a valid OData path template. The number of keys specified in the URI does not match number of key properties for the resource 'API.Order'`.
Investigations reveal that the path parser inside OData throws exception.
Side effect is that if you use Delta<T> to patch on such routes, that object is not populated with the actual data although no error is raised at that time. This is how I actually saw this issue and unfortunately spent a couple of hours debugging to figure out the console warning is at fault and (unintuitively for a OData rookie) Delta<T> doesn't work outside OData context (routes).

What is the right way to make OData recognize this route and register the ODataInputFormatter so that Delta<T> works?

**Comment by jazzmanro** [comment]
@xuzhg Forgot to post the $metadata:

```
<?xml version="1.0" encoding="utf-8"?>
  <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
      <Schema Namespace="API" xmlns="http://docs.oasis-open.org/odata/ns/edm">
        <EntityType Name="Customer">
          <Key>
            <PropertyRef Name="customerId" />
          </Key>
          <Property Name="customerId" Type="Edm.String" Nullable="false" />
          <Property Name="name" Type="Edm.String" Nullable="false" />
          <NavigationProperty Name="orders" Type="Collection(API.Order)" ContainsTarget="true" />
        </EntityType>
        <EntityType Name="Order">
          <Key>
            <PropertyRef Name="customerId" />
            <PropertyRef Name="dateId" />
          </Key>
          <Property Name="customerId" Type="Edm.String" Nullable="false" />
          <Property Name="dateId" Type="Edm.String" Nullable="false" />
          <Property Name="time" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="value" Type="Edm.Double" Nullable="false" />
          <NavigationProperty Name="customer" Type="API.Customer" Nullable="false">
            <ReferentialConstraint Property="customerId" ReferencedProperty="customerId" />
          </NavigationProperty>
        </EntityType>
        <EntityContainer Name="API">
          <EntitySet Name="customers" EntityType="API.Customer" />
          <EntitySet Name="orders" EntityType="API.Order">
            <NavigationPropertyBinding Path="customer" Target="customers" />
          </EntitySet>
        </EntityContainer>
      </Schema>
    </edmx:DataServices>
  </edmx:Edmx>
```

**Comment by xuzhg** [comment]
@jazzmanro based on your csdl, the "Order" type has the composite key, your template is not valid and the error is as expected.

It could be:
 /v1/customers/{customerId}/orders/{customerId=customerId,dateId=orderDate}

Besides, for composite key, it's not good to use key as segment, so, it's better to use key in parenthesis.
/v1/customers({customerId})/orders({customerId=customerId,dateId=orderDate})

**Comment by jazzmanro** [comment]
@xuzhg Thanks for your input. I'll try to see if I can make it work.

However, I also want friendly and readable URLs. They are helpful both for debugging and tracing but I also want to give the API to other people, most of them know about REST, maybe OpenAPI, but have no clue about OData so I am setting up both OpenAPI/Swagger stack and drive ReDoc for documentation that I want to provide but also want to run OData for me or clients that know about this or could actually learn from me, I'll try to promote it where possible.

For people without OData background looking at it just via ReDoc/OpenAPI, it is really weird to redundantly specify customerId in the URL, the `{customerId=customerId,dateId=orderDate}` syntax makes little sense. The parenthesis variant is less readable on top of that.

How can I customise the template that I use and make OData accept my `/v1/customers/{customerId}/orders/{dateId}` format? All the parts of the composite key are there but in different segments.
Do you have an example of that?

In the end it's a pity that the setup almost works except that `Delta<Order>` is not populated for example. All because the template is not recognised properly.

**Comment by xuzhg** [comment]
@jazzmanro remove the "customerId" key from "Order". Since you can get the customerId from the previous segment.

Then you can get it working.

**Comment by jazzmanro** [comment]
@xuzhg Thanks, that seem to have solved the issue. So OData was looking at the [Key] attribute on the model. Isn't there a way to control this without actually removing the attribute? In my case I removed the attribute and configured the composite Key correctly at EFCore level to avoid impacting that. Hopefully there aren't any other side effects.
