### ISSUE TITLE
Odata 8.0.4 with .net6: not matching DeleteRef route

### ISSUE THREAD

**Issue by GabrieleVolpato** [OData/AspNetCoreOData#408]
Hello everyone!

I'm using OData 8.0.4 with asp net core 6.0, and I can't find the correct way to implement ODataController's DeleteRef method. I can't understand if I'm failing something or it's a library problem.

This is the signature of my method:
`public async Task<ActionResult> DeleteRef([FromODataUri] int key, string navigationProperty, [FromODataUri] string relatedKey)`

If I remove the relatedKey parameter, it then matches, but I cannot access the id of the related entity.
For now, I'm extracting data by getting the id manually from Request's Query, but then another problem occurs. I use the following method to extract the id from the odata string `https://localhost:44336/api/Components(3994)`.

```
public static TKey GetKeyFromUri<TKey>(HttpRequest request, Uri uri)
{
    if (uri == null)
    {
        throw new ArgumentNullException("uri");
    }

    var odataFeature = request.ODataFeature();
    var uriParser = new ODataUriParser(odataFeature.Model, new Uri(odataFeature.BaseAddress), uri);
    var keySegment = uriParser.ParsePath().OfType<KeySegment>().FirstOrDefault();
    if (keySegment?.Keys == null || !keySegment.Keys.Any())
    {
        throw new InvalidOperationException("The link does not contain a key.");
    }

    return (TKey)keySegment.Keys.FirstOrDefault().Value;
}
```

But only in this case, oDataFeature.BaseAddress returns null. Other data, like Model, are correctly evaluated.

This is the complete route I'm trying to match: `https://localhost:44336/api/Tools(8)/Components/$ref?$id=https://localhost:44336/api/Components(3994)`

Thanks to anyone who will help me!

**Comment by kfrentzel** [comment]
I'm facing the same problem. Is there a solution in the meantime?

**Comment by julealgon** [comment]
The [convention documentation](https://teams.microsoft.com/l/message/19:f806f65ca48746c09112a1fc46be3385@thread.tacv2/1659619186017?tenantId=c48631c6-3ffd-49a5-b8b1-20cd682c4f5a&groupId=32821375-4efd-446a-856f-e3299e658262&parentMessageId=1659619186017&teamName=Datadog%20Users&channelName=General&createdTime=1659619186017) has the arguments in a different order than what you are using.

![image](https://user-images.githubusercontent.com/461579/182869074-f410daf9-b385-4bfe-83f6-74ea8f6c3745.png)

_(I don't know why the action is called `DeleteLink` there and not `DeleteRef` though...)_

Does it make any difference for you if you swap the last two arguments and use:
```csharp
public async Task<ActionResult> DeleteRef(
    [FromODataUri] int key, 
    [FromODataUri] string relatedKey, 
    string navigationProperty)
```
?

**Comment by kfrentzel** [comment]
I've tried that too. The result is the same: **404 Not found**. The route cannot be resolved. It looks like there are problems with the RefRoutingConvention.

**Comment by gathogojr** [comment]
@kfrentzel @GabrieleVolpato

For a single-valued navigation property, you should implement controller actions matching either of the following:

```csharp
// Let's say the single-valued navigation property is named "Customer"

// DELETE http://localhost:19644/odata/Orders(1)/Customer/$ref
public ActionResult DeleteRefToCustomer([FromRoute] int key)
{
    // ...
}

// Or

// DELETE http://localhost:19644/odata/Orders(1)/Customer/$ref
public ActionResult DeleteRef([FromRoute] int key, [FromRoute] string navigationProperty)
{
    // ...
}
```

For a collection-valued navigation property, you should implement controller actions matching either of the following:

```csharp
// Let's say the collection-valued navigation property is named "Orders"

// DELETE http://localhost:5000/odata/Customers(1)/Orders(2)/$ref
public ActionResult DeleteRefToOrders([FromRoute] int key, [FromRoute] int relatedKey)
{
    // ...
}

// Or
// DELETE http://localhost:5000/odata/Customers(1)/Orders(2)/$ref
public ActionResult DeleteRef([FromRoute] int key, [FromRoute] int relatedKey, [FromRoute] string navigationProperty)
{
    // ...
}
```

Kindly let me know if this helps...

**Comment by gathogojr** [comment]
@GabrieleVolpato I'll go ahead and close this. If the solution I proposed doesn't work, feel free to reopen it
