### ISSUE TITLE
Swagger is not working with 8.0.0 pre-release 

### ISSUE THREAD

**Issue by ut786** [OData/AspNetCoreOData#41]
In my project, swagger is throwing this error.
![image](https://user-images.githubusercontent.com/38358557/101158789-2883b000-364e-11eb-8acd-7e36c27bce49.png)

I have applied the solutions but they only work with the previous versions not with the 8.0.0 pre-release which I am using in my .net 5.0 Web API project.

**Comment by cognvn** [comment]
Try
```csharp
services.AddSwaggerGen(options =>
{
    // ........................
    options.DocInclusionPredicate((name, api) => api.HttpMethod != null);
});
```
Resolve problem
```
SwaggerGeneratorException: Ambiguous HTTP method for action - Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetMetadata (Microsoft.AspNetCore.OData). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
```

**Comment by ut786** [comment]
This has fixed my problem. Thanks a lot!

**Comment by RacketRebel** [comment]
With Odata 8.0.0 preview 3 i just only get the routes with [HttpGet("{id}")] or [HttpGet("")] or [HttpPut("")], even with the above added and suggested solutions.
