### ISSUE TITLE
New release Microsoft.AspNetCore.OData.NewtonsoftJson

### ISSUE THREAD

**Issue by markbeij** [OData/AspNetCoreOData#411]
Can you publish a new nuget package of Microsoft.AspNetCore.OData.NewtonsoftJson?
In master an issue is fixed (https://github.com/OData/AspNetCoreOData/commit/4ab80c7caa657dcadef2815cbdf423402829a67b) which I need.

**Comment by corranrogue9** [comment]
@marabooy , can you please check about the build process? 

@markbeij , you might be able to update the dependency manually in your project and self-service as a one-off.

**Comment by marabooy** [comment]
@markbeij https://www.nuget.org/packages/Microsoft.AspNetCore.OData.NewtonsoftJson/8.0.4 is now available do let me know if this sorts out the issue you experienced.

**Comment by markbeij** [comment]
Yes it did, thanks 🙏
