### ISSUE TITLE
Support for DateOnly and TimeOnly types

### ISSUE THREAD

**Issue by stefanjaspers** [OData/AspNetCoreOData#413]
Hi,

I'm using OData for my Web API and I have entities with a DateOnly and/or TimeOnly property. Sadly, OData doesn't seem to support these types yet. It just returns an empty JSON object for that property, like so:

`"FirstAdmissionDate": {}`

Is there a workaround to enable OData to handle DateOnly and TimeOnly?

**Comment by xuzhg** [comment]
@julealgon @stefanjaspers Would you please help review #450?

**Comment by julealgon** [comment]
@xuzhg I assume this is also a milestone 8.0.7 item?
