### ISSUE TITLE
How to hide OData Metadata Controller for swagger? .NET 6

### ISSUE THREAD

**Issue by Marusyk** [OData/AspNetCoreOData#416]
After updating my project to .NET 6 and OData to 8.0.4, a new Metadata controller with these endpoints appeared:

[![enter image description here][1]][1]

I want to disable it somehow or remove it from my service.

Code for adding OData service:

Startup.cs

    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddControllers(mvcOptions => mvcOptions.EnableEndpointRouting = false)
            .AddOData(opt => opt.AddRouteComponents("", GetEdmModel()).Select().Expand());
    }

Versions:

* .NET 6
* ASP.NET Core 6
* OData 8.0.4

  [1]: https://i.stack.imgur.com/rEO1Z.png

**Comment by xuzhg** [comment]
@Marusyk 
1) You can use Controller feature provider to exclude MetadataController
2) You can use Conventions in ODataOptions to remove MetadataRoutingConvention.

**Comment by Marusyk** [comment]
Hi @xuzhg 
Could you please provide more information how to do that?

**Comment by xuzhg** [comment]
@Marusyk yes, that's for Option 2.

for Option 1:
you can do like:

```C#
public class RemoveMetadataControllerFeatureProvider : ControllerFeatureProvider
    {
        protected override bool IsController(TypeInfo typeInfo)
        {
            if (typeInfo.FullName == "Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController")
            {
                // or just compare the name
                return false;
            }

            return base.IsController(typeInfo);
        }
    }
```

In the startup.cs

```C#
services.AddControllers()
    .ConfigureApplicationPartManager(manager =>
     {
          manager.FeatureProviders.Remove(manager.FeatureProviders.OfType<ControllerFeatureProvider>().FirstOrDefault());
          manager.FeatureProviders.Add(new RemoveMetadataControllerFeatureProvider());
     }).AddOData(....)
```

**Comment by Marusyk** [comment]
Thank you very much
