### ISSUE TITLE
OData Attribute Route not working as expected in ASP.NET Core 5 with Microsoft.AspNetCore.OData v8.0.0-preview2

### ISSUE THREAD

**Issue by dcadlereii** [OData/AspNetCoreOData#42]
I am working on an ASP.NET Core 5 API with Entity Framework Core 5 and I am using Microsoft.AspNetCore.Odata v8.0.0-preview2 and using endpoint routing.
I have reviewed Sam Xu's blogs; [Routing in ASP.NET Core OData 8.0 Preview][1] and [ASP.NET Core OData 8.0 Preview for .NET 5][2]

I am integrating with an existing SQL Server database of which I do not control the schema so I have to work with what is provided.

I am constantly fighting with 404 Not Found for API calls in Postman that seem like they should work, but are not getting resolved. I do not know of a way to actually troubleshoot this problem short of trial and error. There must be an easier way to troubleshoot this but I am just not seeing it.

**How can I view the route table so I can see the routes derived by OData from my EDM and possibly find my problem?**

I had worked with Microsoft OData v7.5.2 on another project with ASP.NET Core 3.1 and with endpoint routing disabled and didn't seem to have this try of problem, but I was also working with my own database schema that I built with EntityFramework Core Migrations and Database Updates so the schema was probably more aligned that the one I am dealing with for my current project.

For example, the existing SQL database I am working with now is provided by a 3rd party vendor and their tables to not have a Primary key identified so I had to spoof it by adding a [Key] attribute to the ID property in the DBContext modelbuilder.

I don't know if that is what is actually causing my difficulty in getting the expected routes to work. 

I am using attribute routes, which I understand have priority over convention routes, so I would expect that if I matched up my URL in the request with the attribute routes specified in my controller, it would work.

For example, I have an OrganizationsController, as follows;

    [Authorize]
    [ODataRoutePrefix("organizations")]
    public class OrganizationsController : ODataController
    {
        private readonly MyContext context;

        public OrganizationsController(MyContext context)
        {
            this.context = context ?? throw new ArgumentNullException(nameof(context));
        }

        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Supported, PageSize = 2000)]
        public IQueryable<Organization> GetOrganizations()
        {
            return context.Organizations;
        }

        [ODataRoute("{id}")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Supported)]
        public SingleResult<Organization> GetOrganizationById([FromODataUri] string id)
        {
            return new SingleResult<Organization>(context.Organizations.Where(o => o.OrganizationId == id));
        }

        [ODataRoute("Locations(organizationId={organizationId}")]
        public IQueryable<OrganizationLocation> GetOrganizationLocations([FromODataUri] string organizationId)
        {
            return context.OrganizationLocations.Where(ol => ol.OrganizationId == organizationId);
        }
    }

With this controller, I can get the following basic requests to find their routes successfully;

https://localhost:43300//odata-v1/organizations?$count=true&$orderby=Name
https://localhost:43300//odata-v1/organizations/'10000'

But I also have a need to retrieve all of the OrganizationLocation records that are owned by a specific Organization record. What I initially wanted to do was to use a typical REST type of URL, like

https://localhost:43300/odata-v1/organizationLocations/1000/locations

...to return all of the locations linked to the specified organizationId.  

And I expected to be able to add attribute routes to my OrganizationLocations controller as shown below;

    [Authorize]
    [ODataRoutePrefix("organizations({id})")]
    public class OrganizationLocationsController : ODataController
    {
        private readonly MyContext context;

        public OrganizationLocationsController(MyContext context)
        {
            this.context = context ?? throw new ArgumentNullException(nameof(context));
        }

        [ODataRoute("locations")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Supported)]
        public IQueryable<OrganizationLocation> GetOrganizationLocations([FromODataUri] string id)
        {
            return context.OrganizationLocations.Where(ol => ol.OrganizationId == id);
        }
    }

But the call to this controller always returns a 404 Not Found.

  [1]: https://devblogs.microsoft.com/odata/routing-in-asp-net-core-8-0-preview/
  [2]: https://devblogs.microsoft.com/odata/asp-net-odata-8-0-preview-for-net-5/

**Comment by navidzehi** [comment]
The same problem exists with Microsoft.AspNetCore.OData v8.0.0-**preview3**

**Comment by xuzhg** [comment]
It should be fixed. If you have further concerns, please file a new issue for us. thanks.
