### ISSUE TITLE
Cannot dynamically add routes in v8

### ISSUE THREAD

**Issue by gordon-matt** [OData/AspNetCoreOData#435]
Changing where the OData EDM model is confgured

FROM: `app.UseEndpoints(endpoints =>` under `Configure()`

TO: `.AddOData(options =>` under `ConfigureServices()`

is somewhat problematic when trying to support multiple routes. In my case, I have a framework with multiple plugins/class libraries.. some provide their own OData routes. I have been using this interface for some time:

```
public interface IODataRegistrar
{
	void Register(IRouteBuilder routes, IServiceProvider services);

	void Register(IEndpointRouteBuilder endpoints, IServiceProvider services);
}
```

An example implementation would be as follows:

```
public class ODataRegistrar : IODataRegistrar
{
	public void Register(IRouteBuilder routes, IServiceProvider services)
	{
		var builder = GetBuilder(services);
		routes.MapODataServiceRoute("OData", "odata", builder.GetEdmModel());
	}

	public void Register(IEndpointRouteBuilder endpoints, IServiceProvider services)
	{
		var builder = GetBuilder(services);
		endpoints.MapODataRoute("OData", "odata", builder.GetEdmModel());
	}

	private ODataModelBuilder GetBuilder(IServiceProvider services)
	{
		ODataModelBuilder builder = new ODataConventionModelBuilder(services);
		builder.EntitySet<Person>("PersonApi");
		return builder;
	}
}
```

I would of course use dependency injection to register all of the `OData Registrars` and then in my Startup, I had this:

```
app.UseEndpoints(endpoints =>
{
	endpoints.Select().Expand().Filter().OrderBy().MaxTop(null).Count();

	var registrars = serviceProvider.GetRequiredService<IEnumerable<IODataRegistrar>>();
	foreach (var registrar in registrars)
	{
		registrar.Register(endpoints, app.ApplicationServices);
	}

	endpoints.MapControllerRoute(
		name: "default",
		pattern: "{controller=Home}/{action=Index}/{id?}");

	endpoints.MapRazorPages();
});
```

As you can see, I just resolve all of the registrars and then use them to register all OData routes. Simple.

Now in v8, it's a different story. Firstly, here is the new `IODataRegistrar`:

```
public interface IODataRegistrar
{
	void Register(ODataOptions options);
}
```

Example implementation:

```
public class ODataRegistrar : IODataRegistrar
{
	public void Register(ODataOptions options)
	{
		ODataModelBuilder builder = new ODataConventionModelBuilder();
		builder.EntitySet<Person>("PersonApi");
		options.AddRouteComponents("odata", builder.GetEdmModel());
	}
}
```

and what I am doing in Startup:

```
services.AddSingleton<IODataRegistrar, ODataRegistrar>(); // What about others???

services.AddControllersWithViews()
    //.AddNewtonsoftJson(options => options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore)
    .AddNewtonsoftJson()
    .AddOData(options =>
    {
        options.Select().Expand().Filter().OrderBy().SetMaxTop(null).Count();

        var registrars = services.BuildServiceProvider().GetRequiredService<IEnumerable<IODataRegistrar>>();
        foreach (var registrar in registrars)
        {
            registrar.Register(options);
        }
    });
```

As you can see, I have 2 problems here:

1. Having to use `services.BuildServiceProvider()` is not good and I believe it means an additional copy of singleton services being created.

2. Most of my dependencies (most improtantly the `OData Registrars`) will be registered with the DI container AFTER this section.. so they won't be able to be resolved here anyway.. unless I do a `services.AddSingleton<IODataRegistrar, ODataRegistrar>();` like in the above example.. but then that prevents dynamically adding unknown registrars later.. I would have to know about them beforehand..

Suggestions?

**Comment by xuzhg** [comment]
@gordon-matt why don't you use this overload? https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/ODataMvcBuilderExtensions.cs#L61

It provides the SP for use.

**Comment by gordon-matt** [comment]
Excellent! I was unaware of that overload. That works great, thanks.
