### ISSUE TITLE
Route debugger showing N/A items?

### ISSUE THREAD

**Issue by TehWardy** [OData/AspNetCoreOData#437]
Hey guys, 

Upgrades the codebase to .Net 6 (rebuilt all the projects from scratch pulling in the code gradually).
I've turned on the odata route debugger using the `app.UseODataRouteDebug()` extension and it's showing me this ...

![image](https://user-images.githubusercontent.com/6891030/148994190-e20552c9-1eae-4597-bf72-7f4f65b398b9.png)

Those N/A items are all th way down th list and seem to be duplicates of the item that follows them except for the template field.
Is there something I did wrong here when I initialised my meta?

Here's how I build out the API layer in my application ...

```cs
// main program.cs file ...
builder.Services.AddStackApiLayer(config, new ODataModelBuilder[] { new MembersModelBuilder(), new CoreModelBuilder(), new B2BModelBuilder() });

// in an IServicCollectionExtensions file I have this ...
public static void AddStackApiLayer(this IServiceCollection services, Config config, ODataModelBuilder[] modelBuilders)
{
    services.AddResponseCompression();
    services.AddMvcCore(options =>
    {
        options.MaxIAsyncEnumerableBufferLimit = int.MaxValue;
        options.MaxModelBindingCollectionSize = 1000000;
        options.MaxModelBindingRecursionDepth = 10;

        options.OutputFormatters.Add(new XmlFormatter());
        options.OutputFormatters.Add(new CsvFormatter());
        options.OutputFormatters.Add(new ExcelFormatter());
    })
        .AddDataAnnotations()
        .AddCors(options => options.AddDefaultPolicy(builder =>
        {
            builder.AllowAnyHeader();
            builder.AllowAnyMethod();
            builder.SetIsOriginAllowed(origin => true);
            builder.AllowCredentials();
        }));

    services.AddControllers()
        .AddOData(opt =>
        {
            opt.EnableAttributeRouting = true;
            opt.Expand().Count().Filter().Select().OrderBy().SetMaxTop(1000);
            modelBuilders.ForEach(b => opt.AddRouteComponents($"/Api/{b.GetType().Name.Replace("ModelBuilder", "")}", b.Build().EDMModel));
        });

    services.AddSignalR();
    services.AddSingleton<ICommonObjectCache>(i => new CommonObjectCache(config, i));

    services.AddEndpointsApiExplorer();
    services.AddSwaggerGen(c =>
    {
        //c.AddServer(new OpenApiServer { Url = "Api" });
        c.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
        {
            Description = @"Authorization header using the Bearer scheme. \r\n\r\n 
                Enter 'Bearer' [space] and then your token in the text input below.
                \r\n\r\nExample: 'bearer 12345abcdef'",
            Name = "Authorization",
            In = ParameterLocation.Header,
            Type = SecuritySchemeType.ApiKey,
            Scheme = "bearer"
        });
    });
}
```

Then when service building is complete ...

```cs
var app = builder.Build();
app.UseRouting();
app.UseMetadata();

// and here's my custom "UseeRouting" extension method ...
public static void UseMetadata(this WebApplication app)
{
    app.UseSwaggerUI();
    app.UseSwagger(s => s.SerializeAsV2 = true);
    app.UseODataRouteDebug();
    app.UseDeveloperExceptionPage();
}
```
... I have been able to confirm that swagger isn't getting in the way or causing any issues, but it does seem that whatever it is that they share (presumably some internal routing table) is causing my swagger UI to contain a load of duplicates too.

This is what appears to be the problem as swagger sees it ...
![image](https://user-images.githubusercontent.com/6891030/148997371-fae367d0-70c0-4bf2-81b1-4fbf0509a8ba.png)

It's like everything has a Default.{something} and one without the "Default." prefix.
Can I turn that off somehow?

**Comment by xuzhg** [comment]
@TehWardy 

1. Default.{something} is a qualified function call. The qualified function starts with namespace, followed by ".", followed by function name.

2. without "Default." prefix is an un-qualified function call. It means to call the function without using namespace.

By default, the conventional routing should generate for both. There's a route option at https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L86

and 
https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L10

that you can full control which one should be generated.

You can use the https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/ODataOptions.cs#L63 to config route option.

the 'N/A' in the route debug could be a bug. Would you please help me to debug the source to understand it or if it's ok, please share your repro for me to dig more. 

Thanks.

**Comment by TehWardy** [comment]
Thanks for the feedback @xuzhg.
I have tried adding that suggested config change like this ...

![image](https://user-images.githubusercontent.com/6891030/149101273-fb650826-b044-415a-986e-00a7d7a34c30.png)

... it made no change to my  $odata output, so i'm not convinced that's working ... unless i'm using it wrong?
I'll get the odata framework libs in my solution and dig more though.

**Comment by xuzhg** [comment]
@TehWardy do you mind to share me your repo and I can dig more?

**Comment by TehWardy** [comment]
I believe I can ... just need an email address for you that's linked to a Microsoft account (it's in azure devops).
If you prefer message me that on Teams `paul.ward @ corporatelinx .com` without the spaces of course.

Thanks :)

**Comment by TehWardy** [comment]
I do ... but this code is in the company azure devops one, it's still git based I just need to grant you access to it as it's not a public solution.
Do you have a better idea?

**Comment by xuzhg** [comment]
Oh, ok.  my email: saxu@microsoft.com

**Comment by TehWardy** [comment]
hmmm it won't let me add users outside the AAD instance.
Ok i've created a private copy on here and invited you to it.

Apologies for the confusion.

**Comment by xuzhg** [comment]
@TehWardy Sorry for the delay. 

I think below is what you are looking for:
![image](https://user-images.githubusercontent.com/9426627/150030347-f6c7b083-dff3-48f6-858d-09af97dd3357.png)

It's output from your project but I don't have the db connection. So, I comment most of the services and middleware out to make the project to run.

I do think it's related to a middleware (Session, maybe), but I can't debug at my side and I don't have all environment setup.
Would you please debug at your side? Our library supports source link and it's easy to debug based on the symbols. Just enable the source link.

let me know if any problem. Or please setup up a meeting and we can debug together remotely. :)

**Comment by TehWardy** [comment]
Oh interesting ... 
I will take a look tomorrow if I can as it almost midnight here and I just finished today.

**Comment by TehWardy** [comment]
Ok found the issue ...
```cs
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapHub<NotificationHub>("/Api/Hubs/Notification");
    endpoints.MapHub<WorkflowHub>("/Api/Hubs/Workflow");
    endpoints.MapHub<LogHub>("/Api/Hubs/Logs");
    //endpoints.MapFallbackToController("Index", "Home");
});
```

The commented out line above needs to be ...
```cs
endpoints.MapDefaultControllerRoute();
```
The idea was to have that any non ~/Api/* route map in to the HomeController for serving up web pages.
I found that adding a [HttpGet("{*path}")] to the controller action solved new routing problem introduced.

Magic!

**Comment by TehWardy** [comment]
Not a complete fix it seems ...
We need the behaviour that the removed call provides other than the metadata issue.

Is ther another way to achieve this to avoid the meta issue?

**Comment by callummarshall9** [comment]
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}/{id?}");
    endpoints.MapControllerRoute(name: "api", pattern: "api/{controller=Default}/{action=Index}/{id?}"); 
    endpoints.MapHub<NotificationHub>("/Api/Hubs/Notification");
    endpoints.MapHub<WorkflowHub>("/Api/Hubs/Workflow");
    endpoints.MapHub<LogHub>("/Api/Hubs/Logs");
});
```

MapControllerRoute seems to of fixed such that the $odata N/A items disappear and routing behaves correctly.

**Comment by TehWardy** [comment]
Ok ... still not solved ... 
    This is frustrating.

The routing behaviour seems to get worse the more situations we try to fix or work around each time we add a new routing fix.

**Comment by TehWardy** [comment]
Hey @xuzhg ,
I think we fixed it late last night and i think the issue is some sort of general aspnet core routing issue rather than something specific to OData lnf story short we had to do this ...

```cs
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(name: "api", pattern: "api/{controller=Root}/{action=Index}");
    endpoints.MapControllerRoute(name: "default", pattern: @"{*path}", defaults: new { controller = "Home", action = "Index" }, constraints: new { path = new NoApiRouteConstraint() });
    ...
});
```

Notice the addition of a "RouteConstraint" here which looks like this ...
```cs
public class NoApiRouteConstraint : IRouteConstraint
{
    public bool Match(HttpContext httpContext, IRouter? route, string routeKey, RouteValueDictionary values, RouteDirection routeDirection)
        => httpContext.Request.Path.HasValue && !(httpContext.Request.Path.Value.ToLower().Contains("/api/"));
}
```
It seems that you can't have a catch all defined globally without the N/A side effect but we wanted all routes except those that have "api" in the first segment to be handled by our CMS controller for handling pages.
This also avoided some other weird affects in other bits of middleware that were mapped to ~/Api/... routes.

I'm not sure why yet but I figured the smart answer would have been a regex expression based route that did  the same.
We also ran in to a ton of issues like static file handling broke with catch all or fallback routing.

This is really just informational, maybe you can pass on a note to another team or something.
Thanks for your help.
