### ISSUE TITLE
AddODataQueryFilter not available in ASP.NET Core OData 8.0 (Preview) 

### ISSUE THREAD

**Issue by DanielHillebrandSWMS** [OData/AspNetCoreOData#44]
Could we get a timeline for incorporation of `AddODataQueryFilter`, please?

I know that it is a preview, but I have migrated a complex customer application to Net 5.0 and the only thing missing to run it is AddODataQueryFilter ...

### Assemblies affected

AspNetCore.OData Odata8.0.0-preview2

**Comment by DanielHillebrandSWMS** [comment]
I have realized that the current 7er version of AspNetCore.OData works quite nicely with a Net5.0 WebApi application. So I can wait paciently for version 8 now. 

Because of the blog entries about OData 8 I have wrongly assumed that version 7 would not play with a Net5 web application

**Comment by xuzhg** [comment]
The APIs are added at https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/ODataServiceCollectionExtensions.cs#L37-L51. Thanks.
