### ISSUE TITLE
[Question] Why hasn't '[EnableNestedPaths]' been added to v8?

### ISSUE THREAD

**Issue by julealgon** [OData/AspNetCoreOData#440]
I just saw [the documentation for `EnableNestedPaths` in MSDN](https://docs.microsoft.com/en-us/odata/webapi/automatic-nested-paths-with-enable-nested-paths) but noticed at the very end of the article a disclaimer regarding v8:

> This feature is not yet available in `Microsoft.AspNetCore.OData` 8.x

Could someone elaborate why this specific piece of functionality is not present in v8? Is there something fundamentally different about v8 that makes this particular feature harder to implement or something along those lines?

**Comment by xuzhg** [comment]
@julealgon in the 7.x, the OData routing is using OData Uri parser to parse the request path first, then use the parsed information to find the controller and action. In 8, it's different. the route templates are built at startup, There's no OData uri parser again.

In my opinion, the implementation in 7 can't simply port to 8 and we need a full re-design.

**Comment by habbes** [comment]
Closing this issue since the question was answered and there's been no follow up. If the feature is request in v8, a new issue should be created.

**Comment by Xriuk** [comment]
I kinda solved this on my own: I copied the `ODataPathQueryBuilder` class and adapted it, by also adding support for `TypeSegment` parsing with `Queryable.OfType<T>`.
And to generate the path I created my own `IODataControllerActionConvention` which applies to a method named Get a single segment template inheriting from EntitySetSegmentTemplate with a wildcard parameter like this:
```
/{entitySet}
/{entitySet}/{*wildcard}
/{entitySet}({key})
/{entitySet}({key})/{*wildcard}
```
When translating the segment template it splits the whole URL by slashes and parentheses and checks which segment may be which, by validating it with the previous too, and if the path is not valid it simply fails and 404 is returned.
And inside my Get method I build the query with `ODataPathQueryBuilder`, apply query options to it (by creating them manually based on the type returned by the final query), and then based on the final type returned by the `ODataPathQueryBuilder` I retrieve the results:
- A collection (ToArray)
- Count (Count)
- Everything else (FirstOrDefault)

**Comment by julealgon** [comment]
@Xriuk any chance you'd be interested in sending your implementation as a PR?

**Comment by Xriuk** [comment]
@julealgon I'm not sure I can because I worked on this for my company, plus it's not very clean and missing some other features the original implementation had. And the way I did it, with a wildcard, seems a bit "hacky" for me, as it is effectively going against how routing works now as @xuzhg said.
