### ISSUE TITLE
Could not load type 'Microsoft.AspNet.OData.MetadataController'

### ISSUE THREAD

**Issue by TehWardy** [OData/AspNetCoreOData#446]
Kicked off a new project to try some Generics based magic out and hit this ...

```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'Microsoft.AspNet.OData.MetadataController' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.AspNet.OData.Routing.Conventions.IODataRoutingConvention' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.AspNet.OData.Routing.Conventions.IODataRoutingConvention' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.AspNet.OData.Routing.Conventions.SelectControllerResult' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.AspNet.OData.Routing.Template.ODataPathTemplate' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'
```

Any idea what would cause this ?
Minimal example can be pulled from here ...
    https://github.com/TehWardy/Dwellant-Rebuild-

**Comment by julealgon** [comment]
What URL are you calling that causes this error?

**Comment by julealgon** [comment]
This error message is very weird:
> 'Microsoft.AspNet.OData.MetadataController' from assembly 'Microsoft.AspNetCore.OData'

The namespace is not matching the dll, as it should for v8. I suspect this is due to breaking changes from 7 to 8 regarding namespace moves.

Can you please try removing the `Microsoft.AspNetCore.OData.Versioning.ApiExplorer` package from the project and giving another try? It doesn't seem like that package is compatible with OData v8.

**Comment by julealgon** [comment]
Interesting... this actually doesn't prevent NuGet from working, but it raises a warning. This is what your project is currently outputing (last warning):

![image](https://user-images.githubusercontent.com/461579/149595424-2e22f899-540f-4da7-aab9-ebdac3674c27.png)

**Comment by TehWardy** [comment]
Weird, I didn't notice that one.
Thanks that fixed it!
