### ISSUE TITLE
$format support to override Accept

### ISSUE THREAD

**Issue by Vaevictus** [OData/AspNetCoreOData#449]

**Comment by Vaevictus** [comment]
Hello,

According to the spec
http://docs.oasis-open.org/odata/odata-atom-format/v4.0/odata-atom-format-v4.0.html

"The OData Atom format MAY be requested using the $format query option in the request URL with the MIME type application/atom+xml, or the case-insensitive abbreviation atom which MUST NOT be followed by format parameters.

Alternatively, this format MAY be requested using the Accept header with the MIME type application/atom+xml.

If specified, $format overrides any value specified in the Accept header."

Is there an intention to implement this part of the spec so that is is available out of the box, or should we plan on just having this added via a custom OutputFormatter?

**Comment by julealgon** [comment]
Found this relevant thread:
https://social.msdn.microsoft.com/Forums/en-US/8feacd21-e871-4e6b-94a5-611301d488f8/odata-v4-always-return-json?forum=aspwebapi

Along with this very old and probably outdated comment:
> In ODATA v4, the ATOM formatter has been disabled by default, since it is not yet a part of the OASIS standard. Some forum posts said this is expected by end of 2015.
>
> Until then, if an Accept header is not specified, it defaults to JSON. Unfortunately this causes issues with opening this ODATA V4 data feed in Excel and Tableau. :-(
>
> Friday, July 31, 2015 9:54 AM

In classic AspNet OData, there was a way to configure this manually it looks like, doing something like this:
```csharp
var odataFormatters = ODataMediaTypeFormatters.Create();
config.Formatters.InsertRange(0, odataFormatters);
```
I can't find any way of doing this in the new AspNetCore version though.

**Comment by xuzhg** [comment]
@Vaevictus @julealgon Yes, ATOM and JSON are two formats in OData's old versions. However, The Atom format has very little adoption, meanwhile, JSON gets more and more popular.  So, ATOM is deprecated and is not included as part of the OData OASIS standard.

You can find the latest OData spec docs at https://www.odata.org/documentation/.

By the way, It's easy to customize the formatter in ASP.NET Core (OData). You can find details at https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-6.0

**Comment by julealgon** [comment]
Interesting, so that comment wasn't outdated after all. Just to clarify, i don't use the atom format myself, was just checking this for OP. I'm totally fine on standardizing on json.

**Comment by mikepizzo** [comment]
Note: if you need to work with older OData V3 applications that require the ATOM format, you can use the [OData Migration Library](https://www.nuget.org/packages/Microsoft.OData.Extensions.Migration/) library to support OData V3 (including ATOM) on top of your OData V4 service.
