### ISSUE TITLE
Fix your samples

### ISSUE THREAD

**Issue by ttustonic** [OData/AspNetCoreOData#459]
Hello
Just downloaded a code for the repository.
ODataCustomizedSample starts in http://localhost:27484/$odata, while it should be http://localhost:27484/odata
http://localhost:27484/convention throws an AmbiguousMatchException
and so does
http://localhost:27484/explicit
Official samples should at least work

**Comment by xuzhg** [comment]
Did a clean at https://github.com/OData/AspNetCoreOData/commit/4f537fa77c2a2de7f60118850c0f017660cff578. Thanks.
