### ISSUE TITLE
Move Nuget package to Microsoft.OData.ModelBuilder 1.0.5

### ISSUE THREAD

**Issue by fabiocbr75** [OData/AspNetCoreOData#46]
Hello,
I have some issues to work with `Microsoft.AspNetCore.OData 8.0.0-preview2` and `EFcore 5.0`.
The problem is related to `System.ComponentModel.Annotations`.
The dependencies are incompatible.
`Microsoft.AspNetCore.OData 8.0.0-preview2` has dependency with` Microsoft.OData.ModelBuilder 1.0.4` that 
want to use `System.ComponentModel.Annotations` >4.6.0 and < 5.0.0
instead` EFcore 5.0` want to use `System.ComponentModel.Annotations` >= 5.0.
Please change the nuget package of `Microsoft.AspNetCore.OData 8.0.0` to have as minimum `Microsoft.OData.ModelBuilder 1.0.5` that have the right dependency to `System.ComponentModel.Annotations` with version >4.6.0.

In my opinion you can change the nuspec file in the following way:
`<dependency id="Microsoft.OData.ModelBuilder" version="[1.0.5, 2.0.0)" />`

Thanks
Fabio

**Comment by xuzhg** [comment]
@fabiocbr75 Can you try preview-3? it should be fixed. Thanks.
