### ISSUE TITLE
Query Validation Filter Throws General Exception 

### ISSUE THREAD

**Issue by karayanni** [OData/AspNetCoreOData#463]
in the Query Validation filter, if one of the query params is invlaid/not supported a ArgumentOutOfRangeException is thrown.

this is causing us issues in handling such case, since we wan't to asume in our error handling filter that a ArgumentOutOfRangeException is only thrown from Odata (not a valid assumption)

https://github.com/OData/AspNetCoreOData/blob/69eec03c7003fe12d92cdc619efdc16781683694/src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs#L703

I suggest solving this issue by throwing a dedicated exception instead. (which inherits OdataException)

**Comment by julealgon** [comment]
I'd also like to point out that an internally thrown `Argument<>Exception` is usually to be considered as a bug. High level libraries and frameworks are never supposed to expose such low level exceptions to the outside. They are, after all, design-time exceptions that should actually never be thrown, but prevented on caller code.

That is to say, I'd actually consider this a bug.

**Comment by xuzhg** [comment]
@karayanni Changed at https://github.com/OData/AspNetCoreOData/commit/1360a59ccf34e426d8e96543bb03b2fae39c8f44.

Will ship in 8.0.7. Thanks.
