### ISSUE TITLE
OData get action with key missing oData metadata and case sensitive issue

### ISSUE THREAD

**Issue by gundogduhasan** [OData/AspNetCoreOData#468]
Hi,
I am using odata 7.x.x with attiribute routing. I am trying to migrate latest version of odata. For that i made a small project to test my old project design.

Here is my startup class
```
public static class Startup
    {
        public static WebApplication InitializeApp(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            ConfigureServices(builder);
            
            var app = builder.Build();
            Configure(app);
            return app;
        }

        private static void ConfigureServices(WebApplicationBuilder builder)
        {
            builder.Services.AddRouting();

            builder.Services.AddControllers().AddOData(options =>
            {
                options.AddRouteComponents("testodata", GetEdmModel()).Count().Filter().Expand()
            .Select().OrderBy()
            .SetMaxTop(null);
            });

        }

        private static void Configure(WebApplication app)
        {
            app.UseAuthorization();
            app.UseRouting();
            app.MapControllers();
            app.Run();
        }
        private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            builder.EnableLowerCamelCase();

            builder.EntitySet<Department>("Department");
            builder.EntitySet<Person>("Person");

            return builder.GetEdmModel();
        }
    }
```
and here is my base controller
 ```
public class BaseController<T> : ODataController where T : BaseModel
    {
        public PersonDBContext personDBContext = new PersonDBContext();

        [HttpGet]
        [EnableQuery]
        public IActionResult Get()
        {
            var result = personDBContext.Set<T>().ToList();

            return Ok(result);
        }

    // [HttpGet("testodata/department({id})")]
        [HttpGet("testodata/[controller]({id})")]
        [EnableQuery]
        public IActionResult Get([FromODataUri] int id)
        {
            var result = personDBContext.Set<T>().Where(x => x.Id == id).First();

            return Ok(result);
        }
    }
```
and finally here is my department controller drive from my base controller
 ```
public class DepartmentController : BaseController<Department>
    {
    }
```

the problem is,
 if i use get with key action, with this route "[HttpGet("testodata/[controller]({id})")]" 
and test it with like this
"http://localhost:5054/testodata/Department(1)?$select=id"
the result is 
```
{
    "Id": 1
}
```
if i use the same action with this route "[HttpGet("testodata/department({id})")]", and test it same way
"http://localhost:5054/testodata/Department(1)?$select=id"
the result is
```
{
    "@odata.context": "http://localhost:5054/testodata/$metadata#Department(id)/$entity",
    "id": 1
}
```
resul as expected. But, using a child controller name in a base controller  not a right solution. I really trying to understand. Why is that happen? Sorry for the long explanation.

**Comment by julealgon** [comment]
> But, using a child controller name in a base controller not a right solution. I really trying to understand. Why is that happen? Sorry for the long explanation.

@gundogduhasan please refer to the following issue which should describe your problem. The `[controller]` replacement is currently not supported in OData v8 attribute routing:
- https://github.com/OData/AspNetCoreOData/issues/430

I'd suggest closing this and keeping track of the issue there.
