### ISSUE TITLE
$apply when combined with $top or $orderby not functioning

### ISSUE THREAD

**Issue by TimFeldmann-Patriot** [OData/AspNetCoreOData#478]
**OData Version:**
Microsoft.AspNetCore.OData - 8.0.7

.NET 6.0

Combining a $apply with a $top or $orderby parameter causes the following exception to be thrown:
`The query specified in the URI is not valid. The given model does not contain the type 'Microsoft.AspNetCore.OData.Query.Wrapper.AggregationWrapper'`

**Example Query:**
`$top=5&$apply=groupby((SomeProperty),aggregate($count as childCount))`

The query does not need to be as complex as this, a simple groupby which also contains a $top or $orderby will cause the above exception to be thrown.

This is a complete show-stopper for the OData implementation my team is planning on doing as we can't perform basic column filtering by getting their aggregates first. This was not an issue at my previous job when we were still on a .NET Core 3.2 version of OData.

**Comment by julealgon** [comment]
Can you check if your problem is similar to this?
- https://github.com/OData/AspNetCoreOData/issues/420

**Comment by TimFeldmann-Patriot** [comment]
It is the same issue, however I noticed that the #420 was marked as an enhancement. I don't know if Microsoft considers bugs enhancements but I figured I'd create a new issue to be clear that it's a bug and not a feature request.

If Microsoft considers enhancements the same as bugs, then this issue can be disregarded in favor of #420.

**Comment by TimFeldmann-Patriot** [comment]
???

**Comment by eyeseesharp1** [comment]
Apparently Microsoft considers bugs the same as feature requests.

**Comment by ElizabethOkerio** [comment]
The issues is related to https://github.com/OData/AspNetCoreOData/issues/420 and is being tracked from there.

**Comment by borisgr04** [comment]
$apply issue with order by fixed. But the **$apply and group by and top** problem continues.
