### ISSUE TITLE
Enable Camel Case in $select queries

### ISSUE THREAD

**Issue by martinmogusu** [OData/AspNetCoreOData#479]
## Enable Camel Case in $select queries

Currently, `$select` queries in ASP.NET Core Odata use pascal case by default. This is different from normal ASP.NET Core Web API's, which use camel case by default when serializing responses.

## To Reproduce:

- Create new project - ASP.Net Core Web API
- Use Default Settings
- Add package `Microsoft.AspNetCore.OData`
- Add Odata in `Program.cs` (Non-EDM configuration)
```C#
builder.Services.AddControllers().AddOData(options => options.Select().Filter().OrderBy());
```
- Enable query in `WeatherForecastController.cs`
```C#
[EnableQuery]
public IEnumerable<WeatherForecast> Get()
```

### Request without $select
Endpoint:  `https://localhost:7158/WeatherForecast`
Response (Property names are in camel case):
```json
[
    {
        "date": "2022-02-08T14:56:26.7139132-08:00",
        "temperatureC": -3,
        "temperatureF": 27,
        "summary": "Mild"
    },
]
```
### Request with $select
Endpoint: `https://localhost:7158/WeatherForecast?$select=summary`
Response (Property names are in pascal case)
```json
[
  {
    "Summary": "Cool"
  },
]

```

We need a way to serialize the responses using camel case, so that API responses are uniform with or without the `$select` query

**Comment by xuzhg** [comment]
@martinmogusu Thanks for reporting this. 

@julealgon  Thanks for the comments.

This is a very common scenario and I'd like to share the solution with the community using a doc.

Please find the detailed information at: https://github.com/OData/AspNetCoreOData/blob/main/docs/camel_case_scenarios.md

**Comment by xuzhg** [comment]
Close it.
