### ISSUE TITLE
Question: Creating Delta<T> from existing object for unit testing purposes

### ISSUE THREAD

**Issue by groogiam** [OData/AspNetCoreOData#485]
Is it possible to create an instance of Delta<T> from an existing object for unit testing purposes? I have some business rule logic classes called from my controller that take the Delta<T> coming from the patch operations as an input and I'm having trouble figure out how to create a mock instance of Delta<T> to properly unit test them. Thanks for you help.

**Comment by julealgon** [comment]
Please use the "Discussions" tab for this type of question in the future @groogiam . This applies to mostly any github project that has the "Discussions" feature enabled.

**Comment by groogiam** [comment]
Will do. Sorry I did not notice that discussions were enabled.
