### ISSUE TITLE
Upgrading to dotnet 6

### ISSUE THREAD

**Issue by surenrao** [OData/AspNetCoreOData#491]
I have a use case where our app is using Swagger, ApiVersioning with namespace convention and ODATA without edm. 

bare minimum Working Example
https://github.com/surenrao/Dotnet5WebApiODataVersioning

How do i upgrade the project to dotnet 6 with ASP.NET Core OData 8.x
When i tried to upgrade, it had breaking changes to OData versioning and EDM is now required?
I believe its due to https://github.com/dotnet/aspnet-api-versioning not supporting OData 8.x

**Comment by surenrao** [comment]
@xuzhg I see the exception, in my old code it was using the namespace to replace v{version:apiVersion},  and
`new VersionByNamespaceConvention()` was responsible for doing that. Is there something similar i can use?

Using `[Route("api/v1/[controller]")] [Route("api/v2/[controller]")]` makes the ambiguous exception to go away. and i can get the results back. however my tests fail. I also have a test page here https://localhost:44392/index.html. Can u take a look.

Thanks for the help.

**Comment by surenrao** [comment]
I got the test to pass when i add 
`.AddJsonOptions(opt => {
                opt.JsonSerializerOptions.PropertyNamingPolicy = null;
            });`
but using AddNewtonsoftJson was giving me below error
`JsonSerializationException: Self referencing loop detected for property 'DeclaringType' with type 'Microsoft.OData.Edm.EdmEntityType'. Path '[0].Model.SchemaElements[0].DeclaredProperties[0]'.`

**Comment by surenrao** [comment]
@xuzhg I found an article https://christian-schou.dk/how-to-use-api-versioning-in-net-core-web-api/ which solves the ambiguous exception. This also matches very closely to what i want after combining with your patch to support odata.

**Comment by xuzhg** [comment]
> @xuzhg I see the exception, in my old code it was using the namespace to replace v{version:apiVersion}, and `new VersionByNamespaceConvention()` was responsible for doing that. Is there something similar i can use?
> 
==> Is this https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-6.0#custom-routing-convention what you are looking for ?

**Comment by surenrao** [comment]
@xuzhg sorry for the late reply, I tried your suggestion and it worked. Below is what is used Thanks
` if (hasAttributeRouteModels)
                {  
                    var text = GetRawApiVersion(controller.ControllerType.Namespace);
                    if (ApiVersion.TryParse(text, out var apiVersion))
                    {
                        controller.Selectors[0].EndpointMetadata.Add(new ApiVersionAttribute(text));
                        controller.Selectors[0].AttributeRouteModel.Template =
                            controller.Selectors[0].AttributeRouteModel.Template.Replace("{version:apiVersion}", apiVersion.MajorVersion.ToString());
                    }
                }`
