### ISSUE TITLE
$metadata 404 endpoint not found in version 8.0.7 worked in 8.0.6

### ISSUE THREAD

**Issue by starsoftnl** [OData/AspNetCoreOData#493]
Starting with version 8.0.7 i get a 404 not found error for the $metadata endpoint.

**Comment by xuzhg** [comment]
@starsoftnl Can you share more details? Or Can you share with me a reproduction?

**Comment by starsoftnl** [comment]
I just tested with version 8.0.8 and now it works

**Comment by habbes** [comment]
Thanks @starsoftnl. I'm closing this issue since it has been resolved.
