### ISSUE TITLE
Support to make metadata localizable

### ISSUE THREAD

**Issue by davhdavh** [OData/AspNetCoreOData#500]
There seems to be no way for the Enums to be localized, since it always returns `.ToString` value and name property takes a fixed string.
This means that the metadata values cannot be used to populate dropdowns or whatever.

Additionally, there is support for adding Description and LongDescription, but none of these are localizeable either taking a fix string rather than `Func<string>`.

```xml
<EnumType Name="Status">
<Member Name="Open" Value="3"/>
...
```

**Comment by xuzhg** [comment]
@davhdavh Can you share more details about `Func<string>` ?

**Comment by davhdavh** [comment]
In the abstract there are 2 methods of translations:
* Magic strings that lookup things magically: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0#dataannotations-localization
* Call a func that returns the right values (which is actually what the above does internally and what the `ResXFileCodeGenerator` generates code for, or something like https://github.com/VocaDB/ResXFileCodeGenerator does). 

As you might have guessed, I am not really a fan of the first option :)

And also to support the 2nd options is very very easy. 


```csharp
        private string _name;
        /// <summary>
        /// Gets or sets the name of the member.
        /// </summary>
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (String.IsNullOrWhiteSpace(value))
                {
                    throw new ArgumentNullException(nameof(value));
                }

                _name = value;
            }
        }
```
becomes
```csharp
        private Func<string> _name;
        /// <summary>
        /// Gets or sets the name of the member. This may return a dynamic value (e.g. for translations) by using <see name="SetDynamicName">
        /// </summary>
        public string Name
        {
            get
            {
                return _name();
            }
            set
            {
                if (String.IsNullOrWhiteSpace(value))
                {
                    throw new ArgumentNullException(nameof(value));
                }
                _name = ()=>value;
            }
        }

        /// <summary>
        /// Every time the name of the member is request this function is called instead.
        /// </summary>
        public void SetDynamicName(Func<string> translator) => _name = translator ?? throw new ArgumentNullException(nameof(translator ));
```

**Comment by corranrogue9** [comment]
To be a bit more clear, the protocol does not support this. If you would like to discuss alternate approaches to localizing your APIs, please reach out and we can provide some resources.
