### ISSUE TITLE
$select operation throwing Self referencing loop detected for property 'declaringType' with type 'Microsoft.OData.Edm.EdmEntityType'

### ISSUE THREAD

**Issue by selva196** [OData/AspNetCoreOData#503]
**Odata Version**
8.0.8 

**Description**
$select operation is throwing Self referencing loop detected for property 'declaringType' with type 'Microsoft.OData.Edm.EdmEntityType'. Path '[0].model.schemaElements[0].declaredKey[0]'. 
Configured OData like below
 
**Startup.cs:**

```
services.AddControllers() .AddOData(options => options.EnableQueryFeatures().AddRouteComponents("", GetEdmModel()));
services.AddODataQueryFilter();

IEdmModel GetEdmModel()
{
   var modelBuilder = new ODataConventionModelBuilder();
   modelBuilder.EntitySet<Book>(nameof(Book));
   return modelBuilder.GetEdmModel();
}
```

**Controller Layer:**

```
public class PrivateApiDevicesController : BaseController
{
	[HttpGet("~/api/books")]
	[EnableQuery]
	public IActionResult GetDetails()
	{
		//returning result from DB as IQueryable object
	}
}

public class BaseController : ODataController
{     

}
```

**Model class**

```
public class Book 
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

**Url** : http://localhost/api/books?$select=id

**Sample response without $select query:**

```
[
  {
    "id": 5,
    "name": "UpdateName"
  },
  {
    "id": 6,
    "name": "Test"
  },
  {
    "id": 8,
    "name": "Dummy"
  }
]
```

**Comment by KenitoInc** [comment]
Kindly share a more detailed repro so that we can investigate this issue

**Comment by selva196** [comment]
Hi @KenitoInc  - I'm not able to reproduce this issue with my sample project.

**Comment by KenitoInc** [comment]
We will close this issue then

**Comment by franticallycodes** [comment]
@selva196 where you using Newtonsoft by chance? Others are having this same issue.
https://github.com/JamesNK/Newtonsoft.Json/issues/2649

**Comment by selva196** [comment]
Hi @franticallycodes - I'm using Newtonsoft like below 
`services.AddControllers()
                .AddOData(options => options.EnableQueryFeatures().AddRouteComponents("", GetEdmModel()))
                .AddODataNewtonsoftJson()
                .AddNewtonsoftJson();`

**Comment by selva196** [comment]
> @selva196 where you using Newtonsoft by chance? Others are having this same issue. [JamesNK/Newtonsoft.Json#2649](https://github.com/JamesNK/Newtonsoft.Json/issues/2649)

Hi @franticallycodes - I'm using Newtonsoft like below 
```
services.AddControllers()
                .AddOData(options => options.EnableQueryFeatures().AddRouteComponents("", GetEdmModel()))
                .AddODataNewtonsoftJson()
                .AddNewtonsoftJson();
```
In controller layer inheriting ODataController:

```
public class BaseController : ODataController
    {
        // code logic

    }
```

**Comment by giangnnt** [comment]
did anyone solve this
