### ISSUE TITLE
Old assembly referencing

### ISSUE THREAD

**Issue by Criperum** [OData/AspNetCoreOData#504]
I'm trying to use latest OData  8.0.8 for .NET 6 ASP project and I'm getting strange build error:
`Assembly 'Microsoft.AspNetCore.OData' with identity 'Microsoft.AspNetCore.OData, Version=8.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Mvc.Core' with identity 'Microsoft.AspNetCore.Mvc.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

As I understand Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0 is a completely old and obsolete package. 
I'm working on VS 2022 if it helps. Nuget cache clening didn't help

**Comment by julealgon** [comment]
@Criperum can you elaborate why you closed this? Did the issue just go away? Was it a mistake on your side?

**Comment by Criperum** [comment]
That was my fault, but the fix was definitely not intuitive. Thanks to VS for that headace.

**Comment by MoamenSoroor** [comment]
> That was my fault, but the fix was definitely not intuitive. Thanks to VS for that headache.

how did you fix the error??

**Comment by Criperum** [comment]
Had to manually add ASP framework into project file. It comes automatically with ASP Web app but not with class lib and no way to add framework from VS.

```
<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
```

**Comment by MoamenSoroor** [comment]
Many Thanks
