### ISSUE TITLE
Pagesize + $top gives wrong result and wrong nextLink

### ISSUE THREAD

**Issue by davhdavh** [OData/AspNetCoreOData#505]
```csharp
[EnableQuery(PageSize=2)]
public IQueryable<Test> Get() => ...;
```

Call with `?$top=100`. It will return 98 rows, and `nextLink` is `?$top=98&$orderby=Name&$skip=2`.

Is there another way to specify a default pagesize?

If I dont have a `PageSize`, even though my totalcount function returns 1000 but I only return 100 rows it will not generate a `nextLink`.

**Comment by KenitoInc** [comment]
`$top` is a client directive that says "i'm only interested in the first n records". Once the service returns n records, it is done -- there is no next link.
`PageSize` is used in server side pagination. A next link is returned by the service when there are more records to be returned than the service wants to return in a single response (more rows than the `PageSize`). This can occur if the result is large and the client hasn't specified a $top, or if the result is large and the client has specified a $top greater than the number of rows the service is configured to return in a single response. The next link both indicates that there are more records to return as well as providing the link to fetch the next page of records.
However, setting PageSize does not need to be dependent up on $top -- the two are composable. If the client-requested $top is greater than pagesize, then the service should return the first page of results, with a next link that fetches the next page of results up to the maximum specified in the client's $top.

For example, if there are 1000 rows but the client specifies $top=100 and the service has a pagesize of 50, the service would return the first 50 records with a nextLink to return a result containing the remaining 50 of the 100 requested rows with no nextlink.
If you define $top=100 and you don't define a `PageSize`, the service would return the first 100 rows and there will be no nextlink.

**Comment by davhdavh** [comment]
> For example, if there are 1000 rows but the client specifies $top=100 and the service has a pagesize of 50, the service would return the first 50 records
Yes, but that is not what happens:
With pagesize = 2, and $top=100 => The IQuerable.Take is called with 100 as parameter (so 100 records are fetched from db), 98 rows are returned, $skip is set to 2 in nextlink. INCORRECT, EITHER it should Take(100) and return 100 records and nextlink=$skip=100 OR Take(2) and return 2 records and nextlink=$skip=2.
With pagesize = 2 and no $top => The IQuerable.Take is called with 2 as parameter (so 2 records are fetched from db), 2 rows are returned, $skip is set to 2 in nextlink. CORRECT.
With no pagesize = 2 and no $top but a odata.maxpagesize http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358876 => returns all rows

**Comment by KenitoInc** [comment]
@davhdavh  Kindly share your repro for further investigation

**Comment by davhdavh** [comment]
I found the problem... the pagesize is applied as a new IQueryable ontop of the user specified IQueryable, so the .Take for that is not available at the time of IQueryProvider.Execute
