### ISSUE TITLE
Unable to use ApiController along with odata controller with the same name

### ISSUE THREAD

**Issue by Naveed-Bentley** [OData/AspNetCoreOData#514]
I have odata controllers which work fine, I need to add same name api controller (sort of v2). Once I add that requests from controller 1 also route to controller 2 , though url prefix is different. If I enable asp.net core API versioning, controller1(odata controller) is no longer supported. All I need is to have legacy odata controllers working along with that v2 controllers, which are not odata controllers. Both APIs refer different api url perfix - so accurate controller is invoked based upon the api endpoint url.

I am using .Net 5 and Microsoft.AspNetCore.OData 8.0.6

**Comment by julealgon** [comment]
I'd suggest renaming your issue to avoid confusion with [the `[ApiController]` attribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apicontrollerattribute?view=aspnetcore-6.0), which _does_ work properly with OData now.

Perhaps using the term "MVC Controller" would be better.

**Comment by Naveed-Bentley** [comment]
I used [ApiController] attribute with odata controllers and versionsing started to work - thanks
