### ISSUE TITLE
OData $batch returns 404 on Microsoft.AspNetCore.OData version >= 8.0.3

### ISSUE THREAD

**Issue by rahul7720** [OData/AspNetCoreOData#521]
Following configuration on the Program.cs file enables OData batching on an Asp.Net Core 6 project.

```
//on service collection
DefaultODataBatchHandler batchHandler = new();
builder.Services.AddControllers().AddOData(o => o.AddRouteComponents("odata", GetEdmModel(), batchHandler));

//on app builder
app.UseODataBatching();
```
The batch requests are working fine on the NuGet package `Microsoft.AspNetCore.OData` version 8.0.2.

**Issue:**

The batch endpoint returns a 404 response once the Nuget package `Microsoft.AspNetCore.OData` is updated to version 8.0.3 or later. The issue exists in the current version 8.0.8 as well.

It looks like some changes on version 8.0.3 broke the batching functionality.

for your attention: @xuzhg and @hassanhabib

**Comment by xuzhg** [comment]
@rahul7720 add 'app.UseRouting();' after `app.UseODataBatching();` could make it working.

Can you test it and Let me know the result?

**Comment by rahul7720** [comment]
@xuzhg It's already in the correct order, and it's not working.

```
app.UseODataBatching();
app.UseRouting();
```

**Comment by xuzhg** [comment]
@rahul7720 can you share with me your repro? 

at my side,
[BatchTestIn8.zip](https://github.com/OData/AspNetCoreOData/files/8250403/BatchTestIn8.zip)
is my test project. 

If you send a http://localhost:5198/odata/$batch

Request content head: application/json

```json
{
  "requests":[
      {
      "id": "2",
      "atomicityGroup": "transaction",
      "method": "post",
      "url": "/odata/customers",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" },
      "body": {"Name":"MyName11"}
      },
      {
      "id": "3",
      "atomicityGroup": "transaction",
      "method": "post",
      "url": "/odata/customers",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" },
      "body": {"Name":"MyName12"}
      },
      {
      "id": "4",
      "atomicityGroup": "transaction",
      "method": "post",
      "url": "/odata/customers",
      "headers": { "content-type": "application/json", "Accept": "application/json", "odata-version": "4.0" },
      "body": {"Name":"MyName13"}
      }
  ]
}
``` 

you can get the following response:
```json
{
    "responses": [
        {
            "id": "2",
            "atomicityGroup": "52ff172b-fc2f-4842-aa8e-25c2846aaf59",
            "status": 201,
            "headers": {
                "location": "http://localhost:5198/odata/Customers(0)",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5198/odata/$metadata#Customers/$entity",
                "Id": 0,
                "Name": "MyName11"
            }
        },
        {
            "id": "3",
            "atomicityGroup": "52ff172b-fc2f-4842-aa8e-25c2846aaf59",
            "status": 201,
            "headers": {
                "location": "http://localhost:5198/odata/Customers(0)",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5198/odata/$metadata#Customers/$entity",
                "Id": 0,
                "Name": "MyName12"
            }
        },
        {
            "id": "4",
            "atomicityGroup": "52ff172b-fc2f-4842-aa8e-25c2846aaf59",
            "status": 201,
            "headers": {
                "location": "http://localhost:5198/odata/Customers(0)",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5198/odata/$metadata#Customers/$entity",
                "Id": 0,
                "Name": "MyName13"
            }
        }
    ]
}
```

**Comment by rahul7720** [comment]
@xuzhg 
In your test project you have referenced the OData project.
I removed the project reference and added the nuget `Microsoft.AspNetCore.OData 8.0.8`  and the issue is recreatable (returns 404). Same project is working fine with `Microsoft.AspNetCore.OData 8.0.2`

Your modified test project:
[BatchTestIn8_V2.zip](https://github.com/OData/AspNetCoreOData/files/8250527/BatchTestIn8_V2.zip)
.

**Comment by xuzhg** [comment]
@rahul772  8.0.8 almost has the same code base as the current main branch.

I also tested my project using 8.0.8 version. It works fine.

Can you double-check at your side? if it still can't work, can you book some time, we can sync with face to face.

**Comment by rahul7720** [comment]
@xuzhg I have re-tested. the result is same.

**Version 8.0.2**
![image](https://user-images.githubusercontent.com/4676251/158926535-b861c0f9-2443-467f-87a7-fc8a45603eda.png)

![image](https://user-images.githubusercontent.com/4676251/158926581-36999244-361e-46ab-b7d1-072c6bde2317.png)

**Version 8.0.8**
![image](https://user-images.githubusercontent.com/4676251/158926644-69d1eaaf-944f-4ae8-887f-1c6d2fe3d032.png)

![image](https://user-images.githubusercontent.com/4676251/158926670-ec7d97ad-b96f-4b97-9851-4d770d9c31dc.png)

Please re-build and run [this demo ](https://github.com/OData/AspNetCoreOData/files/8250527/BatchTestIn8_V2.zip)project to re-produce the issue.

Note:
Please re-build the solution when you change the nuget package reference version.

Please book a time at your convenient  if required.

**Comment by xuzhg** [comment]
@rahul7720 You should use "Post" for the $batch.

**Comment by KenitoInc** [comment]
@rahul7720 Was your issue resolved?

**Comment by xuzhg** [comment]
@rahul7720 I'd close this issue. If you are still facing the issue or have any other questions, feel free to file a new issue for us. Thanks.

**Comment by rahul7720** [comment]
Sending Get Request on versions 8.0.2 and 8.0.8 resulted in different behaviour and that made some confusion.
But the POST is working without any issue. This issue can be closed.
Thanks!
