### ISSUE TITLE
Count disregard filter query

### ISSUE THREAD

**Issue by andrew-vdb** [OData/AspNetCoreOData#523]
Say you have view called "vw_people"

**Scenario:**
When $count=true and being sent with $filter
**Expected:**
The generated count should count with filter being applied
**Actual:**
The generated count all rows in vw_people

**Comment by julealgon** [comment]
Looks like this could be related to discussions had in:
- https://github.com/OData/AspNetCoreOData/issues/516

**Comment by andrew-vdb** [comment]
In my case the page number in my front end will go wrong.....

**Comment by Nthemba** [comment]
@andrew-vdb please share sample code and the assembly used.

**Comment by andrew-vdb** [comment]
I will re-visit this when i work on odata again
