### ISSUE TITLE
Camelcase for Metadata EntityTypes and EntitySets

### ISSUE THREAD

**Issue by venknar** [OData/AspNetCoreOData#530]
Hi
My requirement is that the entity type and entity sets are also camel case. 
Tried this but its not working.

            var builder = new ODataConventionModelBuilder();
            builder.EnableLowerCamelCase(NameResolverOptions.ProcessDataMemberAttributePropertyNames);
            builder.EnableLowerCamelCase(NameResolverOptions.ProcessExplicitPropertyNames);
            builder.EnableLowerCamelCase(NameResolverOptions.ProcessReflectedPropertyNames);
            builder.Namespace = "myodata.service";
            builder.ContainerName = "EntityContainer";

            builder.EntitySet<CustomerEntity>("customers");

In the metadata I need the CustomerEntity to be lower case and also I need to change the name to Customer while emitting instead of CustomerEntity. My output is as follows:

    <EntityContainer Name="EntityContainer">
          <EntitySet Name="customers" EntityType="microsoft.graph.CustomerEntity" />
        </EntityContainer>

My requirement is as follows:
       <EntityContainer Name="EntityContainer">
          <EntitySet Name="customers" EntityType="microsoft.graph.customer" />
        </EntityContainer>

Any suggestion on how we can do the above mapping. Do I need to write custom formatter ? The entity type should be customer lower case instead of CustomerEntity

**Comment by xuzhg** [comment]
@venknar can you use the 'Name' property after calling `EntityType<CustomerEntity>().Name="customerEntity";` to change the type name?

**Comment by venknar** [comment]
There is no Name property on EntitySet. Also there is no EntityType. My requirement is that the class name is pascal casing and so when entity set is added it is having pascal casing and the only way to solve it is to rename the class name in camel case.
