### ISSUE TITLE
Cannot override GetModel method from EnableQueryAttribute

### ISSUE THREAD

**Issue by kjaworski** [OData/AspNetCoreOData#537]
Before it was possible to override GetModel method from EnableQueryAttribute for customizations. That's also what "summary" doc says. But it was changed from "virtual" to "static" in this commit:

https://github.com/OData/AspNetCoreOData/commit/daba95032a182446f6157478b79c80386a5f60ff

**Comment by julealgon** [comment]
Looks like it was changed inadvertently because of where it is called, `ContainsAutoSelectExpandProperty`, which is static (but doesn't seem to need to be).

**Comment by kjaworski** [comment]
@xuzhg Could you please prioritize this one?

It prevents our company from upgrading our products to .NET 6. The workaround will do the trick of course, but we have hundreds of controllers decorating our attribute which inherits from `EnableQueryAttribute`.

The origin of our issue is extraction of `IServiceCollection` to separate "Abstractions" namespace, so `BuildContainer()` from `DefaultContainerBuilder` gets the same error as this one:
https://github.com/dotnet/aspnet-api-versioning/issues/796
There are comments that upgrade to 7.5.12 helps, but it doesn't work for us.

**Comment by kjaworski** [comment]
@xuzhg @habbes Can I submit my fix? I tried to push my branch, but I have no permission to do so.

**Comment by julealgon** [comment]
> I tried to push my branch, but I have no permission to do so.

Create a fork of the project, push your changes there, and then create a PR from your fork's branch into the main repo.

**Comment by kjaworski** [comment]
> > I tried to push my branch, but I have no permission to do so.
> 
> Create a fork of the project, push your changes there, and then create a PR from your fork's branch into the main repo.

Thanks! I didn't know the "forking" workflow yet. PR ready.

**Comment by kjaworski** [comment]
Any plans for next release? When can we expect this?

**Comment by xuzhg** [comment]
@kjaworski https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.0.9 is out. Please try and let me know any problems.

**Comment by kjaworski** [comment]
@xuzhg Thanks a lot, works ok in 8.0.9!
