### ISSUE TITLE
Get the Count for a filtered nested collection . error aggregate|filter|groupby|compute|expand' expected at position 

### ISSUE THREAD

**Issue by padhumailin** [OData/AspNetCoreOData#542]
I need to take the count of nested collection License after applying the filters

`
[
	{
		"Name": Product A
		"StartDateTime":"2012-01-01T00:00:00Z"
		"License":
			[
				{
                                        "ID":1
					"LicenseName":Test
					"StartDateTime":"2020-01-01T00:00:00Z"
					"EndDateTime": "2021-01-01T00:00:00Z"
				},
				{
                                        "ID":2
					"LicenseName": Test2
					"StartDateTime": "2040-01-01T00:00:00Z"
					"EndDateTime": "2050-01-01T00:00:00Z"
				}
			]
		}
	},
	{
		"Name": Product B
		"StartDateTime":"2010-01-01T00:00:00Z"
		"License":
			[
				{
                                        "ID":3
					"LicenseName":Test
					"StartDateTime":"2020-01-01T00:00:00Z"
					"EndDateTime": "2030-01-01T00:00:00Z"
				},
				{
                                        "ID":4
					"LicenseName": Test2
					"StartDateTime": "2040-01-01T00:00:00Z"
					"EndDateTime": "2050-01-01T00:00:00Z"
				}
			]
		}
	}
]`
Expression:
`$apply=expand(License,filter(EndDateTime ge 2017-01-01 and EndDateTime le 2030-01-01),aggregate(ID with countdistinct as Total)`

i need to number of license count satisfying the condition as **1**

but I get this Error:
The query specified in the URI is not valid. 'aggregate|filter|groupby|compute|expand' expected at position 79 in 'expand(License,filter(EndDateTime ge 2017-01-01 and EndDateTime le 2030-01-01),aggregate(ID with countdistinct as Total)'.

How could i write a expression : 

`**Environment**:.Net5, EF5, OData 7.8.3`

**Comment by padhumailin** [comment]
i have added a sample project for repro https://github.com/padhumailin/ODataV8Demo.
sample project used Odata v8 and it has same issue as in v7

URL : http://localhost:34987/api/accounts?$expand=Licenses($filter=StartDate%20ge%202014-01-01%20and%20EndDate%20le%202014-09-10)&$count=true

Issue 1: filter is applied on a nested collection, but still all parent entities are returned with count 6.
My expectation is to return only matching parent entities count which is 1.

**Comment by julealgon** [comment]
> Issue 1: filter is applied on a nested collection, but still all parent entities are returned with count 6.
> My expectation is to return only matching parent entities count which is 1.

But your query still matches all accounts, it just "conditionally expands their `Licenses` properties. Isn't count 6 correct in this case? Wouldn't you need to repeat the filter outside of the expand if you actually wanted to filter the accounts themselves?

**Comment by padhumailin** [comment]
@julealgon , i have filtered the nested collection license, and one license is only matched for the given criteria.
and i am expecting to return the Account which has a matching license.

so 1 account having the matching license right? so only one account to be returned but its returning all 6 accounts

**Comment by habbes** [comment]
@padhumailin As @julealgon has pointed out, your filter isn't applied on accounts, it's applied on the nested Licenses field. So what it's doing is returning all accounts, and for each account expand the `Licenses` property only include the licenses that match the filter condition.

**Comment by padhumailin** [comment]
how to write a expression to get 1 account with matching license
