### ISSUE TITLE
Odata Controller - 404 Not Found response

### ISSUE THREAD

**Issue by cohendana** [OData/AspNetCoreOData#548]
Hey,
I am having issues using an odata controller (Microsoft.AspNetCore.OData 8.0.8). 
I am trying to locally send a get request with the address: /api/Employees/Method, but it results 404- Not Found response. Without the "api" prefix the request works as expected.

The method's structure is:
public static class EmployeesController 
{
          [HttpGet("Employees/Method")]
          public async Task<IActionResult> Method()
          {
              PageResult<employee> result= getEmployees();
              return OK(result)
          }
}
  
The edm:
var action = 
builder.EntityType<employe>().Collection.Function(nameof(EmployeesController.Method)).ReturnsCollection<employee>();
action .Namespace = builder.Namespace;

The exception:
'httpContext.Request.Form' threw an exception of type 'System.InvalidOperationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233079
    HelpLink: null
    InnerException: null
    Message: "Incorrect Content-Type: "
    Source: "Microsoft.AspNetCore.Http"
    StackTrace: "   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()\r\n   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()"
    TargetSite: {Microsoft.AspNetCore.Http.IFormCollection ReadForm()}

I think it is worth mentioning that in the EmployeesController class there is another method with the route /api/Employees that works fine.

**Comment by julealgon** [comment]
@cohendana can you elaborate why you think calling these methods with the `/api` preffix should work?

**Comment by cohendana** [comment]
thanks for the response @gathogojr, I checked the blog in the link and I still can't solve the issue.

**Comment by gathogojr** [comment]
@cohendana Try changing `[HttpGet("Employees/Method")]` to `[HttpGet("api/Employees/Method")]`

**Comment by gathogojr** [comment]
Hi @cohendana 
I don't know if you got to try what I suggested but I believe it should work.
You could also leave out the route template altogether, i.e., just decorate `Method` with `HttpGet` attribute without including the route template.

If you're still stuck, kindly provide sufficient details and syntactically-correct sample code to help repro the issue. I observed the following from the code you provided
1. I'd expect `EmployeeController` to inherit from either `ODataController` or `ControllerBase`
2. `Task` cannot be a valid return type for `Method` given that you're returning an `OkObjectResult` - it should actually be `Ok(result)` not `OK(result)`. Here's how a syntactically-correct version could look like:

    ```csharp
    public Task<ActionResult> Method()
    {
        PageResult result= getEmployees();
        return Task.Run<ActionResult>(() => Ok(result));
    }
    ```
3. Your logic for configuring the OData function is also invalid. In addition, `ReturnsCollection` is used when the return type is either a collection of primitive or complex types. A syntactically-correct way would be:

    ```csharp
    modelBuilder.EntityType<Employee>().Collection.Function("Method").ReturnsCollectionFromEntitySet<Employee>("Employees");
    ```
You'll get better and quicker help if you provide easy-to-follow repro steps and/or valid sample code/repro
