### ISSUE TITLE
SelectExpandWrapperConverter does not work

### ISSUE THREAD

**Issue by cschulzsuper** [OData/AspNetCoreOData#55]
I think there are a couple of issues with `SelectExpandWrapperConverter`.

- I wanted to use it in a non-edm approach, but got stuck on a `$select`.
- The `SelectExpandWrapperConverter` was not even used due to the fact that `CanConvert` would never return true.

If I make `SelectExpandWrapperConverter` generic with a type constrain of `ISelectExpandWrapper` and additionally implement a `SelectExpandWrapperConverterFactory` which implements `JsonConverterFactory` everything works as I would expect it.

An additional small issue in `SelectExpandWrapperConverter.Write()` is, that it is not writing the serialized json to the given writer.

**Assemblies affected**
AspNetCore.OData Odata8.0.0-preview3

**Comment by xuzhg** [comment]
@cschulzsuper SelectExpandWrapperConverter is updated since 8.0. It should work. Please try and let me know any other issues. Thanks.
