### ISSUE TITLE
ETA date for next release

### ISSUE THREAD

**Issue by giulianob** [OData/AspNetCoreOData#550]
Hello,

Is there an ETA for the next release version? We are currently using nightly for development but need a couple of fixes.

Thanks!

**Comment by corranrogue9** [comment]
We don't currently have a date set for the next release. We are working to standardize our release cadence. I see that you've contributed most of the changes since the last release, is there a timeline you are looking for?

**Comment by giulianob** [comment]
@corranrogue9 the sooner the better. We can't merge some changes on our side to main until there's an official package. 

I was unable to create a package source internally with the MyGet nightly builds. We can easily consume preview packages off of Nuget as well if that's a possibility until an official release is out. Thanks!

**Comment by xuzhg** [comment]
@giulianob https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.0.9 is out. Please try and let me know any problems. Thanks.
