### ISSUE TITLE
ODataInputFormatter does not add errors to ModelState

### ISSUE THREAD

**Issue by giulianob** [OData/AspNetCoreOData#551]
**Assemblies affected**
 ASP.NET Core OData Nightly

**Describe the bug**
Errors thrown during model binding are ignored when an `ILogger` is defined and the `ModelState` is considered valid. OData 7.x did not have the same behavior.

**Reproduce steps**
If an ILogger is registered in the request services (for example: `AddRouteComponents(model, s => s.AddSingleton<ILogger, SomeLogger>())`) then the following request will not return the appropriate 400 Bad Request and will instead crash in the controller when trying to access the `parameters["ID"]` argument.

```
POST http://localhost:5000/convention/Employees(1)/AddSkill
Content-Type: application/json

{
}
```

This is due to `ODataInputFormatter` throwing the exception only if an `ILogger` is not registered:
```csharp
// src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatter.cs:244
        private static void LoggerError(HttpContext context, Exception ex)
        {
            ILogger logger = context.RequestServices.GetService<ILogger>();
            if (logger == null)
            {
                ExceptionDispatchInfo.Capture(ex).Throw();
            }

            logger.LogError(ex, string.Empty);
        }
```

And the code that calls it converts to the default value instead:
```
                result = await deserializer.ReadAsync(oDataMessageReader, type, readContext).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                LoggerError(request.HttpContext, ex);
                result = defaultValue;
            }
```

**Expected behavior**
The error should be added to the `ModelState` regardless of whether an `ILogger` is registered. `LoggerError` or the calling code should always throw after logging it.

**Comment by gathogojr** [comment]
Related issue https://github.com/OData/WebApi/issues/1572
