### ISSUE TITLE
How to execute action without using namespace

### ISSUE THREAD

**Issue by komdil** [OData/AspNetCoreOData#561]
**Assemblies affected**
Microsoft.AspNetCore.OData 7.5.12

**Describe the bug**
I didn't understand the purpose of namespace in `ODataConventionModelBuilder`. By default it will be set to `Default`. And for request we need to use namespace to execute action (like `.../Default.ActionName`) or casting properties. For me it looks stange, and I would like to not have namespace on executing actions. 
So, my questions are:

Can we run action without namespace? Like  `.../ActionName`
Can we have multiple namespaces? For example, I would like to work my actions on :
```
.../Default.ActionName
.../Default2.ActionName
```

**Reproduce steps**
Just create any action and run it using Default namespace

**Data Model**
Just create entity with action and map it

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Expected behavior**
I would like do not have a namespace

**Comment by KenitoInc** [comment]
More info: https://devblogs.microsoft.com/odata/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/

**Comment by julealgon** [comment]
This should be moved to discussions.

**Comment by xuzhg** [comment]
@komdil We also have the setting at https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L91, Keep in mind, those settings are only for the conventional routing.

**Comment by KenitoInc** [comment]
Hey @komdil 
We have provided information to assist you. For further discussions, you can open a discussion [here ](https://github.com/OData/AspNetCoreOData/discussions)

Closing this issue for now.

**Comment by komdil** [comment]
I opened discussion here: https://github.com/OData/AspNetCoreOData/discussions/566
The given solutions is not working on me. I couldn't find EnableUnqualifiedOperationCall. Is it on 7.* version?
