### ISSUE TITLE
Slash character ('/') is not proper handled at function or action in quoted string value segment

### ISSUE THREAD

**Issue by wjmirror** [OData/AspNetCoreOData#567]
**Assemblies affected**
Microsoft.AspNetCore.OData

**Describe the bug**
Slash character ('/') is not proper handled at function or action in quoted string value segment

**Reproduce steps**

1. In **ODataRoutingSample** project,  PeopleController, initialize the IList<Person> as below.  see I changed the first person's LastName as "Zha/ngg" .  
```c#
private static IList<Person> _persons = new List<Person>
        {
            new Person
            {
                FirstName = "Goods",
                LastName = "Zha/ngg",
            },
            new Person
            {
                FirstName = "Magazine",
                LastName = "Jingchan",
            },
            new Person
            {
                FirstName = "Fiction",
                LastName = "Hollewye"
            },
        };
``` 
2. Run the sample. 
Get: /People(FirstName='Goods',LastName='Zha%2Fngg') 

It returns  

```json
{
"@odata.context": "https://localhost:64772/$metadata#Edm.String",
"value": "Not found person with FirstName = Goods and LastName = Zha%2Fngg"
}
``` 

Get: /People(FirstName='Goods',LastName='Zha/ngg')
It return HTTP 404

**Data Model**
ODataRoutingSample.Models.Person

**EDM (CSDL) Model**

**Request/Response**
Get: /People(FirstName='Goods',LastName='Zha%2Fngg') 
Get: /People(FirstName='Goods',LastName='Zha/ngg')

**Expected behavior**
Expect to Return
```json
{
"@odata.context": "https://localhost:64772/$metadata#People/$entity",
"FirstName": "Goods",
"LastName": "Zha/ngg"
}
```

**Screenshots**
Get: /People(FirstName='Goods',LastName='Zha/ngg')
![image](https://user-images.githubusercontent.com/31735283/163607081-119ce9bd-cb0f-4a52-a5d0-9353025b0efd.png) 

Get: /People(FirstName='Goods',LastName='Zha%2Fngg') 
![image](https://user-images.githubusercontent.com/31735283/163607166-f7a8b9d0-9f6f-470a-ab46-ad7296cd6ce1.png)

**Additional context**
N/A

**Comment by julealgon** [comment]
A raw `/` character in a quote string should not work as per the docs, but your alternative, using the encoded value, _should_. Looks like there should be some decoding process happening prior to attempting to compare the actual values here.

**Comment by xuzhg** [comment]
@julealgon @wjmirror It looks like a bug. We didn't un-escape the key value/function parameter value from the request URL.

For key value, we need to un-escape the string at: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs#L173

for function parameter value, we need to un-escape the string at: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs#L59

**Comment by xuzhg** [comment]
merged.
