### ISSUE TITLE
How can I exclude type annotations from OData server response?

### ISSUE THREAD

**Issue by GennadyGS** [OData/AspNetCoreOData#577]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.7

Starting from the version mentioned above type annotations appeared in server's response for dynamic models, like `"Field_002@odata.type": "#Decimal"`. Can I configure the server to restore previous behavior, that is to exclude type annotations for properties?
I admit that there might be good reason for this change, particularly it might fix the issue #457, but in my case it causes negative performance impact, since I deal with massive responses containing big number of objects and properties.

**Reproduce steps**
My issue is reproducible with the following sample application: https://github.com/GennadyGS/ODataExperiments/tree/master/src/ODataExperiments.Server

**Data Model**
I use dynamic model, like the following:
```C#
public sealed class Record
{
    public Record(int id, IDictionary<string, object> properties)
    {
        Id = id;
        Properties = properties;
    }

    [Key]
    public int Id { get; set; }

    public IDictionary<string, object> Properties { get; set; }
}
```

**EDM (CSDL) Model**
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="ODataExperiments.Server" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Record" OpenType="true">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Records" EntityType="ODataExperiments.Server.Record" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

**Request/Response**
```txt
GET /odata/Records HTTP/1.1
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Postman-Token: 83968def-132d-4e0a-93fb-8df0d03085df
Host: localhost:44317
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```
```txt
HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
Date: Sat, 23 Apr 2022 08:29:36 GMT
Server: Kestrel
OData-Version: 4.0
Content-Length: 498
```
```json
{
    "@odata.context": "https://localhost:44317/odata/$metadata#Records",
    "value": [
        {
            "Id": 0,
            "Field_000": true,
            "Field_001": false,
            "Field_002@odata.type": "#Decimal",
            "Field_002": 0.8838285691495190,
        }
    ]
}
```
**Expected behavior**
This is OK as default behavior, but I expect that I can configure server to exclude type annotations, like `"Field_002@odata.type": "#Decimal"` from the response, like that:
```json
{
    "@odata.context": "https://localhost:44317/odata/$metadata#Records",
    "value": [
        {
            "Id": 0,
            "Field_000": true,
            "Field_001": false,
            "Field_002": 0.8838285691495190,
        }
    ]
}
```
**Additional context**
In real application I use Simple.OData.Client library, which means that I am limited in possibilities from client side. For example, adding "odata.metadata = none" in Accept header of request does not work and breaks client library, since it also excludes some other required metadata.

**Comment by julealgon** [comment]
Why is type not included for `Field_000` and `Field_001`? Is this somehow specific to `decimal` or some set of "nondefault" types?

**Comment by xuzhg** [comment]
@GennadyGS [GennadyGS](https://github.com/GennadyGS)

Since you want to keep other metadata, I think you can customize the serializer to set the TypeAnnotation = null for the certain property.

**Comment by GennadyGS** [comment]
@xuzhg 
Thank you.
I have tried this options, but it does not work:
https://github.com/GennadyGS/ODataExperiments/blob/f3be1ad4ccac1856c4833c25930e4a7369592599/src/ODataExperiments.Server/AddTypeAnnotationResourceSerializer.cs#L19
In debugger I see that TypeAnnotation is null even before I am trying to set it no null:
![image](https://user-images.githubusercontent.com/6974233/165232494-8f2a63a7-3f8a-4ba4-b10c-dd0a440dcc87.png)

**Comment by corranrogue9** [comment]
> Why is type not included for `Field_000` and `Field_001`? Is this somehow specific to `decimal` or some set of "nondefault" types?

@julealgon based on [this](http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#_Toc38457738) part of the spec, the `Id` property doesn't need it because it is declared as `int`, and `Field_000` and `Field_001` are booleans and do not require the type. Since `Field_002` is not a `double`, `@odata.type` is required.

**Comment by xuzhg** [comment]
@GennadyGS 

You can do this to exclude the type annotation.

```C#
public sealed class MyPrimitiveSerializer : ODataPrimitiveSerializer
{
    public override ODataPrimitiveValue CreateODataPrimitiveValue(
        object graph, IEdmPrimitiveTypeReference primitiveType,
            ODataSerializerContext writeContext)
    {
        ODataPrimitiveValue value = base.CreateODataPrimitiveValue(graph, primitiveType, writeContext);
        if (value.TypeAnnotation == null)
        {
            value.TypeAnnotation = new ODataTypeAnnotation(null); // create a annotation and set the type name as null
        }

        return value;
    }
}
```

You don't need to create the serializer provider, you can inject the primitive serializer directly:

```C#
.AddOData(options =>
    {
        options.AddRouteComponents(
            "odata",
            GetEdmModel(),
            services => services
                .AddSingleton<ODataPrimitiveSerializer, MyPrimitiveSerializer>()
                //.AddSingleton<IODataSerializerProvider, AddTypeAnnotationSerializerProvider>()
                );
        options.EnableQueryFeatures();
    });
```

Here's my test using your sample:


![image](https://user-images.githubusercontent.com/9426627/165372733-647df29f-a4d5-4013-a8e4-b5aae77adedf.png)

**Comment by xuzhg** [comment]
> Why is type not included for `Field_000` and `Field_001`? Is this somehow specific to `decimal` or some set of "nondefault" types?

@julealgon The types can 'easily' be inferred omitted by default.

**Comment by GennadyGS** [comment]
@xuzhg 
This really solves my problem.
Thanks a lot!
