### ISSUE TITLE
How to set routing for 1:N where child entity has its own controller

### ISSUE THREAD

**Issue by kenakamu** [OData/AspNetCoreOData#581]
Let's say we have two models. Customer and Order. Customer has Orders property which is type of List<Order>

1. I have OrdersController in addition to CustomersController
2. I want to access an order as: /api/customers/{cusomer Id}/orders/{order id}
3. order has function as well. /api/customers/{cusomer Id}/orders/{order id}/myfunc()

I don't want to see /api/orders in swagger and i am not sure how to generate EdmModel. If I set both Customer and Order as EntitySet, then I can access order via  /api/orders. If I set [Route] attribute on OrdersController, order entity is not considered to be odata entity.

Any guidance will be appreciated.

**Comment by TehWardy** [comment]
I don't think that's possible since all Entity sets have to first be added to the model as entities in order to appear anywhere in the graph you get "by default" an endpoint mapping for each set.

I think this is an OData spec thing rather than a Microsoft thing.

Question ... 
Why would you not want to expose the Orders set separately on your API ?

**Comment by kenakamu** [comment]
Thanks for your reply! I want orders always related to customer. Of course we can pass customer Id as part of param or header, but /customers/{id}/orders seems easy to understand. The challenge here is that order has function and action so it cannot be simple List<Order> as customer's property. I want /customers/{customerId} as prefix for order, so i will take a look into routings, too.

**Comment by julealgon** [comment]
This should be moved to discussions.

**Comment by TehWardy** [comment]
@kenakamu You can achieve the same result by adding orders to the API model as their own set then query like this ...
    api/orders?filter=CustomerId eq {someCustomerId}

**Comment by kenakamu** [comment]
As @julealgon suggested, i close the issue here and move to discussion
