### ISSUE TITLE
Extraction of Api "Areas" to a class library

### ISSUE THREAD

**Issue by TehWardy** [OData/AspNetCoreOData#582]
**Assemblies affected**
ASP.NET Core OData 8.0.10

**Describe the bug**
Odata seems to depend on versions that only exist in the "Microsoft.NET.Sdk.Web" sdk

**Reproduce steps**

1. Create a new class library
2. Add a reference to the latest OData Library
3. Add a simple controller 
4. Code a simple extension method like this ...
```cs
    public static partial class IServiceCollectionExtensions
    {
        public static void AddApi(this IServiceCollection services)
        {
            _ = services.AddControllers()
                .AddOData(opt =>
                {
                    opt.RouteOptions.EnableQualifiedOperationCall = false;
                    opt.EnableAttributeRouting = true;
                    _ = opt.Expand().Count().Filter().Select().OrderBy().SetMaxTop(1000);
                    opt.AddRouteComponents($"/Api", BuildEdmModel());
                });
        }
    }
```
... it doesn't matter that the BuildEdmModel() model function does only that it returns any valid edm model.

**Expected behavior**
This should all be good when I compile however I get an issue with references as shown in the below image.

**Screenshots**
![image](https://user-images.githubusercontent.com/6891030/165724572-cb89638f-ee6d-4b77-9c1e-a37d91f8ae96.png)

NOTE: Referenced version here is not the latest, but the behavior is the same with OData 8.0.10

**Additional context**
It would be nice if OData's setup didn't require the full web sdk to be defined, so that I can modularise my API layer like this in to multiple class libs then pull them all together later in a web application project that depends on the full web sdk.

Is this an OData issue or something about AspNet Core Mvc ?

**Comment by julealgon** [comment]
Interestingly, its the second time this is raised:
- https://github.com/OData/AspNetCoreOData/issues/504

Seems like it should be fixed somehow.

**Comment by TehWardy** [comment]
That's the thing though I don't think this is an "old" reference ... I think there's something different between SDK's in terms of versioning of AspNetCore.

These SDK's ...
 - Microsoft.NET.Sdk.Web
 - Microsoft.NET.Sdk
 
 ... if I use sdk Microsoft.NET.Sdk and then pull Microsoft.AspNetCore.Mvc.Core from Nuget then assuming I have the latest version today I get given version 2.2.5 of that package.
 
 If I use sdk Microsoft.NET.Sdk.Web then with no other references added to my project I get version 6.0.0 of the same package.

... Or so it seems to think.

The fact that I can't reference directly from nuget something that the OData package requires means I can ONLY use Odata in a project that sits on top of sdk Microsoft.NET.Sdk.Web

Make sense?

**Comment by julealgon** [comment]
> Make sense?

It totally does. I agree there is something weird going on here that needs to be investigated in more detail.

**Comment by xuzhg** [comment]
@TehWardy 

1) make sure the SDK in the csproj is <Project Sdk="Microsoft.NET.Sdk.Web">, not <Project Sdk="Microsoft.NET.Sdk">
2) <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" /> is never needed in new version. It is shipped with framework, not from nuget package.
3) Tiny, you can add <OutputType>Library</OutputType> to make it as a library.

**Comment by TehWardy** [comment]
some weird subtlety here in the SDK's that i'm completely clear on ...
I thought the web sdk was purely for spitting out web apps and since I only wanted a dll I figured I would just ref the few bits I needed from nuget.

Many thanks Sam :)
Let me know if you figure out why this is done like this of course :)
