### ISSUE TITLE
`ArgumentNullException` when calling `AddODataNewtonsoftJson()`

### ISSUE THREAD

**Issue by prochnowc** [OData/AspNetCoreOData#587]
**Assemblies affected**
Microsoft.AspNetCore.OData.NewtonsoftJson v8.0.4

**Describe the bug**
The method `AddODataNewtonsoftJson()` calls `AddNewtonsoftJson(null)` 
Instead it should probably call `AddODataNewtonsoftJson(null)`

**Expected behavior**
The method should not throw.

**Comment by xuzhg** [comment]
https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData.NewtonsoftJson/ODataNewtonsoftJsonMvcBuilderExtensions.cs#L58 could be a problem.

**Comment by prochnowc** [comment]
@xuzhg Thank you.
