### ISSUE TITLE
OData Response change default settings and expose by default @odata.type foreach properties

### ISSUE THREAD

**Issue by bonfi7** [OData/AspNetCoreOData#588]
**Assemblies affected**
ASP.NET Core OData 8.0.9 and next

**Describe the bug**
Response of data request contains @odata.type properties by default. In previous versions these properties are not sent by default.

**Reproduce steps**
The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.

**Data Model**
public class DataItem: IODataSource
    {
        public DataItem()
        {
            __id = null;
        }
        [Key] 
        public int? __id { get; set; }
        public IDictionary<string, object> DynamicProperties { get; set; }
    }

**EDM (CSDL) Model**
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="SedApta.Analytics.EntityManager" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Sales-alj79i1j">
                <Property Name="ProductKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="OrderDateKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="DueDateKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="ShipDateKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="CustomerKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="PromotionKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="CurrencyKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="SalesTerritoryKey" Type="Edm.Int32" Nullable="false" />
                <Property Name="SalesOrderNumber" Type="Edm.String" Nullable="false" />
                <Property Name="SalesOrderLineNumber" Type="Edm.Byte" Nullable="false" />
                <Property Name="RevisionNumber" Type="Edm.Byte" Nullable="false" />
                <Property Name="OrderQuantity" Type="Edm.Int16" Nullable="false" />
                <Property Name="UnitPrice" Type="Edm.Decimal" Nullable="false" />
                <Property Name="ExtendedAmount" Type="Edm.Decimal" Nullable="false" />
                <Property Name="UnitPriceDiscountPct" Type="Edm.Double" Nullable="false" />
                <Property Name="DiscountAmount" Type="Edm.Double" Nullable="false" />
                <Property Name="ProductStandardCost" Type="Edm.Decimal" Nullable="false" />
                <Property Name="TotalProductCost" Type="Edm.Decimal" Nullable="false" />
                <Property Name="SalesAmount" Type="Edm.Decimal" Nullable="false" />
                <Property Name="TaxAmt" Type="Edm.Decimal" Nullable="false" />
                <Property Name="Freight" Type="Edm.Decimal" Nullable="false" />
                <Property Name="CarrierTrackingNumber" Type="Edm.String" />
                <Property Name="CustomerPONumber" Type="Edm.String" />
                <Property Name="OrderDate" Type="Edm.DateTimeOffset" />
                <Property Name="DueDate" Type="Edm.DateTimeOffset" />
                <Property Name="ShipDate" Type="Edm.DateTimeOffset" />
            </EntityType>
            <EntityContainer Name="DefaultContainer">
                <EntitySet Name="Sales-alj79i1j" EntityType="SedApta.Analytics.EntityManager.Sales-alj79i1j" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>

**Request/Response**
Request:
https://localhost:6001/odata/data/GetEntity(entity='Sales-alj79i1j')?$skip=0&$top=30&$count=true

Response:

"@odata.context": "https://localhost:6001/odata/$metadata#Data",
    "@odata.count": 100,
    "value": [
        {
            "__id": null,
            "ProductKey": 310,
            "OrderDateKey": 20050701,
            "DueDateKey": 20050713,
            "ShipDateKey": 20050708,
            "CustomerKey": 21768,
            "PromotionKey": 1,
            "CurrencyKey": 19,
            "SalesTerritoryKey": 6,
            "SalesOrderNumber": "SO43697",
            "SalesOrderLineNumber@odata.type": "#Byte",
            "SalesOrderLineNumber": 1,
            "RevisionNumber@odata.type": "#Byte",
            "RevisionNumber": 1,
            "OrderQuantity@odata.type": "#Int16",
            "OrderQuantity": 2,
            "UnitPrice@odata.type": "#Decimal",
            "UnitPrice": 3578.2700,
            "ExtendedAmount@odata.type": "#Decimal",
            "ExtendedAmount": 3578.2700,
            "UnitPriceDiscountPct": 0.0,
            "DiscountAmount": 0.0,
            "ProductStandardCost@odata.type": "#Decimal",
            "ProductStandardCost": 2171.2942,
            "TotalProductCost@odata.type": "#Decimal",
            "TotalProductCost": 2171.2942,
            "SalesAmount@odata.type": "#Decimal",
            "SalesAmount": 3578.2700,
            "TaxAmt@odata.type": "#Decimal",
            "TaxAmt": 286.2616,
            "Freight@odata.type": "#Decimal",
            "Freight": 89.4568,
            "CarrierTrackingNumber": null,
            "CustomerPONumber": null,
            "OrderDate@odata.type": "#DateTimeOffset",
            "OrderDate": "2005-07-12T00:00:00Z",
            "DueDate@odata.type": "#DateTimeOffset",
...

**Expected behavior**
Get response like previous versions or expose a property to change the default behaviour.
Expected response:

"@odata.context": "https://localhost:6001/odata/$metadata#Data",
    "@odata.count": 100,
    "value": [
        {
            "__id": null,
            "ProductKey": 310,
            "OrderDateKey": 20050701,
            "DueDateKey": 20050713,
            "ShipDateKey": 20050708,
            "CustomerKey": 21768,
            "PromotionKey": 1,
            "CurrencyKey": 19,
            "SalesTerritoryKey": 6,
            "SalesOrderNumber": "SO43697",
            "SalesOrderLineNumber": 1,
            "RevisionNumber": 1,
            "OrderQuantity": 2,
            "UnitPrice": 3578.2700,
            "ExtendedAmount": 3578.2700,
            "UnitPriceDiscountPct": 0.0,
            "DiscountAmount": 0.0,
            "ProductStandardCost": 2171.2942,
            "TotalProductCost": 2171.2942,
            "SalesAmount": 3578.2700,
            "TaxAmt": 286.2616,
            "Freight": 89.4568,
            "CarrierTrackingNumber": null,
            "CustomerPONumber": null,
            "OrderDate": "2005-07-12T00:00:00Z",

**Comment by julealgon** [comment]
@bonfi7 can you elaborate why you closed this one?

**Comment by bonfi7** [comment]
> @bonfi7 can you elaborate why you closed this one?

Hi @julealgon,
Just because i had found this https://github.com/OData/AspNetCoreOData/issues/457 and I think the fix cause my problem…so my problem is not an issue but defenetly the correct behaviour 😅
