### ISSUE TITLE
Inconsistent application of [IgnoreDataMember]

### ISSUE THREAD

**Issue by kjkrum** [OData/AspNetCoreOData#615]
This issue is two things: a critique of the intended behavior, and an inconsistency in the intended behavior (i.e., a bug).

It's suggested [here](https://github.com/OData/AspNetCoreOData/issues/448#issuecomment-1016966525) that if you use *any* explicit model configuration, the model builder ignores *all* conventional model configuration. I found that comment after noticing that the serializer respects `[IgnoreDataMember]` when using conventional routing but ignores `[IgnoreDataMember]` and serializes the properties when using attribute routing. IMO, this violates the principle of least astonishment and is a misapplication/overreach of the intended behavior of ignoring conventions when anything is configured explicitly.

The bug is that the entity schema still includes properties annotated with `[IgnoreDataMember]` even when the controller using conventional routing correctly does not return those properties.

**Comment by julealgon** [comment]
> I found that comment after noticing that the serializer respects `[IgnoreDataMember]` when using conventional routing but ignores `[IgnoreDataMember]` and serializes the properties when using attribute routing.

Are you really sure that's the case? Are you sure your attribute routes are being detected as actual OData routes and not as standard MVC routes, and that's why the data attributes are ignored (different serializer)?

**Comment by kjkrum** [comment]
@julealgon I may be using the terminology incorrectly. By conventional routing, I mean annotating a controller action with `[HttpGet]`. By attribute routing, I mean changing it to `[HttpGet("/some/route")]`. With no other changes to the project, this causes `[IgnoreDataMember]` to be ignored.

But it's only my opinion that there's anything wrong with that. The clearer issue is that `[IgnoreDataMember]` is *always* ignored in the schema. In other words, with `[HttpGet]`, the schema doesn't match what is returned by the controller action.

**Comment by kjkrum** [comment]
Narrowing it further...

`[IgnoreDataMember]` respected:

```C#
		[HttpGet]
		[ProducesResponseType(typeof(IQueryable<User>), 200)]
		public IActionResult Get()
		{
			return Ok(_db.Users);
		}
```


`[IgnoreDataMember]` not respected:

```C#
		[HttpGet("/some/route")]
		[ProducesResponseType(typeof(IQueryable<User>), 200)]
		public IActionResult Get()
		{
			return Ok(_db.Users);
		}
```


`[IgnoreDataMember]` also not respected:

```C#
		[HttpGet]
		public IQueryable<User> Get()
		{
			return _db.Users;
		}
```

**Comment by kjkrum** [comment]
With conventional routing, the schema and the action responses seem to use entirely different serializers. Look at the case of the property names:

![SchemaResponseDifferences](https://user-images.githubusercontent.com/1007080/172472924-e79e0ec3-c5c7-45b8-9a13-de2aec255878.png)

**Comment by julealgon** [comment]
> @julealgon I may be using the terminology incorrectly. By conventional routing, I mean annotating a controller action with `[HttpGet]`. By attribute routing, I mean changing it to `[HttpGet("/some/route")]`. With no other changes to the project, this causes `[IgnoreDataMember]` to be ignored.

I know what you meant. Did you check the odata debug endpoint between these changes to ensure your routes were still actual OData routes though?

The change in serializer would immediately point to a change between OData and MVC to me. I just want to make sure you are not wasting time making invalid comparisons thinking that what you are seeing is still OData.

**Comment by kjkrum** [comment]
You're right, it's not an OData route. So if `ODataRouteAttribute` no longer exists, and `[HttpGet("/some/path")]` changes the route to an MVC route, does that mean there's no such thing as attribute routing in 8.x?

**Comment by kjkrum** [comment]
Thanks for the clues. I achieved what I wanted with attribute routing after putting together bits and pieces from this conversation and a couple blog posts and videos.

- get actions MUST be named Get when using conventional routing
- routes specified in attribute routing MUST be the routes that conventional routing would have created, or they change into plain MVC routes
- get actions MUST NOT be named Get when using attribute routing, or conventional routing will create duplicates and the Swagger UI won't like it
- unlike conventional routing, attribute routing does NOT automatically create the $count segment route

```C#
[HttpGet("odata/Users")]
[HttpGet("odata/Users/$count")]
[EnableQuery]
public IActionResult GetList()
{
	return Ok(_db.Users);
}

[HttpGet("odata/Users/{userId}")]
[EnableQuery]
public IActionResult GetById(int userId)
{
	var user = _db.Users.FirstOrDefault(o => o.UserId == userId);
	return user != null ? Ok(user) : NotFound();
}
```

I never did figure out how to get conventional routing to create routes with parameters like entity ID. And the reason my schema didn't match my action responses is that `[ProducesResponseType]` is strictly an MVC thing, unnecessary and possibly wrong to use with OData.

**Comment by julealgon** [comment]
> * routes specified in attribute routing MUST be the routes that conventional routing would have created, or they change into plain MVC routes

This is probably the key statement. If you have any route that doesn't properly match an entityset or a bound action/function, then OData will basically "ignore" that route and it will surface as a standard MVC route. Since OData and MVC uses different serialization rules (a nasty thing IMHO that I hope will change in the future) we see all these discrepancies.

I'm glad you god it resolved on your end and that I could be of any help.

**Comment by kjkrum** [comment]
I wonder if we could leverage routing conventions to detect that scenario and emit a warning or error.

**Comment by julealgon** [comment]
> I wonder if we could leverage routing conventions to detect that scenario and emit a warning or error.

It's hard to say, because OData was conceived in a way as to allow a mix or OData and non-OData routes in the same controllers. It would be a bit difficult to differentiate actual mistakes from intentional non-OData routes.

Forcing all routes in a `ODataController` inherited controller to be actual OData routes could potentially work, but I'm not sure the team would be willing to go with that.
