### ISSUE TITLE
Unable to build on OData 7.5.15

### ISSUE THREAD

**Issue by ysefwakil** [OData/AspNetCoreOData#618]
Hi there, I am trying to build my project using OData 7.5.15 however I get the following error:
![image](https://user-images.githubusercontent.com/48973627/173259704-520d48ef-ca30-4c2f-a1a5-0f61ae934350.png)

I am able to run it on versions OData 7.5.5 as well as 7.5.8 however anything from 7.5.10 -7.5.15 returns me that error

Thanks

**Comment by julealgon** [comment]
Try removing the explicit `<PackageReference>` to `Microsoft.OData.Edm` (or `Microsoft.OData.Core`) from your project: it should be picked up automatically by the parent package.

If that doesn't work, please post your csproj here for reference.

**Comment by ysefwakil** [comment]
I don't have any packagereference to Microsoft.Odata.Edm or Microsoft.odata.core all i have is:

<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.5.15" />

**Comment by xuzhg** [comment]
> Can you share the contents of your csproj file @ysefwakil ?

+1

**Comment by xuzhg** [comment]
[ysefwakil](https://github.com/ysefwakil) 

Microsoft.AspNetCore.OData 7.5.15 updates the dependency version for OData.Edm from 7.10.0 to 7.11.0; See https://github.com/OData/WebApi/releases/tag/7.5.15.

Could you do:
1) Do 'Clean/Rebuild All' in the Visual Studio
2) If it can't work, can you check any other projects depending on your solution to see whether there's any project referencing 7.10.0?
3) Simply update the OData.Edm, OData.Core to 7.11.0 in your project to see whether it can work or not.

If can't work and need remotely help, you can setup a remote call to me.

**Comment by ysefwakil** [comment]
Would this be a problem if running on .Net 6.0 or would I have to use Odata 8.0.10?

**Comment by julealgon** [comment]
@ysefwakil do you want to share what fixed the issue for you (I assume it was fixed since you closed the ticket)? Could be useful for others having the same problem.

**Comment by ysefwakil** [comment]
Fixed from the suggestion given above, clean/Rebuild all :)

Thank you!
