### ISSUE TITLE
/$batch query breaks when async in use. Throws "Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead."

### ISSUE THREAD

**Issue by lukred** [OData/AspNetCoreOData#624]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.10

**Describe the bug**
We are using /$batch queries.
When our service was refactored to be fully async (from the root controllers all the way to the database), the /$batch queries stopped working.
It was weird exception:
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)

Only adding below code solved the problem:
 services.Configure<KestrelServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });

**Reproduce steps**
Simplest /$batch query failed when controllers were async.
It worked on IIS, but did not work on Generic Host (Kestrel)

**Expected behavior**
Batch Handler should work fine with async API 

**Additional context**

https://khalidabuhakmeh.com/dotnet-core-3-dot-0-allowsynchronousio-workaround

**Comment by habbes** [comment]
Hi @lukred There's a similar issue reported here: https://github.com/OData/odata.net/issues/2441, I wonder whether they are related. What version of Microsoft.OData.Core are you referencing?

**Comment by lukred** [comment]
Microsoft.OData.Core 7.11.0
