### ISSUE TITLE
getting-related-entities convention failed when using multiple words as NavigationPropertyBinding if EnableLowerCamelCase()

### ISSUE THREAD

**Issue by sep2** [OData/AspNetCoreOData#626]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.10

**Describe the bug**
when `EnableLowerCamelCase()` is enabled, the controller method described [here](
https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/entity-relations-in-odata-v4#getting-related-entities) will not be hit if the property name of the entity model consists of two words: `OwnedEvents`.(It doesn't matter what the controller handler name is, I tried the `GetOwnedEvents` / `GetownedEvents` / `Getownedevents` / `GetOwnedevents` with no luck) if the property name is only one word then it is okay by using this technique https://github.com/OData/AspNetCoreOData/issues/563.

**Data Model**
```c#
public class User
{
    public Guid Id { get; set; }

    // this cannot be mapped to an odata controller endpoint no matter what the method name is
    public List<Event> OwnedEvents { get; set; } = new();

    // this can be mapped to `getevents` by https://github.com/OData/AspNetCoreOData/issues/563
    public List<Event> Events { get; set; } = new();
}

public class Event
{
    public Guid Id { get; set; }

    public Guid OwnerId { get; set; }
    public User Owner { get; set; } = null!;
}
```

**Expected behavior**
Entity model property name casing should not affect the odata controllers.

**Comment by KenitoInc** [comment]
@sep2 
I took your repro in #563 and modified as follows

Model
```csharp
public class Event
{
    public int Id { get; set; }
    public List<Activity> Activities { get; set; } = new();

    [Contained]
    public List<User> OwnedUsers { get; set; } = new();
}

public class Activity
{
    public int Id { get; set; }
}

public class User
{
    public int Id { get; set; }
}
```

Controller
```csharp
[EnableQuery]
public IQueryable<User> GetownedUsers(int key)
{
    return _event.OwnedUsers.AsQueryable();
}
```

I could hit the controller when I invoke `GET https://localhost:7079/api/odata/Events(1)/ownedUsers`
![GetOwnedUsers](https://user-images.githubusercontent.com/7702964/176134824-1f5a893d-f92c-4aff-958f-91a5b4e850d0.PNG)

**Comment by sep2** [comment]
`[Contained]` did the trick, thanks!
