### ISSUE TITLE
UTF-8 BOM is added to raw value response when running on ASP .NET Core 3+

### ISSUE THREAD

**Issue by VirusQuartirus** [OData/AspNetCoreOData#628]
**Assemblies affected**
ASP.NET Core OData 7.x

**Describe the bug**
When client sends request that expects raw value to be returned ($count for example) and doesn't specify `Accept-Charset` header UTF-8 BOM is written prior to content and `Content-Type: text/plain`. This happens when application is built using ASP .NET Core ~~5+~~ 3+.

**Reproduce steps**
See attached Fiddler logs.

**Possible solution**
It looks like ASP .NET Core 5 changed behavior of `Microsoft.AspNetCore.Http.Headers.RequestHeaders` class and now properties like ~~AcceptEncoding~~ `AcceptCharset` return empty collection instead of null value. It looks like it may be fixed in `ODataOutputFormatter.WriteResponseHeaders` change current line
```csharp
if (requestHeader != null && requestHeader.AcceptCharset != null)
```
to
```csharp
if (requestHeader?.AcceptCharset?.Count > 0)
```

[FiddlerLogs.zip](https://github.com/OData/AspNetCoreOData/files/8986854/FiddlerLogs.zip)

**Comment by julealgon** [comment]
The change in behavior you describe seems to indeed exist:
- https://github.com/dotnet/aspnetcore/pull/10972

However, it appears to have been made in AspNetCore 3. You sure this only happens in 5+?

Also, you mention `AcceptEncoding` but then add code that mentions `AcceptCharset`. Was that intentional?

For future reference, actual link:

https://github.com/OData/AspNetCoreOData/blob/69eec03c7003fe12d92cdc619efdc16781683694/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs#L197-L207

**Comment by VirusQuartirus** [comment]
> However, it appears to have been made in AspNetCore 3. You sure this only happens in 5+?
Indeed, 3.x also suffers from this issue.


> Also, you mention `AcceptEncoding` but then add code that mentions `AcceptCharset`. Was that intentional?
Just a typo.

**Comment by VirusQuartirus** [comment]
> @VirusQuartirus We welcome contributions. We will be happy to review your PR.

I don't have write permissions to this repo.

**Comment by julealgon** [comment]
> I don't have write permissions to this repo.

That's usually how it works with public repositories. You don't create branches directly in the target repo: instead, you fork the repository to your account, make your branch and changes there, and then submit a pull request to the target repo from your fork.

This flow doesn't require you any kind of write permission on the target repo.
