### ISSUE TITLE
Dynamic OData 

### ISSUE THREAD

**Issue by fabiocbr75** [OData/AspNetCoreOData#636]
Hello,
I need to create an OData endpoint dynamically.
I see that there are two possibilities:

- https://github.com/microsoft/dynamic-odata
- https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataDynamicModel

I don't understand what are the differences between the two projects and what is the best way to perform my job.
Can you help me to understand the difference?

Regards

**Comment by julealgon** [comment]
This should be moved to discussions.

@fabiocbr75 , whenever you intend to ask a question in a new repo, please double check if the repo has the 'Discussions' feature enabled first. If so, its best to use that part of the repo for this type of question.
