### ISSUE TITLE
Execute $apply on function result

### ISSUE THREAD

**Issue by ramil-mux** [OData/AspNetCoreOData#654]
Hello!
I am trying to execute $apply after OData function. Does OData have such capabilities? Use Microsoft.AspNetCore.OData 8.0.10

### Example
I have next GetEdmModel function

            var builder = new ODataConventionModelBuilder();

            builder.EntitySet<TrainListResponse>("Trains").EntityType.HasKey(x => x.Id);

            var trainFunction = builder.EntityType<TrainListResponse>()
                .Collection
                .Function("FindTrainsBy")
                .ReturnsCollectionFromEntitySet<TrainListResponse>("Trains");
            trainFunction.Parameter<string>("originCode");
            trainFunction.Parameter<string>("destinationCode");
            trainFunction.Parameter<DateTime>("dateFrom");
            trainFunction.Parameter<DateTime>("dateTo");

Have controller method

        [EnableQuery]
        [HttpGet("FindTrainsBy(originCode={originCode}, destinationCode={destinationCode}, dateFrom={dateFrom:datetime}, dateTo={dateTo:datetime})")]
        public async Task<IEnumerable<TrainListResponse>> FindTrainsBy(string originCode, string destinationCode, DateTime dateFrom, DateTime dateTo)
        {
            return await _trainsFinder.FindAsync(originCode, destinationCode, dateFrom, dateTo);
        }

And try execute this HTTP GET query

http://localhost:5000/odata/Trains/FindTrainsBy(originCode='2000000',destinationCode='2004000',dateFrom=2022-07-01,dateTo=2022-07-03)?$apply=grouby((DestinationName))

After execution I have exception:
_"The query specified in the URI is not valid. 'aggregate|filter|groupby|compute|expand' expected at position 0 in 'grouby((DestinationName))'."_

I was thinking that the FindTrainsBy function returns the same data structure as the TrainListResponse endpoint - the TrainListResponse list. And thought that $apply could be right after the FindTrainsBy function.

**Comment by julealgon** [comment]
> I was thinking that the FindTrainsBy function returns the same data structure as the TrainListResponse endpoint - the TrainListResponse list. And thought that $apply could be right after the FindTrainsBy function.

Does it work if you remove your custom function call?

**Comment by ramil-mux** [comment]
Yes, it works

**Comment by julealgon** [comment]
Can you please try to set the `IsComposable` property on the function definition to `true` and see if that changes your results?

**Comment by xuzhg** [comment]
@ramil-mux the error message says there's a typo. not 'grouby', but 'groupby'. Can you try and let us know the result?

**Comment by ramil-mux** [comment]
@xuzhg @julealgon Sorry for the long wait. Yes, the error has disappeared, but I haven't done a thorough research yet

**Comment by habbes** [comment]
Seems like that issue was resolve and related to a typo so I will go ahead and close the issue. If there's another concern, feel free to open a new issue.

**Comment by ramil-mux** [comment]
@xuzhg @julealgon Good afternoon! Thank you for your help everything is working.
