### ISSUE TITLE
Expose ability to over-control complex property serialization

### ISSUE THREAD

**Issue by xuzhg** [OData/AspNetCoreOData#658]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**
Recently, We have had customers who want to omit the null complex property.

So far, we don't have a better for them to omit null complex property. As a workaround, they have to override the "CreateSelectExpandNode" virtual method to change the "SelectExpandNode" returns from this method.

This is ugly because "SelectExpandNode" is an "entity scope" object used to control all entities' serialization for the same type.

So, we'd like to have a better "overridable" method for customers to use to control the serialization of the complex.

**Comment by corranrogue9** [comment]
We need to make sure that the client can handle these responses before supporting this on the service side.

**Comment by chrisspre** [comment]
see #657

**Comment by corranrogue9** [comment]
Can we make sure to also create the other issues where needed?

**Comment by xuzhg** [comment]
created a separate issue for omit-values prefer header at server side, see details at: https://github.com/OData/AspNetCoreOData/issues/672
