### ISSUE TITLE
samples target dot net 5 not 6 - update them ?

### ISSUE THREAD

**Issue by figuerres** [OData/AspNetCoreOData#661]
**Assemblies affected**
 ?

**Describe the bug**
samples are targeting dot net 5 not 6

**Reproduce steps**
downloaded and copied the odataopenapi routing sample and try to use it... got warning that it was targeting the old version

trying to determine the best setup for a project using the new odata and swagger .... seems like the sample needs to be updated?

**Comment by xuzhg** [comment]
There was no .NET 6 when I built the sample. I still can't fully understand the "guides" about the updating.
I mean "shall we always update the dependency to the latest version?" 
@figuerres @julealgon anyone can point me to an "official" docs about this?

**Comment by julealgon** [comment]
> @figuerres @julealgon anyone can point me to an "official" docs about this?

Not exactly sure which docs you are after Sam. Can you elaborate?

I think the biggest issue on this one is that we are using an out of support framework on something that will most likely serve as templates to people. It is very likely (and even expected) that people will start uninstalling .NET5 support in their local tools (so they won't even be able to open and build the project) and having a legacy framework in a template will also invariably lead other less tech savvy folks into creating unsupported projects on their side as well based on the examples.

> I mean "shall we always update the dependency to the latest version?"

If you mean using the latest versions of OData itself and other packages in the samples, my vote would be absolutely. Again, people will likely use these example projects as references, as "sources of truth". The more updated they are, the less chance that we see bugs being reported that have already been fixed etc.

IMHO these samples should be treated as production code that needs constant maintenance.

Now... I know this requires a lot of effort, but that's a separate discussion.

**Comment by xuzhg** [comment]
@julealgon Since .net 5 is out of support, shall we remove it from the product package?

Since removing a target framework is a breaking change, right? We should update the version to 9? But, I don't want to update the version to 9. Maybe it's time to move on 8.1.

**Comment by julealgon** [comment]
> @julealgon Since .net 5 is out of support, shall we remove it from the product package?

That would be the way to go IMHO.

> Since removing a target framework is a breaking change, right? We should update the version to 9? 

Actually, I'm not so sure... since folks using NET5 wouldn't be able to consume the new package, it wouldn't be breaking for them. At the same time, other people wouldn't experience any breaking changes either.

I feel like this is not a breaking change at all really.

**Comment by robertmclaws** [comment]
Going to 8.1 for this is probably warranted. it's not a breaking change, but it's a big enough change that it should not be hidden inside a point release.
