### ISSUE TITLE
Multiple Edm in separate project

### ISSUE THREAD

**Issue by datnt97** [OData/AspNetCoreOData#680]
Hi, I have a problem with OData. In case 1, I configure odata in one place and it works. Case 2, I try to add new Edm throught `AddRouteComponents` because I have some modules what can active later.

```cs
// Case 1: Work
services.AddControllers().AddOData(opts =>
{
	opts
		.EnableQueryFeatures(50)
		.AddRouteComponents("odata_products", GetEdmModel(), s => s.AddSingleton<ODataBatchHandler, DefaultODataBatchHandler>())
		.Conventions.Add(new BaseConvention());
});

// Case 2: Doesn't work
var odataOptions = serviceProvider.GetRequiredService<IOptions<ODataOptions>>();
odataOptions.Value.AddRouteComponents("odata_products", GetEdmModel(), s => s.AddSingleton<ODataBatchHandler, DefaultODataBatchHandler>());
```

Hope this helps! Please!

**Comment by julealgon** [comment]
@datnt97 this is not how you configure existing options objects in the options framework. What you are doing there is just modifying a local copy of the `ODataOptions` that is not used later.

To configure an existing options, please use something such as the `IConfigureOptions` interface or the `.Configure` methods on `IServiceCollection`.

Note that both approaches support dependency injection, so you can inject whatever you need to perform the configuration there.

Also, this should be moved to discussions.

**Comment by datnt97** [comment]
> Also, this should be moved to discussions.

I've already read the document [here](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion). But I can't see any 'Convert to discussions'. Sorry about my silly

**Comment by gathogojr** [comment]
@datnt97 Did you try the suggestions by @julealgon? Did either of the suggestions work?

**Comment by datnt97** [comment]
I try this. It works.
```cs
// Main module
services.AddControllers()
	.AddOData(opts =>
	{
		opts.EnableQueryFeatures(50);
	});

// Other module
services.Configure<ODataOptions>(config =>
{
	config.AddRouteComponents("odata_products", GetEdmModel(), new DefaultODataBatchHandler());
});
```

**Comment by gathogojr** [comment]
Proposed solution works
