### ISSUE TITLE
https://github.com/OData/AspNetCoreOData/pull/623/commits  (SHA 75833e2e8dbb66a81aa2a682fc4543cc8c031e8a ) introduces a breaking change.

### ISSUE THREAD

**Issue by garegina** [OData/AspNetCoreOData#699]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**

**Reproduce steps**
In your controller method, try to return this code when you want to generate 404 error with your custom error code.

  **return NotFound(
  new OData.ODataError()
  {
  ErrorCode = "ErrorEntityNotFound",
  Message = "The specified entity was not found."
  });**

**Data Model**
Please share your Data model, for example, your C# class.

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Request/Response**
The code above currently fails with validation, the asp.net code odata 8.0.11 now expects that odata.error.code in this case must be "404", while before it could be any user defined string.

**Expected behavior**
As documented in OData spec, odata error's code can be a language-independent string.
9.4 [Error Response Body](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ErrorResponseBody)
The representation of an error response body is format-specific. It consists at least of the following information:

·         code: required non-null, non-empty, language-independent string. Its value is a service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.

·         message: required non-null, non-empty, language-dependent, human-readable string describing the error. The [Content-Language](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_HeaderContentLanguage) header MUST contain the language code from [[RFC5646]](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#rfc5646) corresponding to the language in which the value for message is written.

·         target: optional nullable, potentially empty string indicating the target of the error, for example, the name of the property in error.

·         details: optional, potentially empty collection of structured instances with code, message, and target following the rules above.

·         innererror: optional structured instance with service-defined content.

**Screenshots**

**Additional context**
Please share your call stack or any error message

**Comment by KenitoInc** [comment]
Fixed by https://github.com/OData/AspNetCoreOData/pull/700
