### ISSUE TITLE
Updating ODataSamples for creating dynamically EDM models

### ISSUE THREAD

**Issue by maikelvanhaaren** [OData/AspNetCoreOData#70]
There is a great sample which shows how to dynamically create an EDM model and bind it into OData pipeline for an older version. Can this sample (and the others) be updated and included in this project? It will help me and alot of other people to understand the new version.

**Comment by xuzhg** [comment]
@LeonardSpencer would you please share more about your requirement about dynamically create an Edm model?

**Comment by LeonardSpencer** [comment]
We created a datamanager system where the user can create own entities with properties attached (like the entity Car with a licence year, brand etc.). I want to expose this data with ODATA. I need the EDM model and endpoints created at runtime for the user.

**Comment by donta** [comment]
I'm very interested in this as well. Our project will need to load a dynamic EDM model depending the particular access users have to database. A sister system will allow users to select which parts of the database they require and the access will be approved by a review board. Once approved, the user would hit the OData endpoints and we hope to build the model(according to their approved permissions) via a route attribute or a value passed via the Authorization header. The system needs to allow new users to be added daily so we need a dynamic solution.

**Comment by AntonioSCoelho** [comment]
I'm very interested in this as well. Something like this sample [DynamicEdmModelCreation](https://github.com/OData/ODataSamples/tree/master/WebApiCore/DynamicEdmModelCreation).

**Comment by adrua** [comment]
Hi, OData Team

Thanks for your work. 

Please help $Filter don't works.

**Comment by xuzhg** [comment]
@AntonioSCoelho you can find the sample at:  https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataDynamicModel

@adrua Would you please share more details about "$filter doesn't work"? Can you file a new issue with that?
