### ISSUE TITLE
PageResult  items,nextpagelink and count are no longer returning after migrating to Net6 and upgrading to 8.0.11

### ISSUE THREAD

**Issue by ramaseshulukka** [OData/AspNetCoreOData#739]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**
PageResult  items,nextpagelink and count are no longer returning after migrating to Net6 and upgrading to 8.0.11

**Reproduce steps**
Have below code to generate page result  to get below expected result but i am getting below  current result. Client using this end point is breaking as there are no items,nextpagelink and count available after upgrading the framework to net6 and odata to 8.0.11

Expected Result : 

{
"items":    [
           {"id":6975,"name":"Dummy Value","phone":"999999999","fax":null,"address":"Dummy street","city":"Some","state":"some","zipCode":"99999","countryId":1}],
"nextPageLink":"/Vendors?$filter=zipCode%20eq%20%2785022%27&$orderby=name%20asc&$skip=50",
"count":null
}

Current Result :
{
    "@odata.context": "http://localhost:8080/$metadata#Vendors",
    "value":
[
    {
        "id": 6975,
        "name": "Dummy Value",
        "phone": "999999999",
        "fax": null,
        "address": "Dummy",
        "city": "Some",
        "state": "Some",
        "zipCode": "99999",
        "countryId": 1
    }
],
 "@odata.nextLink": "/Vendors?$filter=zipCode%20eq%20%2799999%27&$orderby=name%20asc&$skip=50"

Controller Code:

![image](https://user-images.githubusercontent.com/20219224/200058016-4f5f49c4-03d5-406c-a9d8-9ed3b2e675b7.png)

Start up.cs :

![image](https://user-images.githubusercontent.com/20219224/200056780-6161ebf7-2ff0-420d-baed-2e2c875fb78d.png)

**Comment by ramaseshulukka** [comment]
I am able to fix this by using controller instead of odatacontroller and also using below JPageresultvalueconverter by calling it from startup.cs as below


https://github.com/OData/AspNetCoreOData/blob/69eec03c7003fe12d92cdc619efdc16781683694/src/Microsoft.AspNetCore.OData.NewtonsoftJson/JPageResultValueConverter.cs


statup.cs :
![image](https://user-images.githubusercontent.com/20219224/200129367-e813c9a4-86d5-4660-b6f8-7f0ee7956f31.png)

**Comment by anzeha** [comment]
I faced the same problem, and noticed that `JPageResultValueConverter` in an internal class of `Microsoft.AspNetCore.OData.NewtonsoftJson` and therefore is not accessible the way you used it in your code screenshot posted. Did you just implement the converter in your own class based on `JPageResultValueConverter`, or is there another workaround?
