### ISSUE TITLE
QueryContext not passed to nested ODataSerializerContext

### ISSUE THREAD

**Issue by uffelauesen** [OData/AspNetCoreOData#758]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.x

**Describe the bug**
Custom SkipTokenHandler is not called for expanded entity collections.

**Reproduce steps**
Implement a custom SkipTokenHandler and do a query with an expand of a collection.
Expected: The SkipTokenHandler is invoked for both the top level resource set and the expanded child collection resource set.
Actual: It is only invoked for the top level resource set.

**Data Model**
With the TripPin model it could be reproduced with the query: /People?$expand=Friends 

**EDM (CSDL) Model**

**Request/Response**
Request /People?$expand=Friends 
Will only have nextLinks generated by the custom SkipTokenHandler for People. The nextLinks for Friends will either be missing or generated by the DefaultSkipTokenHandler.

**Expected behavior**
Both nextLinks should be generated by my custom SkipTokenHandler.

**Screenshots**

**Additional context**
The code for getting this to work as expected is actually in the ODataResourceSerializer.cs source files but has been commented out.
ODataSerializerContext nestedWriteContext = new ODataSerializerContext(resourceContext, edmProperty, null /*resourceContext.SerializerContext.QueryContext*/, selectItem);

**Comment by ElizabethOkerio** [comment]
TODO: Find out why the code was commented and what the effects of uncommenting it will be.
