### ISSUE TITLE
SetTimeZoneInfo(TimeZoneInfo.Utc) seems to not work using 8.0.0-preview3

### ISSUE THREAD

**Issue by XzaR90** [OData/AspNetCoreOData#78]
I add SetTimeZoneInfo(TimeZoneInfo.Utc) in AddOdata -> options.
But it seems like it does not work, the datetime is printed with local timezone.

Actual: "2021-01-25T13:00:00.99999+01:00"
Excepted: "2021-01-25T12:00:00.99999Z" or should it be 13:00?

I am using Net5.0

https://github.com/OData/AspNetCoreOData/commit/2864bf9610b8e9c1907814e7c9c4673fcb3c5761?branch=2864bf9610b8e9c1907814e7c9c4673fcb3c5761&diff=unified ?

**Comment by xuzhg** [comment]
@XzaR90 Would you please share a simple repro?

**Comment by XzaR90** [comment]
Hello again, here is a example.

https://github.com/XzaR90/OdataNet5DateTime/tree/main/OdataNet5DateTime

**Comment by xuzhg** [comment]
@XzaR90 Thanks for your repro. I found a bug in the code and fixed it in https://github.com/OData/AspNetCoreOData/commit/874f9f822672aa1320dc8aa89033e23011338adf.

I tested it with the latest nightly version, 

![image](https://user-images.githubusercontent.com/9426627/105892577-e7ad7500-5fc6-11eb-837e-d1e7e2a67a81.png)

and I got the following response:

![image](https://user-images.githubusercontent.com/9426627/105892526-d6fcff00-5fc6-11eb-9496-d0d7595c97eb.png)


I will release a beta version soon to include this fix. 
If you are interested in the nightly, you can use the following feed to try the preview version. 
**Be noted** Remember to click the "Include prerelease"

![image](https://user-images.githubusercontent.com/9426627/105892714-188daa00-5fc7-11eb-89b7-40cf29af14d9.png)

**Comment by XzaR90** [comment]
Great, thank you. I will use the nightly build. 😄

**Comment by xuzhg** [comment]
That's fixed in beta version. Close it.
