### ISSUE TITLE
OData action throwing unexpected key value error

### ISSUE THREAD

**Issue by gordon-matt** [OData/AspNetCoreOData#790]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.11

**Describe the bug**
OData action throwing the following error:

```
Microsoft.OData.ODataException: The key value (Default.GetComparitiveTable(cultureCode='en-US')) from request is not valid. The key value should be format of type 'Edm.Guid'.
```

**Reproduce steps**
I have created a small app to demo the issue. You can find it here: [ODataActionKeyValueFormatError](https://github.com/gordon-matt/ODataActionKeyValueFormatError). Run that and navigate to **/odata/LocalizableStringApi/Default.GetComparitiveTable('en-US')** to see the issue.

**Data Model**
It's in the demo.

**Request/Response**
Navigate to **/odata/LocalizableStringApi/Default.GetComparitiveTable('en-US')** as mentioned above.

**Expected behavior**
I would expect it to successfully return the data, not throw the aforementioned error.

**Screenshots**

![Error](https://user-images.githubusercontent.com/2860937/209487204-a1511acc-9d7e-4ff8-ac07-f7c2ab7e17e8.PNG)

**Additional context**
I have been using OData since MVC5 and this particular OData action for about that long as well.. I've had no issue with it for all these years, but one of 2 things must be causing the issue:

1. Either it's due to the new version of OData
2. .. or somehow using Blazor instead of MVC (which is what I was using until now) is causing the issue.

I figure number 2 is unlikely, but mentioning it anyway, as it's still something different compared to before.

**Comment by julealgon** [comment]
Add `[HttpGet]` to your `GetComparitiveTable` method.

I wish OData would throw exceptions instead of "silently failing to match" like this...

If something is defined in the EDM but is missing from the controller, an exception should be thrown indicating why.
