### ISSUE TITLE
Request path segments gets double unescaped

### ISSUE THREAD

**Issue by uffelauesen** [OData/AspNetCoreOData#796]
**Assemblies affected**
ASP.NET Core OData 8.x

**Describe the bug**
ASP.NET Core has Request.Path unencoded already. ODL will also unencode path part. This results in double unencoded path parts.

**Reproduce steps**
In project ODataAlternateKeySample modify the AlternateKeyRepositoryInMemory, changing the format of Customer.SSN property value...

From:
                SSN = "SSN-" + e + "-" + (100 + e),

To:
                SSN = "SSN-%25-" + e + "-" + (100 + e),

Running the sample it should be possible to get the customer "Tom" by alternate key with single correct client encoding of % like...
**http://localhost:5219/odata/Customers(SSN='SSN-%2525-1-101')**

But it doesn't work as it get unencode twice in the service (once by ASP.NET Core and once by ODL) leaving the SSN value that a searched for in the in memory repository like 'SSN-%-1-101' instead of the correct 'SSN-%25-1-101'. Customer "Tom" is not found.

Doing it as $filter does however work correctly. The following query will find Customer 'Tom'...
**http://localhost:5219/odata/Customers?$filter=SSN%20eq%20'SSN-%2525-1-101'**

So the issue appears to be related to the Path part only.

The odata.id, odata.readLink, odata.editLink and all odata.associationLink and odata.navigationLink also seems wrong - they have lost one encoding (if the actual key were a string with values like this).

**Data Model**
Use ODataAlternateKeySample

**EDM (CSDL) Model**
Use ODataAlternateKeySample

**Request/Response**
See repro steps.

**Expected behavior**
It should be possible to get "Tom" by alternate key 'SSN-%25-1-101'

**Screenshots**

**Additional context**
"Tom" can be found by alternate key if we do double encoding on client (which no Client will do)...
**http://localhost:5219/odata/Customers(SSN='SSN-%252525-1-101'**

**Comment by xuzhg** [comment]
https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs#L199

**Comment by xuzhg** [comment]
@uffelauesen I tested as follows:

## http://localhost:5219/odata/Customers(SSN='SSN-%-1-101')

<img width="494" alt="image" src="https://user-images.githubusercontent.com/9426627/211924494-28a6def3-23e9-41e7-8f27-ab2cfd8f0119.png">


## http://localhost:5219/odata/Customers(SSN='SSN-%25-1-101')
<img width="501" alt="image" src="https://user-images.githubusercontent.com/9426627/211924375-510609da-150b-42ec-8267-14206a252df1.png">

## http://localhost:5219/odata/Customers(SSN='SSN-%2525-1-101')
<img width="481" alt="image" src="https://user-images.githubusercontent.com/9426627/211924572-89201a80-f6de-4ab9-a80a-ce946a8e2329.png">

## http://localhost:5219/odata/Customers(SSN='SSN-%252525-1-101')

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/9426627/211924737-daeb8585-1b1f-48fe-a48b-e4c4d14e6f7f.png">

**Comment by uffelauesen** [comment]
@xuzhg Thanks for digging into this. I have made a mistake in my bug description of the code change you need to do for this to match with what I write following. In AlternateKeyRepositoryInMemory you need to change the line like this...

From:
`SSN = "SSN-" + e + "-" + (100 + e),`

To:
`SSN = "SSN-%25-" + e + "-" + (100 + e),`

I have updated the bug description to reflect this. Sorry for the mistake.

**Comment by xuzhg** [comment]
@uffelauesen I see. I have a fix for that. Please take review at #806.

The following requests return 'Not-Found'.

- http://localhost:5219/odata/Customers(SSN='SSN-%-2-102')
- http://localhost:5219/odata/Customers(SSN='SSN-%25-2-102')
- http://localhost:5219/odata/Customers(SSN='SSN-%252525-2-102')

The following request returns the correct data: (I have updated the sample data generation)

<img width="486" alt="image" src="https://user-images.githubusercontent.com/9426627/212167726-258a723c-e75d-41d5-933c-5f32fdc5c733.png">

**Comment by uffelauesen** [comment]
@xuzhg Thanks. Your changes ito KeySegmentTemplate.cs fixes the issue I ran into.
Your changes to ODataTemplateTranslateContext.cs seems wrong to me. Query options are also escaped already.
I will expect to be able to find Tom using parameters with requests like this:

http://localhost:5219/odata/Customers(SSN=@a)?@a='SSN-%2525-1-101'
http://localhost:5219/odata/Customers(SSN=@a)?@a=%27SSN-%2525-1-101%27

But with your proposed changes to ODataTemplateTranslateContext.cs they fail as you now get the value double unencoded to 'SSN-%-1-101'.

**Comment by xuzhg** [comment]
@uffelauesen the query option part also unescaped already? We don't need to unescape it. 

I can't remember why I added "unescape" to it. But, I think it's related to escape/unescape. Is it related to any client?

**Comment by uffelauesen** [comment]
Correct it is unescaped already.

**Comment by xuzhg** [comment]
https://github.com/OData/AspNetCoreOData/commit/3c7e83f454709a3cd943b655f68da4261a1660fe

**Comment by xuzhg** [comment]
@uffelauesen I updated my PR. Now, 

[http://localhost:5219/odata/Customers(SSN=@a)?@a='SSN-%2525-1-101](http://localhost:5219/odata/Customers(SSN=@a)?@a=%27SSN-%2525-1-101)'
http://localhost:5219/odata/Customers(SSN=@a)?@a=%27SSN-%2525-1-101%27

Shold work. Let me know any result.

**Comment by uffelauesen** [comment]
Looks good to me.

Thanks for looking into this.
/uffe

**Comment by xuzhg** [comment]
More related: Because of https://github.com/dotnet/aspnetcore/issues/30655. %2F is special because un-escaping it would change the path segment boundaries.  From .NET team information, they are still trying to come up with a good solution, but for now let's replace %2F with '/' in route values.
