### ISSUE TITLE
Function & action endpoints have two templates instead of one

### ISSUE THREAD

**Issue by davidyee** [OData/AspNetCoreOData#80]
Hi Sam thanks for bringing the OData project to .NET 5.0. I've been trying the latest beta package out in a new project and noticed something which I believe is different in the endpoint behaviour of OData function and action definitions.

**Observed behaviour:**

- Functions and actions definitions cause two endpoints to be created now instead of one as it was in the former OData WebApi 7.x. The two endpoints are in the format of:
  1. `{namespace}.{function name}`
  2. `{function name}`

For example, the following shows up in the ODataRoutingSample project /$odata table for the `Product` collection `GetOptional` function:

Controller | Action | HttpMethods | Templates
-- | -- | -- | --
ODataRoutingSample.Controllers.ProductsController | String GetOptional() | GET | ~/Products/Default.GetOptional()
ODataRoutingSample.Controllers.ProductsController | String GetOptional() | GET | ~/Products/GetOptional()

**Expected behaviour:**

- I believe in the previous OData WebApi it was required that OData functions and actions followed the format of `{namespace}.{function name}` as per the [OData v4 specification](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752667). So in the above example I would have expected that there would only be this single endpoint available: `~/Products/Default.GetOptional()`

Can you please clarify if the above is expected behaviour and if so, if it is possible to use the former behaviour instead?

**Comment by xuzhg** [comment]
@davidyee 

That's expected by design. 
Since OData v4 spec says to call odata function/action using {namespace}.{functionName} pattern, more than 90% restful developer doesn't like this pattern. So, as default, I generate the two templates for one function/action call.

By the way, I am working a PR to provide routing options to let developer configure the output template.

**Comment by RobTF** [comment]
I like the current behavior as our API consumers would find it overly verbose to put `Default.` at the start of every name and we would only ever have one namespace anyway. Please leave as-is, or have a switch allowing the non-namespaced endpoints it to be switched on or off so it doesn't break existing consumers. Thanks!

**Comment by xuzhg** [comment]
@RobTF I have such functionality enabled, see sample codes at: https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Startup.cs#L65

And it should enable in 'Microsoft.AspNetCore.OData.8.0.0-Nightly202102051314.nupkg'

thanks, please let me know your result.

**Comment by RobTF** [comment]
wow excellent! In which case the answer to the original question from the OP is that those who don't like the unqualified names can just turn them off then I guess?

**Comment by xuzhg** [comment]
Now, you can use https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L91-L109 to control the route template. @RobTF @davidyee
