### ISSUE TITLE
MaxExpansionDepth not respected

### ISSUE THREAD

**Issue by Emp1Motus** [OData/AspNetCoreOData#809]
Assemblies affected:
ASP.NET Core OData 8.x

Describe the bug:
It seems the MaxExpansiondepth is ignored or not working correctly. 
Maybe we just misunderstood a concept.
But:
The url http://localhost:7026/ODataApi/ProjectTaskActivityODataApi in the given sample returns no customer details
but http://localhost:7026/ODataApi/ProjectTaskODataApi does.
We are wondering why the third level with customer details is cut off when  calling the ProjectTaskActivityODataApi .

Expected behavior:
The call to http://localhost:7026/ODataApi/ProjectTaskActivityODataApi returns Customer details.

Question:
Is there an error in our EDM model ?
Is this a bug?

[OdataSample.zip](https://github.com/OData/AspNetCoreOData/files/10427275/OdataSample.zip)

**Comment by julealgon** [comment]
Please rename your issue title to something more specific. It should provide enough information so that it avoids the need to actually open the issue to know what exactly it is you are talking about.

Additionally, for these types of questions, it is better to rely on the "Discussions" section for github repos that have that functionality enabled. It seems like what you are asking would be better as an actual "Question" there instead of an issue.

**Comment by julealgon** [comment]
> It seems the MaxExpansiondepth is ignored or not working correctly.

That setting controls what the user can ask, not the actual default value. The default expansion depth value is always 2.

You can use `$expand=*` to get all the data in your query.

As far as I'm aware, it is not possible to change that default depth of 2, though someone from the team can confirm.

**Comment by Emp1Motus** [comment]
i am so sorry. 
there has been a misunderstanding on our part.
thanks a lot for your help!

**Comment by julealgon** [comment]
> i am so sorry. there has been a misunderstanding on our part.

No worries at all.

> thanks a lot for your help!

Sure. Just keep in mind my answer is not authoritative. I'd still suggest keeping this open and waiting for someone on the OData team to confirm. I currently _believe_ one can't change the default expansion depth, but that might not be the case.
