### ISSUE TITLE
8.0.12 : PATCH against one entity is attempting to update a related entity collection that is empty b/c of Delta<T>

### ISSUE THREAD

**Issue by LeviateK** [OData/AspNetCoreOData#811]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.12

**Describe the bug**
PATCH update failing - I am using Syncfusion Blazor Grids Edit/Update to complete this operation.  POST operation is not impacted - able to add an entry, but then not able to update it.

**Data Model**
Have several impacted models - seems to only impact those with 2 or more referenced 1-Many relationships. 
Examples: 
Asset references Facility & AssetType - can't update Asset; Conversely Facility references Client and contains a collection of Assets, updates fine.

**Request/Response**
Request: /odata/AssetsOdata(1)
Payload: 
{
  "AssetID": 1,
  "Name": "Larger Tank 100",
  "AssetTypeID": 1,
  "Facility": {},
  "AssetType": {}
}

Response: Either 400 or 500, with the following on server console: 
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Name', table 'ZOGCMDEV.dbo.AssetTypes'; column does not allow nulls. INSERT fails.

**Expected behavior**
Method goes through w/o error like it did on 8.0.11 and prior versions with response 200 received back.

**Additional context**
Also in the server output, is a call to AssetTypes (related table) that was not there previously: 

Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (12ms) [Parameters=[@p0='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [AssetTypes] ([Name])
      VALUES (@p0);
      SELECT [AssetTypeID], [PeriodEnd], [PeriodStart]
      FROM [AssetTypes]
      WHERE @@ROWCOUNT = 1 AND [AssetTypeID] = scope_identity();
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type '.Server.Data.Context'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Name', table '.dbo.AssetTypes'; column does not allow nulls. INSERT fails.

**Comment by julealgon** [comment]
> **Request/Response**
> Request: /odata/AssetsOdata(1)
> Payload:
> {
> "AssetID": 1,
> "Name": "Larger Tank 100",
> "AssetTypeID": 1,
> "Facility": {},
> "AssetType": {}
> }

I'm confused by your PATCH payload. If you only want to update the `Asset` entity itself, why are you passing
```json
"AssetTypeID": 1,
"Facility": {},
"AssetType": {}
```
?

Can you clarify exactly what it is that you wanted to update in the `Asset` object? Was it the name?

As for why this might be happening, a fix was made recently to properly handle nested updates with PATCH:
- https://github.com/OData/AspNetCoreOData/pull/747

The behavior you are seeing, at first glance to me, appears to be correct: since you are passing an empty `AssetType` object, it is now attempting to set the `AssetType` properties to those empty/null values.

Remember that `"AssetType": {}` is basically equivalent to `new AssetType()`.

**Comment by LeviateK** [comment]
Thanks for the quick update, I had a feeling it would be related to that fix & the grid control's behavior.  The PATCH payload is how the Syncfusion Grid control has always been sending it using their inline or dialog modes of editing - I have not adjusted anything on that side.

It uses their SfDataManager component with an ODataV4Adaptor, Url to populate the Grid, CrudUrl property for updates (as necessary):

<SfDataManager Url="/odata/AssetsOdata?$expand=Facility,AssetType" CrudUrl="/odata/AssetsOdata" Adaptor="Adaptors.ODataV4Adaptor"></SfDataManager>

I'm reviewing their docs to see if there is an easy way to customize the payload before it's sent, as well as reaching out to their support for ideas.  I have one grid that uses an external form with 1 related data source, and it does not have this behavior since the arguments are binded on RowSelect.

**Comment by ElizabethOkerio** [comment]
@LeviateK  Sounds like this is an issue with the Grid. Let's know if there is anything that needs fixing on the OData side.

**Comment by LeviateK** [comment]
Thanks!  I'm still waiting on a response from Syncfusion, but I was able to develop a working solution based on my other grid & their documentation that does work more in line with this OData behavior.

Cheers!
