### ISSUE TITLE
Can OData send pass-through SQL and also run stored procedures with parameters on SQL Server?

### ISSUE THREAD

**Issue by exquirentibus** [OData/AspNetCoreOData#818]
Can I use OData to send pass-through SQL directly to SQL Server and return a result set or errors?

Same for calling a Stored Procedure by name and passing parameters to the Stored Procedure?

I like OData's functionality and it's .. Wonderful .. but I need this capability.    I wrote code years ago with .NET Remoting (a bit deprecated now lol) that did exactly that so I'm hoping that years later my clumsy but very workable efforts had been replace by something Way more elegant.

If Not, what's my best way forward?

**Comment by julealgon** [comment]
You can take the `ODataQueryOptions` instance and do literally whatever you want with the parsed OData filter values. 

I have at one point used Dapper this way.

This should be moved to discussions.

**Comment by exquirentibus** [comment]
Thanks Juliano!  Would you happen to have and code snippets or have links to some?

I've got complex SQL queries that create several records in multiple tables using the primary keys of a new table as fields of another so the basic selection features aren't going to be enough for me.

I've been following and reading about OData for a while and am ready to jump in but none of the videos or articles I've stumbled across mention how to do this - or how to send a stored procedure name with parameters .. and all my google searches have returned nothing useful to me so I figured I'd ask the OData experts!

I'm unclear on how to move this to discussions?   Sorry if I posted in the wrong area?  I'm not that Github-fluent?

**Comment by julealgon** [comment]
> Thanks Juliano! Would you happen to have and code snippets or have links to some?

I'm not at the computer right now but if you look into some basic OData samples you should see the usage of manual `ODataQueryOptions<T>`. Basically it's the "manual mode" of OData, kind of the opposite of the `[EnableQuery]` attribute. 

> I've got complex SQL queries that create several records in multiple tables using the primary keys of a new table as fields of another so the basic selection features aren't going to be enough for me.

It looks like you might have to resort to custom bound actions. OData allows you to create completely custom side effecting routes that are either attached to an entity, or a collection of entities,  where you can pass arbitrary data to, and still remain in "odata space", so to speak. 

"actions" are called with POST and cause side effects, while "functions" are called with GET and are pure. 

> I've been following and reading about OData for a while and am ready to jump in but none of the videos or articles I've stumbled across mention how to do this - or how to send a stored procedure name with parameters .. and all my google searches have returned nothing useful to me so I figured I'd ask the OData experts!

Look for odata custom actions. 

> I'm unclear on how to move this to discussions? Sorry if I posted in the wrong area? I'm not that Github-fluent?

No worries. Some mod can convert it later.

In general whenever you see a repository with the "Discussions" tab active, it is better to ask questions over there instead of creating issues.

**Comment by exquirentibus** [comment]
Excellent!  it sounds like I Can use normal SQL !!  Hopefully I can send a number of SQL statements inside of SQL Server transaction SQL keywords and get back the data or the error codes?

I'll search for some code samples (this seems a bit above the normal samples I've seen - just bought a new Book 'Apps and Services with .NET 7' that covers OData, GraphQL and gRPC but .. way to much on the beginner side - and all of the samples and videos I've seen from Microsoft and their evangelists just show the terribly cool way OData queries the data but .. nothing about the more Advanced features .. so if you happen to get in front of a computer .. I'd Love to see any snippets you might have!!

Enjoy your evening!  Cheers!

**Comment by xuzhg** [comment]
> Can I use OData to send pass-through SQL directly to SQL Server and return a result set or errors?
> 
> Same for calling a Stored Procedure by name and passing parameters to the Stored Procedure?
> 
> I like OData's functionality and it's .. Wonderful .. but I need this capability. I wrote code years ago with .NET Remoting (a bit deprecated now lol) that did exactly that so I'm hoping that years later my clumsy but very workable efforts had been replace by something Way more elegant.
> 
> If Not, what's my best way forward?

@exquirentibus I do think you can do it using the way mentioned from @julealgon  or by customizing the Query binder.

For manually process ODataQueryOptions, you can refer to: https://github.com/xuzhg/WebApiSample/blob/7114b3941b61d4448a89cb5f31568a51636d1bd7/ODataSpatialSample/ODataSpatialSample/Controllers/CustomersController.cs

For customizing the Query binder: you can refer to: https://github.com/xuzhg/mydotnetconf/blob/main/OData/OData.WebApi/Extensions/SchoolStudentFilterBinder.cs

Let me know whether it can work or need further help. Thanks.

**Comment by exquirentibus** [comment]
> > Can I use OData to send pass-through SQL directly to SQL Server and return a result set or errors?
> > Same for calling a Stored Procedure by name and passing parameters to the Stored Procedure?
> > I like OData's functionality and it's .. Wonderful .. but I need this capability. I wrote code years ago with .NET Remoting (a bit deprecated now lol) that did exactly that so I'm hoping that years later my clumsy but very workable efforts had been replace by something Way more elegant.
> > If Not, what's my best way forward?
> 
> @exquirentibus I do think you can do it using the way mentioned from @julealgon or by customizing the Query binder.
> 
> For manually process ODataQueryOptions, you can refer to: https://github.com/xuzhg/WebApiSample/blob/7114b3941b61d4448a89cb5f31568a51636d1bd7/ODataSpatialSample/ODataSpatialSample/Controllers/CustomersController.cs
> 
> For customizing the Query binder: you can refer to: https://github.com/xuzhg/mydotnetconf/blob/main/OData/OData.WebApi/Extensions/SchoolStudentFilterBinder.cs
> 
> Let me know whether it can work or need further help. Thanks.

Thank you for the code!!  I'm just starting down the path with OData and needed to know if I could do it.

I'm going to try to put together a 'hello world' example where I can return the results of an SQL select statement (just like I'd paste into a SQL Server Management Console query window) .. and also call a simple stored procedure with a single parameter.

Start simple with baby steps and build from there!

I'll Definitely reach out to you when I have questions.

BTW - I'd been looking at Restier when I started evaluating.   Is that worth pursuing at all?

Are there other repositories with code that will facilitate using OData or add functionality that I should be looking at?

Thanks!!

**Comment by julealgon** [comment]
> Are there other repositories with code that will facilitate using OData

I'd suggest relying on the OData Connected Service extension which generates client proxies based on the API's metadata:
https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService

**Comment by mikepizzo** [comment]
As per above, Stored Procedures in SQL generally map well to actions in OData.  Beyond that, the framework gives you the opportunity to extend in multiple ways.

**Comment by mikepizzo** [comment]
I'm going to resolve this as closed, as I believe your initial question has been answered. Feel free to reach out if you have additional questions or run into any issues!
