### ISSUE TITLE
SetTimeZoneInfo(TimeZoneInfo.Utc) seems to not work for POST using 8.0.0-nightly202101271313

### ISSUE THREAD

**Issue by fukalov** [OData/AspNetCoreOData#82]
Hello.

I added ODataOptions -> SetTimeZoneInfo(TimeZoneInfo.Utc)
Serialization works fine ("2021-01-31T**14**:09:52.797Z")

Deserialization seems to not work for POST method. 
It returns DateTimeKind.Unspecified and time is converted to local time, also doesn't metter how to send in utc "2021-01-31T**14**:09:52.797Z" or local "2021-01-31T**20**:09:52.797+06:00" result is "2021-01-31T**20**:09:52.797" DateTimeKind.Unspecified
Is it Ok or should it be in Utc "2021-01-31T**14**:09:52.797" (14 hours)?

Maybe is better to use the DateTimeOffset?

I am using Net5.0
using Microsoft.EntityFrameworkCore;
....
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Formatter.Value;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.AspNetCore.OData.Routing.Controllers;
namespace Server.Controllers {
public class EmployeesController : ODataController
{
        private readonly MyDbContext _context;
        public EmployeesController(MyDbContext context)
        {
            _context = context;
        }

	public async Task<IActionResult> Post([FromBody] Employee employee)
	 {
		_context.Employees.Add(employee);
		await _context.SaveChangesAsync();
		return Created(employee);
	}
}
} //I have cut the class above
Employee class has: public DateTime Created { get; set; }

Thanks,
Best regards.

**Comment by fukalov** [comment]
I did a small research and based on it I have to change types: C# DateTime to DateTimeOffset and MS SQL datetime2(7) to datetimeoffset(7) in my project.

Reason: DateTimeOffset is unchangeable by serialization/deserialization and database write/read operations, DateTime loses the TimeZoneInfo and can be converted by serialization/deserialization

So the issue TimeZoneInfo is a global issue and we should use the DateTimeOffset if system works with multiple time zones.

Please, feel free to close this issue.
Best regrds.

**Comment by xuzhg** [comment]
@fukalov Would you help check `Microsoft.AspNetCore.OData.8.0.0-Nightly202102030720`

**Comment by fukalov** [comment]
@xuzhg I checked the latest Microsoft.AspNetCore.OData 8.0.0-Nightly202102031311 with SetTimeZoneInfo(TimeZoneInfo.Utc)

POST request "2021-02-04T10:34:55.838+06:00"
Deserialized:
Kind = Unspecified
value = {02/04/2021 04:34:55}

POST request "2021-02-04T04:44:58.831+00:00"
Deserialized:
Kind = Unspecified
value = {02/04/2021 04:44:58}

Should DateTimeKind be Utc or Unspecified?

**Comment by xuzhg** [comment]
It should be UTC

**Comment by xuzhg** [comment]
It should be fixed. Please file a new issue if you have further concerns. Thanks.
