### ISSUE TITLE
404 on Unbound Function when passing () - works fine without the parens

### ISSUE THREAD

**Issue by christophwille** [OData/AspNetCoreOData#827]
In porting code from Microsoft.AspNet.WebApi.OData version 5.7.0 (netfw48) to 8 (net7) I stumbled on a problem that has me stumped:

            modelBuilder.Function("SomeFunc")
                .Returns<string>();

With the old app, it reacts to being called "/api/SomeFunc()" - with the ported controller (which is easy enough), it only reacts to "/api/SomeFunc" and 404s on "/api/SomeFunc()".

I looked at various samples eg https://github.com/OData/ODataSamples/blob/master/AspNetCoreOData8x/AspNetCoreOData8xSamples/Lab02Sample03/Controllers/BooksController.cs and https://github.com/OData/AspNetCoreOData/blob/main/sample/ODataCustomizedSample/Controllers/AnyController.cs but don't see any differences to my code.

The controller is derived from ODataController, and decorated like this

    [ApiController]
    [ApiExplorerSettings(IgnoreApi = true)]
    [ODataAttributeRouting]
    [Route("myapi/[controller]")]

Using either [HttpGet("ConnectDelegate365()")] or [HttpGet("ConnectDelegate365")] doesn't make a change. Any ideas?

Edit: no, removing [ApiController] doesn't change a thing.

**Comment by julealgon** [comment]
Share the results of the `$odata` route debugging endpoint please.

The fact that it is "working" without the parenthesis, suggests to me that what you are looking at is a standard MVC route and not an OData-enabled custom function route.

Also, looking at your example, this could very well be the problem:
`[Route("myapi/[controller]")]`

- https://github.com/OData/AspNetCoreOData/issues/430

Try replacing `[controller]` with your controller name prefix.

**Comment by christophwille** [comment]
Yes, I just saw this in the console output:

`[14:48:18 WRN] The path template 'adminapi/[controller]/SomeFunc()' on the action 'SomeFunc' in controller 'UnboundFunctions' is not a valid OData path template. Resource not found for the segment '[controller]'.`

**Comment by christophwille** [comment]
Ok, I tried `[Route("myapi/actualcontrollername")]` - result:

`[14:56:27 WRN] The path template 'myapi/actualcontrollername/SomeFunc()' on the action 'SomeFunc' in controller 'ActualControllerName' is not a valid OData path template. The request URI is not valid. The segment 'SomeFunc' must be the last segment in the URI because it is one of the following: $ref, $batch, $count, $value, $metadata, a named media resource, an action, a noncomposable function, an action import, a noncomposable function import, an operation with void return type, or an operation import with void return type.`

Then I switched to `[Route("myapi")]` because it is a top-level unbound function. Yep, that works. Thanks for the help! (although having to copy paste the controller names to the Route attributes isn't "nice", meaning: not refactor-safe)

**Comment by julealgon** [comment]
> (although having to copy paste the controller names to the Route attributes isn't "nice", meaning: not refactor-safe)

Yep... that is pretty bad... hopefully it will be fixed soon as it is a fairly common cause of problems especially when migrating standard MVC controllers to OData controllers.

**Comment by christophwille** [comment]
I have enabled $odata to find out more about some warnings I still have - but that doesn't really add more information, eg:

`[15:23:07 WRN] The path template 'myapi/entities1/MyAction' on the action 'MyAction' in controller 'Entities1' is not a valid OData path template. Bad Request - Error in query syntax.`

Is there a way to find out more?

Code in question for the model builder:

```
            modelBuilder.EntitySet<Entity1>("Entities1").EntityType.Name = "Entities1";
            var funcDContacts = modelBuilder.Action("MyAction");
            funcDContacts.Parameter<string>("req");
            funcDContacts.ReturnsCollectionFromEntitySet<Entity1>("Entities1");
```

[HttpPost("MyAction")] is the attribute. I guess that again I am missing some subtle change in between versions.

**Comment by julealgon** [comment]
> I have enabled $odata to find out more about some warnings I still have - but that doesn't really add more information, eg:
> 
> `[15:23:07 WRN] The path template 'myapi/entities1/MyAction' on the action 'MyAction' in controller 'Entities1' is not a valid OData path template. Bad Request - Error in query syntax.`
> 
> Is there a way to find out more?
> 
> Code in question for the model builder:
> 
> ```
>             modelBuilder.EntitySet<Entity1>("Entities1").EntityType.Name = "Entity1";
>             var funcDContacts = modelBuilder.Action("MyAction");
>             funcDContacts.Parameter<string>("req");
>             funcDContacts.ReturnsCollectionFromEntitySet<Entity1>("Entities1");
> ```
> 
> `[HttpPost("MyAction")]` is the attribute. I guess that again I am missing some subtle change in between versions.

You are adding the custom action to the root of the model builder, meaning it is now an unbounded global action, and not an action on `Entities1` as you wanted it to be.

For the action to be scoped to the `Entity1` entityset, you have to define it in that type:
```
            var entity1Type = modelBuilder.EntitySet<Entity1>("Entities1").EntityType;
            entity1Type.Name = "Entity1";
            var funcDContacts = entity1Type.Collection.Action("MyAction");
            funcDContacts.Parameter<string>("req");
            funcDContacts.ReturnsCollectionFromEntitySet<Entity1>("Entities1");
```
Notice how I'm calling `Action` on the `entity1Type` with the added `Collection`, which makes it scoped to the entity set itself. This will allow you to call from the entity set:
- `myapi/entities1/MyAction()`

If you want the action to be bound to specific entities, just remove the `.Collection` part and call it like:
- `myapi/entities1/{id}/MyAction()`
or
- `myapi/entities1({id})/MyAction()`

**Comment by christophwille** [comment]
Thanks! There are tons of things that worked "magically" the "correct way" in that old version we were using vs how it should be now with the ASP.NET routing.
