### ISSUE TITLE
Camel case enum values?

### ISSUE THREAD

**Issue by RobTF** [OData/AspNetCoreOData#84]
Hi,

I've noticed that despite being able to switch on camel casing for property names, the enum values are not camel cased. Before I go digging, would this be possible via a custom implementation of `ODataEnumSerializer.cs`? would it be possible to get a nice switch like we do for property names?

thanks

**Comment by xuzhg** [comment]
@RobTF In the model builder, you can use the [EnumMember] attribute to set the enum property name.

**Comment by KenitoInc** [comment]
@RobTF Was your issue resolved?

**Comment by RobTF** [comment]
Yes thanks. I found there are two way of doing it; using `[EnumMember]` as above or using `builder.EnumType<MyEnum>().Member(MyEnum.Something).Name = "something"` in the model builder would make it work.
