### ISSUE TITLE
"No media types found" error on ODataRoutingSample Swagger generation

### ISSUE THREAD

**Issue by JohnGoldInc** [OData/AspNetCoreOData#86]
Running the  Version="8.0.0-preview3" ODataRoutingSample project and going to http://localhost:64771/swagger/v1/swagger.json I get the error:

`InvalidOperationException: No media types found in 'Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.`

**Comment by RobTF** [comment]
I think there are changes to the library required to make this work that aren't released yet.

The changes are in [this commit](https://github.com/OData/AspNetCoreOData/commit/fa95d13326006ab112e3a576f9e6bb583cb9538a). Which looks to be currently newer than the latest released NuGet package. If you build from the latest nightly I'm guessing it will work. It's slightly misleading as the readme mentions it.

**Comment by xuzhg** [comment]
@JohnGoldInc 

You can try the nightly bit

```C#
PM> Install-Package Microsoft.AspNetCore.OData -Version 8.0.0-Nightly202102081315 -Source https://www.myget.org/F/webapinetcore/api/v3/index.json
```

**Comment by JohnGoldInc** [comment]
@xuzhg Something with that command is not working: I am not seeing Odata in the json, should be different URL?

NU1603: Northwind.OData depends on Microsoft.AspNetCore.OData (>= 8.0.0-Nightly202102081315) but Microsoft.AspNetCore.OData 8.0.0-Nightly202102081315 was not found. An approximate best match of Microsoft.AspNetCore.OData 8.0.0-preview was resolved.
Install-Package : NU1107: Version conflict detected for System.ComponentModel.Annotations. Install/reference System.ComponentModel.Annotations 5.0.0 directly to project Northwind.OData to resolve this issue. 
 Northwind.OData -> Microsoft.EntityFrameworkCore.SqlServer 5.0.3 -> Microsoft.EntityFrameworkCore.Relational 5.0.3 -> Microsoft.EntityFrameworkCore 5.0.3 -> System.ComponentModel.Annotations (>= 5.0.0) 
 Northwind.OData -> Microsoft.AspNetCore.OData 8.0.0-preview -> Microsoft.OData.ModelBuilder 1.0.4 -> System.ComponentModel.Annotations (>= 4.6.0 && < 5.0.0).
At line:1 char:1
+ Install-Package Microsoft.AspNetCore.OData -Version 8.0.0-Nightly2021 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Northwind.OData'.

**Comment by xuzhg** [comment]
It should works now in the nuget RC and coming release version.  Close it and let me know if you have further question.
