### ISSUE TITLE
How to replicate convention based EntitySet routes manually?

### ISSUE THREAD

**Issue by awbacker** [OData/AspNetCoreOData#866]
I want to recreate some basic routes from the `EntitySetRoutingConvention` manually.  This is partially to avoid routes I do not want, like $count, and which are created even when that feature is not enabled on the models. This is a very simple api - **read only** lists with pagination.  

Things work _in general_, but the format of the response is wrong. There are legends of an `ODataFormattingAttribute`, but that cannot be found in `v8`?

The [output I am trying to achieve](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/entityset-routing?tabs=netcoreapp31%2Cnetcore-cli#retrieving-an-entity-set) looks like this:

```
HTTP localhost:5000/odata/
{
    "@odata.context": "http://localhost:5000/odata/$metadata#Shapes",
    "value": [
        {
            "@odata.type": "#EntitySetRouting.Models.Rectangle",
            "Id": 1,
            "Area": 28.0,
            "Length": 7.0,
        },
```
_note: the embedded `@odata.type` is something I have *never* seen in output, but it is in the docs?_

The output I get is the same data, but just the values array:
```
[
    {
        "Id": 1,
        "Area": 28.0,
        ...
    },
```

This is the basic controller I have, which works great otherwise:

```
[Route("odata/[controller]")]
public class ShapesController : ODataController
{
    ....
    [EnableQuery, HttpGet]
    public IQueryable<Shape> Get()
    {
        return Context.Shapes;
    }

    [EnableQuery, HttpGet("{id}")]
    public SingleResult<Shape> Get(int id)
    {
        return SingleResult.Create(Context.Shapes.Where(o => o.Id == id));
    }
}
```

I disable the generation of the other routes/conventions in `program.cs`:
```
builder.Services.AddControllers().AddOData(options =>
{
    options.Conventions.Clear(); // remove all
    options.Conventions.Add(new MetadataRoutingConvention());
```

**Comment by awbacker** [comment]
> meaning OData is not recognizing your endpoint as an OData endpoint.

Yes.  How does one go about making it recognized. 

It is already an `ODataController`, $expand/$top work too.  What extra bit is needed? I did try to clone/modify the `EntitySetRoutingConvention` but _too many important bits_ were needlessly "internal" so I had to drop the effort.

> `[Route("odata/Shapes")]`

I have I have done both, and both work fine for me.  Regardless, I will use the explicit name from now on.  

> Please check the results of the $odata debug endpoint 

As you thought, the controller is under `Non-OData Endpoint Mappings`.  I hadn't thought to check here before, and still don't know what to do about that.

**Comment by awbacker** [comment]
@julealgon I'm not sure what you would like to see, so I'll update this if something is missing.  There wasn't much to this project, but I'm sure I can recreate it - it was really quite simple.  I've concatenated it below as best as I can remember, but I've just resigned myself to using the convention.  

The main question still exists - how to make `ShapesController.Get()` behave like it does when wired up via the `EntitySetRoutingConvention`.

#### `program.cs`
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddControllers().AddOData(options =>
{
    options.Conventions.Clear();
    options.Conventions.Add(new MetadataRoutingConvention());
    options.AddRouteComponents("odata/v1/", ODataModel.GetEdmModel())
        .Filter().Select().Count().SkipToken();
});
var app = builder.Build();
app.UseRouting();
app.MapControllers();
app.Run();
```

#### `Models/Shape.cs`
```cs
[Table("Shape")] public class Shape 
{
    [Key] public long Id { get; set; }
    public float Area { get; set; } = 0.0;
    public float Length { get; set; } = 0.0;
}
```

#### `Models/MyDbContext.cs`
```cs
public partial class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) {}
    public virtual DbSet<Shape> Shapes { get; set; } = null!;
}
``

#### `ODataModel.cs`
```cs
public class ODataModel
{
    public static IEdmModel GetEdmModel()
    {
        var builder = new ODataConventionModelBuilder();
        builder.EntitySet<Shape>("Shapes");
        return builder.GetEdmModel();
    }
}
```

#### `Controllers/ShapeController.cs`
```cs
[Route("odata/v1/Shapes")]
public class ShapesController : ODataController
{
    private readonly MyDbContext DB { get; } = null!

    public ShapesControllers(MyDbContext context) {
        DB = context;    
    }
    
    [EnableQuery, HttpGet] 
    public IQueryable<Shape> Get() {
        return DB.Shapes;
    }
}
```

**Comment by julealgon** [comment]
@awbacker why is your new code different than the old one you showed?

In the old one, you didn't have the `/v1` in the route. If the route doesn't match precisely, it won't be detected as an OData route.

Your new code looks correct to me at first glance. Can you try this
```csharp
options.AddRouteComponents("odata/v1",...
```

Instead of:
```csharp
options.AddRouteComponents("odata/v1/",...
```
?

Also, if you want the GET method to behave the same as the OData convention, you need to also manually define the count route. to point to the same action, but the general GET should already be working.

**Comment by awbacker** [comment]
It has changed a little between first post and now as the code has moved on a bit.  Sorry for the confusion!

Thanks for the `/` on `AddRouteComponents`, but sadly that had no effect :(  I tried with a random route name just to be safe, with the same result:

```cs
options.AddRouteComponents("xyz",  ...
options.AddRouteComponents("xyz/", ...

[Route("xyz/Shapes")]
```

FWIW, I am trying to avoid a `$count`.  The tables are too big and count will take too long, but with conventions I am forced to either use `.count()` to enable it, or have the endpoint crash. 

The quest to get rid of `$count` is what got me started down this road.  

I think I need to create a new minimal example.  Without that, I feel I'm wasting your kindly given time!

**Comment by xuzhg** [comment]
> @awbacker I'm honestly not seeing any further issues with your samples here, so its weird its still not working properly.
> 
> If you want, you can share your full project (or a repro of the issue as a project) somewhere and link it here. I could then look at the project as a whole and see if I can spot what the issue is.

+1

**Comment by awbacker** [comment]
Replication:

* https://github.com/awbacker/odata-format-issue
  * [program.cs](https://github.com/awbacker/odata-format-issue/blob/main/Program.cs)
  * [controller](https://github.com/awbacker/odata-format-issue/blob/main/ProductsController.cs)
  * [data/edm context](https://github.com/awbacker/odata-format-issue/blob/main/DatabaseContext.cs)

It has been greatly simplified, and I was pretty impressed how much you could do with odata+ef+aspnetcore in so little code. 

If anyone wishes to run it, it should create the database on startup and the endpoint(s) work.

```
builder.Services.AddControllers().AddOData(options =>
{
    options.Conventions.Clear();
    options.Conventions.Add(new MetadataRoutingConvention());
    options.AddRouteComponents("xyz", ODataModel.GetEdmModel());
});
```

```
[Route("xyz/Products")]
public class ProductsController : ODataController
```

**Comment by julealgon** [comment]
Oh boy.... can't believe I didn't spot the problem earlier 🤦‍♂️ 

@awbacker , there is another convention that is added by default that is actually responsible for honoring attribute routing... called `AttributeRoutingConvention`. Your `Clear` call is removing that (as expected).

I'd suggest removing the specific conventions you don't need instead of performing a full `Clear` on the collection. This will probably be easier than trying to instantiate the `AttributeRoutingConvention` since it relies on a couple of dependencies.

Either that, or you could loop through the list of conventions and remove all but the metadata and attribute routing ones (just keep in mind that you can't remove while iterating so this is a bit convoluted to do).

Something like this should work:
```csharp
    var conventionsToRemove = options
        .Conventions
        .Where(c => c is not MetadataRoutingConvention and not AttributeRoutingConvention)
        .ToList();

    foreach (var convention in conventionsToRemove)
    {
        options.Conventions.Remove(convention);
    }
```

Hope this helps.

**Comment by awbacker** [comment]
Well I'll be ..., keeping the `AttributeRoutingConvention` worked perfectly!  I had tried adding that (and others) manually before, but as you say it is a bit tricky with the parameters.  I didn't try very hard on that one, just skipped it.

Thank you for all your time on this, @julealgon !

This is what I ended up with for adding odata:

```cs
builder.Services.AddControllers().AddOData(options =>
{
    options.Conventions
        .Where(c => c is not MetadataRoutingConvention)
        .Where(c => c is not AttributeRoutingConvention) // notices [HttpGet] and does formatting
        .ToList()
        .ForEach(c => options.Conventions.Remove(c));

    options.EnableQueryFeatures(maxTopValue: null);
    options.AddRouteComponents("odata/v1/", ODataModel.GetEdmModel());
});
```

**Comment by gathogojr** [comment]
Proposed solution/workaround fixed the issue
