### ISSUE TITLE
Memory leak when using OData 8.0.11 and Automapper 3.0.5

### ISSUE THREAD

**Issue by kinshuk1990** [OData/AspNetCoreOData#873]
I am running a .net core application hosted on azure app service, that is exposing a bunch of odata endpoints. We are observing an issue where we see the memory keeps growing and is never released.  This eventually results into the application crashing.  Unfortunately, I won't be able to  provide the source code and I couldn't reproduce this problem in a sample project. 

Looking at the objects in the managed heap, I see a large number of of instances of class Microsoft.OData.Edm.EdmStructuralProperty	and the Path to the root seems to be pointing to a static variable 											Microsoft.AspNetCore.OData.Edm.DefaultODataTypeMapper.Default.  

**Assemblies used:**
Microsoft.AspNetCore.OData   8.0.11
AutoMapper.AspNetCore.OData.EFCore 3.0.5

**Here are the screenshots:**

Private bytes for azure app service

![github-memory-usage](https://user-images.githubusercontent.com/16712372/227983593-d23d4467-e750-437c-9c28-1b3154909cd7.png)

managed memory heap view

![github-managed-memory](https://user-images.githubusercontent.com/16712372/227981214-984d75c0-b38f-4e6e-aa07-4c5c08ae317f.png)

**Comment by xuzhg** [comment]
@kinshuk1990 

There's a 'cache' to hold the model type mappings. see here at: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs#L149

It thinks this could be the root cause. Basically, it's not a problem, because we only have the `static` model, however, if your service creates the model every time within every request and never cached, this is a big problem, since the model is cached. 

Would you please check on your side to see how your edm model was created? If need help, feel free to book time so we can investigate together remotely. Thanks.

**Comment by gathogojr** [comment]
@kinshuk1990 Please let me know if the response by Sam helped resolve your issue

**Comment by kinshuk1990** [comment]
@gathogojr  Based on the suggestions from Sam, I checked on our side and in one of the code flows we were creating edm model for each request. After  fixing that we have seen the memory footprint has gone down a little. We are still testing this and will confim if this resolves the issue for us.

**Comment by gathogojr** [comment]
@kinshuk1990 Great! Keep us posted

**Comment by kinshuk1990** [comment]
@gathogojr  The change seems to have fixed the issue for us. We have tested this for a couple of weeks now and we are not observing any memory leak in our application.

**Comment by AdeZwart** [comment]
> @gathogojr Based on the suggestions from Sam, I checked on our side and in one of the code flows we were creating edm model for each request. After fixing that we have seen the memory footprint has gone down a little. We are still testing this and will confim if this resolves the issue for us.

How did you fix this? Did you implement a caching mechanism yourself? Or did you (re)use the cache on the linked source?

**Comment by Bosu123l** [comment]
Hey, do you happen to know what’s going on with the topic?
