### ISSUE TITLE
Override host of @odata.context

### ISSUE THREAD

**Issue by seturaas** [OData/AspNetCoreOData#876]
If OData service is deployed in a pod, it returns pod's IP/hostname in the @odata.context. Here is an example of @odata.context when the service is deployed in a pod:
https://10-xxx-xx-184.xxx.pod.cluster.local:5001/cache/$metadata#orders(OrderId,Amout)

It is possible to override the hostname using following statement in each action:
`Request.Host = new Microsoft.AspNetCore.Http.HostString("overridehostname");`

There is no way to override the prefix or the route name.

Can you please provide a better way to override the hostname and also the prefix.

**Comment by julealgon** [comment]
Have you tried enabling the forwarded headers middleware in AspNetCore?
- https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

Specifically, I'm pretty sure the X-Forwarded-Host header exists for scenarios like yours where there is something inbetween the consumer and the API itself, either a proxy or a load balancer of sorts. This header then sets the original host back and I _assume_  OData would just respect it.

IIRC to enable the middleware all you need to do is set a specific environment variable (the middleware is always added by default but is not active by default).

**Comment by xuzhg** [comment]
@seturaas Try to specify the call back function for ODataOuputFormatter at: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs#L60

Let me know if you need more codes to make it working?

**Comment by seturaas** [comment]
After enabling the forwarded headers middleware, it works. Thanks a lot @julealgon.

**Comment by lf-novelt** [comment]
hello, it seems the forwarded headers only cover the Host and the Proto, but not the Path. 
What would be the way to override the full base address url?

I've tried https://github.com/OData/WebApi/issues/1817#issuecomment-656157130 but it does not cover the `@odata.nextlink`

**Comment by julealgon** [comment]
@lf-novelt I would suggest creating another question, preferably over the "Discussions" area. This particular issue was specific to the Host value as per the title.

**Comment by lf-novelt** [comment]
hello @julealgon, thanks for the answer. 
In the initial message, overriding the prefix was also mentionned, I assumed it refers to the non-host part of the url.

As suggested, I've opened a new ticket https://github.com/OData/AspNetCoreOData/issues/1257, a ticket rather than a discussion because it could be considered a bug in the behavior of the `ODataOutputFormatter.BaseAddressFactory` to rewrite some urls in the response but not all, I hope you agree.

Thanks again for the support.
