### ISSUE TITLE
DynamicProperty binding with Json attribute value string containing square bracket followed by double quotes breaks the response.

### ISSUE THREAD

**Issue by manu1502** [OData/AspNetCoreOData#879]
**Assemblies affected**
Microsoft.AspNetCore.OData (8.0.12)

**Describe the bug**
I created a Dictionary<string, object> DynamicProperty and Deserialized Json containing something like {"IP":["10.10.10.1"] }
The response errored. I don't have the exact error details as the error is not trapped in the middleware. 
The response rendered is partial till it encounters the above attribute. And response code is 500.

**Data Model**
Dictionary<string, object> DynamicProperty

**Expected behavior**
I expect the reponse to be in the form 
"IP": ["10.10.10.1"   ], along with the rest of the Json without breaking.

**Comment by xuzhg** [comment]
@manu1502 Do you have a repro for me to dig more?

**Comment by manu1502** [comment]
Here is a small sample how I could repro:

Entity:
public class MyTestEntity
    {
        public int MyTestId { get; set; }
        public Dictionary<string, object> MyProperties { get; set; }
    }

EDM:
 odataBuilder.EntitySet<MyTestEntity>("myTestEntities");
            odataBuilder.EntitySet<MyTestEntity>("myTestEntities").EntityType.HasKey(p => p.MyTestId);



public class MyTestEntitiesController : ODataController
    {

        public MyTestEntitiesController()
        {
        }


        [HttpGet(Name = "ListMyTestEntitiesAsync")]
        [EnableQuery]
        public async Task<ActionResult<IEnumerable<MyTestEntity>>> ListMyTestEntitiesAsync(ODataQueryOptions<MyTestEntity> options)
        {
            try
            {
                

                StreamReader str = new StreamReader("C:\\Temp.txt");
                var prop = JsonConvert.DeserializeObject<Dictionary<string, object>>(str.ReadToEnd().ToString(), new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
                
                return new List<MyTestEntity>
                { 
                    new MyTestEntity 
                    { 
                        MyTestId = 1, 
                        MyProperties = prop                      
                    }
                };
            }
            catch (Exception ex)
            {
                return new ObjectResult(HttpStatusCode.InternalServerError);
            }
        }
    }



Temp.txt has the following content: {"Prop1":["10.10.10.1"]}	

Remove the square brackets, it works fine.

**Comment by xuzhg** [comment]
@manu1502 Check the sample in  branch https://github.com/OData/AspNetCoreOData/tree/issue879

Run sample and send $odata, you can get:

![image](https://user-images.githubusercontent.com/9426627/229231414-ab40042d-f28f-470c-b0b7-4ac6adc4e45c.png)


Click the first endpoint, you can get

![image](https://user-images.githubusercontent.com/9426627/229231254-8467c5bf-f9c8-42fd-8b4f-1384be53ad0a.png)
