### ISSUE TITLE
ODataConventionModelBuilder - Microsoft.OData.ModelBuilder vs Microsoft.AspNet.OData.Builder namespaces

### ISSUE THREAD

**Issue by tr1ckyk1d** [OData/AspNetCoreOData#88]
Hi,

I needed some functionality from Microsoft.OData.ModelBuilder.ODataConventionModelBuilder which is not available in the Microsoft.AspNet.OData.Builder namespace (I basically needed HasDeleteRestrictions().IsDeletable(false) API).

But when I used Microsoft.OData.ModelBuilder the API response type appeared to be plain json, not odata.metadata=minimal;
Plus response was missing {"@odata.context" and collections were serialized as arrays [{...},{...},..].

So is it possible to get HasDeleteRestrictions() call from the  Microsoft.AspNet.OData.Builder namespace? Or how to format response with ODataFormatter for model built with Microsoft.OData.ModelBuilder.ODataConventionModelBuilde?

Thanks!

**Comment by xuzhg** [comment]
We don't have plan to port the HasXXXRestrictions back to 7.x model builder.
In 7.x, you can use the lower api (something like AddVocabularyAnnotation) to add the restriction to your model.

**Comment by xuzhg** [comment]
Close it. If you have further question, please file new issue. Thanks.
