### ISSUE TITLE
Routing for Function not working as expected

### ISSUE THREAD

**Issue by alvachien** [OData/AspNetCoreOData#89]
Using the example project which copied from this repo: https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataRoutingSample

Difference from project wide:
- Remove project depences
- Add NUGET dependence to Nightbuild 8.0.0-Nightly202102081315

Run it.

Testing following URLs:
http://localhost:64771/Products/GetWholeSalary(minSalary=4,maxSalary=5,aveSalary=9)
HTTP 404.

http://localhost:64771/Products/GetWholeSalary(minSalary=4)
WORK, and routed to following method:
```C#
        [HttpGet]
        // ~/....(minSalary=4)
        // ~/....(minSalary=4, name='abc')
        public string GetWholeSalary(int minSalary, /*[FromBody]*/double name)
        {
            return $"Products/GetWholeSalary: {minSalary}, {name}";
        }
```

http://localhost:64771/Products/GetWholeSalary(minSalary=4,maxSalary=5)

Worked. Routed to following method:
```C#
        [HttpGet]
        // ~/....(minSalary=4, maxSalary=5)
        public string GetWholeSalary(int minSalary, int maxSalary)
        {
            // return $"Products/GetWholeSalary: {minSalary}, {maxSalary}";
            return GetWholeSalary(minSalary, maxSalary, aveSalary: "9");
        }
```

**Comment by xuzhg** [comment]
@alvachien 

aveSalary is a string type.

![image](https://user-images.githubusercontent.com/9426627/107610216-f8303300-6bf5-11eb-8a23-fe1890d4357b.png)

http://localhost:5000/Products/GetWholeSalary(minSalary=4,maxSalary=5,aveSalary='9') should work fine.

Feel free let me know any other issues. 

Thanks,
-Sam

**Comment by alvachien** [comment]
@xuzhg 

Thank you!
