### ISSUE TITLE
ODataController.Created<TEntity>(TEntity entity) fails when TEntity is IEdmObject

### ISSUE THREAD

**Issue by uffelauesen** [OData/AspNetCoreOData#893]
**Assemblies affected**
ASP.NET Core OData 8.x

**Describe the bug**
In a dynamic model setup where entities are based on `IEdmObject` the `CreatedODataResult<>` fails to construct as the object type is not in the model.

**Reproduce steps**
In an `ODataController` (could be the `HandleAllController` in ODataDynamicModel sample) add a Post method like this...

```
        public object Post([FromBody] EdmEntityObject entity)
        {
            // Do something with entity like assigning a key
            // ...

            // Then return the Created response
            return Created(entity);
        }
```
Also add the POST selector for this inside `MyODataRoutingApplicationModelProvider.ProcessHandleAll`.

Now POST'ing to this will give an exception as it fails to get the `IEdmEntityTypeReference` of the entity.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot find the resource type 'Microsoft.AspNetCore.OData.Formatter.Value.EdmEntityObject' in the model.
  Source=Microsoft.AspNetCore.OData
  StackTrace:
   at Microsoft.AspNetCore.OData.Results.ResultHelpers.GetEntityType(IEdmModel model, Object entity) in C:\Projects\GitHub\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Results\ResultHelpers.cs:line 186

```

**Data Model**
Use ODataDynamicModel sample project as a basis.

**EDM (CSDL) Model**
ODataDynamicModel

**Request/Response**
Issue a `POST` request to `/Products`

**Expected behavior**
The request succeeds and the correct Location response header is set.

**Comment by KenitoInc** [comment]
Fixed by #894
