### ISSUE TITLE
Routing is not working for Function which bound with EntityType

### ISSUE THREAD

**Issue by alvachien** [OData/AspNetCoreOData#90]
Using the example project which copied from this repo: https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataRoutingSample

Difference from project wide:

Remove project depences
Add NUGET dependence to Nightbuild 8.0.0-Nightly202102081315
Run it.

Based on metadata, there is one function 'CanMoveToAddress' on OrderControllers:
```C#
            var functionWithComplexTypeParameter = builder.EntityType<Order>().Function("CanMoveToAddress").Returns<bool>();
            functionWithComplexTypeParameter.Parameter<Address>("address");
```

And method defintion:
```C#
        [HttpGet]
        public bool CanMoveToAddress(int key, [FromODataUri] Address address)
        {
            return true;
        }
```

Testing following URLs:
http://localhost:64771/v21/Orders(2)/CanMoveToAddress(Address='%7B%7D')

It will results in HTTP 404.

Testing following URLs:
http://localhost:64771/v21/Orders(2)/CanMoveToAddress(Address=%7BCity='aaa',Street='bbb'%7D)

It will results in HTTP 404, too.

Testing following URLs:
http://localhost:64771/v21/Orders(2)/CanMoveToAddress(Address=%7BCity='aaa',Street='bbb'%7D)

It will results in HTTP 404, too.

Anyway, tried several times, failed to figure out a way to make it works.

Put a debug point at testing middleware:
```C#
            // Test middelware
            app.Use(next => context =>
            {
                var endpoint = context.GetEndpoint();
                if (endpoint == null)
                {
                    return next(context);
                }

                return next(context);
            });
```

The variable *endpoint* always null as there is inner exceptions.

**Comment by xuzhg** [comment]
@alvachien Why do you remove the project dependency and use the nightly?

**Comment by xuzhg** [comment]
@alvachien

Thanks point out this problem. A fix is merged at 97095f0a1408ac53962a80c74c739bf345b55249. 

Please feel free let me know any further problem.

**Comment by xuzhg** [comment]
@alvachien There are two ways:

- Inline
http://localhost:5000/v21/Orders(2)/CanMoveToAddress(address={"City":"abc","Street":"fdsfg"})

- parameter alias
http://localhost:5000/v21/Orders(2)/CanMoveToAddress(address=@p)?@p={"City":"abc","Street":"fdsfg"}

**Comment by alvachien** [comment]
@xuzhg 

Thanks, it works in your example project but not working in my own repo.

See my repo (branch: dev): https://github.com/alvachien/acgalleryapi

Issue 1: $odata is different with $metadata.

The functions/actions below won't appear in $odata page:

```C#
/ Function on Album - GetAlbumPhotos
var funcOnEntity = builder.EntityType<Album>().Function("GetRelatedPhotos").ReturnsCollectionFromEntitySet<Photo>("Photos");
funcOnEntity.Parameter<string>("AccessCode").Optional();

// Action on Album - Change Access Code
var action = builder.EntityType<Album>().Action("ChangeAccessCode");
action.Parameter<string>("AccessCode"); // .Optional();
action.ReturnsFromEntitySet<Album>("Albums");
```

Issue 2. Cannot call to Action:

```C#
        [HttpPost]
        public IActionResult ChangeAccessCode(int key, [FromODataUri] string AccessCode)
        {
            var album = _context.Albums.FirstOrDefault(c => c.Id == key);
            if (album == null)
            {
                return NotFound();
            }

            // album.AccessCode = (string)paras["AccessCode"];
            if (string.IsNullOrEmpty(AccessCode))
            {
                album.AccessCodeHint = null;
            } 
            else
            {
                album.AccessCodeHint = AccessCode;
            }

            _context.Attach(album);
            _context.SaveChanges();

            return Ok(album);
        }
```

Call it via URL results in 404: 
> https://localhost:25325/Albums(2)/ChangeAccessCode(AccessCode='aaa')


Change it to the following codes:
```C#
        [HttpPost]
        public IActionResult ChangeAccessCode(int key, ODataParameters paras)
        {
            var album = _context.Albums.FirstOrDefault(c => c.Id == key);
            if (album == null)
            {
                return NotFound();
            }

            album.AccessCode = (string)paras["AccessCode"];

            _context.Attach(album);
            _context.SaveChanges();

            return Ok(album);
        }
```

Call it via URL, again 404:
> https://localhost:25325/Albums(2)/ChangeAccessCode(AccessCode='aaa')


And it will work but there is no way to pass *paras*:
https://localhost:25325/Albums(2)/ChangeAccessCode

Not quite sure it is an issue in my repo, it will be much helpful if the sample project can give a clear usage. 

Thank you!

**Comment by xuzhg** [comment]
@alvachien 

your method signature should change as follows:

```
public IActionResult ChangeAccessCode(int key, ODataActionParameters parameters)
```
Then you can find your methods in `$odata`

![image](https://user-images.githubusercontent.com/9426627/107983953-b4358900-6f7b-11eb-9a0f-f5607f98848c.png)

To call the `Action`, you should use 
1) Post
2) https://localhost:25325/Albums(2)/ChangeAccessCode   // without any parameter
3) request content type: appliation/json
4) request body:

```json
{
    "AccessCode":"abc"
}

```

**Comment by alvachien** [comment]
@xuzhg 

Thank you very much!

Now it works.
