### ISSUE TITLE
Linq errors with queries, only when code is deployed.

### ISSUE THREAD

**Issue by ScottLeWarne** [OData/AspNetCoreOData#902]
Hi, my team is experiencing some odd behavior with the OData library that we are looking for some help with.  We are using the latest version, 8.1.1.  We've been using the library in our app for about a year now but have ran into some issues recently with certain queries, mainly ones that use the 'any' and 'all' lambda's across relationships.  The queries are failing to translate to Linq, but the really odd part is that the exception is only thrown when running against the published code in the app service, it works just fine when running locally in Visual Studio (in either of debug or release modes).

We are using .net 7 and the latest versions of this and related libraries.  Locally we run on Windows with the latest Visual Studio version, and we publish to Azure app services running Linux.

Below is the exception.  A type seems to be missing, but I'm unable to debug in and pinpoint what type specifically because it doesn't throw the exception when running locally.

Any ideas around what might be causing this exception, or to the bigger question of why the exception is only throw in published code?

[
    {
        "id": "49494617",
        "message": "Value cannot be null. (Parameter 'type')",
        "outerId": "0",
        "parsedStack": [
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 0,
                "line": 0,
                "method": "System.ArgumentNullException.Throw"
            },
            {
                "assembly": "System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
                "level": 1,
                "line": 0,
                "method": "System.Linq.Expressions.Expression.Parameter"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 2,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.Expressions.QueryBinderContext.HandleLambdaParameters"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 3,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.Expressions.QueryBinder.BindAnyNode"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 4,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindFilter"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 5,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 6,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo"
            },
            {
                "assembly": "ECAR.ElasticDataService.Query.API, Version=1.0.0.739, Culture=neutral, PublicKeyToken=null",
                "fileName": "D:\\a\\1\\s\\QueryAPI\\source\\ECAR.ElasticDataService.Query.API\\Infrastructure\\OData\\EdsEnableQueryAttribute.cs",
                "level": 7,
                "line": 68,
                "method": "ECAR.ElasticDataService.Query.API.Infrastructure.OData.EdsEnableQueryAttribute.ApplyQuery"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 8,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 9,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted"
            },
            {
                "assembly": "Microsoft.AspNetCore.OData, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                "level": 10,
                "line": 0,
                "method": "Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 11,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute+<OnActionExecutionAsync>d__6.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 12,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 13,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 14,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 15,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker+<<InvokeNextActionFilterAsync>g__Awaited|10_0>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 16,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 17,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 18,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 19,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 20,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 21,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 22,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 23,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 24,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 25,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 26,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 27,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 28,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 29,
                "line": 0,
                "method": "Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 30,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 31,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 32,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 33,
                "line": 0,
                "method": "Microsoft.AspNetCore.Routing.EndpointMiddleware+<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 34,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 35,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 36,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "Microsoft.AspNetCore.Authorization.Policy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
                "level": 37,
                "line": 0,
                "method": "Microsoft.AspNetCore.Authorization.AuthorizationMiddleware+<Invoke>d__9.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 38,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 39,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 40,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "ECAR.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "level": 41,
                "line": 0,
                "method": "ECAR.Core.WebApi.Middleware.FrontDoorExtensions+<>c__DisplayClass2_0+<<UseFrontDoorValidation>b__0>d.MoveNext"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 42,
                "line": 0,
                "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 43,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess"
            },
            {
                "assembly": "System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
                "level": 44,
                "line": 0,
                "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification"
            },
            {
                "assembly": "ECAR.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "level": 45,
                "line": 0,
                "method": "ECAR.Core.Services.ExceptionService.ExceptionHandlerMiddleware+<InvokeAsync>d__3.MoveNext"
            }
        ],
        "severityLevel": "Critical",
        "type": "System.ArgumentNullException"
    }
]

**Comment by mikepizzo** [comment]
@xuzhg  -- Can you work with Scott to help track this down?

**Comment by julealgon** [comment]
@ScottLeWarne are you 100% sure there is nothing different in your code in regards to setup/middlewares/etc when comparing development and production versions?

No `if (environment.IsDevelopment()) do x`-type statements that could be influencing this?

**Comment by ScottLeWarne** [comment]
Thanks to some help from @xuzhg we were able to resolve the issue.  Not 100% sure but we think the difference in behavior was due to windows and linux treating case-sensitive string compares differently.  We've implemented a custom IODataTypeMapper that uses a case-insensitive equals when looking for types and that seems to have done it.

Thanks again @xuzhg

**Comment by julealgon** [comment]
Could you provide a bit more detail on the specific use cases where the failures were happening @ScottLeWarne ? I'm actually a bit worried by this myself.

**Comment by xuzhg** [comment]
@julealgon

Thanks for follow up. There's an email thread to discuss it. Let me share some information.
At the beginning, my thoughts, (from the call stack) is that it seems the exception is thrown when calling 'Expression.Parameter' within HandleLambdaParameters at
[https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinderContext.cs#L213](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinderContext.cs#L213)

So, I guest ‘Model.GetClrType’ method returns null. 

Based on customer codes,  customer is using type-less Edm model (Type-less means you build the Edm model using ODL APIs, and there’s no C# types mapping by default).

In this case, ‘Model.GetClrType(…)’ heavily depends on the Edm type full name and C# types from IAssemblyResolver.

By default, we will use the Edm type full name to search all types from IAssemblyResolver, if matches, catch it and use it, otherwise ‘Model.GetClrType(…)’ returns ‘null’.

Here’s the default assembly resolver.
[https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Helpers/DefaultAssemblyResolver.cs](https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Helpers/DefaultAssemblyResolver.cs)

Here’s the matching codes:
```C#
private static IEnumerable<Type> GetMatchingTypes(string edmFullName, IAssemblyResolver assembliesResolver)
            => TypeHelper.GetLoadedTypes(assembliesResolver).Where(t => t.IsPublic && t.EdmFullName() == edmFullName);
```
You can see the naming matching is **case-sensitive**. Since customer uses linux for production (it can't work) and windows for local test (it works fine).
So, we guess "it is related to the type name case sensitivity on different platforms?" So far, we don't know the answer for this.

But, as a workaround i gave as below:

1)	Derived from DefaultODataTypeMapper
2)	Override the ‘GetClrType’, you can explicitly return the C# type using the given Edm type.
3)	Call edmModel.SetTypeMapper(…) extension method to set your own type mapper;

It seems the issue got resolved.

Here's the customer resonse:
_Using a custom type mapper looks to have resolved the issue.  I can’t pinpoint the exact issue, since I’m not able to do debugging under linux presently, but it’s resolved our issue.  And its given the hooks to put some logging around it as well, which helps._

**Comment by julealgon** [comment]
Thanks for the details @xuzhg . This looks like a nasty issue... shouldn't OData itself try to fix it instead of relying on a custom implementation from consumers like this? From the looks of it, it would affect at least a subset of users if not now, in the future, as Linux is gaining a lot of ground with .NET especially in production.

It does make me less nervous though to hear it only seems to impact this particular flow with an EDM model without links to the CLR types, since that's not as usual and certainly not something I see myself personally using.
