### ISSUE TITLE
Can you use $search inside of an any lambda?

### ISSUE THREAD

**Issue by ScottLeWarne** [OData/AspNetCoreOData#908]
Hi all,

I'm looking to verify whether or not the library supports using $search inside of an 'any' lambda, and if so how I would structure the $filter to support it?  

Take for example two entities: Student and Course
Student has a Courses navigation property to the Course entity.

I want to filter Students based on using $search for the Course entity to limit to certain named courses.  This is a first pass that does not work, and I'm sure is wrong, but first I wanted to make sure that it was even supported.

StudentCollection?$filter=Courses/any(x0:($search=Chemistry OR Botany))

**Comment by gathogojr** [comment]
Thanks @ScottLeWarne for raising the issue. OData currently doesn't support $search within a $filter expression. Can you try to use `contains`? You'd have to specify particular properties though when using `contains`.

**Comment by ScottLeWarne** [comment]
Thanks for the confirmation.
