### ISSUE TITLE
`CreateRefTo` / `DeleteRefTo` Property Casing issues

### ISSUE THREAD

**Issue by samtrion** [OData/AspNetCoreOData#911]
We are currently facing an issue with the latest versions (8.1.x), with unrecognized endpoints of Type `CreateRefTo{navigationProperty}` & `DeleteRefTo{navigationProperty}`.

When we define a method with the signature `public async ValueTask<IActionResult> DeleteRefToStandardDiscountAsync([FromRoute] int key, CancellationToken cancellationToken) { }`, the endpoint is not recognized. When we lower the first letter of the navigation property (`public async ValueTask<IActionResult> DeleteRefTostandardDiscountAsync([FromRoute] int key, CancellationToken cancellationToken) { }`) the method is fully recognized and functional. This is a strange behaviour, which we tracked down to
https://github.com/OData/AspNetCoreOData/blob/9225d1eba1601bf1470b7e611cdd595fa479dbfc/src/Microsoft.AspNetCore.OData/Routing/Conventions/RefRoutingConvention.cs#L104

We provide a possible fix in the next minutes.

**Comment by gathogojr** [comment]
@samtrion Thank you for reporting this issue. Quick question... Are you calling `EnableLowerCamelCase` method on the model builder in your scenario?

**Comment by samtrion** [comment]
No, we work with `IModelConfiguration`.

We have already tried in the `Program.cs`, various settings without effect:

```cs
// OData
.AddOData(options =>
{
    options.EnableQueryFeatures(100);

    options.RouteOptions.EnableKeyAsSegment = true;
    options.RouteOptions.EnableKeyInParenthesis = false;

    options.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;

    options.RouteOptions.EnablePropertyNameCaseInsensitive = true;
    options.RouteOptions.EnableActionNameCaseInsensitive = true;
    options.RouteOptions.EnableQualifiedOperationCall = false;
    options.RouteOptions.EnableUnqualifiedOperationCall = true;

    options.EnableNoDollarQueryOptions = false;
});
```

**Comment by gathogojr** [comment]
Hi @samtrion. How does your request URL for CreateRefTo{NavigationProperty} and DeleteRefTo{NavigationProperty} requests look like? Does it have the navigation property segment in case-insensitive form?
Asking because so far I haven't been able to reproduce the issue

Given a `Customer` type with a navigation property `Orders`, I'm able to hit the `DeleteRef` endpoint using both:
- /Customers/1/Orders/7/$ref - Title case `Orders`
- /Customers/1)/orders/7/$ref - Lower camel-case `orders`

**Comment by samtrion** [comment]
@gathogojr Happy to assist with this.

## Display: Swagger 
![Display: Swagger](https://github.com/OData/AspNetCoreOData/assets/3283596/62e61205-4c45-4531-b2d0-3407226d0248)
## Display: OData Endpoint Mappings 
![Display: OData Endpoint Mappings](https://github.com/OData/AspNetCoreOData/assets/3283596/d0ff809e-ff72-419c-8665-eeb31520251c)

```cs
public class Plant
{
    // Implementation shortened ....

    /// <summary>
    /// Referenced <see cref="BaseData.StandardDiscount"/>
    /// </summary>
    public StandardDiscount? StandardDiscount { get; set; }
}
```

**Comment by samtrion** [comment]
Info: `/api/v1/$metadata`

```xml
<EntitySet Name="Plants" EntityType="MB.DLM.Entities.Locations.Plant">
    <NavigationPropertyBinding Path="calendars" Target="Calendars"/>
    <NavigationPropertyBinding Path="clientPermissions" Target="ClientPermissions"/>
    <NavigationPropertyBinding Path="costCenters" Target="CostCenters"/>
    <NavigationPropertyBinding Path="locations" Target="Locations"/>
    <NavigationPropertyBinding Path="standardDiscount" Target="StandardDiscounts"/>
    <NavigationPropertyBinding Path="suppliers" Target="Suppliers"/>
</EntitySet>
```

**Comment by gathogojr** [comment]
@samtrion I was able to repro the issue. Thank you for your PR contribution. I left a comment to add a test or tests to verify that the change fixes the issue

**Comment by samtrion** [comment]
I will add Tests later today.

**Comment by samtrion** [comment]
@gathogojr updated the PR and added tests
