### ISSUE TITLE
OData not working in F#

### ISSUE THREAD

**Issue by ckashyap91** [OData/AspNetCoreOData#913]
I am trying to create Odata service in F#. Using Below packages.

 "Microsoft.AspNetCore.OData" Version="8.0.12"
 "Microsoft.EntityFrameworkCore" Version="7.0.5"
 "Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5"
Struggling with Finding a proper example for this.

![image](https://github.com/OData/AspNetCoreOData/assets/17470191/d58b2e78-6da4-4a98-8805-11430993107d)

I have tried AddModel but AddModel is not found in ODataOptions.

What's the correct way to do it in F#?

Same code working into C#.

Also, GetEdmModel throws an error. Which is also not in the case of C#.

System.InvalidOperationException
  HResult=0x80131509
  Message=The entity set 'Persons' is based on type 'ODataServiceApp.Data.Person' that has no keys defined.
  Source=Microsoft.OData.ModelBuilder
  StackTrace:
   at Microsoft.OData.ModelBuilder.ODataModelBuilder.ValidateModel(IEdmModel model)
   at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.ValidateModel(IEdmModel model)
   at Microsoft.OData.ModelBuilder.ODataModelBuilder.GetEdmModel()
   at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.GetEdmModel()
   at ODataServiceApp.Program.main(String[] args) in E:\Project\ODataServiceApp\Program.fs:line 50

Is there any difference between C# and F#?

**Comment by gathogojr** [comment]
Thanks @ckashyap91 for raising the issue. Could you please the class definitions for `Person` for both C# and F#?

**Comment by ckashyap91** [comment]
Its same in both
type Person = 
     {
        Id: int
        FirstName: string
        LastName: string
        Age: int
     }
 
public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
    }

**Comment by gathogojr** [comment]
@ckashyap91 I suspect that the model builder is not able to infer the key property in the case of F# by convention. Luckily, you have the option to explicitly specify the key property using the model builder fluent API. The code below should do it:
```fsharp
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.OData
open Microsoft.Extensions.DependencyInjection
open Microsoft.Extensions.Hosting
open Microsoft.OData.ModelBuilder
open Models  // Namespace for Person type

[<EntryPoint>]
let main args =
    let builder = WebApplication.CreateBuilder(args)

    let modelBuilder = new ODataConventionModelBuilder();
    modelBuilder.EntitySet<Person>("Persons").EntityType.HasKey(fun d -> d.Id) |> ignore
    
    let model = modelBuilder.GetEdmModel()

    builder.Services.AddControllers().AddOData(fun options ->
        options.EnableQueryFeatures().AddRouteComponents(model) |> ignore) |> ignore

    let app = builder.Build()

    app.UseRouting() |> ignore
    app.UseEndpoints(fun endpoints ->
        endpoints.MapControllers() |> ignore) |> ignore

    app.Run()

    0 // Exit code
```

**Comment by xuzhg** [comment]
By the way, 'AddModel ' is replaced as 'AddRouteComponents' since 8.0.0 RTM. Thanks.

**Comment by ckashyap91** [comment]
Thanks @gathogojr 
Its working.
Closing this bug.

Is this documentented somewhere? Because I have spent lots of time to make it working.
Thanks in advance.
