### ISSUE TITLE
Use ODataProperty directly to write Edm.Untyped property

### ISSUE THREAD

**Issue by xuzhg** [OData/AspNetCoreOData#923]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**

**Reproduce steps**
As these comments mentioned, 
https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs#L1338-L1351

When updating to ODL 7.16.0, please fix it.

**Data Model**
Please share your Data model, for example, your C# class.

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Request/Response**
Please share your request Uri, head or the request body
Please share your response head, body.

**Expected behavior**

**Screenshots**

**Additional context**
Please share your call stack or any error message

**Comment by corranrogue9** [comment]
There is an ODL fix PR [here](https://github.com/OData/odata.net/pull/2664)

**Comment by corranrogue9** [comment]
Once the new ODL version has been released, we should take that version and remove the code that @xuzhg  has referenced in this issue.
