### ISSUE TITLE
Removing Metadata Controller

### ISSUE THREAD

**Issue by michallabuzsybilla** [OData/AspNetCoreOData#932]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.2.0

**Describe the bug**
I want to completely remove Metadata controller. I dont want it, I dont use it, I want it gone. Is there currently any way to remove it?

**Configuration**
Below you can find my startup configuration

```
            services.AddControllers()
                .AddOData(
                    options =>
                    {
                        options.AddRouteComponents("api/my-route/odata", GetEdmModel())
                            .Filter()
                            .Select()
                            .OrderBy()
                            .Count()
                            .SetMaxTop(100);
                    });
```

Example of my Controller:

```
    [ApiController]
    [Route("api/my-route/odata")]
    [ODataAttributeRouting]
    public sealed class ODataController : BaseController
    {
        private readonly ODataValidationSettings _validationSettings;
        private readonly ODataQuerySettings _querySettings;
        private readonly IMapper _mapper;
        private readonly IDataService _dataService;
        public ODataController(IMapper mapper, IDataService dataService) 
        {
            _dataService = dataService;
            _mapper = mapper;
            _validationSettings = new ODataValidationSettings
            {
                MaxTop = 100,
                AllowedQueryOptions = AllowedQueryOptions.All & ~AllowedQueryOptions.Select & ~AllowedQueryOptions.Expand,
            };
            _querySettings = new ODataQuerySettings() { PageSize = 100, TimeZone = TimeZoneInfo.Utc };
        }

        [HttpGet("myobjects")]
        public ActionResult<List<MyObjectDto>> GetMyObjects(ODataQueryOptions<MyObjectDto> options)
        {
           var query = _dataService.GetMyObjects(_claimService)
                                   .ProjectTo<MyObjectDto>(Mapper.ConfigurationProvider);
           var objects= options.ApplyTo(query, _querySettings)
                               .Cast<MyObjectDto>()
                               .ToList();
           //do something with list

           return Ok(objects);
        }
     }
```

**Expected behavior**
I want to end up ONLY with methods from my controller (GET myobjects). I dont want Metadata like below:
![image](https://github.com/OData/AspNetCoreOData/assets/119861943/64f82269-54a8-4450-9668-798dda8b6fa9)

Is there any way to remove it? And just to be clear - I dont want to remove it only from Swagger, I just dont want to expose these endpoints at all

**Comment by awbacker** [comment]
Does the approach presented in issue #866 help, and can you remove it directly from the conventions collection?

```
builder.Services.AddControllers().AddOData(options =>
{
    // find the convention instance in the list and remove it
    options.Conventions
        .Where(c => c is MetadataRoutingConvention)
        .ToList()
        .ForEach(c => options.Conventions.Remove(c));

    ...
```

You can also reverse that and choose which ones to keep:

```
builder.Services.AddControllers().AddOData(options =>
{
    // for example, keep only these two conventions
    options.Conventions
        .Where(c => c is not EntitySetRoutingConvention)
        .Where(c => c is not AttributeRoutingConvention) // notices [HttpGet], does formatting
        .ToList()
        .ForEach(c => options.Conventions.Remove(c));

    options.AddRouteComponents("my-route/odata/", ODataModel.GetEdmModel())
        .Filter()
        .Select();
});
```

**Comment by michallabuzsybilla** [comment]
This approach indeed removes controllers but Swagger are still presenting models related to this controller (like ETag)

**Comment by awbacker** [comment]
That method removes conventions, some of which link routes to controllers, yes.  There should be no metadata endpoint now, as you asked, is that correct?

**Comment by julealgon** [comment]
@michallabuzsybilla is the controller causing you any problems? I don't get why someone would go out of their way to try and remove something that is part of the OData spec that is so transparent to dev (i.e. has no extra code to maintain) as well as is only activated on request.

Was curious if there was more to this than just "I don't use it".

**Comment by michallabuzsybilla** [comment]
> That method removes conventions, some of which link routes to controllers, yes. There should be no metadata endpoint now, as you asked, is that correct?
> 
> As to swagger - you want the swagger _page_ but not the swagger _models_, is that what you mean? I'm confused then, because one is needed to create the other.

It is correct, there is no metadata endpoint now. There are, however, EDM related models in Swagger models definition, like below
![image](https://github.com/OData/AspNetCoreOData/assets/119861943/b02a1514-d50e-4b3f-a11a-0d2457353e17)
But I just realized that they come from ODataQueryOptions (that I am using), not from MetadataController. Thats my mistake, sorry!

> @michallabuzsybilla is the controller causing you any problems? I don't get why someone would go out of their way to try and remove something that is part of the OData spec that is so transparent to dev (i.e. has no extra code to maintain) as well as is only activated on request.
> 
> Was curious if there was more to this than just "I don't use it".

Well, I see number of reasons one might not want to have it and one of them is to hide that OData is used. As you might have noticed I am using ODataQueryOptions with Enumerable returned from controller instead of IQueryable. I am not using most of the OData features and its not even possible to use them (like expand or select). I use OData mostly for filtering and pagination. I have C# client defined that is dealing with OData queries internally. I dont really see how it could be beneficial in any way to expose Metadata. On the other hand it raises question from customers - what is it, why is it there, why are there only specific models defined etc. Its just too much troubles, at least in my case.

Anyway, problem solved - mentioned endpoint is gone

**Comment by ElizabethOkerio** [comment]
Closing this as was answered.
