### ISSUE TITLE
Is it possible to make SearchBinder and batch functionality work together?

### ISSUE THREAD

**Issue by AndriiLesiuk** [OData/AspNetCoreOData#933]
I have this part of code in my Program class in my Asp.Net Core web api
Here I make some settings to work with the Odata protocol:

`builder.Services.AddControllers().AddOData(opt =>
{
    opt.EnableQueryFeatures(3000);
    opt.AddRouteComponents(routePrefix: "odata", model: modelBuilder.GetEdmModel(), services => services.AddSingleton<ISearchBinder, SearchBinder>());
    opt.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;
    opt.EnableAttributeRouting = true;
});`

![image](https://github.com/OData/AspNetCoreOData/assets/50627950/9a0e5067-cc82-47b2-a21e-61b93a7e5721)

In this function I need to use batchHandler as parammeter in order to be able to implement batch functionality:
https://localhost:port/odata/$batch

But the AddRouteComponents() method does not have an overload to pass all parameters together.
I tried this but it doesn't work either:

`
opt.AddRouteComponents(routePrefix: "odata", model: modelBuilder.GetEdmModel(), services => services.AddSingleton<ISearchBinder, SearchBinder>().AddSingleton(batchHandler));
`
![image](https://github.com/OData/AspNetCoreOData/assets/50627950/0fdb671f-a32e-496f-9603-e17f911507d0)

It is also not possible to use this method 2 times, because GetEdmModel() can be called only once.

Can this functionality be used together?

Microsoft.AspNetCore.OData 8.2.0
.NET 7.0

**Comment by ElizabethOkerio** [comment]
@AndriiLesiuk you can configure more than one service with the `AddRouteComponents`

For Example You can do something like this: 

```c#
 builder.Services.AddControllers()
            .AddOData(
                .AddRouteComponents(
                    "odata",
                    EdmModelBuilder.GetEdmModel(),
                    services => services.AddSingleton<ISearchBinder, SearchBinder>().
                        AddSingleton<ODataBatchHandler, batchHandler>()
                ) 
            )
```

Are you getting any exceptions when you try this?
