### ISSUE TITLE
Metadata Controller missing when using OData in an WebApi Project as Class Library

### ISSUE THREAD

**Issue by vaecone** [OData/AspNetCoreOData#935]
**Assemblies affected**
ASP.NET Core OData 8.04 and up

**Describe the bug**
The Metadata-Controller routes are missing, when the Api is a Class Library. 
An additional Console Application runs the Api, needed when you want to run an API as a Windows-Service for example. 

The Metadata-Routes disappeared as i switched the Projecttype from Console Application to Class Library. 
When i run my API Project directly it works. 

**Reproduce steps**
I created a sample Repository.: https://github.com/vaecone/ExampleApi

1. API as Class Library.
2. Additional Console Application running the API using the WebHostBuilder.
3. Run the Project. 
4. Call /$odata or /api/odata/$metadata#Teams using Postman/wget/curl
5. Metadata routes missing in the endpoint mappings

**Data Model**
https://github.com/vaecone/ExampleApi/blob/main/ExampleApi.Shared/Models/Team.cs
Ill tried different Models. 

**EDM (CSDL) Model**
$metadata is not working. 

**Request/Response**
Request: https://localhost:5001/$odata
Response: 
```
<html>

<head>
	<title>OData Endpoint Routing Debugger</title>
	<style>
		table {
			font-family: arial, sans-serif;
			border-collapse: collapse;
			width: 100%;
		}

		td,
		th {
			border: 1px solid #dddddd;
			text-align: left;
			padding: 8px;
		}

		tr:nth-child(even) {
			background-color: #dddddd;
		}
	</style>
</head>

<body>
	<h1 id="odata">OData Endpoint Mappings</h1>
	<p>
		<a href="#standard">Go to none OData endpoint mappings</a>
	</p>
	<table>
		<tr>
			<th> Controller & Action </th>
			<th> HttpMethods </th>
			<th> Template </th>
		</tr>
		<tr>
			<td>ExampleApi.Controllers.TeamsController.Get (ExampleApi)</td>
			<td>GET</td>
			<td><a href="api/odata/Teams">api/odata/Teams</a></td>
		</tr>
		<tr>
			<td>ExampleApi.Controllers.TeamsController.Get (ExampleApi)</td>
			<td>GET</td>
			<td><a href="api/odata/Teams/$count">api/odata/Teams/$count</a></td>
		</tr>

	</table>
	<h1 id="standard">None OData Endpoint Mappings</h1>
	<p>
		<a href="#odata">Go to OData endpoint mappings</a>
	</p>
	<table>
		<tr>
			<th> Controller </th>
			<th> HttpMethods </th>
			<th> Template </th>
		</tr>

	</table>
</body>

</html>
```

**Expected behavior**
I expect the Metadata routes to be attached and visible.

**Screenshots**

**Additional context**
See the sample Repo: https://github.com/vaecone/ExampleApi
If you got errors, change or remove the global.json

**Comment by xuzhg** [comment]
@vaecone 
Please explicitly add the assembly into the ApplicationPart and let ASP.NET Core to identify the controller.

![image](https://github.com/OData/AspNetCoreOData/assets/9426627/d440b176-a3aa-4f92-b7f1-beb861508209)

At OData side, maybe consider to add the Controller by default if Customer calls 'AddOData'.

**Comment by vaecone** [comment]
@xuzhg Thank you for your quick Response. That solves the Problem for me. 

The metadata Controller is added by default if the WebApi solution is startet directly. 
In my case, only if the project type is changed to Library and then is started&referenced by another project, the metadata Controller is not added automatically. 

We use the Odata Library in our software and in earlier Versions this architectury was no probllem. I think this changed when we upgraded to .NET 6.
