### ISSUE TITLE
Excluding model fields from response model does not seem to work

### ISSUE THREAD

**Issue by oionut** [OData/AspNetCoreOData#937]
**Assemblies affected**
ASP.NET Core OData 8.1.2

**Describe the bug**
I have a query only OData endpoint and I need to hide one of the model fields.
The solution I'm trying to use is the one documented [here](https://learn.microsoft.com/en-us/odata/webapi/odata-security#edm-security), the programmatically one as I need to keep my models clean.

I have Edm model builder configured as follows:
```
public static IEdmModel Get()
{
    var builder = new ODataConventionModelBuilder();
    builder.EnableLowerCamelCase();
    builder.AddEntityType(typeof(MyModelBase));
    var model = builder.EntitySet<MyModel>("MyModel");
    model.EntityType.Ignore(m => m.PropertyToHide);
    return builder.GetEdmModel();
}
```

The OData registration as follows:
```
builder.AddOData((Action<ODataOptions>) (options =>
{
       options.Conventions.Remove(options.Conventions.OfType<MetadataRoutingConvention>().First());
       options.EnableQueryFeatures().AddRouteComponents("api", EdmModel.Get())));
})
```

And the controller action:
```
public IQueryable<MyModel> Get()
{
    return _dbContext.MyModel!.AsNoTracking();
}
```

What I'm expecting to happen (and try to achieve) is to have the PropertyToHide field excluded from the response model, but this does not happen.
Isn't this the way the Ignore feature should be used?

**Comment by awbacker** [comment]
I ignore may fields this way, with no issue.  Can you try reformatting your post to include code blocks?

```
var builder = new ODataConventionModelBuilder();

var pi = builder.EntitySet<Room>("Rooms");
pi.EntityType.Ignore(o => o.Location);
pi.EntityType.Ignore(o => o.LocationId);

return builder.GetEdmModel();
```

**Comment by oionut** [comment]
> 1. Can you try reformatting your post to include code blocks?

Done

> 2. Does it work if you don't remove the Metadata route?

 I've tried this but the end result is the same (the property is noignored)

**Comment by awbacker** [comment]
Does it work right if you remove the line: `builder.AddEntityType(typeof(MyModel));`.

**Comment by oionut** [comment]
Hi @awbacker, thanks for the suggestion. This was indeed what causes the issue (it is actually the addition of MyModel base class), I will close this though not sure why it behaves like this.
