### ISSUE TITLE
Missing Release and tag for 8.2.0

### ISSUE THREAD

**Issue by owns** [OData/AspNetCoreOData#938]
**Assemblies affected**
https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.2.0

**Describe the bug**
The repo is missing a release & tag for 8.2.0.
This is just an oddity I noticed, and wanted to bring it to your attention in case it was missed.

**Reproduce steps**
1. view NuGet package
2. View repo to check what changes where pushed.
3. no release or tag to see what commits went in.

**Data Model**
NA

**EDM (CSDL) Model**
NA

**Request/Response**
NA

**Expected behavior**
Each new package version has a corresponding release and tag.

**Screenshots**
NA

**Additional context**
NA

**Comment by xuzhg** [comment]
@owns Thanks for reporting. I added the tag and the release. Thanks.
