### ISSUE TITLE
NuGet version 8.2.0 is different from Github release 8.2.0

### ISSUE THREAD

**Issue by fabiocbr75** [OData/AspNetCoreOData#950]
Hello,
The NuGet version 8.2.0 (18 May) doesn't contain all the "What's Changed" included in the GitHub release (commits on 30 May).
Can you check and put on NuGet the right version? 
From the point of view of release management is a critical bug don't have the "binary" aligned with the sources.

Best regards,
Fabio

**Comment by xuzhg** [comment]
do you mean this location?  https://github.com/OData/AspNetCoreOData/releases/tag/8.2.0

@fabiocbr75
