### ISSUE TITLE
Fetching data of type DateTimeOffset is serialized as Datetime UTC  in response 

### ISSUE THREAD

**Issue by padhumailin** [OData/AspNetCoreOData#957]
**Assemblies affected**
NET6
ODATA  8.0.12

**Describe the bug**
In sql we have stored data of type datetimeoffset, when reading the data with ODATA enabled API endpoint, and also the DTO with the type  DateTimeOffset. 

But the API response is returned as type UTC formatted DateTime type

**Reproduce steps**
DTO
public class Period{
public DateTimeOffset? StartDateTime { get; set; }
}

**EDM (CSDL) Model**
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
var Period = builder.ComplexType<Period>();
Period.Property(fields => fields.StartDateTime);

**Response**
{
"StartDateTime" : "2019-06-28T00:00:00Z"
}

**Expected behavior**
{
"StartDateTime" : "2019-06-28T00:00:00.00+00:00"
}

This happens only when odata is enabled, but without an odata enabled endpoint. the response is returned as value stored in SQL table the expected behaviour.

Is there any way the show the datetimeoffset value as it in SQL field in a odata read endpoint?

**Comment by gathogojr** [comment]
@padhumailin Thank you for reporting the issue.
`2019-06-28T00:00:00Z` is equivalent to `2019-06-28T00:00:00.00+00:00`

https://262.ecma-international.org/#sec-date-time-string-format
> Z is the UTC offset representation specified as "Z" (for UTC with no offset) or an offset of either "+" or "-" followed by a time expression HH:mm (indicating local time ahead of or behind UTC, respectively)
 
It'd appear that our library uses the UTC offset representation when the datetimeoffset value is in UTC. The longer format is used for the other timezones. I can understand why you'd want the display format consistent and we'll look into how we can make it happen.

For now, you could supply your own converter as follows:

1. Override `ODataPayloadValueConverter`
    ```csharp
    public class CustomODataPayloadValueConverter : ODataPayloadValueConverter
    {
        public override object ConvertToPayloadValue(object value, IEdmTypeReference edmTypeReference)
        {
            if (edmTypeReference.PrimitiveKind() == EdmPrimitiveTypeKind.DateTimeOffset)
            {
                var dateTimeOffset = (DateTimeOffset)value;
                return dateTimeOffset.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffffzzz");
            }

            return base.ConvertToPayloadValue(value, edmTypeReference);
        }
    }
    ```
2. Inject the custom converter into the DI container
    ```csharp
    var builder = WebApplication.CreateBuilder(args);

    var modelBuilder = new ODataConventionModelBuilder();
    // YOUR LOGIC FOR BUILDING EDM MODEL

    builder.Services.AddControllers().AddOData(
        options =>
        {
            options.AddRouteComponents(
                routePrefix: string.Empty,
                model: modelBuilder.GetEdmModel(),
                configureServices: (services) =>
                {
                    services.AddSingleton<ODataPayloadValueConverter>(sp => new CustomODataPayloadValueConverter());
                });
        });

    var app = builder.Build();

    app.UseRouting();
    app.UseEndpoints(endpoints => endpoints.MapControllers());

    app.Run();
    ```

**Comment by padhumailin** [comment]
Thanks @gathogojr .

In the  custom converter, you are formatting to the desired result as string
` return dateTimeOffset.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffffzzz"); // YOUR DESIRED FORMAT HERE`

so for this OData parameter $filter will not work as a DateTime datatype? am i right.

**Comment by gathogojr** [comment]
@padhumailin The `DateTime` is automatically mapped to `Edm.DateTimeOffset` type by the OData library. The Edm doesn't support an `Edm.DateTime` data type.
Whether the data type is DateTimeOffset or DateTime, and irrespective of the format string you apply on the converter, you should be able to do:
```
$filter=DateField eq 2019-06-28T00:00:00Z
```
or
```
$filter=DateField eq 2019-06-28T00:00:00.00+00:00
```
or
```
$filter=DateField eq 2019-06-28T00:00:00.00Z
```
or
```
$filter=DateField eq 2019-06-28T00:00:00.000000Z
```
or
```
$filter=DateField eq 2019-06-28T00:00:00.000000+00:00
```
The formatting is a display concern.

**Note**: On the URL, you may need to replace `+` with `%2B` since `+` is reserved for a different use on a URL.

**Comment by gathogojr** [comment]
The OData team had a long discussion and decided against implementing a change to format `DateTimeOffset` values (and `DateTime` values by extension) into the longer format where the shorter UTC offset representation (using "Z") is possible. Both representations adhere to the ISO 8601 interchange standard and depending on the requirements, there are those who favour the shorter representation - for reason of payload size for example. Given that there's a reasonably easy-to-implement workaround to tweak the representation, the team prefers to maintain the current behaviour.
