### ISSUE TITLE
PageResult invalid de/serialization

### ISSUE THREAD

**Issue by johan-v-r** [OData/AspNetCoreOData#96]
Referred here from [aspnetcore](https://github.com/dotnet/aspnetcore/issues/30362)

### Describe the bug

`Microsoft.AspNet.OData.PageResult` excludes properties when serializing, and fails on deserialization with `System.Text.Json.JsonSerializer`

### To Reproduce
```cs
var foo = new Microsoft.AspNet.OData.PageResult<string>(new List<string>
{
	"test"
}, new Uri("http://foo"), 1);

var json = System.Text.Json.JsonSerializer.Serialize(foo); // serializes to [\"test\"]
var bar = System.Text.Json.JsonSerializer.Deserialize<Microsoft.AspNet.OData.PageResult<string>>(json); // throws System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated.
```

### Exceptions (if any)

>  System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
    ---- System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated.

### Further technical details
- ASP.NET 5.0

**Comment by johan-v-r** [comment]
Get the same behavior from the `microsoft.aspnetcore.odata\8.0.0-preview3` package:
```cs
var foo = new Microsoft.AspNetCore.OData.Results.PageResult<string>(new List<string>
{
	"test"
}, new System.Uri("http://foo"), 1);

var json = System.Text.Json.JsonSerializer.Serialize(foo); // serializes to [\"test\"]
var bar = System.Text.Json.JsonSerializer.Deserialize<Microsoft.AspNetCore.OData.Results.PageResult<string>>(json); // System.NotSupportedException : The collection type 'Microsoft.AspNetCore.OData.Results.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated.
```

This is also an issue when wanting to return these values from an endpoint as I've detailed [here](https://stackoverflow.com/q/59844505/5954805).

The workaround is to use `Newtonsoft.Json` for now, but ideally wouldn't want to always rely on that.

**Comment by xuzhg** [comment]
@johan-v-r I have a new value converter implemented at: "https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs".

Can you try it? It can get from nightly bit, or from the source code (project reference)

**Comment by johan-v-r** [comment]
Thanks @xuzhg the serialization works with the below:

```cs
var foo = new Microsoft.AspNetCore.OData.Results.PageResult<string>(new List<string>
{
    "test"
}, new System.Uri("http://foo"), 1);

var options = new JsonSerializerOptions();
options.Converters.Add(new PageResultValueConverter());

var json = System.Text.Json.JsonSerializer.Serialize(foo, options); // serializes to "{\"items\":[\"test\"],\"nextpagelink\":\"http://foo\",\"count\":1}"
var bar = System.Text.Json.JsonSerializer.Deserialize<Microsoft.AspNetCore.OData.Results.PageResult<string>>(json, options); // NotImplementedException
```

Can you please explain why [deserialization is not allowed](https://github.com/OData/AspNetCoreOData/blob/b14b02102ca0d571bb9a41bf7028c12e3616f307/src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs#L49)? What's the alternative for consuming services?

**Comment by xuzhg** [comment]
@johan-v-r Deserialize for PageResult doesn't make sense. 
From OData spec, there's no scenarios supporting this.

Can you share your thought about the scenario to read a pageresult request payload? 

Since it's working. Let me close it.

If you have further question, let me know or create a new issue. Thanks

**Comment by johan-v-r** [comment]
I'm consuming an OData endpoint from another .NET service, and need to inspect the **response** payload.
The above examples are just to illustrate the behavior, which again works fine with `Newtonsoft.Json`.

Don't think it's too crazy to expect both serialization and deserialization to work for the same type..?

**Comment by johan-v-r** [comment]
Hi @xuzhg - any advice on how to consume and deserialize the response in C#?

Deserializing `PageResult<T>` in the latest `Microsoft.AspNetCore.OData` v8.0.7 with `Newtonsoft.Json` now also fails.

**Comment by johan-v-r** [comment]
I think we just used the old version, or created a custom POCO with that structure. Neither really ideal solutions unfortunately.

**Comment by DzonnyDZ** [comment]
Hi, how am I supposed to use `PageResultValueConverter`? If I just return `PageResult<T>` from a controller it serializes as array, not as object. If I register `PageResultValueConverter` using reflection like

    builder.Services.AddControllers().AddJsonOptions(o => o.JsonSerializerOptions.Converters.Add((JsonConverterFactory)Activator.CreateInstance(Type.GetType("Microsoft.AspNetCore.OData.Results.PageResultValueConverter, Microsoft.AspNetCore.OData", true)!)!));

it works, but is there some public way to do this?

**Comment by baruba-cons** [comment]
> it works, but is there some public way to do this?

The class modifier would need to be changed from `internal`.

https://github.com/OData/AspNetCoreOData/blob/7b710507d4330ebd702a11485641f9b869c7367e/src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs#L15

It would be great if a custom converter type could also be specified.

`public class PageResultValueConverter(Type converterType) : JsonConverterFactory`

**Comment by mguinness** [comment]
> it works, but is there some public way to do this?

The class modifier would need to be changed from `internal`.

https://github.com/OData/AspNetCoreOData/blob/7b710507d4330ebd702a11485641f9b869c7367e/src/Microsoft.AspNetCore.OData/Results/PageResultValueConverter.cs#L15

It would be great if a custom converter type could also be specified.

`public class PageResultValueConverter(Type converterType) : JsonConverterFactory`
