### ISSUE TITLE
Getting 404 with [HttpPatch]

### ISSUE THREAD

**Issue by petkau-pin** [OData/AspNetCoreOData#97]
Hi,
I'm trying to build a very simple OData sample with one ODataController. It works well except I can't update entities using `[HttpPatch]`. I always get 404 response.
The implementation:
```cs
public class PackagesController: ODataController
{
    private readonly PackageDatabaseContext _context;

    public PackagesController(PackageDatabaseContext context)
    {
.....
    }
    [EnableCors("MySuspiciousHeaderPolicy")]
    [HttpPatch]
    public IActionResult Patch(int id, Delta<Package> package)
    {
        var originalPackage = _context.Packages.FirstOrDefault(p => p.Id == id);
        if (originalPackage == null)
        {
            return NotFound($"Not found {nameof(Package)} with id = {id}");
        }

        package.Patch(originalPackage);
        _context.SaveChanges();
        return Updated(originalPackage);
    }
```

The NuGet packages:
![image](https://user-images.githubusercontent.com/78539547/108982274-48979e00-7696-11eb-9684-3bee4477b90d.png)

The header policy is to allow any requests from any addresses.
Can anyone point me to the right direction here?

**Comment by xuzhg** [comment]
@petkau-pin Can you share a repo? 
Or would you please try to check at your side with this controller 'https://github.com/OData/AspNetCoreOData/blob/master/sample/ODataRoutingSample/Controllers/ODataEndpointController.cs` (Might need some code change owing to the display name)

**Comment by magneticcore** [comment]
Hi @petkau-pin ,

We had the same problem with the same versions of dependencies of assemblies.
What we did is to remove the [HttpXXX] on CRUD functions of OData controllers (Put, Post, Patch, Delete).

Juste remove [HttpPatch], OData will search Patch() or PatchPackage() functions.

**Comment by petkau-pin** [comment]
Hi,
It seems that `MySuspiciousHeaderPolicy` with CORS was causing the error. Thanks for the help.
