### ISSUE TITLE
Make UpdatedODataResult inherit from ObjectResult

### ISSUE THREAD

**Issue by Yglioh** [OData/AspNetCoreOData#972]
In a recent fix #906, `CreatedODataResult` was modified to inherit from `ObjectResult`. This resolved some issues when applying query options in a POST operation.

`UpdatedODataResult` actually suffers from the same issue and PUT and PATCH operations would benefit when it would also inherit from `ObjectResult`. This would I believe also solve #434.

Is this something that can be implemented? Or would a pull request help?

**Comment by habbes** [comment]
@KenitoInc is there a reason `UpdatedODataResult` does not also inherit from `ObjectResult`?

**Comment by KenitoInc** [comment]
@habbes There is no reason.
We should update the inheritance.
