### ISSUE TITLE
OData one-to-many relationship $expand not working

### ISSUE THREAD

**Issue by KamranMammadov** [OData/AspNetCoreOData#982]
```
public class CustomerEntity
{
    public int Id { get; set; }
    public ICollection<ProductEntity>? Products { get; set; }
}

public class ProductEntity
    {
        public string Code { get; set; } = string.Empty;
        [ForeignKey("CustomerId")]
        public int? CustomerId { get; set; }
        public CustomerEntity? Customer { get; set; }
    }
```
 Models:
```
 public class CustomerModel
{
    public int Id { get; set; }
    public ICollection<ProductModel>? Products { get; set; }
}

public class ProductModel
    {
        public string Code { get; set; } = string.Empty;
        public CustomerModel? Customer { get; set; }
    }
```
DTO:
```
 public class CustomerModel
{
    public int Id { get; set; }
    public ICollection<ProductModel>? Products { get; set; }
}

public class ProductModel
    {
        public string Code { get; set; } = string.Empty;
        public CustomerModel? Customer { get; set; }
    }
```

**Comment by KamranMammadov** [comment]
and I get Error when I want use :
https://localhost:7173/api/v1/ODataCustomers?$expand=products
Error:
The LINQ expression '$it => new SelectAll<ProductModel>{ \r\n    Model = __TypedProperty_1, \r\n    Instance = $it, \r\n    UseInstanceForProperties = True \r\n}\r\n' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

**Comment by julealgon** [comment]
@KamranMammadov did you figure it out? Or did you close this by mistake?

**Comment by KamranMammadov** [comment]
I use 2 time _mapper.ProjectTo 
First in my Generic Repository then in Service layer.


> @KamranMammadov did you figure it out? Or did you close this by mistake?

**Comment by KamranMammadov** [comment]
> @KamranMammadov , if you want to discuss a completely different topic, I'd recommend starting a discussion.
> 
> However, on the question about Clean Architecture, the only thing I can see happening is that you might want to isolate querying from other layers, but this will for the most part force you to pass `ODataQueryOptions<T>` manually down into your repository layer (your repository interface would take `ODataQueryOptions<T>` as a parameter).
> 
> I would not recommend attempting to "abstract away" `ODataQueryOptions<T>` at this point since it is a fairly complex beast. This will mean that you might have to reference the OData package in a bunch of projects however.
> 
> If that's not enough information for you please open a discussion and we can talk about it more over there.

@julealgon  interesting part is - everything works with CustomerEntity but when I want get Products with $expand=Customer, it throw exception.

**Comment by julealgon** [comment]
@KamranMammadov can you share your OData setup code including the EDM model as well as how you are applying the `ODataQueryOptions`?

If you could also share the specific exception details you are seeing that would be good.

**Comment by KamranMammadov** [comment]
> @KamranMammadov can you share your OData setup code including the EDM model as well as how you are applying the `ODataQueryOptions`?
> 
> If you could also share the specific exception details you are seeing that would be good.
```

   public static IEdmModel GetEdmModel()
    {
        ODataConventionModelBuilder builder = new();
        builder.EnableLowerCamelCase();
        builder.EntitySet<CustomerDto>("ODataCustomers");
        builder.EntitySet<ProductDto>("ODataProducts").EntityType.HasKey(entity => entity.Code);

        return builder.GetEdmModel();
    }
```
I dont use ODataQueryOptions:
```
     [HttpGet("$nonodata")]
        [EnableQuery]
        public IActionResult Get()
        {
            var result = _customersService.GetAllQueryable();
            return Ok(result);
        }
```

**Comment by KamranMammadov** [comment]
The LINQ expression '$it => new SelectAll<ProductDto>{ \r\n    Model = __TypedProperty_1, \r\n    Instance = $it, \r\n    UseInstanceForProperties = True \r\n}\r\n' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."
@julealgon  Error Message

**Comment by KamranMammadov** [comment]
@julealgon 
//_customerService.GetAllQueryable()
```
  public IQueryable<CustomerDto> GetAllQueryable()
        {
            var result = _repository.GetAllQueryable();
            return _mapper.ProjectTo<CustomerDto>(result);
        }
```
// _repository.GetAllQueryable()

```
  public IQueryable<TModel> GetAllQueryable()
    {
        var result = _context.Set<TEntity>().AsNoTracking();
        return _mapper.ProjectTo<TModel>(result);
    }
```

**Comment by julealgon** [comment]
I see you are using AutoMapper projections with custom DTOs there @KamranMammadov .

May I suggest looking into AutoMapper.OData instead?
- https://github.com/AutoMapper/AutoMapper.Extensions.OData

I believe projections don't fully work with OData and should not be used for this purpose.

Hopefully that sets you in the right path.

PS: I'm a bit surprised you are following Clean Architecture while exposing `IQueryable` from the service layer. Usually folks will frown upon allowing external consumers to modify your query. And this is not necessarily criticism, just pointing it out really since I personally don't quite agree with some of the stuff behind Clean Architecture.

**Comment by KamranMammadov** [comment]
> I see you are using AutoMapper projections with custom DTOs there @KamranMammadov .
> 
> May I suggest looking into AutoMapper.OData instead?
> 
> * https://github.com/AutoMapper/AutoMapper.Extensions.OData
> 
> I believe projections don't fully work with OData and should not be used for this purpose.
> 
> Hopefully that sets you in the right path.
> 
> PS: I'm a bit surprised you are following Clean Architecture while exposing `IQueryable` from the service layer. Usually folks will frown upon allowing external consumers to modify your query. And this is not necessarily criticism, just pointing it out really since I personally don't quite agree with some of the stuff behind Clean Architecture.

@julealgon  I tried this approach too. To be honest didnt work as expected and SQL queries not generated optimal

**Comment by julealgon** [comment]
I see @KamranMammadov . Have you considered opening an issue in the AutoMapper.OData repo about the SQL problems you saw?

Alternatively, and I know this is against Clean Architecture but... have you considered just not having DTOs and using the mapped models directly in the API layer? Not having the DTO layer makes it infinitely more simple to work with OData.

**Comment by KamranMammadov** [comment]
Probably yes we will continue on this way. I understood that sometimes we should to  modify “best practices”  suitable to our needs @julealgon Thanks a lot!
