### ISSUE TITLE
[Question] When is a new release planned?

### ISSUE THREAD

**Issue by JustinDroege** [OData/AspNetCoreOData#998]
I wanted to ask when a new release is planned? I'm generally interested in the following issue: #987 and when you can expect approximately a new package to be released where this change is included. Have a nice day!

**Comment by JustinDroege** [comment]
Does no one know about a possible release :(?

**Comment by KenitoInc** [comment]
Here it is https://github.com/OData/AspNetCoreOData/releases/tag/8.2.1

**Comment by julealgon** [comment]
Just wanted to say that the work you guys are doing is absolutely awesome... this last release has _so many_ insane fixes and great improvements in it it's not even funny!

As someone who watches this repository closely and loves OData to heart, thank you very much to the entire team.

@xuzhg / @habbes to spread the love to the rest of the group o/
